### ISSUE TITLE
Shopify General Issues

### ISSUE THREAD

**Issue by BhuvneshSoniApporio** [osiset/laravel-shopify#1003]
Hello @Kyon147 

Could you please give me answer of below questions.
How to verify Shop on another page not inside shopify iframe ?

As i already told you that i am using same table for laravel auth, So let me know how can i authenticate user as well for laravel auth with shopify authentication when user install the shopify app. what you suggest for that.

According to my project architecture, What i need to do is, When user install my app, first authenticate the shop, then redirect to my login page then user login here, then it use previously authenticated shop and store the access code of that. So i can access the shop orders in future when its required.

So please help me on this.

**Comment by Kyon147** [comment]
Please don't create duplicate issues as your question is already been talked about in #473
