### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hapo-ducdl** [osiset/laravel-shopify#1012]
### Discussed in https://github.com/osiset/laravel-shopify/discussions/1008

<div type='discussions-op-text'>

<sup>Originally posted by **hapo-ducdl** November 15, 2021</sup>
composer require osiset/laravel-shopify
Class name must be a valid object or a string at vendor/osiset/laravel-shopify/src/ShopifyAppProvider.php:294
laravel 8.12
</div>

**Comment by saddamsegwitz** [comment]
same problem

**Comment by saddamsegwitz** [comment]
`Class name must be a valid object or a string

  at vendor/osiset/laravel-shopify/src/ShopifyApp/ShopifyAppProvider.php:344
    340▕      */
    341▕     private function bootObservers(): void
    342▕     {
    343▕         $model = $this->app['config']->get('auth.providers.users.model');
  ➜ 344▕         $model::observe($this->app->make(ShopObserver::class));
    345▕     }
    346▕ 
    347▕     /**
    348▕      * Boot the middlewares for the package.
`

**Comment by saddamsegwitz** [comment]
I have tried recache using `php artisan config:cache` and deleting the *.php file inside bootstrap/cache folder. But still same problem

**Comment by HatimLagzar** [comment]
Make sure you have a user model and it's linked in `config/auth.php` under providers array, like this: 
`
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => \App\Models\User::class,
        ],
    ],
`
and re-run the command `composer require osiset/laravel-shopify`

**Comment by Kyon147** [comment]
Closing old ticket, if still an issue please reopen.
