### ISSUE TITLE
About shopify extensions online store 2.0

### ISSUE THREAD

**Issue by damquanghieu** [osiset/laravel-shopify#1013]
I used API script_tags for my app, Shopify requires me to have extensions online store.
How can I do that? 
Please help me!
Thank you su much.

**Comment by brucelee90** [comment]
This question has already been asked here: https://github.com/osiset/laravel-shopify/issues/1004 and here https://github.com/osiset/laravel-shopify/issues/980

**Comment by damquanghieu** [comment]
> This question has already been asked here: #1004 and here #980

Thanks so much

**Comment by tanseercena** [comment]
@damquanghieu You can check this: https://github.com/osiset/laravel-shopify/issues/1167#issuecomment-1202443351

**Comment by Kyon147** [comment]
Closing as duplicate Q have been provided.
