### ISSUE TITLE
How to get session token when using laravel Vuejs embedded app(v17)

### ISSUE THREAD

**Issue by hamzasgd** [osiset/laravel-shopify#1014]
how to use tokenRoute when using Vuejs

**Comment by sahilcrawlapps** [comment]
You can use app bridge which is NPM package. Its provided in shopify documentation here [https://shopify.dev/apps/auth/session-tokens/app-bridge-utilities](url) you can find it.

**Comment by hamzasgd** [comment]
I Figured out another solution for it.

**Comment by tanseercena** [comment]
> I Figured out another solution for it.

@hamzasgd Can you list your solution here so it can help other developers? 

I have same issue and need tokenRoute in vuejs component.
Thanks

**Comment by hamzasgd** [comment]
@tanseercena Yes I added the class `.session-token` in the body tag and get the token from body when calling axios request

**Comment by hamzasgd** [comment]
@tanseercena by adding the class package automatically updating the token every minute so I just get from the body tag every time I make a axios request.
