### ISSUE TITLE
Unable to verify signature.

### ISSUE THREAD

**Issue by ThiagoMineDealweb** [osiset/laravel-shopify#1015]
## Expected Behavior

Normal instalation of a public app in a test store

## Current Behavior

In the test store app installation process, I always get the message: "Unable to verify signature.".
I've updated the keys and it didn't solve my problem

## Failure Information

Osiset\ShopifyApp\Exceptions\SignatureVerificationException
Unable to verify signature.

![Screenshot_20211117_120251](https://user-images.githubusercontent.com/45767137/142225387-9663bc9d-6355-4123-9e27-c821a4efd3d6.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try toinstall app throught the partners portal in a test store

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.0.5
* Laravel Version: v8.71.0
* PHP Version: v7.4.0
* Using Docker

**Comment by sarik-k** [comment]
Check if you put shopify api credentials in .env file

**Comment by ThiagoMineDealweb** [comment]
Thanks @sarik-k

**Comment by Kyon147** [comment]
Closing this as no new updates.
