### ISSUE TITLE
Change Model User Authentication

### ISSUE THREAD

**Issue by ha2mza** [osiset/laravel-shopify#1016]
If you can change UserModel For Authentication To Costum Model or ShopModel Because User it's not a realy name and  maybe  user have more then one shop so if you do A ShopModel For authentication it will be  realy realy better 

if i have already projet and i have user for another utility i cannot use your library  this  is other problem it's will be good  if change Authentication to other model 

thanks.

**Comment by ha2mza** [comment]
i have an idea for this solution it's add item  like this  ('auth_model' => App\Models\User) to shopify-app.php in config
for dont create problem for old user  
and if hi went to change model User  it's simple just i will go to  shopify-app.php in config and change item auth_model to  App\Models\Shop for example . it will be the result  lik this   ('auth_model' => App\Models\Shop)

**Comment by Kyon147** [comment]
You should be able to using the config file to update the Auth Model to something else..

```
    /*
    |--------------------------------------------------------------------------
    | Shop auth provider
    |--------------------------------------------------------------------------
    |
    | This option allows you to override package's build-in auth model
    | If you need to keep User model intact, add custom auth provider and route middlewares for it
    |
    */
    'shop_auth_provider' => env('SHOPIFY_SHOP_AUTH_PROVIDER', 'users'),
```
