### ISSUE TITLE
How to use ShopifyQL with Public App?

### ISSUE THREAD

**Issue by veed76** [osiset/laravel-shopify#1017]
Hi @osiset 
Using this package is it possible to query this `SHOW sum(pageview_count) OVER month(timestamp) AS month` statement?
If yes then how we can execute it programmatically?

I'm trying like this way, But it throwing the error.

Example Code:
```
$response = $shop->api()->graph("SHOW sum(pageview_count) OVER month(timestamp) AS month");
dd($response);
```

Error: https://prnt.sc/2005osy

Can you please help me on this?
Thank you.

**Comment by Kyon147** [comment]
This looks like a GraphQl error not a package one and as it is old I'm going to close it.
