### ISSUE TITLE
Webhook 201 created

### ISSUE THREAD

**Issue by yimincheah** [osiset/laravel-shopify#1018]
I have issue with the webhook response 201, I already follow the ngrok documentation with the $url->forceScheme('https') but still cannot get 200

![image](https://user-images.githubusercontent.com/77157121/142445012-291f0e0d-0a09-495d-a31f-bd0e26b46180.png)

![image](https://user-images.githubusercontent.com/77157121/142446415-84eb7c97-5201-4fcc-a902-b92902c97a9d.png)

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Contracts\Routing\UrlGenerator as URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(URL $url)
    {
        $url->forceScheme('https');
    }
}
```

**Comment by Kyon147** [comment]
Hey @yimincheah 

Cleaning up older tickets and wanted to mention 201 is right.

When creating webhooks, the response is 201 - see the shopify doc below

https://shopify.dev/api/admin-rest/2022-01/resources/webhook#post-webhooks

![image](https://user-images.githubusercontent.com/32519106/159476598-4188b594-091e-46af-81ca-01bff46b6144.png)
