### ISSUE TITLE
Webhooks not registering

### ISSUE THREAD

**Issue by t08-apporio** [osiset/laravel-shopify#1020]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Webhooks should register

## Current Behavior

Webhooks are not registering

> During installation there is no error received about webhooks of any sorts

### Steps to Reproduce

1. Follow wiki instructions on Creating Webhooks
2. vendor:publish --tag=shopify-jobs
3. added webhooks' topic and address to the shopify-config file
4. tried with topic/event and TOPIC_EVENT formats

### Context

I am using ngrok with the forceScheme('https') enabled on my localhost. I have set the APP_URL to the ngrok url
Access scopes have been set according to the webhooks required

* Package Version: v17.1
* Laravel Version: v7.29
* PHP Version: v7.4.3

After installation of the app on shopify development store, I try to view the list of webhooks registered and it returns empty. As in the webhooks are not registering.

**Comment by LonnyX** [comment]
if the user exists before this webhook, you should dispatch new WebhookInstaller
like this:

```php
$shop = auth()->user();
dispatch(new WebhookInstaller($shop->getId(), Util::getShopifyConfig('webhooks')));
```

**Comment by t08-apporio** [comment]
Hi @LonnyX a new row is inserted on app install in the jobs tabls. The payload field contains details about which webhooks need to be registered but they dont seem to run. Any idea why?

**Comment by t08-apporio** [comment]
Hi @LonnyX. I think I got the issue. I had to run `php artisan queue:work` for the registration of webhooks. In the [wiki](https://github.com/osiset/laravel-shopify/wiki/Creating-Webhooks#:~:text=When%20a%20shop%20logs%20into%20your%20app%2C%20this%20webhook%20entry%20will%20automatically%20be%20installed%20and%20App/Jobs/OrdersCreateJob%20will%20be%20ready%20to%20accept%20data.) it said the webhooks are installed automatically. I think that needs to be changed
