### ISSUE TITLE
Embedded App Navigation Gives AppBridgeError: host must be provided 

### ISSUE THREAD

**Issue by EvaDenys99** [osiset/laravel-shopify#1022]
## Expected Behavior

When navigating with the App navigation from the App setup > Embedded app > navigation I expect it to go to the right page.

<img width="1298" alt="Screenshot 2021-11-25 at 16 11 20" src="https://user-images.githubusercontent.com/44461075/143465589-df67d9aa-5967-4553-9895-c19796497983.png">

## Current Behavior

I get a white screen with an error. (see error screenshot in Failure Information)

## Failure Information

![Screenshot 2021-11-25 at 16 09 12](https://user-images.githubusercontent.com/44461075/143465452-671b9643-468d-488a-938e-f21c2ec2f3be.png)

### Steps to Reproduce

1. Go to an app with the new osiset configuration that is yours (that is in development / not live)
2. Go to App setup > Embedded app > navigation
3. Setup some navigation items
4. Go to a shopify store admin
5. Go to apps
6. Go to the app that you just configured
7. Test your navigation in the app

### Context

* Laravel Version: v7
* PHP Version: v7.4
* "@shopify/app-bridge": "^2.0.3",
* "@shopify/app-bridge-react": "^2.0.3",
* "@shopify/app-bridge-utils": "^2.0.4",
* "@shopify/polaris": "^6.5.0",
*  "react": "^16.13.1",
* "react-dom": "^16.13.1",

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by kmajay978** [comment]
Have you solved it ? @EvaDenys99
