### ISSUE TITLE
Missing auth url

### ISSUE THREAD

**Issue by waleakande** [osiset/laravel-shopify#1023]
I created a development store in the Partners Dashboard. When I try to install the app it redirects to the Store just fine but it throws this error

Osiset\ShopifyApp\Exceptions\MissingAuthUrlException
Missing auth url

* Package Version: latest
* Laravel Version: v8.73.2
* PHP Version: v7.4.1

**Comment by abishekrsrikaanth** [comment]
Got the same error. @waleakande were you able to fix this?

@osiset any idea why this would occur?

**Comment by talkwithdeveloper** [comment]
Got the same error ,@osiset any idea why its coming during installation?

**Comment by Kyon147** [comment]
Hi @waleakande 

A fresh install for me works fine. Can you provide more information on your setup and process to try and narrow it down.

Closing the ticket for now but reopen if you still have issues.
