### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by ahmedobjects** [osiset/laravel-shopify#1025]
I am trying to make an ajax post request.
The first request passed successfully and give 200 status code.
But the second one give me error with "419" status code and an error message "CSRF token mismatch.".
Note: i sent this csrf token in the request but still get the same error in the second request.
This is my request code
$.ajax({
url: "/test",
type: 'POST',
headers: {
'X-CSRF-TOKEN': "{{ csrf_token() }}"
},
success: function (data) {
console.log(data);
return true;
},
error: function(error) {
console.log(error);
return false;
}
});

**Comment by enmaboya** [comment]
disable csrf checking .

since jwt tokens are used, this is not necessary

**Comment by objectsweb** [comment]
@enmaboya
At First thinks so much for your reply.
Do we use the jwt tokens??
I mean the jwt is used by default in the laravel shopify package??
Beacuse i did not use jwt package :)

**Comment by vdubov** [comment]
using this package you are using JWT anyway, otherwise your application simply will not pass moderation.

even if you don't have a spa application, you still pass the token every time you request it, just in the get parameter or with a hidden input

**Comment by enmaboya** [comment]
using this package you are using JWT anyway, otherwise your application simply will not pass moderation.

even if you don't have a spa application, you still pass the token every time you request it, just in the get parameter or with a hidden input

**Comment by ItsGageH** [comment]
Further information on this package's use of JWT in v17 can be found at:
https://github.com/osiset/laravel-shopify/wiki/Authentication-Process
https://github.com/osiset/laravel-shopify/wiki/Installation#csrf

**Comment by Kyon147** [comment]
@enmaboya is right - you need to use the JWT token helpers.

https://github.com/osiset/laravel-shopify/wiki/Authentication-Process

Closing this.
