### ISSUE TITLE
Change method of target URL to POST

### ISSUE THREAD

**Issue by Buyonecollective** [osiset/laravel-shopify#1027]
Hi there,
I want to set the target method of URL to POST after authenticate/token request.
I am submitting a form, as I request my route i.e. campaign.update, my request redirects to authenticate/token route and after that it redirect back to my route with GET requests and my form data is lost plus the request is wasted.
I am stuck in this and couldn't find a way out, need help in this regard.

My Route:
![image](https://user-images.githubusercontent.com/94851820/144047888-b68250d3-aec7-4641-9260-7a33e8b7679c.png)

Request flow:
1 Request:
![image](https://user-images.githubusercontent.com/94851820/144048019-a80df805-ea08-4e84-8d5c-69df1fa6db98.png)
2 Request: 
![image](https://user-images.githubusercontent.com/94851820/144048092-e9dfd2a9-6f61-40c2-86b9-b244d1221a15.png)
3 Request:
![image](https://user-images.githubusercontent.com/94851820/144048137-c5d2c13e-def8-4fbe-bd9d-6cdca32f9942.png)

The Form Im using:
![image](https://user-images.githubusercontent.com/94851820/144048280-cdf579d0-d106-415c-a2d1-53edf19a004a.png)

For the 3 request, I want it to be a POST one and with form data. Pls help.

**Comment by Kyon147** [comment]
Closing as this ticket is old.
