### ISSUE TITLE
Call to a member function getDomain() on null

### ISSUE THREAD

**Issue by maulik41** [osiset/laravel-shopify#1029]
When i tried to call localhost it gives error
![Screenshot from 2021-12-08 12-29-02](https://user-images.githubusercontent.com/44226986/145163070-a053589d-1d17-4808-85f3-d9a6d0fd7897.png)

**Comment by faizan-glowlogix** [comment]
@maulik41 follow this guy https://www.youtube.com/watch?v=YepqHFryFN0&t=951s

**Comment by faizan-glowlogix** [comment]
Facing same error.

**Comment by ugurmuslim** [comment]
Laravel app can not get session token. Actually there is a code block which integrates with shopify via App bridge and from there I could manage to send shopfiy session token to the middleware.

![image](https://user-images.githubusercontent.com/28356905/146745216-e9979f80-e859-4476-a683-6c5c5a6119b6.png)

So as you see if there is a session-token class, it will write the session value inside it. If you send your requests with that input there won't be a problem.

<input type="text" class="session-token" name="token"
                       value="">

**Comment by faizan-glowlogix** [comment]
@ugurmuslim you added this to your middleware?

**Comment by adrianmihaila** [comment]
I created a PR for adding a login page to fix this issue: https://github.com/osiset/laravel-shopify/pull/1121

**Comment by Kyon147** [comment]
Closing as issue is potentially resolved in another PR. Reopen if still and issue.
