### ISSUE TITLE
Webhook not giving data

### ISSUE THREAD

**Issue by faizan-glowlogix** [osiset/laravel-shopify#1034]
I am creating a Shopify custom app using laravel. I have created a webhook fulfillment/update. This webhook is created now and it is showing when I check from the rest api. but still, I have not been able to receive data from this webhook. I am using expose for hosting my site temporarily. I am not receiving any error in my application log anywhere. Please let me know how can I test this endpoint. What's the issue here?

**Comment by Kyon147** [comment]
Webhooks can be tricky to test, but I'd recommend using Ngrok as it is usually quite good. 

Also, with v17 the topic has changed to match the GraphQL so it would be `FULFILLMENT_UPDATE`.
