### ISSUE TITLE
Authentication from store failed

### ISSUE THREAD

**Issue by theanh8898** [osiset/laravel-shopify#1035]
TypeError
Osiset\ShopifyApp\Storage\Observers\Shop::creating(): Argument #1 ($shop) must be of type Osiset\ShopifyApp\Contracts\ShopModel, App\Models\User given, called in /home/theanhhp/Documents/shopify_app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 424

**Failure Logs**
TypeError
Osiset\ShopifyApp\Storage\Observers\Shop::creating(): Argument #1 ($shop) must be of type Osiset\ShopifyApp\Contracts\ShopModel, App\Models\User given, called in /home/theanhhp/Documents/shopify_app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 424

Osiset\ShopifyApp\Storage\Observers\Shop::creating
vendor/ohmybrew/laravel-shopify/src/Storage/Observers/Shop.php:41

Osiset\ShopifyApp\Storage\Commands\Shop::make
vendor/ohmybrew/laravel-shopify/src/Storage/Commands/Shop.php:53

Illuminate\Database\Eloquent\Model::fireModelEvent
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:189

**Comment by theanh8898** [comment]
@osiset please help me!

**Comment by theanh8898** [comment]
I tried following this tutorial (https://weeklyhow.com/shopify-app-development-with-laravel/) with my custom app and development store but when I choose store to install it shows the above error screen

**Comment by KimKJDesigns** [comment]
Try following the steps outlined in the [wiki](https://github.com/osiset/laravel-shopify/wiki).

**Comment by theanh8898** [comment]
> Try following the steps outlined in the [wiki](https://github.com/osiset/laravel-shopify/wiki).

oh, I followed the instructions and it worked, thank you very much
