### ISSUE TITLE
Session token is undefined when reload page

### ISSUE THREAD

**Issue by dandyleon19** [osiset/laravel-shopify#1038]
When i load the page at first time, all good, but when i reload the page the sessionToken is undefined for a moment, however, when i move to another page the session token is correct or when i use the setTimeOut function for 1 second, the sessionToken is available.

![image](https://user-images.githubusercontent.com/48505581/146452686-fe734979-87ac-4b1a-9176-8048328bd9f7.png)

I don't want to use setTimeOut, some solution for that?

* Package Version: v17.1
* Laravel Version: v7.0
* PHP Version: v7.4.20

**Comment by Kyon147** [comment]
There are some instances that I have seen undefined with the `window.sessionToken` and to solve it I have set up an `axios` interceptor.

```
axios.interceptors.request.use(function (config) {
    return utils.getSessionToken(window['app-bridge-app']) // requires a Shopify App Bridge instance
        .then((token) => {
            console.log('axios token');
            // Append your request headers with an authenticated token
            config.headers.Authorization = `Bearer ${token}`;
            return config;
        });
});
```

You need to make sure you include this where you import axios. usually `app.js`

**Comment by Kyon147** [comment]
Marking this as closed for now.
