### ISSUE TITLE
Payment using extension

### ISSUE THREAD

**Issue by TungPham198** [osiset/laravel-shopify#1041]
Hi. Currently I am developing an application to add effects to an online store. I used scripttag in old version. However when switching to version 2.0 shopify requires using an extension, how can I let free users use it but mean more functionality than paid users. I haven't found a single document about that. Any help is much needed.

**Comment by daniyal741** [comment]
Hi, you can use Shopify  CLI to create a theme app extension in that app. In the app, setup make a new version of the app extension. Then your app will be compatible with both versions of Shopify.

**Comment by Kyon147** [comment]
Closing ticket as it is old but reopen if issue persists.
