### ISSUE TITLE
Randomly Error of `[API] Invalid API key or access token (unrecognized login or wrong password)` from  API call

### ISSUE THREAD

**Issue by ajaymakwana888** [osiset/laravel-shopify#1042]
Firstly I want to Thanks for this awesome package.

## Current Behavior
I have created Shopify public App using this package.
This app is working fine, also app is published on the Shopify App Store.

but recently I got errors of `[API] Invalid API key or access token (unrecognized login or wrong password)` in each Shopify API call.

### Using versions:
  `"laravel/framework": "^8.12"`
  `"osiset/laravel-shopify": "^17.0",`
  
 This is happening for all stores which are using this app.

### Temp Solution for me. 

* whenever API failed & got this error that time we update App from the store by the given URL.

"https://shop.myshopify.com/admin/oauth/authorize/?client_id=xxxxxxxxxx&redirect_uri=https://shopify-app.com/authenticate&scope=read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_inventory&grant_options[]=per-user"

one another option
* set an empty password in the user's table in the database.

After doing this App working fine for the next 2-3 days.
after 2-3 days again get these problems & fix them by updating the app from the store.

I'm not sure why & when this happens.

### Failure Logs

Response of Failed Shopify Rest API.

![image](https://user-images.githubusercontent.com/24936717/146914368-78687920-ca8e-49a0-9b6d-d4c521b87351.png)

Can anyone help me to fix this problem?
Thanks in advance.

**Comment by chrismeats** [comment]
I am having the same issue randomly for random stores. However, I am unable to find a work around to make it work either.

Anyone have any suggestions on this?

**Comment by ajaympanther** [comment]
same issues with me.

Does anyone help me?

**Comment by sunil-panthercodx** [comment]
The same issue occurs with me for the last week. A temporary solution is to update the app.
Does anyone have a solution?
@osiset  @lucasmichot  Please guide me...

**Comment by Kyon147** [comment]
Hi @ajaymakwana888 

Have you tried doing a direct API call to one of the stores using their token saved in the users table? 

That error from Shopify is basically saying the API key is no longer valid, i.e the store has uninstalled the app and they revoke the key.

**Comment by ajaymakwana888** [comment]
Hello there, thanks for replying

My issue was fixed. (sorry to say this is a code mistake from my side)
I'm passing `grant_options[]=per-user` while Updating App from the store.
so it's generated `Online access` & this token is valid for 24 hours.

I must be the use **offline-access**  
https://shopify.dev/apps/auth/oauth/access-modes#offline-access
