### ISSUE TITLE
After installing the app the view page not render on store? app installed successfully everything working fine but facing this issue

### ISSUE THREAD

**Issue by Msk101** [osiset/laravel-shopify#1047]
After installing the app the view page not render on the store? app installed successfully everything working fine but facing this issue.

* Package Version: osiset/laravel-shopify": "^17.1
* Laravel Version: 8.65
* PHP Version: v7.3

**Comment by Kyon147** [comment]
Hi @Msk101 

Can you provide steps on how I can reproduce this issue and anything specific you have done to the package which differs from the standard install?

**Comment by siva2602** [comment]
After installing the app the view page not render on the store? app installed successfully everything working fine but facing this issue. how to solve it,

**Comment by Kyon147** [comment]
> After installing the app the view page not render on the store? app installed successfully everything working fine but facing this issue. how to solve it,

Can you provide steps to reproduce and code snippets. We can't help otherwise.

**Comment by siva2602** [comment]
![image](https://user-images.githubusercontent.com/87166285/159056650-5e4cf239-402b-44c0-b35a-20d79026ba34.png)

**Comment by Kyon147** [comment]
Can you please share the url and your code in `web.php` and your home blade view.

**Comment by ali-cartgeek** [comment]
I'm also facing the same issue.
below URL used for app setups.

https://tsm.cgprojects.in
https://tsm.cgprojects.in/authenticate

...waiting for the resolution on the same.

**Comment by ali-cartgeek** [comment]
Route::get('/', function () {
    return view('welcome');
})->middleware(['verify.shopify'])->name('home');

**Comment by ali-cartgeek** [comment]
View file code - LSRI\resources\views\welcome.blade.php

@extends('shopify-app::layouts.default')

@section('content')
    
    <p>You are: {{ $shopDomain ?? Auth::user()->name }}</p>
@endsection

@section('scripts')
    @parent

    <script>
        actions.TitleBar.create(app, { title: 'Welcome' });
    </script>
@endsection

**Comment by Kyon147** [comment]
@ali-cartgeek I can't replicate this but can you update to 17.2 and try.

**Comment by usmanpakistan** [comment]
@ali-cartgeek this sems to be a code-igniter project.

**Comment by Kyon147** [comment]
@usmanpakistan good spot actually, closing this out as it does we don't support codeigniter.
