### ISSUE TITLE
What config changes are required to get Livewire to work correctly?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [osiset/laravel-shopify#1052]
What are the config changes that are required to get Livewire working with this package? Any livewire calls redirects the request to `/login`. I have jetstream installed on my app and I also have `SHOPIFY_TURBO_ENABLED` set to true and all livewire requests redirect to the `/login`

**Comment by Kyon147** [comment]
Hi @abishekrsrikaanth 

Can you move this over to a discussion if you'd like to talk about this. As it is not a direct issue or bug I'm going to close it.
