### ISSUE TITLE
Attempt to read property "name" on null - using URL::tokenRoute

### ISSUE THREAD

**Issue by daniel-nakoneczka** [osiset/laravel-shopify#1054]
## Expected Behavior

When I click "Options" link on my App menu I should be redirected to autenticate/token and then to "Options" page because I use URL::tokenRoute in my blade template. 

## Current Behavior

System redirect to https://mydomain.com/authenticate/token?target=https%3A%2F%2Fmydomain.com%2Fsettings
and throw error: Attempt to read property "name" on null
for: vendor/osiset/laravel-shopify/src/resources/views/layouts/default.blade.php:33

## Failure Information

Laravel has problems to access Auth::user()->name on the line 33 in file vendor/osiset/laravel-shopify/src/resources/views/layouts/default.blade.php
App's welcome (home) page works fine, shows name property. Error happen only when I try to access other pages from app menu.

I checked if I didn't miss something during installation, all looks ok. Also I checked database, "users" tab contains shop record, looks correct.

### Context

* Package Version: v17.1
* Laravel Version: v8.78.1
* PHP Version: v8.1

**Comment by Kyon147** [comment]
Have you made sure to add `verify.shopify` to your routes?

**Comment by daniel-nakoneczka** [comment]
Yes. middleware is added correctly.
Error disappeared when I started using 
{{ route('settings', ['shop' => auth()->user()->name]) }} 
instead of 
URL::tokenRoute

Looks like this ['shop' => auth()->user()->name] is mandatory in every route.
Or maybe there is another way?

**Comment by Sanjay-100** [comment]
@daniel-nakoneczka  I have same issue did you fixed it ?

**Comment by daniel-nakoneczka** [comment]
I didn't fix this improper way. 
I just added shop parameter to every route in blade, like that {{ route('settings', ['shop' => auth()->user()->name]) }}

Looks like not everyone has this issue, maybe it happens only for php8? I didn't try different version of php as my project require min 8.0

**Comment by Kyon147** [comment]
You should not need to add shop, because the `tokenRoute` uses `TokenUrl` class which has the shop on it.

```
abstract class TokenUrl
{
    /**
     * Return a URL to token path with shop and target.
     *
     * @param string $route    The route name.
     * @param array  $params   Additional route params.
     * @param bool   $absolute Absolute or relative?
     *
     * @return array
     */
    public function generateParams(string $route, $params = [], bool $absolute = true): array
    {
        return [
            Util::getShopifyConfig('route_names.authenticate.token'),
            [
                'shop' => ShopDomain::fromRequest(Request::instance())->toNative(),
                'target' => URL::route($route, $params, $absolute),
            ],
        ];
    }
}
```

If you've fixed it though I will close this ticket.
