### ISSUE TITLE
The issue in creating Non-embedded app

### ISSUE THREAD

**Issue by Anjali-Maru** [osiset/laravel-shopify#1062]
Hi

How can I create not embedded app? Even if I disable my embedded app from my partner account and re-open the app, the app is still embedded. How can I make it non-embedded?

* Laravel Version: 8.80.0
* PHP Version: 7.4.3

**Comment by Kyon147** [comment]
This is a known issue and it currently not support yet. 

Keep an eye on this PR.

https://github.com/osiset/laravel-shopify/pull/935
