### ISSUE TITLE
Webhooks installation fails

### ISSUE THREAD

**Issue by daniel-nakoneczka** [osiset/laravel-shopify#1065]
## Expected Behavior

Webhooks should be installed after app installation.

## Current Behavior

Laravel Webhooks job fails.

## Information

App is installed on the real domain with ssl installed so it is not localhost. 

Webhooks array:

`
'webhooks' => [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'APP_UNINSTALLED'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', env('APP_URL') . '/webhook/app-uninstalled')
        ],
        [
            'topic' => env('SHOPIFY_WEBHOOK_2_TOPIC', 'ORDERS_CREATE'),
            'address' => env('SHOPIFY_WEBHOOK_2_ADDRESS', env('APP_URL') . '/webhook/orders-create')
        ],
        [
            'topic' => env('SHOPIFY_WEBHOOK_3_TOPIC', 'ORDERS_DELETE'),
            'address' => env('SHOPIFY_WEBHOOK_3_ADDRESS', env('APP_URL') . '/webhook/orders-delete')
        ],
        [
            'topic' => env('SHOPIFY_WEBHOOK_4_TOPIC', 'CUSTOMERS_CREATE'),
            'address' => env('SHOPIFY_WEBHOOK_4_ADDRESS', env('APP_URL') . '/webhook/customers-create')
        ],
        [
            'topic' => env('SHOPIFY_WEBHOOK_5_TOPIC', 'CUSTOMERS_DELETE'),
            'address' => env('SHOPIFY_WEBHOOK_5_ADDRESS', env('APP_URL') . '/webhook/customers-delete')
        ]
    ],
`

### Context

* Package Version: v17.1
* Laravel Version: v8.80.0
* PHP Version: v8.0

### Failure Logs from failed_jobs table
`
Exception: 1 in /home/forge/xxxxxxxxxxxx/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php:540
Stack trace:
#0 /home/forge/xxxxxxxxxxxx/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php(375): Osiset\ShopifyApp\Services\ApiHelper->doRequestGraphQL()
#1 /home/forge/xxxxxxxxxxxx/vendor/osiset/laravel-shopify/src/Actions/CreateWebhooks.php(70): Osiset\ShopifyApp\Services\ApiHelper->getWebhooks()
#2 [internal function]: Osiset\ShopifyApp\Actions\CreateWebhooks->__invoke()
#3 /home/forge/xxxxxxxxxxxx/vendor/osiset/laravel-shopify/src/Messaging/Jobs/WebhookInstaller.php(63): call_user_func()
#4 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller->handle()
#5 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#9 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#10 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#11 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#13 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#14 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#15 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#17 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#18 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#19 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#20 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#21 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(329): Illuminate\Queue\Worker->runJob()
#22 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->runNextJob()
#23 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#24 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#25 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#27 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#28 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#29 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#30 /home/forge/xxxxxxxxxxxx/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#31 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#32 /home/forge/xxxxxxxxxxxx/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run()
#33 /home/forge/xxxxxxxxxxxx/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#34 /home/forge/xxxxxxxxxxxx/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#35 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#36 /home/forge/xxxxxxxxxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#37 /home/forge/xxxxxxxxxxxx/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#38 {main}
`

**Comment by usmanwixpa** [comment]
I have also facing same issue please answer about @osiset

**Comment by Kyon147** [comment]
Hey @daniel-nakoneczka 

Can you provide any more detail on how to replicate this error as webhooks are working for me fine.

**Comment by Kyon147** [comment]
Closing as no reply. Re-open if still an issue.

**Comment by jordiruizp** [comment]
Hi @Kyon147 

I am facing the same issue. App installation works perfectly in Shopify, but if I check the failed_jobs table I get the same error as @daniel-nakoneczka 

I dumped the $query and $payload variables into the doRequestGraphQL function. The following query appears in the $query variable:

```
Exception: 
        mutation webhookSubscriptionCreate(
            $topic: WebhookSubscriptionTopic!,
            $webhookSubscription: WebhookSubscriptionInput!
        ) {
            webhookSubscriptionCreate(
                topic: $topic
                webhookSubscription: $webhookSubscription
            ) {
                userErrors {
                    field
                    message
                }
                webhookSubscription {
                    id
                    topic
                }
            }
        }

```
But the $payload variable is empty and consequently Shopify returns an error and the job queue stops working.
