### ISSUE TITLE
Call to a member function getDomain() on null in Safari

### ISSUE THREAD

**Issue by artem55555p** [osiset/laravel-shopify#1067]
I logged in https://partners.shopify.com/xxxxxxx/resources/get_started to the Apps section. ->Test Application -> Select Store -> name-store. The error is only in safari. Chrome and Mozilla are fine.
Does anyone have any ideas?

![изображение](https://user-images.githubusercontent.com/12828397/150926505-5223dbd9-98ef-44e0-a105-f7172e44fec4.png)

**Comment by Sanjay-100** [comment]
@artem55555p   This is not package  Error you have to check the database you clean-up manfully  so Delete app and Install again.

**Comment by Kyon147** [comment]
I've tested this successfully on my own apps and new blank build. Closing it for now as the issue is quite old. Reopen if it still exists.
