### ISSUE TITLE
App must verify the authenticity of the request from Shopify.

### ISSUE THREAD

**Issue by somin-parate** [osiset/laravel-shopify#1073]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

While submitting app we are having those 2 issue 

## Expected Behavior

https://prnt.sc/26ng19g

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 17.1
* Laravel Version: 7.2
* PHP Version: 7
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
I'm not 100% sure that is correct from Shopify.

The first requests look correct for me (this is triggering it from the partner dash but same sort of thing)

![image](https://user-images.githubusercontent.com/32519106/152537225-bf5edde9-2c58-4f36-9beb-e74bed9fb16d.png)

- Click "install" 
- We are sent to the auth route as it has been set up in the app admin.
- We then go to `/admin/oauth/authorize`
- From there it gets redirected to `/admin/oauth/request_grant` where you see the "Install Page"
- Click install and we go to `/admin/oauth/post_grant` to grant the charges (if any)
- Then `/authenticate` happens again with the new `?code` parameter to be authed and all the usual stuff happens i.e we store the API Access Token etc.
- `/authenticate/token` should only happen in between page changes within the app itself not as part of the authentication flow.

Can you provide more detail on your set up with your routes etc.

**Comment by somin-parate** [comment]
@Kyon147  Yes so when we are trying its allowing me to do everything i tried to install that multiple times and its working perfect but still they are sending me same https://wishlist.partners.gemfind.com/login
here is my instance where you can check

**Comment by Kyon147** [comment]
Following the routes via a redirect tracking tool - I don't see /authenticate/token in the flow at all - the only one is when it lands on `/authenticate` and then going to `/oauth/authorize`.

**Comment by Kyon147** [comment]
> @Kyon147 Yes so when we are trying its allowing me to do everything i tried to install that multiple times and its working perfect but still they are sending me same https://wishlist.partners.gemfind.com/login here is my instance where you can check

Question, have you manually added the login page back into your application? As this view was removed a while back.

**Comment by somin-parate** [comment]
yes i added that manually otherwise if we try to open that page its give me shop domain error.

**Comment by Kyon147** [comment]
Yeah, I don't see the `auth/token` directly but I do see the `authenticate` route. 

I'll need to do a little more digging and I'll tag @osiset as he knows the auth flow a lot better than me.

**Comment by somin-parate** [comment]
please check my video as mentioned for each step routing we are following https://watch.screencastify.com/v/Ugt28T0xmltwPKJnJNVI

**Comment by somin-parate** [comment]
@Kyon147  is there any idea after looking at video?

**Comment by somin-parate** [comment]
@Kyon147  Thanks for the info but yes its working as same mentioned that its passing with above route

**Comment by Kyon147** [comment]
@somin-parate - I've created a new PR which avoids the full page redirect and does seem to keep the package running as normal. Just need @osiset to take a look and merge into master if he's happy.

**Comment by osiset** [comment]
I'll make some time Friday morning, sorry guys, I'm still full-tilt on work
and external issues! Appreciate it!

**Comment by ugurmuslim** [comment]
Hi.  Any news on that issue.We are having the same feedback from Shopify.

**Comment by ugurmuslim** [comment]
> _For bug reporting only! If you're posting a feature request or discussion, please ignore._
> 
> While submitting app we are having those 2 issue
> 
> ## Expected Behavior
> https://prnt.sc/26ng19g
> 
> Please describe the behavior you are expecting.
> 
> ## Current Behavior
> Please describe the current behavior?
> 
> ## Failure Information
> Please help provide information about the failure if this is a bug.
> 
> ### Steps to Reproduce
> Please provide detailed steps for reproducing the issue.
> 
> 1. Step 1
> 2. Step 2
> 3. ...
> 
> ### Context
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> 
> * Package Version: 17.1
> * Laravel Version: 7.2
> * PHP Version: 7
> * Using a toolset (Docker, Laradock, Vagrant, etc.):
> 
> ### Failure Logs
> Please include any relevant log snippets or files here.

Hi @somin-parate  have you solved this problem?

**Comment by ugurmuslim** [comment]
I figured out the problem. Actually app is not broken. The problem is not with the install but reinstall.

When the shop is being installed for the first time there is not a problem, but if you delete the app and install it again because the app finds it in the database it tries to find a token etc.

To solve this problem you must subscribe to  APP_UNINSTALL Webhook. This is not the same thing as GDPR Shop_Redact. 

When this webhook calls you if you delete the shop on the next install for the same shop you won't get this problem.

**Comment by baristinaz** [comment]
> I figured out the problem. Actually app is not broken. The problem is not with the install but reinstall.
> 
> When the shop is being installed for the first time there is not a problem, but if you delete the app and install it again because the app finds it in the database it tries to find a token etc.
> 
> To solve this problem you must subscribe to APP_UNINSTALL Webhook. This is not the same thing as GDPR Shop_Redact.
> 
> When this webhook calls you if you delete the shop on the next install for the same shop you won't get this problem.

How do you figure out it? Did you create a new command then assign hook to the new one Or there is method named "softDelete" did you customize this method.

**Comment by Kyon147** [comment]
@baristinaz - the uninstall webhook is all detailed in the wiki - please give it a read.

https://github.com/osiset/laravel-shopify/wiki/Installation#uninstalled-job-recommended

**Comment by headisveryiron** [comment]
> 第一个请求对我来说看起来是正确的（这是从伙伴破折号触发它，但同样的事情）。有一个身份验证/令牌请求，但那是为了获得一个能够安装的令牌。
> 
> ![图片](https://user-images.githubusercontent.com/32519106/152537225-bf5edde9-2c58-4f36-9beb-e74bed9fb16d.png)
> 
> * 点击“安装”
> * 我们被发送到 auth 路由，因为它已在应用程序管理员中设置。
> * 然后我们去`/admin/oauth/authorize`
> * 从那里它被重定向到`/admin/oauth/request_grant`您看到“安装页面”的位置
> * 点击安装，我们去`/admin/oauth/post_grant`授予费用（如果有的话）
> * 然后使用要验证`/authenticate`的新`?code`参数再次发生，所有常见的事情都会发生，即我们存储 API 访问令牌等。
> 
> 您能否提供有关您的路线设置等的更多详细信息？



> The first requests look correct for me (this is triggering it from the partner dash but same sort of thing). There is an auth/token request but that's to get a token to be able to install.
> 
> ![image](https://user-images.githubusercontent.com/32519106/152537225-bf5edde9-2c58-4f36-9beb-e74bed9fb16d.png)
> 
> * Click "install"
> * We are sent to the auth route as it has been set up in the app admin.
> * We then go to `/admin/oauth/authorize`
> * From there it gets redirected to `/admin/oauth/request_grant` where you see the "Install Page"
> * Click install and we go to `/admin/oauth/post_grant` to grant the charges (if any)
> * Then `/authenticate` happens again with the new `?code` parameter to be authed and all the usual stuff happens i.e we store the API Access Token etc.
> 
> Can you provide more detail on your set up with your routes etc.




> The first requests look correct for me (this is triggering it from the partner dash but same sort of thing). There is an auth/token request but that's to get a token to be able to install.
> 
> ![image](https://user-images.githubusercontent.com/32519106/152537225-bf5edde9-2c58-4f36-9beb-e74bed9fb16d.png)
> 
> * Click "install"
> * We are sent to the auth route as it has been set up in the app admin.
> * We then go to `/admin/oauth/authorize`
> * From there it gets redirected to `/admin/oauth/request_grant` where you see the "Install Page"
> * Click install and we go to `/admin/oauth/post_grant` to grant the charges (if any)
> * Then `/authenticate` happens again with the new `?code` parameter to be authed and all the usual stuff happens i.e we store the API Access Token etc.
> 
> Can you provide more detail on your set up with your routes etc.

Hello, two lists were rejected when I submitted the public application online

The details are as follows:

1. App must set security headers to protect against clickjacking. Your app does not request installation on the shop immediately after clicking "add app". Apps must ask a shop for access when being installed on a shop for the first time, as well as when they are being reinstalled after having been removed. During install or reinstall we expected OAuth to be initiated at https://cambridgetestshop.myshopify.com/admin/oauth/request_grant but was redirected to https://xxx.com?hmac=xxx Learn more about authentication in our developer documentation

2. App must verify the authenticity of the request from Shopify. Your app does not request installation on the shop immediately after clicking "add app". Apps must ask a shop for access when being installed on a shop for the first time, as well as when they are being reinstalled after having been removed. During install or reinstall we expected OAuth to be initiated at https://xxx.com?hmac=xxx Learn more about authentication in our developer documentation

But OAuth is not a link generated by our own system to provide users with authorization?

I consulted Shopify's official customer service and only provided me with three links

https://community.shopify.com/c/shopify-apis-and-sdks/app-submission-failing-at-app-must-verify-the-authenticity-of/td-p/1435848

https://community.shopify.com/c/shopify-apps/shopify-app-clickjacking-app-must-set-security-headers/td-p/1424255

https://github.com/osiset/laravel-shopify/issues/1073

What should I do?
