### ISSUE TITLE
App is slowing down because of a post request being sent every second in background

### ISSUE THREAD

**Issue by pangiras** [osiset/laravel-shopify#1076]
A post request is being sent to "https://monorail-edge.shopifysvc.com/v1/produce" every second in app background. The issue appeared after updating the app to the latest version. Attaching a snapshot that shows number of requests that were sent in about half hour. It keeps on going up without ever stopping. This is dramatically slowing down the app.

![Angiras_0-1643744554180 (1)](https://user-images.githubusercontent.com/76610727/152636156-f4d69d4b-66ae-4e90-a7bb-8413a0db3bbc.png)

Kindly help,
Best Regards
Prashant Angiras

**Comment by Kyon147** [comment]
This is down to the session token request that happens every two seconds by default. 

You can do what I've done in my own apps and change to using an interceptor within AXIOS and stop the polling from happening inside `token_handler.blade`

Or just up the `SESSION_TOKEN_REFRESH_INTERVAL` interval to a higher number. Session tokens are valid for around 60 seconds anyways.

it might be worth moving this refresh time into a ENV var so it can be controller a bit better.

**Comment by Noido** [comment]
@pangiras I got same problem can you explain how you have done with sample plz

**Comment by Kyon147** [comment]
Hi @Noido 

The solution is in my comment above ☝️

**Comment by Noido** [comment]
Thanks @Kyon147 i have try add that in my .env but not work

SESSION_TOKEN_REFRESH_INTERVAL=3600000

**Comment by Kyon147** [comment]
Hi @Noido 

It is not an ENV setting at the moment. If you read my solution above you'll see you need to go to the token_handler.blade file which is in the `vendor` folder as part of the `osiset/laravel-shopify-package` package.

**Comment by Noido** [comment]
Thnkas @Kyon147 it s ok now

But got a little bug when i click on a link i got 3 to 5 produce call it s normal ?
![image](https://user-images.githubusercontent.com/5593403/163096743-9079b978-c372-4c00-8a23-77f7785fd4b7.png)
