### ISSUE TITLE
Call to undefined function Osiset\ShopifyApp\createHmac()

### ISSUE THREAD

**Issue by haseebbutt1999** [osiset/laravel-shopify#1077]
In ossist version 16 it was working perfect.
I have just upgraded it to 17 version and this error showing.

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.1
* Laravel Version: v7.29
* PHP Version: v7.2.5

### Failure Logs

Call to undefined function Osiset\ShopifyApp\createHmac()
![image](https://user-images.githubusercontent.com/72742608/152939275-4dfc21b6-9d9e-4a45-8a5b-473ee64a0259.png)

**Comment by pengbo37877** [comment]
v17.1 has issue with usage charge

**Comment by haseebtanveerbutt** [comment]
> v17.1 has issue with usage charge

So, is thier any solution to solve this issue ? or any alernative?

**Comment by pengbo37877** [comment]
@haseebtanveerbutt there is no solution so far

**Comment by inaryu** [comment]
Hi @pengbo37877 
Are you calling `Osiset\ShopifyApp\createHmac()` on your own somewhere in your process?

**Comment by pengbo37877** [comment]
> Hi @pengbo37877 Are you calling `Osiset\ShopifyApp\createHmac()` on your own somewhere in your process?

You can use `Osiset\ShopifyApp\Util\createHmac()` instead of `Osiset\ShopifyApp\createHmac()`

**Comment by inaryu** [comment]
@pengbo37877 Yes, since v17, createHmac() has been migrated to Util::createHmac().

**Comment by Kyon147** [comment]
As this is stale I'm going to close for now. Reopen if issue persists.
