### ISSUE TITLE
osiset package not working in laravel sub directory its pointing to main domain

### ISSUE THREAD

**Issue by somin-parate** [osiset/laravel-shopify#1080]
osiset package not working in laravel sub directory its pointing to main domain.
project setup : https://prnt.sc/26r1avl
my project is running in ring-builder-react and in main domain calling index.php
after installation its going to index.php of main domain
php version : 7.4.3
osiset version: "^17.1"

**Comment by Sanjay-100** [comment]
@somin-parate   It not about the package issue,
 you can render react app into the laravel welcome route or root route 
if you using laravel 8 version it was working.

https://www.positronx.io/how-to-install-react-js-in-laravel-with-bootstrap/

See this example there all the steps you need.

**Comment by Kyon147** [comment]
You also mentioned this on your other ticket #1056 which I have given you some direction but as it is not about the package I am closing these tickets. 

Good luck with your app :)
