### ISSUE TITLE
Update your app to theme app extensions to ensure compatibility with Online Store 2.0 themes. 

### ISSUE THREAD

**Issue by haseebtanveerbutt** [osiset/laravel-shopify#1084]
Shopify sends this point while i apply for list our app on shopify app store.

Your app is currently using ScriptTag API. Update your app to theme app extensions to ensure compatibility with Online Store 2.0 themes. Refer to [this help doc](https://shopify.dev/apps/online-store/theme-app-extensions/migrate#migrate-your-apps) for more context. 
See [this screenshot](https://shopify.click/11-43-56928-38797.png) for additional details.

* Package Version: 17.1
* Laravel Version: 7
* PHP Version: v7.3

**Comment by Kyon147** [comment]
Hi, thanks for posting this but as it is not a direct issue but rather a feature I am going to close this.

**Comment by haseebtanveerbutt** [comment]
ok got it !
but can you please tll me, how i can add using this feature or anything else?

**Comment by Kyon147** [comment]
You would need to follow the instructions and make changes to the app. I can't tell you how as I've not read the documentation in detail and there's bound to be multiple things needed.

Either you'll have to implement your own way, or wait for us to pick up this in the main package.

**Comment by tanseercena** [comment]
@haseebtanveerbutt you can check this: https://github.com/osiset/laravel-shopify/issues/1167#issuecomment-1202443351
