### ISSUE TITLE
Login page not found error

### ISSUE THREAD

**Issue by sumersinghharawat** [osiset/laravel-shopify#1087]
https://fac2-2001-8f8-133b-976-84a8-3393-1102-d081.ngrok.io/login

I'm using URL on my ngrok but It's showing not found.
Please help me resolve this.

**Comment by enmaboya** [comment]
the login page was removed from the package a long time ago

**Comment by Kyon147** [comment]
Yeah as @enmaboya has mentioned this was removed a while back and there's multiple issues using the search that show you how to bring it back if you want.

**Comment by sumersinghharawat** [comment]
So how can i manage this?

**Comment by Kyon147** [comment]
Inside `Exceptions.php` which you can find in app/Exceptions/Exceptions.php.

Go to the render function and add something like:

````
        if ($exception instanceof \Osiset\ShopifyApp\Exceptions\MissingShopDomainException) {
            return response()->view('login', ['error' => 'Please enter your myShopify domain to continue.']);
        }
````

This will return the login view whenever there is a `MissingShopDomainException` exception.
