### ISSUE TITLE
Shopify Webhooks break with heavy load.

### ISSUE THREAD

**Issue by faizan-glowlogix** [osiset/laravel-shopify#1088]
I have implemented a webhook using the instructions provided in this package. I wanted to confirm that if let's say there is a lot of load in the Shopify, for example, 2k order in the 2 3 hours then will this webhook will work. Just for confirmation that it won't break. Because with the previous version of this packages I faced some issues regarding this.

**Comment by abishekrsrikaanth** [comment]
As long as your app is hosted on a decent server that can hold the load, I don't see why webhooks would break your app. The package itself doesn't break anything with the loads from Shopify. It has everything to do with the server on which you host your application. I have an `ec2 micro instance` that takes about 100k orders a day, haven't had any issues. All I do is push the object I receive from Shopify into the queue and return a successful response and then handle all the logic in the queue, that way the endpoint that handles the webhooks is just to accept data and return a response, nothing else..

**Comment by Kyon147** [comment]
@faizan-glowlogix, @abishekrsrikaanth is right. 

Load would be down to your server etc and Shopify does have retry logic built in to any webhooks that don't get a `201` response.
