### ISSUE TITLE
compatible with latest version of laravel and php 

### ISSUE THREAD

**Issue by Sanjay-100** [osiset/laravel-shopify#1089]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.  package work  with laravel 9 version

## Current Behavior

Please describe the current behavior?  not able to add osiser/laravel-shopify  package to project

## Failure Information

Please help provide information about the failure if this is a bug.

Running composer update osiset/laravel-shopify

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create new laravel project 
2. composer require osiset/laravel-shopify

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v 17
* Laravel Version: v 8
* PHP Version: v 8.1
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

./composer.json has been updated
Running composer update osiset/laravel-shopify
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires osiset/laravel-shopify ^17.1 -> satisfiable by osiset/laravel-shopify[v17.1.0, 17.1.x-dev].
    - osiset/laravel-shopify[v17.1.0, ..., 17.1.x-dev] require laravel/framework ^7.0 || ^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require osiset/laravel-shopify:*" to figure out if any version is installable, or "composer require osiset/laravel-shopify:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by usmanwixpa** [comment]
composer require osiset/laravel-shopify:* 
use this command

**Comment by cjogloc** [comment]
> composer require osiset/laravel-shopify:* use this command

This didn't work for me on Laravel 9.0

**Comment by Kyon147** [comment]
Laravel 9 is not currently supported. @Sanjay-100 has an open PR out if he can get it working we can look at getting it into a release in the near future.
