### ISSUE TITLE
Please add support for laravel 9

### ISSUE THREAD

**Issue by nonghinh** [osiset/laravel-shopify#1093]

**Comment by raghav-zwt** [comment]
Any news on this?

**Comment by adrianmihaila** [comment]
Is already created a PR for this: https://github.com/osiset/laravel-shopify/pull/1090/files but I think we need to check every flow to prevent any inconsistency.

**Comment by Kyon147** [comment]
Hi @nonghinh @raghav-zwt @adrianmihaila 

There's an open PR as you say but I am not sure if the owner of it is available to fix the issues. If not, I will try and make a start on Laravel 9 next week.

**Comment by nonghinh** [comment]
Many thanks @Kyon147
