### ISSUE TITLE
Migrating Charges from ruby app

### ISSUE THREAD

**Issue by chrismeats** [osiset/laravel-shopify#1098]
I am migrating an app from Ruby. The app has a monthly recurring charge and I am wondering what needs transferred over from the old app to keep everything working?

Obviously the access token for each shop needs transferred to the users table. However, do charge records need added as well? or will those just populate every month as they are billed through shopify?

Thank you for the help!

**Comment by Kyon147** [comment]
Hi @chrismeats 

The charges in the DB are just records mainly to confirm that an app has a successful charge. Shopify handles the main "billing" side of it each month. 

A new record is not inserted every month, only the response from an actual accepted billing route. So only the "first time" they accept the charges or if they go to a different plan, i.e upgrading. Charges are also used to determine if someone is on a trial as there is a field called `trial_ends_on` which is used. 

I've never migrated from another codebase, so not 100% but I think your charges on the other app will just get charged as normal, you just wont have any record of them in the laravel shopify app if you don't migrate them.
