### ISSUE TITLE
UnInstalled and themepublish WebHook not fire. How to check it work?

### ISSUE THREAD

**Issue by usmanwixpa** [osiset/laravel-shopify#1101]
Aslo shopify give warnings in previous running projects that is given below
![image](https://user-images.githubusercontent.com/97025622/156763105-eb8fa771-0edb-4257-a1b5-af4fe6c3b8dc.png)

**Comment by Kyon147** [comment]
Testing webhooks on local can be very cumbersome. Usually we see most people being able to test using ngrok.
