### ISSUE TITLE
Safari: Blocked Mixed Content

### ISSUE THREAD

**Issue by VikasGhai** [osiset/laravel-shopify#1102]
Hi All,

I am having an issue in my app. It is working fine except the Safari browser and iPhones. I am getting following error:
Blocked mixed content t [http://app_name.herokuapp.com/authenticate/token?shop=test-dash-discount.myshopify.com&target=%2Fhom...](http://app_name.herokuapp.com/authenticate/token?shop=test-dash-discount.myshopify.com&target=%2Fhome%3Fhost%3DdGVzdC1kYXNoLWRpc2NvdW50Lm15c2hvcGlmeS5jb20vYWRtaW4) block-all-mixed-content' appears in the Content Security Policy.

My App is hosted on Heroku and it is also in production. Here is the link of my production app. 
https://apps.shopify.com/dash-discounts

This is my staging app using same code and I am getting following error.
![image](https://user-images.githubusercontent.com/100939546/156767879-71fd7ea9-6d0f-477f-a301-8a6aa922efbb.png)

Please help me to fix this issue.

**Comment by bougsid** [comment]
Please guys do you have any docker-compose to get the app up and running on my local?

**Comment by Kyon147** [comment]
Hi @VikasGhai 

That is a standard browser error as you are serving the app from both `http` and `https`. It does not sound like an issue with the package. You just need to make sure all your content is being served from HTTPS.
