### ISSUE TITLE
Osiset\ShopifyApp\Exceptions\MissingAuthUrlException Missing auth url

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#1103]
I just install new Laravel and Osiset.

1. There is not /login route - so now we can install app only from Shopify admin page - is that correct?
2. I got error message when I install first time app: Osiset\ShopifyApp\Exceptions\MissingAuthUrlException Missing auth url

![image](https://user-images.githubusercontent.com/10516734/156936299-d1a38f82-8c35-4370-b1b6-6091782939f7.png)

I follow all the installation steps like on docs

* Package Version: v17.1
* Laravel Version: v8.75
* PHP Version: v7.3

Please help

**Comment by CHEWX** [comment]
How did you solve the issue @APdevelopments

**Comment by APdevelopments** [comment]
SOrry I would like to help if possible but its not resolved yet. I just roll back to older version.

**Comment by CHEWX** [comment]
@APdevelopments Of what? Should keep open if not resolved as others are experiencing the same.

**Comment by APdevelopments** [comment]
Yes, please keep open
