### ISSUE TITLE
New feature required: Open app on a new tab without url parameters

### ISSUE THREAD

**Issue by codex5** [osiset/laravel-shopify#1107]
## Expected Behavior
I want to always open the app from a new tab without shop, hmac parameters inside the URL,
There should be a cookie value to store logged in store.

## Current Behavior

It shows invalid **shop** parameter

### Context

* Package Version: v17.1
* Laravel Version: v8.75
* PHP Version: v7.4

**Comment by Kyon147** [comment]
The package currently does not support an app outside the shopify admin.
