### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by yogeshausp** [osiset/laravel-shopify#1109]
I have run the    webhook 

   [
                'topic' => env('SHOPIFY_WEBHOOK_3_TOPIC', 'SHOP_REDACT'),
                'address' => env('SHOPIFY_WEBHOOK_3_ADDRESS', 'https://xyx.com/public/webhook/shop-redact')
            ],

after adding  the webhook it showing me the  subscription error $topic  please check screenshot : https://prnt.sc/09GGNaCNLA4W

I have also attach the webhook in app screenshot : https://prnt.sc/jHhZpe1ZR2mf

while i installing the app it showing me error.

**Comment by Kyon147** [comment]
It should be `https://xyx.com/webhook/shop-redact`

You don't access the webhook on the `public` path because the whole laravel application goes through public.

**Comment by Kyon147** [comment]
Closing as no reply. Re-open if still an issue.
