### ISSUE TITLE
Shopify Payments Apps

### ISSUE THREAD

**Issue by stanwarri** [osiset/laravel-shopify#1111]
Hey, 

I'm looking to build a custom Shopify payments app using their new documentation  - https://shopify.dev/apps/payments

Is this package a good starting point for a payment app?

Thanks,

**Comment by Kyon147** [comment]
Hi @stanwarri 

We've not tested the package using the payments app functionality for Shopify.

The biggest issue I can foresee, is that currently the package only works inside the shopify admin using AppBridge.  Where as Shopify expect you to show them a page to "complete payment" and redirect them back. So not sure how it would work exactly with the current package.

Also, this package has not taking into account and PCI compliance you'd need to do for any payment processing.

Feel free to give it a try but we can't say yes or no that it would work.
