### ISSUE TITLE
SESSION_TOKEN_REFRESH_INTERVAL

### ISSUE THREAD

**Issue by Noido** [osiset/laravel-shopify#1116]
Hi, A post request is being sent to "https://monorail-edge.shopifysvc.com/v1/produce" every second in app background. 

Apparently need up the SESSION_TOKEN_REFRESH_INTERVAL interval to a higher number. 

I try add in .env 
SESSION_TOKEN_REFRESH_INTERVAL=3600000

But nothing change got produce every second

Can you help me thanks

**Comment by Noido** [comment]
@lucasmichot ?

**Comment by Kyon147** [comment]
Closing as I have provided a temp solution in #1076
