### ISSUE TITLE
Shopify React not work on app

### ISSUE THREAD

**Issue by Noido** [osiset/laravel-shopify#1118]
Hi, i want use react with laravel in my shopify app_proxy but not work

`Route::group(['middleware' =>['auth.proxy']],function(){`
    `Route::get('/sample',[WelcomeController::class,'getSample'])->name('sample.index');`
`});`

`Route::get('/sample2',[WelcomeController::class,'getSample'])->name('sample.index2');`

If i go directly on server url with /sample2 i got my react page no problem; but on shopify when i go on my apps/sample got only my view welcome.blade.php but no react like react not loaded on shopify

my controller is equal to
` 
return view('welcome');
`
In chrome developper network i have my html load, with app.js but all react components don't work when it s on shopify store

in app.js i have only 
`require('./Components/Sample')`

Thanks for your help

**Comment by Noido** [comment]
Was a cache issue with chrome and incognito mode

**Comment by jhaineymilevis** [comment]
> Was a cache issue with chrome and incognito mode

hi! can you share and example of how you implement it with react?
