### ISSUE TITLE
Cant send a ajax request

### ISSUE THREAD

**Issue by officialGerero** [osiset/laravel-shopify#1125]
When im trying to send a AJAX request, from my app page, that i get to from shopify apps, im getting a redirect from route that im trying access, to authenticate. 

My route :
Route::get('/add-script-tags', [ShopifyController::class, 'addScriptTags'])->middleware('verify.shopify')->name('add-script-tags');
My ajax call:
```
$.ajax({
                url : $(this).attr('href'),
                type: 'get',
                headers: {
                    Authorization: `Bearer ${window.sessionToken}`,
                },
            });
```
Header is added but still isnt recognized by the middleware, or am i missing something?

**Comment by officialGerero** [comment]
My bad, request had accept */* insted of json

**Comment by Kyon147** [comment]
Closing as it looks like you've solved it 👍
