### ISSUE TITLE
After adding more scopes to the approved public app we are getting "Oauth error missing_shopify_permission"

### ISSUE THREAD

**Issue by whidegroup** [osiset/laravel-shopify#1127]
After we have a working app we needed to extend the functionality and add scopes "write_orders, read_orders". It resulted in the next error message when installing an app OR when trying to access the already installed app inside the shopify store admin panel:
Oauth error missing_shopify_permission: write_orders, read_orders

Shopify support advises next:
_You will need to request the OAuth for the access to the merchants previous order history._

Can anybody advise how to proceed properly?

**Comment by pengbo37877** [comment]
same issue

**Comment by whidegroup** [comment]
> same issue

Any progress so far? @pengbo37877

**Comment by whidegroup** [comment]
To tell the story short:
If you have an approved app and you want to extend API's usage (add new scopes, especially read_orders and write_orders because they are sensitive) you should undergo the additional verification of the new app's functionality that uses those callbacks.
