### ISSUE TITLE
Installation error on Laravel 9

### ISSUE THREAD

**Issue by petrov-codedot** [osiset/laravel-shopify#1128]
## Expected Behavior
Installing package on laravel v9

## Current Behavior
Now it gives an error.

## Failure Information
```
Problem 1
     - osiset/laravel-shopify[v17.1.0, ..., 17.1.x-dev] require laravel/framework ^7.0 || ^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0 ).
     - Root composer.json requires osiset/laravel-shopify ^17.1 -> satisfiable by osiset/laravel-shopify[v17.1.0, v17.1.1, 17.1.x-dev].
```

### Steps to Reproduce
1. Install laravel package, version 9
2. Run package installation

###Context
Laravel Version: v9.0
PHP Version: v8.0.8

There is approximate information when it will be available on the new version of laravel or how to solve the problem on your own without changing the version of laravel?

**Comment by rome2o** [comment]
This is because the package currently don't seem to support Laravel 9.  However, some folks are working to update it to Laravel 9:
https://github.com/osiset/laravel-shopify/pull/1100

If you face issues, you're more than welcome to share back to the community which might help prepare any roadmap.

**Comment by Kyon147** [comment]
Hi @petrov-codedot 

The package is not currently support for Laravel 9 but as @rome2o has said there is an open PR for it at the moment. 

So until it is merged in, you'll need to use Laravel 8 or you would have to edit the package.json yourself to allow 9.
