### ISSUE TITLE
Cannot install draft app on my development store

### ISSUE THREAD

**Issue by golaod** [osiset/laravel-shopify#1129]
## Expected Behavior

After setting up a draft public app, when I click on 'test on development store' my application should be installed.

## Current Behavior

It's not being installed.

## Failure Information

Getting redirected to shopify page with message "There’s no page at this address" which from what I checked on the internet, is an issue on my side...but not sure what type.

### Steps to Reproduce

1. Follow up instruction on how to install laravel manually
2. Add this package to composer
3. Follow instruction of that plugin (publish, config, User model changes, routes, csrf)
4. Create draft of public app
5. Try to test it on development store

### Context

The only thing I can say is that it works ok if I set up custom app instead of draft of public app and it works for draft of public app when I go to: https://mydomain.com/authenticate?shop=my-shop

### Failure Logs

There are no logs, cause shopify doesn't provide any and I don't see any in my PHP app.

**Comment by Kyon147** [comment]
That sounds like you have no exposed your app correctly in the settings for the app url and the redirect whitelist url.

Try following the wiki steps https://github.com/osiset/laravel-shopify/wiki/Installation but it does not sound like a package isue.
