### ISSUE TITLE
Using Laravel Socialite in the App

### ISSUE THREAD

**Issue by SkullDark1** [osiset/laravel-shopify#1131]
Hello,

As we can't use redirect(), I am looking to use this 

`return Socialite::driver('facebook')->redirect();` 

Therefore, I tried many ways, but I couldn't.

![image](https://user-images.githubusercontent.com/73682305/167489321-b0a40c74-bc2b-458f-bb04-e386422bcb72.png)

* Package Version: 17
* Laravel Version: 8

**Comment by Kyon147** [comment]
Hi @SkullDark1

The package has not really been set up in mind to work alongside Socialite as we handle the OAUTH for Shopify itself as part of the auth flow.

Going to close this ticket for now as it is not an issue or in scope with the package.
