### ISSUE TITLE
Send reports in mails

### ISSUE THREAD

**Issue by TackyGautam** [osiset/laravel-shopify#1132]
Hello @osiset I want to create a cron which will create the reports and send the reporta to shopify store mail address for every user in the table having a particular plan_id.

I checked whole internet but didnt get any point. please let me knkw ASAP.. pls pls. I have to implement it on 4 running projects. I am using Osiset laravel.

**Comment by ncpope** [comment]
@TackyGautam this isn't really related specifically to this package and might fall out of scope.

You might want to take a look into more general Laravel cron job guides and guides on sending email using Laravel.

**Comment by Kyon147** [comment]
Hi @TackyGautam 

This is for issues relating to the package, you'd be better off putting your question on StackOverflow rather on here.

I'll give you some direction on how I'd implement it.

- Create a job that creates the reports for each user_id in your DB. Then this job sends those reports to a mailable job.
- Create another job that uses that data and send the mail. You can use the laravel mailable set up or any other service you want.
- You could also store reports sent to each user ID, to keep track of successful vs not successful reports sent to try and add some resend logic in too.
- Finally, set up the first "report generating job" up in the Scheduler to run however often you want. 

I'm going to close this ticket now, so feel free to take this info to help you set up a question on StackOverflow.
