### ISSUE TITLE
Inertia.js is untestable with Laravel feature tests

### ISSUE THREAD

**Issue by grahamsutton** [osiset/laravel-shopify#1134]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I should be able to use `$response->assertInertia(...)` without getting an error.

## Current Behavior

Currently I am trying to write a feature test that keeps resulting in a `Not a valid Inertia response.`.

In the `AuthController@token` action where `/authenticate/token` goes to, it appears that the app renders its own view, and I believe this is interfering with the ability of my test to use `$response->assertInertia(...)` because it renders a completely different view before it even reaches the controller.

Initially, I tried to test this by making a request directly to the route, but this is counter-intuitive as it doesn't simulate the _real_ scenario which requires authentication.

### Steps to Reproduce

1. Install fresh Laravel project
2. Install Inertia.js
3. Create a controller and route that should render an Inertia component.
4. Create a feature tests and use `$response->assertInertia(...)` to assert the component gets rendered.
5. Observe "Not a valid Inertia response." failure.

### Context

* Package Version: v17.1
* Laravel Version: v8.75
* PHP Version: 8.1
* Using a toolset (Docker, Laradock, Vagrant, etc.): Inertia.js, Laravel Sail

### Failure Logs

```sh
  • Tests\Feature\Boxes\ListBoxesTest > can list boxes
  Not a valid Inertia response.

  at vendor/inertiajs/inertia-laravel/src/Testing/AssertableInertia.php:34
     30▕             PHPUnit::assertArrayHasKey('props', $page);
     31▕             PHPUnit::assertArrayHasKey('url', $page);
     32▕             PHPUnit::assertArrayHasKey('version', $page);
     33▕         } catch (AssertionFailedError $e) {
  ➜  34▕             PHPUnit::fail('Not a valid Inertia response.');
     35▕         }
     36▕ 
     37▕         $instance = static::fromArray($page['props']);
     38▕         $instance->component = $page['component'];

      +2 vendor frames 
  3   tests/Feature/Boxes/ListBoxesTest.php:34
      Illuminate\Testing\TestResponse::__call()


  Tests:  1 failed
  Time:   0.13s
```

and my test looks like:

```php

    use Inertia\Testing\AssertableInertia as Assert;
    ...

    /** @test */
    public function can_list_boxes()
    {
        $this->followingRedirects();

        $user = User::factory()
            ->hasBoxes(5)
            ->create([
                'email' => 'test.myshopify.com'
            ]);

        $path = url()->tokenRoute('boxes.index', ['shop' => 'test.myshopify.com']);

        $response = $this->actingAs($user)->get($path);

        $response->assertStatus(200);

        $response->assertInertia(fn (Assert $page) => $page
            ->component('Boxes/List')
            ->has('boxes', 5)
        );
    }
```

and the route in `routes/web.php`:

```php
Route::middleware('verify.shopify')->group(function () {
    Route::get('/boxes', 'BoxesController@index')->name('boxes.index');
});
```

**Comment by grahamsutton** [comment]
Closing this issue in favor of #1141 which addresses the issue more generally.

**Comment by sahilcrawlapps** [comment]
Hello, Have you faced any problems building shopify apps with this package and inertia both ? I am thinking to use inertia for my next project so asking.
