### ISSUE TITLE
Payment app? 

### ISSUE THREAD

**Issue by ashawkat** [osiset/laravel-shopify#1136]
Hi there,

Can you let me know if I can use this app to build a Shopify payment processor app like Stripe or PayPal? I want to create a payment app that is public & used by all as a product. Can you let me know if it's doable & if yes then any doc or guideline would be appreciated.

Regards

**Comment by Kyon147** [comment]
I don't know the requirements for a payment app but a quick look on https://shopify.dev/apps/payments#how-payments-apps-work there's a lot of stuff around PCI so you'd need to make your own decision on if you could use this package to fulfil their requirements.
