### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'worker-src'

### ISSUE THREAD

**Issue by unlimix** [osiset/laravel-shopify#1153]
Hi, all

A have some problem with Safari brouser.

![problem](https://user-images.githubusercontent.com/3293956/173608913-490e05fd-98dc-461c-aab8-3fe778b9bd7e.jpg)

Please help me to fix this issue.

**Comment by Kyon147** [comment]
Hi @unlimix 

Please provide more information, as the ticket is quite old I will close this for now but reopen if you still have the problem and can provide more detail.
