### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by AcriCAA** [osiset/laravel-shopify#1157]
Will there be forthcoming support for Laravel 9? 

Composer is throwing this message:
osiset/laravel-shopify[v17.1.0, ..., 17.1.x-dev] require laravel/framework ^7.0 || ^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).

**Comment by RensBruil** [comment]
Up for visibility :)

**Comment by dutsik** [comment]
up

**Comment by fjarrett** [comment]
Security fixes for Laravel 8 will stop in about 5 months from now.

<img width="897" alt="Screen Shot 2022-08-18 at 4 34 24 PM" src="https://user-images.githubusercontent.com/522158/185499355-ff19496a-23f5-4b98-82c7-2923ffaa1f67.png">

**Comment by fjarrett** [comment]
There is a PR for this in #1100.

If you need an immediate workaround until that PR is merged...

Update `composer.json` with:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:steveperrycreative/laravel-shopify.git"
    }
  ],
  "require": {
    "osiset/laravel-shopify": "dev-master"
  }
}
```

Then:

```
composer install
```

**Comment by Kyon147** [comment]
Duplicate, so closing.
