### ISSUE TITLE
Laravel 9 

### ISSUE THREAD

**Issue by jalpab** [osiset/laravel-shopify#1159]
Laravel 9 version does not support to osiset/laravel-shopify package for shopify so any suggestions for this? and please can you give any approx time when an updated version of this package is launching?

**Comment by zeeshanhaider6236dev** [comment]
Laravel 9 its still in pending, i hope this will be review and osiset new release available with laravel 9

**Comment by jalpab** [comment]
@zeeshanhaider6236dev any other option to use shopify in laravel 9

**Comment by KingFisch** [comment]
is there still no update from devs?

**Comment by zeeshanhaider6236dev** [comment]
Yes

**Comment by fjarrett** [comment]
Duplicate of #1157
