### ISSUE TITLE
Redirection issue, 404 after install using version 17.1, version 16.0.5 works fine

### ISSUE THREAD

**Issue by jithinjoyj4** [osiset/laravel-shopify#1161]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

After install authenticate successfully & show welcome message in view, works fine in version 16 apps, getting 404 in version17

## Current Behavior

Followed all the installation procedures, package version 17.1 installed on fresh laravel 8, project is inside a subfolder in public_html, after install showing 404, I think its redirecting to server root instead the subfolder, app url and redirection url in app setup is correct, everything works with version 16 in same situation

## Failure Information

Getting 404 after install when using version 17, console error shows it redirecting to server root instead the subfolder, screenshots are provided

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install laravel 8
2. install package by following wiki
3. put the project folder inside a subfolder in public_html, install in a development store

any help would be appreciated, thanks

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.1
* Laravel Version: v8.75
* PHP Version: v7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): litespeed server, cyberpanel

### Failure Logs

![image_2022_06_28T11_54_23_721Z](https://user-images.githubusercontent.com/57803136/176173701-1dbff739-e728-4ed6-bacd-d66c1e00e6de.png)

![image_2022_06_28T11_56_23_954Z](https://user-images.githubusercontent.com/57803136/176173793-da707ac3-db08-4965-8071-b53fa9c2af25.png)

**Comment by mhmdbdwy** [comment]
same here

**Comment by tsujihidetaka** [comment]
same with Nginx.
so I have changed to Apache then it is solved.
I guess you need to do 

> For Nginx, and Laravel Forge, you must specifically comment-out or remove the line below from the Nginx configuration:
> add_header X-Frame-Options "SAMEORIGIN";
> 

https://github.com/osiset/laravel-shopify/wiki/Installation#appbridge

**Comment by Kyon147** [comment]
Closing as a solution has been provided.
