### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted.

### ISSUE THREAD

**Issue by manasirfan** [osiset/laravel-shopify#1165]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior
in laravel 8 am using osiset/laravel-shopify package . when i hit shopify url its always return error, Oauth error invalid_request: The redirect_uri is not whitelisted

## Current Behavior

![image](https://user-images.githubusercontent.com/80257319/177568593-85d91189-de14-46ba-b8cc-f85964a2a154.png)

I am using Ngrok for tunneling my connections

App Url  https://260b-72-255-1-66.in.ngrok.io/
Redirect Url  https://260b-72-255-1-66.in.ngrok.io/shopify

error page url
https://glaviso.myshopify.com/admin/oauth/authorize?client_id=0274500b933f4db1ba16521161159256&scope=read_products%2Cwrite_products&redirect_uri=https%3A%2F%2Flocalhost%3A8000%2Fauthenticate
when am changing the redirect url custom its work like
https://glaviso.myshopify.com/admin/oauth/authorize?client_id=0274500b933f4db1ba16521161159256&scope=read_products%2Cwrite_products&redirect_uri=https://260b-72-255-1-66.in.ngrok.io/shopify

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

*Package Version: v17.1
*Laravel Version: v8.75
*PHP Version: v8.1.5

**Comment by jammy-git** [comment]
I believe your redirect URL should be https://260b-72-255-1-66.in.ngrok.io/authenticate

Make sure you've created this route in your web routes file as per the install instructions.

**Comment by manasirfan** [comment]
thanks for helping
