### ISSUE TITLE
Add Publishing Views Tag

### ISSUE THREAD

**Issue by ronnorthrip** [osiset/laravel-shopify#1170]
I'd suggest that we add the ability to publish the views so people can override them easier and so we can match other packages. 

```
php artisan vendor:publish --provider="osiset\laravel-shopify" --tag=views
```

Should copy the files from src/resources/views into APP/resources/vendor/shopify-app.

I point this out not only to follow the dev ex from other packages but also because the dir name isn't the exact same as the vendor package.

Thoughts?

**Comment by dev-talha-anwar** [comment]
it is already done you can use use php artisan vendor:publish command to check the list and publish the views using shopify-views tag

**Comment by ronnorthrip** [comment]
views would be better than shopify-views - but at least put that in the docs please

**Comment by Kyon147** [comment]
You can override views already in packages, as you just need to put the vendor folder inside the views folder and then the file you wish to override.

It would look something like this

````
- resources 
- - vendor
- - - shopify-app
- - - - layouts 
- - - - - default.blade.php
````
