### ISSUE TITLE
Call Shopify Wehbook without laravel job and queue

### ISSUE THREAD

**Issue by BhuvneshSoniApporio** [osiset/laravel-shopify#1175]
Hii Developers,

In my application i don't want to run queue to listen continuously. So please help me how can i configure custom webhook that will run from shopify after an event like after create the order etc.

**Comment by BhuvneshSoniApporio** [comment]
@osiset Could you please help on this.

**Comment by Kyon147** [comment]
@BhuvneshSoniApporio please move over to discussion if you want to request help or start a conversation.

Please keep issues relating to package bugs etc not for seeking help. This helps us to narrow down actual issues more quickly.

**Comment by BhuvneshSoniApporio** [comment]
Hi @Kyon147  There is an issue with package that i facing. I have removed all the webhooks from list those are install while installing app. 
Now i am getting exception message and that is

Class '\App\Jobs\ShopRedactJob' not found

I am getting this exception continuously. Could you please help me to identify this issue. Also let me know the reason of occurring this.

**Comment by Kyon147** [comment]
You need to create this job, as Shopify will fire this webhook usually 3 days after the uninstall.
