### ISSUE TITLE
App must set security headers to protect against clickjacking

### ISSUE THREAD

**Issue by manasirfan** [osiset/laravel-shopify#1176]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

when am review our app from shopify that show this issue before submitting 

There was an error installing your app. The app must be installed to perform the security check. We expected OAuth to be initiated at https://app-security.myshopify.com/admin/oauth/authorize but were redirected to https://mysite.com/login. Your app must request installation immediately after clicking "add app." Apps must request shop access during installation, or reinstallation if the app was previously uninstalled from the shop.

## Current Behavior
this is my website first user login in our site 
![image](https://user-images.githubusercontent.com/80257319/181203060-cf247141-5a68-4550-9cf2-e9a5ba07c652.png)

after login then user go this page and put store url and fetching the products against the store

![image](https://user-images.githubusercontent.com/80257319/181203803-b43071e4-7bad-4dfb-aeaa-c2732ffddd09.png)

But am not find what's the shopify app are required for approve the app

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

*Package Version: v17.1
*Laravel Version: v8.75
*PHP Version: v8.1.5

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by manasirfan** [comment]
Anyone can help me for solving this issue?.
Thanks in advance.

**Comment by enmaboya** [comment]
it has nothing to do with the package, you can do it at the application level

**Comment by enmaboya** [comment]
You can take an implementation from here 
https://github.com/osiset/laravel-shopify/pull/1178

but it has nothing to do with the package and can be exposed by the application.

**Comment by manasirfan** [comment]
Hi, thanks for reply.
Am follow your steps but we changing in the vendor file, therefore changing not add on live please guide me more,
Thanks in advance !

**Comment by manasirfan** [comment]
@enmaboya sir kindly help me !

**Comment by tanseercena** [comment]
@manasirfan You can check this: https://github.com/osiset/laravel-shopify/issues/1070#issuecomment-1039959161

I created the same and it fixed the issue.

I hope that this will help you :)

**Comment by manasirfan** [comment]
hi @tanseercena am using the same middleware but again rejected, middleware used globally ,kindly solving this issue


 protected const HEADER_FORMAT = 'frame-ancestors %s %s';
     protected const ADMIN_SHOPIFY_URL = 'https://admin.shopify.com';
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);
        if ($response instanceof Response && !$request->ajax()) {
            if ($request->has('shop')) {
                $shopDomain = ShopDomain::fromNative($request->get('shop'));
            }elseif ($request->user() instanceof User) {
                $shopDomain = $request->user()->getDomain();

            }else{
                $shopDomain = ShopDomain::fromRequest($request);

            }

            if ($shopDomain instanceof ShopDomain) {
                $response->header('Content-Security-Policy', sprintf(self::HEADER_FORMAT,'https://'. $shopDomain->toNative(), self::ADMIN_SHOPIFY_URL));
            }

        }
        return $response;
    }

**Comment by tanseercena** [comment]
@manasirfan Did you add it in web middlewares in Kernal.php?

**Comment by manasirfan** [comment]
@tanseercena oops am added another middleware not group,please check now its fine ?
 protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \App\Http\Middleware\ContentSecurityPolicy::class,

        ]
];

**Comment by Kyon147** [comment]
We wll try and get https://github.com/osiset/laravel-shopify/pull/1178 into the next release which should help.
