### ISSUE TITLE
App block using scripttag in vintage theme

### ISSUE THREAD

**Issue by Sajidali123** [osiset/laravel-shopify#1183]
Hello, Can anybody help me.

i am get stuck on integrating **scripttag** in shopify app for vintage theme basically the aim is that my app use theme-app-extension functionality for 2.0 theme and for vintage themes my app will use **scripttag** for app block.
so i am done with theme-app-extension but stuck on **scripttag** below is the error i am getting after adding **scripttag** code in shopify-app.php file. The error i am getting right after install app.

Illuminate\Database\Grammar::parameterize(): Argument #1 ($values) must be of type array, int given, called in /home/ 

**Note**: i am done with permission for **scripttag**

**Comment by Kyon147** [comment]
@Sajidali123 - the error is telling you the issue but without more context around your code it will be hard to provide any meaningful help.

**Comment by Kyon147** [comment]
Closing as a stale issue, reopen if you still have the problem
