### ISSUE TITLE
App Authentication issue

### ISSUE THREAD

**Issue by yogeshausp** [osiset/laravel-shopify#1193]
I have redirect my domain to public by using .htaccess file in root folder

<IfModule mod_rewrite.c>
# That was ONLY to protect you from 500 errors
# if your server did not have mod_rewrite enabled

RewriteEngine On
# RewriteBase /
# NOT needed unless you're using mod_alias to redirect

RewriteCond %{REQUEST_URI} !/public
RewriteRule ^(.*)$ public/$1 [L]
# Direct all requests to /public folder

</IfModule>

But now when I have installed my app it gives authentication error.

![Screenshot_7](https://user-images.githubusercontent.com/99256150/186837471-b61f4cd9-cbde-4f09-bb9a-1f58a587835b.png)

Kindly provide the solution.

Thanks

**Comment by Kyon147** [comment]
@yogeshausp so you have this issue still as #1190 shows your app working.

**Comment by yogeshausp** [comment]
Yes. I have still this issue when I install the app on dev store.

**Comment by Kyon147** [comment]
Can you provide more information on how to replicate?  Does it happen all the time or only sometimes?

**Comment by yogeshausp** [comment]
Actually I have develop the custom app on this partner account first time. The server used is linux server.  But when I have installed the app on development store it gives the error.

**Comment by Kyon147** [comment]
It sounds like an issue somewhere on the server side potentially. Does the app work locally?

**Comment by yogeshausp** [comment]
Yes

**Comment by Kyon147** [comment]
If it works locally, you have an issue somewhere on your server setup - we can't really help with the devops side as there's a lot of variation from server to server.
