### ISSUE TITLE
App Installed issue (Return value of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet() )

### ISSUE THREAD

**Issue by beingak** [osiset/laravel-shopify#1202]
Hello @osiset Team,

I have issue occur when i installed Shopify app. its The error occur is. 
Can you please let me know the issue ASAP.

TypeError
Return value of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet() must be an instance of Osiset\BasicShopifyAPI\mixed, string returned

**Comment by Kyon147** [comment]
Please update to v17.2.0.
