### ISSUE TITLE
App install issue Return value of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet() must be an instance of Osiset\BasicShopifyAPI\mixed, string returned

### ISSUE THREAD

**Issue by CodeByVijay** [osiset/laravel-shopify#1203]
![Screenshot from 2022-09-07 16-23-15](https://user-images.githubusercontent.com/94886827/188861501-fa382973-2aa4-444c-bb9e-998b6c064f1a.png)
Hey! Developers

Please find this issue shopify app installation time.

Issue :
Return value of Osiset\BasicShopifyAPI\ResponseAccess::offsetGet() must be an instance of Osiset\BasicShopifyAPI\mixed, string returned

**Comment by CodeByVijay** [comment]
![Screenshot from 2022-09-07 16-23-15](https://user-images.githubusercontent.com/94886827/188861264-ac9cfe87-d4cf-4cc9-821c-1a21f40e8ec3.png)

**Comment by Kyon147** [comment]
Please update to v17.2.0 as this should be fixed in the latest release.
