### ISSUE TITLE
Shopify non embedded app are unpublished because of shopify 

### ISSUE THREAD

**Issue by simoni2cool** [osiset/laravel-shopify#1206]
Hii, my laravel app in shopify non embedded app are unpublished because of shopify tell us that "Use OAuth to ask for scope permissions immediately after merchants add your app. 

Check and troubleshoot your app's OAuth by reinstalling your app on your test store using this method. After you've installed your app on a development store, make sure you can uninstall and reinstall that app on the same shop." I used osiset library for authentication... i don't know how can i fix it.

**Comment by Kyon147** [comment]
This package does not currently support non-embedded apps. So you would need to either be embedded with this package or create your own logic to handle it.  There's an open PR but it is on hold for the most part at the moment #929
