### ISSUE TITLE
Undefined array key "shop_auth_provider"

### ISSUE THREAD

**Issue by hungryforjs** [osiset/laravel-shopify#1213]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

Ran:  `composer require osiset/laravel-shopify` 
## Expected Behavior
Should be installed without any issues.

## Current Behavior
Fails with error:
```
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
Class App\Http\Mapping\Mapping_Base located in ./app/Http/Mapping/MappingBase.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Http\Mapping\Mapping_Order located in ./app/Http/Mapping/MappingOrder.php does not comply with psr-4 autoloading standard. Skipping.
Class App\checklistdetail located in ./app/Models/checklistdetail.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException 

  Undefined array key "shop_auth_provider"

  at vendor/osiset/laravel-shopify/src/Util.php:169
    165|     public static function getShopifyConfig(string $key, $shop = null)
    166|     {
    167|         $config = Config::get('shopify-app', []);
    168| 
  > 169|         $config['user_model'] = Config::get("auth.providers.{$config['shop_auth_provider']}.model", Config::get('auth.providers.users.model'));
    170| 
    171| 
    172|         if (Str::is('route_names.*', $key)) {
    173|             // scope the Arr::get() call to the "route_names" array

      +12 vendor frames 
  13  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by hungryforjs** [comment]
I haven't published any config yet. Just running the composer require results in this error.

**Comment by Kyon147** [comment]
If you are upgrading, have you followed the steps in the [upgrading wiki? ](https://github.com/osiset/laravel-shopify/wiki/Upgrading)

it sounds to me that as you are upgrading and it is not a new install, you are just missing upgrade steps like the new additions to the configs.  v16 to v17 was a big upgrade too, so I really suggest you check out the upgrading wiki if you have not.

Does not sound like any PRs are needed.

**Comment by hungryforjs** [comment]
I added the array key value pair as provided above. So I am sure either the error should change or it should work but I am still getting the same error.

**Comment by hungryforjs** [comment]
I had to add the `config:clear` before running this code.
We might have to add the `config:clear` command to be invoked because changes cannot be read by the config file.

**Comment by Kyon147** [comment]
Glad you got it sorted.

**Comment by hungryforjs** [comment]
> Glad you got it sorted.

Do we need a config clear command to be called programmatically inside `Util.php`. Might be helpful while upgrading the code. 
I do not mind putting up a PR for this.

**Comment by Kyon147** [comment]
Hi @hungryforjs 

I don't believe so, it's common practice for devs to clear the config if you change it. Not just for this package but for Laravel configs in general.

**Comment by hungryforjs** [comment]
> Hi @hungryforjs
> 
> I don't believe so, it's common practice for devs to clear the config if you change it. Not just for this package but for Laravel configs in general.

Everytime I ran the command:

**Comment by Kyon147** [comment]
You should be updating using `composer update` and just changing the version in `composer.json` rather than `composer require osiset/laravel-shopify` if you already have the package installed. 

You likely got the error because you tried to include the package again even though you already had it installed.
