### ISSUE TITLE
CSRF token mismatch error in POST call using Ajax

### ISSUE THREAD

**Issue by yogeshausp** [osiset/laravel-shopify#1216]
Response give error 419 on post method call from ajax when I have uploaded csv file using ajax

## Expected Behavior

It will upload the CSV.

## Current Behavior

Error 419 csrf mismatch

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: Latest
* Laravel Version: 7.2
* PHP Version: 7.4
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
The CSRF is not used anymore because of the session token that Appbridge uses to validate all request to Shopify. You can read here if you are missing the global flag https://github.com/osiset/laravel-shopify/wiki/Installation#csrf
