### ISSUE TITLE
17.2 In the package in which I am facing the problem 302 status, I send the request or delete the error value, this is a problem facing

### ISSUE THREAD

**Issue by faisalaltaf** [osiset/laravel-shopify#1221]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

![image](https://user-images.githubusercontent.com/56771761/192488792-ed4bf2d2-d56b-418e-b8ba-e0bc8e2c1ddc.png)

* Package Version: 17.2
* Laravel Version: 8.0
* PHP Version: 7.2.5
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure [Logs](### url)

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
Can you provide code of your routes etc, did you have the middleware on them?

**Comment by Kyon147** [comment]
@faisalaltaf can you provide more information please, code snippets etc as it is hard to debug with just that screenshot at the moment.

**Comment by Kyon147** [comment]
Closing as stale now.
