### ISSUE TITLE
App must set security headers to protect against clickjacking && App must verify the authenticity of the request from Shopify.

### ISSUE THREAD

**Issue by DeveloperHashmi** [osiset/laravel-shopify#1225]
## Expected Behavior
App must be accepted by Shopify App Store. Please guide us that our app can submitted earliest. @osiset and @Kyon147 

## Current Behavior
Getting error mail from Shopify App Store.

There was an error installing your app. The app must be installed to perform the security check. We expected OAuth to be initiated at https://app-security.myshopify.com/admin/oauth/authorize but were redirected to https://app-security.myshopify.com/admin/apps/6845cd34467e62fc1570f47c8265a2a0/authenticate/token?shop=app-security.myshopify.com&target=%2F%3Fhost%3DYXBwLXNlY3VyaXR5Lm15c2hvcGlmeS5jb20vYWRtaW4. Your app must request installation immediately after clicking "add app." Apps must request shop access during installation, or reinstallation if the app was previously uninstalled from the shop. [Learn more about authentication in our developer documentation](https://shopify.dev/apps/store/requirements#a-authentication)

![image](https://user-images.githubusercontent.com/51310612/193398017-e01125b1-edf2-4f9e-9bea-2fce8f195445.png)

### Steps to Reproduce
Several times I submitted the App to the Shopify Store and got rejection from there.

### Context

* Package Version: v ^17.1
* Laravel Version: v ^8.65
* PHP Version: v ^8.0

**Comment by Kyon147** [comment]
Hey @DeveloperHashmi 

Clickjacking has been fixed if you update to `17.2.0`.

The other issue looks like the auth/token which runs before each request is being picked up on the OAUTH which is not allowed.

We may have to tweak this but I've not looked at the code for the token route, so @osiset will have more insight.

**Comment by Kyon147** [comment]
@osiset - looking into this a bit more - I think blade might have to be killed off...

<img width="968" alt="image" src="https://user-images.githubusercontent.com/32519106/193402870-1240be8a-b688-4b4c-8e2b-2966becbfaa0.png">

Shopify are leaning towards SPAs - they do say Turbolinks can be used but I've never used it. The biggest problem at the moment is the /auth/token route can no longer happen after OAUTH. So we might need to get that SPA PR out as it will help move the app package to be more user friendly with SPA and bypasses the need for the token request between each route anyway which would then solve the installation rejections.

**Comment by DeveloperHashmi** [comment]
Hi @Kyon147,
Thanks for the reply, May I know the expected timeline for this fixed.

I'm already using 17.2.0 (SS attached for your reference).

FYI : I already followed the instruction from #1070 and #1176 for security headers to protect against clickjacking.

![image](https://user-images.githubusercontent.com/51310612/193403399-51a92e71-10a0-4544-a468-210ee221b419.png)

**Comment by Kyon147** [comment]
@DeveloperHashmi - the fix is moving to an SPA app really and then we push out a new PR that bypasses the blade token requirement. 

Are you using react or vue to scaffold your frontend?

**Comment by DeveloperHashmi** [comment]
I'm not using react or vue. I am using Laravel blade itself for view. @Kyon147

**Comment by Kyon147** [comment]
I'll see what @osiset thinks but we might have to get the session token after hitting them home route (to avoid the oauth  redirect issue) but osiset has a deeper understanding of this package's auth and how possible this is.

With Shopify itself saying multi page apps are not supported unless you make it function like an SPA they are moving away from multipage apps.

**Comment by Kyon147** [comment]
@osiset - I personally don't use the Blade templates with this package. I use VueJS and have my own Polaris component library that I maintain.

So it might be worth leaning towards that has a requirement, more so with the "frontend_engine" feature we just implemented. 

My latest app with the new version, is going into review soon - so if it passes review and ends on the store we have a real world example to base it on.

I'm currently updating working on a "vue-app-bridge" package too which works the same as their react one.

**Comment by Kyon147** [comment]
Going to close this for now as it looks like blade templates don't fit at the moment with the apps overall.

**Comment by Kyon147** [comment]
Just updating here, i've had an app pass the security review using v17.3.1 but importantly, it passed because it was using VueJs as the frontend and did not use the auth/token route.

cc @osiset
