### ISSUE TITLE
shopify appuinstalljob problem

### ISSUE THREAD

**Issue by yasminekamal** [osiset/laravel-shopify#1233]
* this is the error in log file in laravel project when i am trying to unistall  shopify app 
* Argument 1 passed to Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob::__construct() must be an instance of Osiset\ShopifyApp\Contracts\Objects\Values\ShopDomain, string given, 

* "php": "^7.2.5"
* "laravel/framework": "^7.0"
* "osiset/laravel-shopify": "^11.5"

any solution for this problem?

**Comment by Kyon147** [comment]
@yasminekamal - your PHP, laravel and laravel-shopify package are too old. Can you try using the newer versions. We are not on `v17.3.x` so you are 6 major versions behind.

**Comment by Kyon147** [comment]
Closing as issue is stale, reopen if you need to.
