### ISSUE TITLE
Missing host parameter on getConfig(api_key) call

### ISSUE THREAD

**Issue by mingppl** [osiset/laravel-shopify#1239]
## Expected Behavior

On Http/Middleware/AuthToken.php line 93, the getConfig('api_key') should receive the shop domain parameter so config_api_callback function can support api_key / api_secret pairs for custom apps.

* Package Version: v15.1.1

**Comment by Kyon147** [comment]
Hi @mingppl - you need to update your package version to the latest which is `v17.3.1`
