### ISSUE TITLE
ORDER_TRANSACTIONS_CREATE Webhook not register on shopify

### ISSUE THREAD

**Issue by Pramod-HulkApps** [osiset/laravel-shopify#1241]
Hello guys,

Webhook is not registered on Shopify with the production URL. can anyone please tell me what I am doing wrong?
`'webhooks' => [       
        [
            'topic' => 'ORDER_TRANSACTIONS_CREATE',
            'address' => env('APP_URL').'/webhook/orders-transactions-create'
            //'address' => 'https://c7db-49-36-49-213.ngrok.io/webhook/orders-transactions-create'            
        ]        
    ],`
    
    For local it is working.
    Thank you

**Comment by Kyon147** [comment]
Have you tried setting the fallback on the `env()` to your prod url to see if that works?

**Comment by Pramod-HulkApps** [comment]
Yes I did it. 
Now I register Webhook using webhook Installer by manually calling it. and its resolved but when I tried using the app install it didn't work.

**Comment by Pramod-HulkApps** [comment]
Closing the issue. as it fixed using webhook installer
