### ISSUE TITLE
How to update webhook URL's for old stores?

### ISSUE THREAD

**Issue by ingalesachin7** [osiset/laravel-shopify#1243]
Hello, I have switched from ruby to Laravel for the app already running and also changed the app URL, so already registered webhook how do we update with new url for all installed stores?

**Comment by Kyon147** [comment]
@ingalesachin7 if you have stores on another package that you are migrating, you may have to run a custom script that updates the existing stores webhook, to the new one.

Webhooks do run at `authenticate` but the store has to access the app for that to happen.

**Comment by Kyon147** [comment]
Going to close this as it is not an issue but feel free to reply or open up a discussion.
