### ISSUE TITLE
application/json header in auth.shop middleware

### ISSUE THREAD

**Issue by awebartisan** [osiset/laravel-shopify#164]
I am trying to return json response from my controller but its being returned `text/html; charset=UTF-8`. On further digging, I found out that it only happens if I apply auth.shop middleware, as I remove it proper json response is returned. Kindly look into it. <br>
![image](https://user-images.githubusercontent.com/29105478/50735987-96ac6780-11d8-11e9-95f5-b44786ee0482.png)

**Comment by ohmybrew** [comment]
Hmm will look into this. Are you doing a Ajax call? Maybe I can check if the request is Ajax, if so, I'll leave the headers alone.

**Comment by awebartisan** [comment]
Yes. Ajax request using Axios.

**Comment by ohmybrew** [comment]
Great! I think this will be a easy fix then :) stay tuned.

**Comment by reijovosu** [comment]
I have same issue and this is still giving same error. Withaout middleware it is working

**Comment by ohmybrew** [comment]
Are you using the release I just issued out? I have a check in there for Ajax requests

**Comment by reijovosu** [comment]
Yes I am using.

I fount that React fetch needs to include  "X-Requested-With": "XMLHttpRequest" headers. Otherwise ajax() function returns false

fetch("/this/is/url", {
            credentials: "include",
            withCredentials: true,
            headers: {
                "Content-Type": "application/json",
                "X-Requested-With": "XMLHttpRequest"
            }
        })

**Comment by ohmybrew** [comment]
I'll add "wantsjson" method from laravel to it, that'll fix it
________________________________

**Comment by ericnkatz** [comment]
@ohmybrew this looks like its still not quite right.

returning something like in a controller using the middleware,

`return response()->json(Model::all());`

gives a response that is text/html; charset=UTF-8 but looks like
```HTTP/1.1 200 OK
Cache-Control: no-cache, private
Content-Type:  application/json
Date:          Fri, 25 Jan 2019 05:39:47 GMT

[]```
