### ISSUE TITLE
install webhook not working afte April 09, 2019 | Shopify Admin API Versioning

### ISSUE THREAD

**Issue by rakib78** [osiset/laravel-shopify#231]
Please check.

**Comment by ohmybrew** [comment]
what exactly is the issue

**Comment by rakib78** [comment]
When i install app on a new development store, webhook not adding on store.

**Comment by fyroc** [comment]
Some webhooks just don’t work on local instances. You’ll need to test on a staging or production server.

**Comment by fyroc** [comment]
@ohmybrew Looks like I'm also having this issue. With version 4.2.1, none of my jobs are firing. They're not even failing.

**Comment by ohmybrew** [comment]
@fyroc Odd both of yours are failing, especially on 4.2 since that's before any major changes I've introduced with the new user sessions and such.

whats failing exactly do you know? is the the job not firing itself, or an API call? what version of Laravel is it running on? maybe I can try and replicate it.

**Comment by fyroc** [comment]
@ohmybrew sorry, I'm on 6.0 not 4.2, I was looking at my working app. It's hard to debug.. usually I can see what's happening by turning off my listener and reviewing the jobs in the jobs table. However, the web hooks are not even getting to the jobs table.

```
 "php": "^7.1.3",
  "laravel/framework": "5.7.*",
  "ohmybrew/laravel-shopify": "^6.0.0",
```

```
SHOPIFY_SHOP_REDACT="https://boxsy.loc/webhook/shop-redact"
SHOPIFY_CUSTOMERS_REDACT="https://boxsy.loc/webhook/customers-redact"
SHOPIFY_WEBHOOK_1_TOPIC="app/uninstalled"
SHOPIFY_WEBHOOK_1_ADDRESS="https://boxsy.loc/webhook/app-uninstalled"
```

shopify-app.php
https://gist.github.com/fyroc/733744827c91867dd8f031a37bda7870

**Comment by fyroc** [comment]
@ohmybrew did this help at all? Am I going to need to downgrade to 4.2?

**Comment by ohmybrew** [comment]
@fyroc Thanks for the info. Going to spin up a fresh instance tonight and see whats up. Flow-wise I see nothing wrong at the moment... line 71 in Traits/AuthControllerTrait fires the jobs on auth.

I'll get to the bottom of it. And theres no errors in log files or anything like a 500 error?

**Comment by fyroc** [comment]
@ohmybrew I get nothing. If you can't replicate it via a fresh install, I suggest starting with 4.2.1 and updating to 6.0 manually, since that was my process.

**Comment by ohmybrew** [comment]
Yup good idea.On May 7, 2019 13:26, Cory Fail <notifications@github.com> wrote:@ohmybrew I get nothing. If you can't replicate it via a fresh install, I suggest starting with 4.2.1 and updating to 6.0 manually, since that was my process.

**Comment by ohmybrew** [comment]
@fyroc  On initial try of fresh install I'm able to see the webhook request go through hmm.

Can you add

```php
        /*
    |--------------------------------------------------------------------------
    | Shopify API Grant Mode
    |--------------------------------------------------------------------------
    |
    | This option is for the grant mode when authenticating.
    | Default is "offline", "per-user" is available as well.
    | Note: Install will always be in offline mode.
    |
    */

    'api_grant_mode' => env('SHOPIFY_API_GRANT_MODE', 'offline'),

        /*
    |--------------------------------------------------------------------------
    | Shopify API Version
    |--------------------------------------------------------------------------
    |
    | This option is for the app's API version string.
    | Use "YYYY-MM" or "unstable". Refer to Shopify's documentation
    | on API versioning for the current stable version.
    |
    */

    'api_version' => env('SHOPIFY_API_VERSION', '2019-04'),
```

And see if that helps?

**Comment by fyroc** [comment]
@ohmybrew I've done the following with no joy.

- Updated laravel to 5.8.*
- Updated laravel-shopify to 7.0
- Added the config info above
- Deleted the Vendor folder and ran `composer install`

I'm still not getting any jobs firing

**Comment by fyroc** [comment]
I ended up just downgrading to 4.2.1

**Comment by ohmybrew** [comment]
Alright odd. I'm going to keep digging on this one

**Comment by fyroc** [comment]
It could have been something in the boilerplate I made, I'm not sure. What I did to fix it was to just make a copy of my working 4.2.1 app and replaced the app components with the new app. I'll try to upgrade to 7.0 later to see if it was something in the boilerplate, or it's indeed something with the package update.

**Comment by ohmybrew** [comment]
@fyroc  are you sure it's not reaching your job table? I'm wondering if it's some odd error in the actual API call like the token not being passed in properly or something

**Comment by fyroc** [comment]
It is definitely not.

**Comment by ohmybrew** [comment]
@fyroc Can you confirm for me again the versions, I want to try and target what you have.

Laravel version, and PHP version.

**Comment by fyroc** [comment]
Laravel: 5.7 & 5.8
PHP 7.3.2

**Comment by ohmybrew** [comment]
@fyroc Sorry still having trouble with this... investigating still on what to do.

**Comment by ohmybrew** [comment]
@fyroc  there was a bug with the session check which was patched last week, it had a case where it would skip over the firing of the webhook manager. Maybe give it a try and see if its now OK on the new patch?

**Comment by fyroc** [comment]
I'll have to check. I'm using an older version for this package at the moment.

**Comment by ncpope** [comment]
@fyroc @ohmybrew 

Any updates on this? I'm using an older version and would like to upgrade but waiting on the issues to get resolved before moving forward.

**Comment by chandlerwilcox88** [comment]
I am using laravel 5.8 and the latest "ohmybrew/laravel-shopify": "^9.1"

I have gone into the OhMyBrew\ShopifyApp\Services\WebhookManager and logged if they are being created and the function fires and everything looks good but when I look at my xhr requests on the server I don't see them sending a request to shopify so maybe that is where things are going wrong?

**Comment by fyroc** [comment]
I haven't tested it. I've moved away from creating new Shopify apps.

**Comment by StefanNeuser** [comment]
@fyroc why?

**Comment by fyroc** [comment]
@StefanNeuser ever since they updated the app store, downloads have decreased and the quality of the clients have decreased as well.

**Comment by jesephan** [comment]
in my end, the webhook no longer works due to messed up **api_scopes** values in the **shopify-app.php** configuration file. Like if you want to add webhook for **orders/created** then make sure to add **read_orders** in your **api_scopes**
