### ISSUE TITLE
Same browser session issue (Store A shows data from store B)

### ISSUE THREAD

**Issue by mansoorbilalrana** [osiset/laravel-shopify#344]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

On the same browser, a shop must show its own data( products, customers etc).

## Current Behavior

On the same browser, Store A shows data information of Store B.

## Failure Information

https://share.getcloudapp.com/7Kux2gvo

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Login into a store (Store A) and install the developed app. Open the app route where data is coming from API (products, customer etc).
2. Login into another store on the same browser (Store B) and install the developed app. Open the app route where data is coming from API (products, customer etc).
3. Switch back to Store A and switch the routes and open the route on which data is coming from API. 

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.1.0
* Laravel Version: v5.5.*
* PHP Version: v7.1.3

**Comment by mansoorbilalrana** [comment]
@ohmybrew @darrynten @StefanNeuser

**Comment by ohmybrew** [comment]
I'll try and replicate

**Comment by ohmybrew** [comment]
Was unable to reproduce... maybe its a browser thing... what browser were you using?

**Comment by mansoorbilalrana** [comment]
We are using the Chrome browser.

**Comment by vomitHatSteve** [comment]
Came here looking for specifically this issue, huzzah!

In my office, we have had this issue on Chrome, Firefox, and Safari. Across a variety of 5.x versions of laravel and up through 6.x versions of OMB/Laravel-shopify and 4.x versions of OMB/basic-shopify-api.
It's been in queue to find a resolution for some months. It was consistent on all of our configurations and all of our browsers.

However, earlier this week, we updated our app to deal with Shopify's new versioned API and Link-based pagination.
This entailed updating our app to Laravel 6.5.1, basic-shopify-api 6.1.2, and OMB/laravel-shopify 10.2.1; and explicitily using Shopify API version 2019-10.
The fully updated app is no longer experiencing the issue
However, the app that is on laravel 5.8, and basic-shopify-api 4.0.2 still is.

All that is to say, I have been able to replicate the error, but it may have been resolved inadvertently with a recent update to OMB, Laravel, or Shopify.

**Comment by mansoorbilalrana** [comment]
@vomitHatSteve Thanks for your reply. I am still facing the issue after upgrade to ```laravel-shopify v10.2.1```  ```basic-shopify-api 6.1.2``` ```Laravel Framework 6.5.1``` ```Shopify api version 2019-10```
 Could you please share the code snippet how you are calling the 
shopify API. 
Thanks

**Comment by ohmybrew** [comment]
I'm going to try and take some time tonight to find out the issue here. I wasnt able to replicate it, maybe I was doing something different.

**Comment by vomitHatSteve** [comment]
@mansoorbilalrana, I'll have to consult with my team re: sharing internal code and see if I can compile something.

**Comment by vomitHatSteve** [comment]
Ok, here's what's in our working environment that might be affecting Shopify authentication:

So since we're using the Laravel-shopify library, most of our authentication etc. is being handled by that code.

Our routes are are almost all in the form:
```
Route::METHOD('PATH', 'CONTROLLER@FUNCTION')
  ->middleware('auth.shop', 'billable')
  ->name('NAME');
```
We do have Laravel's App\Http\Controller\Auth\LoginController included, which has

```
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
```

I don't recall what we have it for, but it could be affecting things

Our config('session.driver') is 'database'

Let's see, what else could have affected the process...

We went through the full [laravel-shopify update process](https://github.com/ohmybrew/laravel-shopify/wiki/Upgrading) version by version from v4.0.x

**Comment by florinsith** [comment]
That makes perfect sense, there is only one session, the second store overrides the shopDomain in session.
I wouldnt consider this an issue, its normal webapp behaviour. I dont know of any  webapp that allowes you to login with 2 accounts in 2 different tabs. You can use an incognito tab or a different browser.

**Comment by vomitHatSteve** [comment]
While that's normally true, this is a change in behavior within the last year or so.

This is almost certainly a change on Shopify's part rather than the OMB library, but last year, you could log into the same app from multiple stores simultaneously.

Plus, it makes intuitive sense: Shopify allows you to log into multiple _stores_ at the same time. It's not great UX that when you access an app through store A on Shopify, it shows store B's data instead.

**Comment by florinsith** [comment]
With shopify you have a different url for each store, your app has the same url once you originally opened it. You would need to change your app and make sure to put the shop in every link your app produces and then use that to get separate session data.
I like csrf tokens, for get requests as well not only post. Addiing that wouldnt allow you to login to multiple stores at the same time but it would solve the ux issue and add better security.

**Comment by vomitHatSteve** [comment]
I'm looking at some request headers right now...
It seems that the only thing that Shopify passes to embedded apps - when logged into multiple stores concurrently - is the store domain via the referrer. Both sessions get the same XSRF token (via cookie)

**Comment by phplead4** [comment]
I am also facing same issue. app showing store 1 products in store 2.

**Comment by StefanNeuser** [comment]
Seam's like you are not refreshing the php session.

**Comment by phplead4** [comment]
same session is used on both apps. when I am accessing the store 1 and then go store 2 and refresh the page after that store 2 show store 1 products

**Comment by florinsith** [comment]
> I'm looking at some request headers right now...
> It seems that the only thing that Shopify passes to embedded apps - when logged into multiple stores concurrently - is the store domain via the referrer. Both sessions get the same XSRF token (via cookie)

I dont think it even matters what shopify passes, once you are in the app the requests will no longer have that.  The only way I can think of to overcome this is to have a session based url token and then the session data in the app would be saved and retrived based on the url token.

**Comment by darrynten** [comment]
See #295
