### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by maruf-cefalo** [osiset/laravel-shopify#371]
Case #1: 
I have created a Route::post('/webhook/orders/create') in my api and in the shopify shop settings/notifications have created a webhook using url myngrokurl/api/webhook/orders/create in 
such case the webhook is sending the test data. Have listed the route in the api to avoid csrf issue. But working fine as expected. 

Case #2 : Problem is: 
have created a webhook as documented 
```
[
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'orders/create'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', env('APP_URL') . '/webhook/orders-create')
]

```
where env('APP_URL') is my ngrok url created and the jobs are crated as well. 

but when i create an order in the shopify admin manually not from the notification area, this is the response I am getting 

> POST /webhook/orders-create    401 Unauthorized

Please help

**Comment by maruf-cefalo** [comment]
@ohmybrew can you please help

**Comment by hbl-anhnt1** [comment]
@ohmybrew  I'm having exactly the same issue

**Comment by Kyon147** [comment]
The one thing I would make sure is the APP_URL needs to be an external domain, so it should not be https://localhost as Shopify will not be able to access that.

You need to make it whatever you login route faces, to https://myappurl.com/webhook/app-uninstalled

By default, you will probably have your local URL or 127.0.0.1 both which won't face externally.

**Comment by hbl-anhnt1** [comment]
@Kyon147 oh, thanks. I try it now
