### ISSUE TITLE
ScriptTag not loaded on the storefront

### ISSUE THREAD

**Issue by samir-patil29** [osiset/laravel-shopify#373]
## Expected Behavior

ScriptTag should be loaded on the storefront

## Current Behavior

I have added the ScriptTag as described in the installation documentation but the ScriptTag is not loaded on the storefront.

**Comment by Kyon147** [comment]
@samir-patil29 please fill out the form completely as this is hard to diagnose with just "should be loaded".

Steps to replicate, code examples and as much info as possible will help someone answer and help your issue. Otherwise, this is likely to be ignored with such little information about the problem.

**Comment by samir-patil29** [comment]
Hey @Kyon147 ,

Thank you for your response.

Please find the details below - 

## Expected Behavior

ScriptTag should be loaded on the storefront in order to invoke the functionality - I am building a shopify app to display a popup - when added any item to the cart / when cart is displayed.

## Current Behavior

I have added the ScriptTag as described in the installation documentation but the ScriptTag is not loaded on the storefront when I submit the shopify app for review - while, I am able to get the ScriptTag ID and ScriptTag SRC when I hit the following API - "GET /admin/api/2020-01/script_tags.json"


## Failure Information

There are no logs created on our local test server - and there is no communication channel with Shopify App Reviewers to debug this issue further and get the logs.

### Steps to Reproduce

I am a little confused here as I am not able to replicate the same on our local test server. I could replicate this issue once - but the ScriptTag was not loaded because of the SSL Certificate being expired. I cross checked that again and its in position.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v9.2
* Laravel Version: v5.8
* PHP Version: v7.2


Please let me know if I have missed something or you need any other information from my end.

Regards,
Samir Patil
