### ISSUE TITLE
Iss there a way to get rid of full page redirects, It actually looks very odd when app runing on two stores in same browser

### ISSUE THREAD

**Issue by iwaheedshahzad** [osiset/laravel-shopify#379]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
There was a partial flow at one point, but there were too many issues with it and the iFrame so it was removed. 

You would be able to do something similar with it if you look at the old code but it was taken out of production because it was not stable.
