### ISSUE TITLE
Call to a member function getBody() on null

### ISSUE THREAD

**Issue by monika-dev** [osiset/laravel-shopify#381]
I have connected my shopify app with the laravel in order to fetch the data from api When i have used it to get the data. it was working fine. but all of sudden, everytime i hit the api, it started giving me an error "Call to a member function getBody() on null" . But the api is running fine in postman, giving me the correct data. 

Can you please let me know, is there any problem in omybrew library?

**Comment by darrynten** [comment]
I've started seeing this behaviour too

**Comment by jedimdan** [comment]
I saw this issue (https://github.com/ohmybrew/Basic-Shopify-API/issues/57) while browsing the basic-shopify-api package. Is this the same thing?
