### ISSUE TITLE
App Uninstalled Not Being Called

### ISSUE THREAD

**Issue by Dlas1212** [osiset/laravel-shopify#383]
## Expected Behavior

The Job: AppUninstalledJob should be ran but the webhook is not registering. 

## Current Behavior

The webhook is set up and the job is present in my folder.

Here is my webhook.
```
'webhooks' => [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://mydomain.com/webhook/app-uninstalled')
        ],
```

I am also running` php artisan queue:work`and have restarted it many times and done tests.
The app deletes no problem but the Job does not execute. Although the Webhook installer job executes on install. 

When I visit `/admin/webhooks.json` the json array is empty.

I have tried to set my Shopify API to all the possible api version, in the shopify backend and in the Laravel application itself too.

* Package Version: "dev-master"
* Laravel Version: 6.2
* PHP Version: 7.2

NOTE: I've updated the package to "`ohmybrew/laravel-shopify": "^10.2.1"`, deleted vendor folder and ran `composer update`. The webhooks.json file still empty.

I am using Valet for Laravel to get my URL and even uploaded to my live server and tested it on there - Doesn't register webhook.

**Comment by Dlas1212** [comment]
Any updates on this? I've updated to 10.3.1. 
I want the uninstall to run the default uninstall from OhMyBrew and cancel subscriptions.
Do I have to put anything inside my AppUninstalledJob for it to use default?
Please help. This is the only thing stopping me from making my app live.

**Comment by Kyon147** [comment]
Did you follow the wiki and set up the uninstall job by publishing the file?

**Comment by Dlas1212** [comment]
@Kyon147 Yes, I published the file, I even tired to make my own webhook, that didn't work either. Nothing gets called. I know it isn't the jobs since my app uses jobs and processes them but the uninstall just won't trigger.

**Comment by ohmybrew** [comment]
No, sorry, I stated in another ticket, I simply don't have enough of my time to spread to both current issues and the rewrite of the library in another branch.The library has been rewritten to a better more maintainable structure in another branch and is in testing phase. Once I am done there I will be looking at current issues so that they can be fixed in both places at once.On Feb. 7, 2020 20:57, Dlas1212 <notifications@github.com> wrote:Any updates on this @ohmybrew ? I've updated to 10.3.1.
I want the uninstall to run the default uninstall from OhMyBrew and cancel subscriptions.
Do I have to put anything inside my AppUninstalledJob for it to use default?
Please help. This is the only thing stopping me from making my app live.

**Comment by Kyon147** [comment]
> No, sorry, I stated in another ticket, I simply don't have enough of my time to spread to both current issues and the rewrite of the library in another branch.The library has been rewritten to a better more maintainable structure in another branch and is in testing phase. Once I am done there I will be looking at current issues so that they can be fixed in both places at once.On Feb. 7, 2020 20:57, Dlas1212 <notifications@github.com> wrote:Any updates on this @ohmybrew ? I've updated to 10.3.1. I want the uninstall to run the default uninstall from OhMyBrew and cancel subscriptions. Do I have to put anything inside my AppUninstalledJob for it to use default? Please help. This is the only thing stopping me from making my app live. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Makes sense @ohmybrew 

I'll try and help him so you can focus on the rewrite which helps everyone 👍

**Comment by Dlas1212** [comment]
Hey @Kyon147! I have updated to the latest version, and did the artisan command to publish the job, it created an empty uninstall job which extends the OhMyBrew one. In my Shopify config, I tried both options by setting my address to both local address via valet and using my servers address (I uploaded the site there too).
My app uses Jobs and those jobs are working normally. The uninstall job just does not get called.

I have also tried making my own Webhook to uninstall and just logging anything, and that fails too. I don't know if theres something in my Laravel settings thats blocking it or something is broken.

**Comment by Kyon147** [comment]
> Hey @Kyon147! I have updated to the latest version, and did the artisan command to publish the job, it created an empty uninstall job which extends the OhMyBrew one. In my Shopify config, I tried both options by setting my address to both local address via valet and using my servers address (I uploaded the site there too).
> My app uses Jobs and those jobs are working normally. The uninstall job just does not get called.
> 
> I have also tried making my own Webhook to uninstall and just logging anything, and that fails too. I don't know if theres something in my Laravel settings thats blocking it or something is broken.

Hey @Dlas1212 

Have you tried debugging it live, so connecting up to the app locally and setting a debug point on the uninstall file to see if it gets triggered?

As there are so many variables for these apps, it can be hard to find a specific issue.

Let me try and spin up a new local app and see if it works for me.

**Comment by Dlas1212** [comment]
@Kyon147 Yeah, I tried just doing a Log("Test") and nothing got triggered. 
Maybe its my Laravel Version? 6.2

Have you tried it?

**Comment by Kyon147** [comment]
Hey @Dlas1212 

Have you also run migrate too as mentioned in #394

**Comment by Dlas1212** [comment]
@Kyon147 Hey, I ran migrations and I have nothing pending. Weird. DId you just use the default webhook file?

**Comment by Kyon147** [comment]
@Dlas1212 yeah, just the default migration which adds the blank Uninstall Job. Does the package set a deleted DateTime in the Shop table? Plus remove the shopify_token? This is part of the uninstall job, so it could help diagnose where you are getting to at least.

Also, do you have anything in the job itself? What are you trying to happen if the above is happening? As I can then spin up another instance and give it another go with your requirements to make sure.

**Comment by Kyon147** [comment]
Hey @Dlas1212 

Just to update you, I've tried on a new app of mine (still on 10.3.1) and it works on a live server. I could not get it to work at all using Ngrok.

Sorry, I could not find any more - it is hard to diagnose the environmental factors on different setups.

There's not an issue with the package though on 10.3.1 I can find.
