### ISSUE TITLE
Issue with Wamp and local server

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#397]
Hi,

I follow the instruction and use ngrok to authenticate my app but then when click on "Install Unlisted App" I got the problem with cURL:

![2020-02-24_1316](https://user-images.githubusercontent.com/10516734/75151879-fe3cb380-5707-11ea-91da-105aea864eb6.png)

How I can solve the problem?

**Comment by Kyon147** [comment]
This is not an issue with the package but your set up. You need to fix your local certificate.
