### ISSUE TITLE
Upgrade plan not work

### ISSUE THREAD

**Issue by JDSHINDE** [osiset/laravel-shopify#398]
When i click on upgrade plan button as plan id [2] using billing router but it's show old plan data.

I have two plan first as 4.99 USD with it's related info and second is 19.99 USD, but when i am trying to upgrade its show old plan data as 4.99 USD with it's info.

Also i have 2 plan in my plan table i don't know why it's not working.

![Screenshot_147](https://user-images.githubusercontent.com/46311508/75219133-fb05fe00-57c1-11ea-933f-d62f1437cf51.png)

Can you please help me in this, thanks

**Comment by veed76** [comment]
@JDSHINDE 
In your route pass plan id in this key plan_id=2
ex: https://domain.com/YOURROUTESEGMENT?**plan_id=2**

**Comment by JDSHINDE** [comment]
hi @veed76 this issue was fixed the problem is that the link was set with plan_id = 2 in router with vue js like /billing?plan_id=2.
and i did with billing/2 and it's work like charm.

Thank you..
