### ISSUE TITLE
Infinite redirects

### ISSUE THREAD

**Issue by Jamesking56** [osiset/laravel-shopify#400]
## Expected Behavior

When visiting the app inside of Shopify after it has installed, I see the `home` route displayed inside an iFrame in Shopify Admin.

## Current Behavior

The app does a full page redirect to the main screen, which then does a redirect back to Shopify, which then does a full page redirect to the main screen...

## Failure Information

I've done some digging and it seems to me that the session is never valid even though a token exists.

### Steps to Reproduce

I've just cleanly installed following the install instructions and it does this.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.3.1
* Laravel Version: v6.17.1
* PHP Version: v7.4.2
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker (Vessel) + ngrok

### Failure Logs

No logs

**Comment by Kyon147** [comment]
I've started to see this behaviour on local when the app is trying to auth for the first time after the session expires.

Mine though loops a couple of times but then goes to the login page, when you click back it then goes to the app as the session has been set correctly.

**Comment by Jamesking56** [comment]
After clearing my browser cache, this stopped happening for me :man_shrugging:

**Comment by Jamesking56** [comment]
I also found this was caused sometime by Brave's built in Shields being enabled both for Shopify admin as well as your app URL inside of the frame. Disabling for both also stopped this reappearing at random
