### ISSUE TITLE
After installation throw back to login page

### ISSUE THREAD

**Issue by veed76** [osiset/laravel-shopify#402]
@osiset 
I setup the app on my server having nginx. Please see this video you can see the issue.
After installation it redirecting to login page.
https://www.loom.com/share/aed5c3fca2234936a63d9c14f132ff0c

* Package Version: 10.3
* Laravel Version: 6.0
* PHP Version: 7.2

Please help me with this.
Thank you.

**Comment by veed76** [comment]
here is my Nginx conf file for this project
```
server {

        root /var/www/html/shopify-apps/temp/public;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        server_name subdomain.domain.com;
        #add_header X-Frame-Options "SAMEORIGIN";
        location / {
                try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        location ~ \.php$ {
         include snippets/fastcgi-php.conf;
         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        }

    location ~ /\.ht {
           deny all;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/subdomain.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = subdomain.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name subdomain.domain.com;
        return 404; # managed by Certbot

}
```

**Comment by Kyon147** [comment]
This might not just be an Nginx issue as I have started to see this behaviour as well but only on local using Apache at the moment.

Live apps I am not seeing it but there is something causing the session to not be valid and is throwing to the login page.

Not done enough to debug it yet though.

**Comment by veed76** [comment]
@Kyon147 
Thanks for the reply.
In my local, I have Nginx and created the domain using laravel valet. In my local, it working fine.

**Comment by Kyon147** [comment]
There was a similar issue #400 which was caused by session/cookies for them. Have you tried clearing your browser cache and trying again?

**Comment by veed76** [comment]
Hi @Kyon147 
I just replaced this section in my conf file and it works.
```
location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
```
