### ISSUE TITLE
How to use CRON to access user products

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#403]
Currently, I'm fetching shop products with this function:

```
 public function index() {
  
        $shop = ShopifyApp::shop();
	$requests = $shop->api()->rest('GET', '/admin/api/2019-07/products.json');
        return serialize($requests->body);

    }
```

but what I need is to run CRON each day to fetch shop products. Is that possible using CRON -

**Comment by Kyon147** [comment]
You should look at the scheduling in Laravel.

You set up one Cron jobs to run `schedule:run` and then set up your reoccurring actions in Laravel.

**Comment by APdevelopments** [comment]
Yes, I know about CRON and schedule: run just how to get the shop authentication... or I dont need the shop authentication

**Comment by Kyon147** [comment]
Just load the shop from the DB. Then initialise the shop API

$shop = Shop::first(shop_id)

$shop->api()

**Comment by APdevelopments** [comment]
wow, thank you very much... very easy

**Comment by APdevelopments** [comment]
Sorry for trivial questions just I'm new to Shopify API. I check about products and it seems that the limit is 250 products ...

What is the way to get all the products ? Is that possible with this library?

**Comment by Kyon147** [comment]
You just need to loop through them. 

With a request there is a link object in the response which is used in the next API call to get the next list of products.

This explains how you do it.

https://shopify.dev/tutorials/make-paginated-requests-to-rest-admin-api

**Comment by Kyon147** [comment]
@APdevelopments has this solved your issue, if so can you close to make sure issues are not stagnating :)
