### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by awebartisan** [osiset/laravel-shopify#404]
## Current Behavior

Unable to install this package in Laravel 7 project. Need to update composer.json

**Comment by Kyon147** [comment]
I suspect this won't be happening as @osiset is concentrating on the package update which is being rewritten from scratch.

You might need to wait until then if you want to use V7 or just used V6 for now.

**Comment by mtownsend5512** [comment]
Even with the latest release supporting Laravel 7 I can't install it on a fresh Laravel 7 install.

Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: remove laravel/framework v7.0.8
- Conclusion: don't install laravel/framework v7.0.8
- osiset/laravel-shopify v10.3.0 requires laravel/framework ~5.6 | ^6.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
- osiset/laravel-shopify v10.3.1 requires laravel/framework ~5.6 | ^6.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
- Can only install one of: laravel/framework[6.x-dev, v7.0.8].
- Can only install one of: laravel/framework[5.6.x-dev, v7.0.8].
- Can only install one of: laravel/framework[5.7.x-dev, v7.0.8].
- Can only install one of: laravel/framework[5.8.x-dev, v7.0.8].
- Installation request for laravel/framework (locked at v7.0.8, required as ^7.0) -> satisfiable by laravel/framework[v7.0.8].
- Installation request for osiset/laravel-shopify ^10.3 -> satisfiable by osiset/laravel-shopify

**Comment by awebartisan** [comment]
Hi. Laravel 7 support is added in `master` branch which has not been turned into a *release* yet. 
So, the latest release (10.3) still doesn't support Laravel 7.

**Comment by mtownsend5512** [comment]
Ah, I see. Thanks for the clarification. I'll be watching the progress of this package. I was developing a Shopify app and took a break but now I'd like to refresh it on the latest version of Laravel and this package.

**Comment by mlgrozev** [comment]
Hello @awebartisan, thanks for the information.

When do you plan to release the support for Laravel 7?

**Comment by jedimdan** [comment]
@mlgrozev you might want to take a look at the note on this project's read me. The app is going through major refactoring right now, although it looks like the next major version is going to be ready quite soon. I would recommend staying on Laravel 6 for now so that we can let the maintainers focus on finishing up the next major version.
