### ISSUE TITLE
Discussion - redirect user for asking more permissions

### ISSUE THREAD

**Issue by tzookb** [osiset/laravel-shopify#406]
I already got a way to fetch the current store scopes.

Now as I have another feature, I need to ask for existing customers to give the app more permissions.

I do see if I got to the "/authenticate" page and submit the form, if there is a missing scope. Shopify will ask for approval again.

But if the user is in the app, how should I redirect him to the approval page?
maybe even skipping the "authenticate" page.

Thanks!

**Comment by Kyon147** [comment]
Hi @tzookb,

The easiest is just to wait until the user needs to reauth again. Once the session expires they will go through the auth route and need to accept to use of the app.

If you 100% need them to accept, then have a flag in the DB, i.e reauth_needed and if theirs is set to 0 they then get pushed to the auth route. You can add this check on your home route to make sure you catch everyone.

**Comment by tzookb** [comment]
Thanks @Kyon147 

that was exactly what I was thinking

but if the page loads inside Shopify,
my redirect will be just for the iframe.

So the will be in shopify, but my app will show the authenticate form.

I would like to skip that form for the users to submit and directly move them to the approval page

**Comment by Kyon147** [comment]
@tzookb  is you push anyone already in Shopify to your authenticate route, it will do a full-page redirect again. 

Then will go back to OAuth to accept the new permissions, so it would be the normal user flow which would be fine?

**Comment by tzookb** [comment]
I just tried this:
```
return redirect('/authenticate');
```

on my main entry route.

I got redirected to authenticate form page, but I see the form inside shopify UI

**Comment by Kyon147** [comment]
When you mean authenticate form page, can you send a screenshot?

**Comment by tzookb** [comment]
@Kyon147 
my bad its the "login" page:
<img width="706" alt="Screen Shot 2020-03-04 at 16 05 11" src="https://user-images.githubusercontent.com/3749973/75887128-faa8db00-5e31-11ea-95a9-34489f2274ff.png">

**Comment by Kyon147** [comment]
Hmm, that is strange - pishing them to /authenticate should run them through the auth method again and as long as you have updated your ENV file with the new api_scopes you should get the OAuth again,

If you are seeing the login page, you might be getting one of the recent issues mentioned in #402 or #400.

Try clearing your browser cache, and if not, you might need to debug and step through the authenticate method in AuthShopTrait

**Comment by tzookb** [comment]
got this code in my main controller, and that seems to work.
Just dont like the copy pasting from the package Trait

```php
        $shop = ShopifyApp::shop();
        $shopDomain = $shop->shopify_domain;

        if ($shop->needs_update) {
            $shop->needs_update = false;
            $shop->save();

            $auth = new AuthShopHandler($shop);

            $authUrl = $auth->buildAuthUrl(
                $shop->hasOfflineAccess() ?
                    Config::get('shopify-app.api_grant_mode') :
                    ShopSession::GRANT_OFFLINE
            );

            return View::make(
                'shopify-app::auth.fullpage_redirect',
                compact('authUrl', 'shopDomain')
            );
        }
```

**Comment by Kyon147** [comment]
Yeah you should not have to copy the code from the trait, but something in your setup is causing an error somewhere when you are trying to reauth through the package trait directly. More so, if the copy pasted code is working.

You would need to set up XDebug or something and run through the process to see what the issue is.

**Comment by Kyon147** [comment]
@tzookb did you manage to solve your issue are do you still need help?

**Comment by tzookb** [comment]
Hey @Kyon147 

I just used the same code above in the end :| :)

**Comment by abishekrsrikaanth** [comment]
@osiset are there any options for this with the new update?

**Comment by osiset** [comment]
No, I do not provide a baked in solution for this. You need to force the user to go through the authenticate URL.

**Comment by Kyon147** [comment]
What I usually do is just push them back through authenticate, makes it easy and requires no additional coding.

Also, once their session expires, they will go back through it anyway but if you wanted to put up a "gate" - just add a flag or something in the user table, like `accepted_permissions`.

Then whenever you want to force someone, you could check to see if that is true or false and push them over and or lock them out of certain features until that is true again.

**Comment by abishekrsrikaanth** [comment]
> No, I do not provide a baked in solution for this. You need to force the user to go through the authenticate URL.

Is there a way to get the authenticate URL with the required parameters to redirect? If I just redirect to `/authenticate`, I get the following error

```
Osiset\ShopifyApp\Exceptions\MissingShopDomainException
No authenticated user or shop domain
```

**Comment by Kyon147** [comment]
Are you redirecting them within the Shopify admin and have they been authenticated successfully before this?

**Comment by abishekrsrikaanth** [comment]
Yes, I tried the following and this doesn't seem to work either. 
```php
        $shop = Auth::user();

        if (isset($shop->re_auth_required) && $shop->re_auth_required) {
            $shop->re_auth_required = false;
            $shop->save();
            return redirect("/authenticate?shop=" . $shop->name);
        }

        return $next($request);
```

I have tried the above code that @tzookb posted, can't seem to get that working. As a new feature on the app we needed to add in a few more scopes and we want the existing app customers to redirect to the re-authorize the permissions on Shopify.
