### ISSUE TITLE
Error with db when installing app on shopify

### ISSUE THREAD

**Issue by stifboy** [osiset/laravel-shopify#410]
I have installed laravel and laravel-shopify as per the instructions provided. However when I generate shopify install app link and try to install the app, I get the error

`lluminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx.shops' doesn't exist (SQL: select * from `shops` where (`shopify_domain` = xxxx.myshopify.com) and `namespace` is null limit 1)`

Screenshot - https://i.imgur.com/dFFcB5j.jpg

Laravel Framework 5.8.37
Php Version: 7.2

**Comment by Kyon147** [comment]
Have you run the `php artisan migrate` to install the tables?

**Comment by stifboy** [comment]
> Have you run the `php artisan migrate` to install the tables?

Thanks. This fixed it.
