### ISSUE TITLE
Error: 'Unable to get shop domain' after successful billing redirect to homepage

### ISSUE THREAD

**Issue by zuk22** [osiset/laravel-shopify#414]
Hi!
I've got next error after successful billing process, when redirecting to homepage. Can you please help is this an issue or normal behavior?

**....local.ERROR: Unable to get shop domain. {"exception":"[object] (OhMyBrew\\ShopifyApp\\Exceptions\\MissingShopDomainException(code: 0): Unable to get shop domain. at C:\\wamp\\www\\shopifyapp\\vendor\\ohmybrew\\laravel-shopify\\src\\ShopifyApp\\Middleware\\AuthShop.php:136) .....**

![support1](https://user-images.githubusercontent.com/7103128/76617993-2281f800-6530-11ea-9243-0e66a54976a7.jpg)

**routes/web.php** contain next code:

```
Route::get(
    '/',
    'HomeController@index'
)->middleware(['auth.shop', 'billable'])->name('home');
```

**Environment:** 
WAMP 3.1.7
PHP 7.2.14
MySQL 5.7.24
Laravel 5.8
ngrok

**Comment by Kyon147** [comment]
If you then go back to your app, after this does it log you in?

There have been similar issues which has happened because of local being redirected back to HTTP instead of https.

**Comment by zuk22** [comment]
@Kyon147
Through shopify admin app loading fine after billing.
Is there any advice how to avoid such behavior with redirection?

**Comment by Kyon147** [comment]
> @Kyon147
> Through shopify admin app loading fine after billing.
> Is there any advice how to avoid such behavior with redirection?

So it only happens after the first time you access and accept the billing screen? But going to the app through the admin after authenticates fine? 

There's been similar issues with redirection, so I am just trying to work out a cause.

**Comment by zuk22** [comment]
@Kyon147
> So it only happens after the first time you access and accept the billing screen?

**Yes**

> But going to the app through the admin after authenticates fine?

**Yes. Through [mydomain].myshopify.com/admin/apps/[app-name]**

**It happen in such way:**
1) I confirming installation of app to my shop
2) Shopify redirects me to billing screen where I press button which confirm charge/start free trial
3) I'm redirecting to the screen above (home page of the Laravel site)
4) Now I can go to my shopify [mydomain].myshopify.com/admin/apps/[app-name] and can get to my app settings page
Charge appear in database tables 'charges'

**And yes, I noticed that in some requests referral URL starts with HTTP. I've attached log file with first request.**
[log.txt](https://github.com/osiset/laravel-shopify/files/4331307/log.txt)

**Do you need any additional information?**

**Comment by Kyon147** [comment]
@zuk22 that's fine on the amount of information for now.

I've had a similar issue brought to one of my live apps. Someone has tried to install and it creates a redirect loop at the billing accept the screen.

I am just trying to replicate the issue and will let you know more.

**Comment by zuk22** [comment]
@Kyon147 Ok. Thanks!
I have one more question. Today I started testing recurring charging with trial days. After app passed trial days, I didn't get redirection to billing screen. 

Do I need to use some methods to charge for the app?

**Comment by Kyon147** [comment]
Have you added `billable` to your routes?

Without this, it won't go through the middleware to check to see if they have an active charge.

**Comment by zuk22** [comment]
@Kyon147 **Yes. Here is my route:**
`
Route::get(
    '/',
    'HomeController@index'
)->middleware(['auth.shop', 'billable'])->name('home');
`

**Comment by Kyon147** [comment]
> @Kyon147 **Yes. Here is my route:**
> `Route::get( '/', 'HomeController@index' )->middleware(['auth.shop', 'billable'])->name('home');`

What does your plan look like in the plans table?

**Comment by zuk22** [comment]
@Kyon147 
![support_2](https://user-images.githubusercontent.com/7103128/76765264-cd97e900-679e-11ea-9f81-29bf856d5cfd.jpg)

**Comment by zuk22** [comment]
@Kyon147 Is there a way to contact with you in another way, so not to create a tons of messages here?

**Comment by Kyon147** [comment]
After the trial, you will just be automatically enrolled. 

As you can see the charge is still active - so your "trial" has ended but the paid version will start.

Shopify bills their users every month when their actual Shopify invoice is generated and that is when your charge would be applied.

You could access the charges API and output the response to make sure the store has an active reoccurring plan. From what I can see it all seems correct.

**Comment by zuk22** [comment]
> Shopify bills their users every month when their actual Shopify invoice is generated and that is when your charge would be applied.
> You could access the charges API and output the response to make sure the store has an active reoccurring plan. From what I can see it all seems correct.

Ok, I understand. Thanks for clarification!

> EDIT: keeping the convo in the thread is a good idea. It means anyone with your similar issue might find the solution, without needing to open a new issue for the same thing.

No problems. Thanks for help!

**Comment by Kyon147** [comment]
That's no problem at all :)

If that is all sorted then please close the issue you can always reopen it is the issue persists later.

**Comment by zuk22** [comment]
> If that is all sorted then please close the issue you can always reopen it is the issue persists later.

Redirection issue isn't resolved, you told that will test and let me know.

**Comment by Kyon147** [comment]
> > If that is all sorted then please close the issue you can always reopen it is the issue persists later.
> 
> Redirection issue isn't resolved, you told that will test and let me know.

Sorry! That is true got the issues mixed up - just doing some testing today so try and replicate it,
