### ISSUE TITLE
Error on the auth page due to object/stdClass mismatch

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#416]
## Expected Behavior
login page will load

## Current Behavior
error:
Declaration of Osiset\ShopifyApp\Services\ApiHelper::createScriptTag(array $payload): Osiset\ShopifyApp\Services\object must be compatible with Osiset\ShopifyApp\Contracts\ApiHelper::createScriptTag(array $payload): Osiset\ShopifyApp\Contracts\object

vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php:23

### Steps to Reproduce
1) install laravel
2) install shopify laravel
3) add keys to .env
4) add a route from readme
5) edit resources/views/welcome.blade.php
6) modify Laravel user model.
7) run migrations
8) try to get on /authenticate

### Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
* Package Version: v11.0.0
* Laravel Version: v6.18.1
* PHP Version: v7.2.2

### Failure Logs
 1 [2020-03-17 13:58:40] local.ERROR: Declaration of Osiset\ShopifyApp\Services\ApiHelper::createScriptTag(array $payload): Osiset\ShopifyApp\Services\object must be compatible w
   ith Osiset\ShopifyApp\Contracts\ApiHelper::createScriptTag(array $payload): Osiset\ShopifyApp\Contracts\object {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\Fa
   talErrorException(code: 64): Declaration of Osiset\\ShopifyApp\\Services\\ApiHelper::createScriptTag(array $payload): Osiset\\ShopifyApp\\Services\\object must be compatible w
   ith Osiset\\ShopifyApp\\Contracts\\ApiHelper::createScriptTag(array $payload): Osiset\\ShopifyApp\\Contracts\\object at /home/user/public_html/blog/vendor/osiset/laravel-sho
   pify/src/ShopifyApp/Services/ApiHelper.php:23)
 2 [stacktrace]
 3 #0 {main}
 4 "}

**Comment by osiset** [comment]
Hmm I will probably need to switch everything to use stdClass as it seems <7.3 its looking for `object` type in the namespace.

**Comment by osiset** [comment]
I have the mapping fixed and will release a patch tonight for you to try.

**Comment by osiset** [comment]
Patch v11.0.1 in place, please give it a try :)

**Comment by Enmaboya** [comment]
> Patch v11.0.1 in place, please give it a try :)

Now I can't go to 
myapp.us/login
and install the application.

but after installation, I get an error:
"Argument 1 passed to Osiset\ShopifyApp\Services\ShopSession::setAccess() must be an instance of Osiset\ShopifyApp\Services\object, instance of stdClass given, called in /home/user/public_html/blog/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/AuthorizeShop.php on line 101".

when you try to install an application from a shoplifter, the same thing happens

**Comment by osiset** [comment]
Give v11.0.2 a try, sorry, its really difficult when tests are passing for PHP 7.2 yet its complaining about the namespacing.

**Comment by Enmaboya** [comment]
> Give v11.0.2 a try, sorry, its really difficult when tests are passing for PHP 7.2 yet its complaining about the namespacing.

it seems to be working now, thank you!
