### ISSUE TITLE
Authentication from store failed

### ISSUE THREAD

**Issue by mlgrozev** [osiset/laravel-shopify#417]
TypeError
Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in /Users/grozev/code/rec-sale/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ShopSession.php on line 120

## Expected Behavior

To install the app on test store trough OAuth

## Current Behavior

When registering the app on a test merchant store an error is appearing.

## Failure Information

If I return the Redirect route in "vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php" (125)
The problem is solved and the app is installed

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install laravel
2. install shopify laravel
3. add keys to .env
4. add a route from valet share in Shopify
5. edit resources/views/welcome.blade.php
6. modify Laravel user model.
7. run migrations
8. Install the app on dev store try to get on /authenticate

### Context

Laravel version:
7.1.3
Laravel locale:
en
Laravel config cached:
false
PHP version:
7.2.28
Package version:
11.0
Using a toolset (Docker, Laradock, Vagrant, etc.):
Valet MacOS

### Failure Logs

TypeError
Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in rec-sale/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ShopSession.php on line 120

lluminate\Auth\SessionGuard::login
vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:419

Osiset\ShopifyApp\Services\ShopSession::make
vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ShopSession.php:120

Osiset\ShopifyApp\Http\Middleware\AuthShopify::loginShop
vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:122

**Comment by osiset** [comment]
So you we're at /login route, entered the store domain, hit install, accepted the oauth screen, and then this error appeared?

OR

App was already installed, you clicked the app in Shopify admin, and got that error?

**Comment by sandeshcartmade** [comment]
Hi I  have encountered the same error, It appears before oauth screen appeared.

**Comment by RandomWeasel** [comment]
Hi @osiset, I'm getting the same error message.  I'm attempting to install my app via the 'Test on development store' screen shown below
![image](https://user-images.githubusercontent.com/16453825/77064622-b8f26580-69d7-11ea-92a6-532c0609a4cb.png)

As soon as I click the 'install' option, I'm redirected to my apps 'App url' as specified in settings, with hmac and shop in the query string.
I immediately receive the error below, as per the original post.  

```
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in /home/rebound_connector/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ShopSession.php on line 120
```

This is before the oauth screen is reached, and appears to take place on the 'home' route
I can also see this query is being made, which will be returning no results as my users table is empty at this point in the process
![image](https://user-images.githubusercontent.com/16453825/77065315-f60b2780-69d8-11ea-95ed-47697ec980c8.png)

I have followed all the installation steps, migrated, and have modified the user model as instructed

**Comment by osiset** [comment]
Ah.. I have not tested install from development store in partner page like that, will look into this.

**Comment by osiset** [comment]
@RandomWeasel Sorry mobile, just trying to figure out what could be up here actually...

Is it sending you to /authenticate when you click install on development store?

I think the issue may be its not sending ?shop as a query param. If thats the case, then thats the issue, and I may need to extract the getShopDomainFromData function into some service to use in the auth controller.

**Comment by RandomWeasel** [comment]
@osiset no worries, appreciate the quick response!  

It doesn't seem to be sending me to authenticate, and the shop url is present in the query string, the url I end up on is `https://pw-shopify-app.ngrok.io/?hmac=74a5ee0885d65639ed13d253b0fb8ca003e3fd67a70c99b96686aa58f6ac97f2&shop=custom-peaks-uk.myshopify.com&timestamp=1584628354`

Looking in the network tab, from clicking 'install' onwards, I see

Graph QL POST request to `https://partners.shopify.com/310493/api/graphql`

```
operationName: "GenerateSignedInstallUrl"
variables: {input: {appId: "3216535", shopId: "15422249"}}
input: {appId: "3216535", shopId: "15422249"}
appId: "3216535"
shopId: "15422249"
query: "mutation GenerateSignedInstallUrl($input: GenerateSignedInstallUrlInput!) {↵  generateSignedInstallUrl(input: $input) {↵    signedInstallUrl↵    userErrors {↵      message↵      __typename↵    }↵    __typename↵  }↵}↵"
```

A GET request to `https://custom-peaks-uk.myshopify.com/admin/oauth/redirect_from_partners_dashboard?client_id=a1933619258faeb2f42bf8af849e0c24&signature=eyJleHBpcmVzX2F0IjoxNTg0NjI4OTUxLCJwZXJtYW5lbnRfZG9tYWluIjoiY3VzdG9tLXBlYWtzLXVrLm15c2hvcGlmeS5jb20iLCJjbGllbnRfaWQiOiJhMTkzMzYxOTI1OGZhZWIyZjQyYmY4YWY4NDllMGMyNCJ9--2261de7b951c993d4bd0e4034b26831f5183b28f`

and finally a GET to my app url `https://pw-shopify-app.ngrok.io/?hmac=a82df183db49685635f1903d8400fa725143caafa19ce78fe0cd66c5234bb7aa&shop=custom-peaks-uk.myshopify.com&timestamp=1584628652`

Which is where I see the original exception message

-------------------

I was also messing about with it, and tried adding 'auth' middleware to the 'home' route

```
Route::get('/', function () {
    return view('welcome');
})->middleware(['auth', 'auth.shopify'])->name('home');
```

which oddly changes the result I get completely - when I do this I see the same three requests in network, followed by finally  `http://pw-shopify-app.ngrok.io/setup/login`, where the 'enter shopify domain' screen is shown.

After I enter my shop url and click 'install' on that page, a user record is created in my database (with password field filled), I also see requests:

POST to `http://pw-shopify-app.ngrok.io/setup/authenticate` with token and shop values

GET to `https://custom-peaks-uk.myshopify.com/admin/oauth/authorize?client_id=a1933619258faeb2f42bf8af849e0c24&scope=read_products%2Cread_orders&redirect_uri=https%3A%2F%2Fpw-shopify-app.ngrok.io%2Fsetup%2Fauthenticate`

GET to `https://pw-shopify-app.ngrok.io/setup/authenticate?code=c6d420648ac9351b0fe53361e9c67cca&hmac=4a2ed6fbd48ac819803d3cb033b6181dc5129f56c021ead37b1dc0447a1d02b8&shop=custom-peaks-uk.myshopify.com&timestamp=1584629605`

GET to http://pw-shopify-app.ngrok.io/

and then I finally end up on `http://pw-shopify-app.ngrok.io/setup/login` again (presumably redirected by the Auth middleware at this point?)

Re-entering and submitting my shop domain at this point takes me to `http://pw-shopify-app.ngrok.io/setup/authenticate` with a `419 Page Expired` message

The app is also not shown in the Apps list for the store, which suggests it isn't installed properly - I also never see the OAuth screen at any point in this process.


Not sure if the above just muddies the waters, but thought I'd share anyway in case it gives any clues as to what's going on!

**Comment by osiset** [comment]
I have a fix in place for this and working now... will push a patch tonight.

**Comment by osiset** [comment]
Present in v11.1.0, any issue, feel free to reopen.

**Comment by RandomWeasel** [comment]
Hi @osiset , thanks for that!  Seems to be most of the way there but still having a small issue 

It seems like the shop domain or user authentication isn't being correctly stored somewhere along the process, as I'm seeing the login screen again after OAuth authentication

Immediately after clicking 'install' I see the login screen (yay)

There's a POST request to my authentication route with the token and shop domain

I then see the OAuth screen at `https://custom-peaks-uk.myshopify.com/admin/oauth/request_grant?client_id=a1933619258faeb2f42bf8af849e0c24&redirect_uri=https%3A%2F%2Fpw-shopify-app.ngrok.io%2Fsetup%2Fauthenticate&scope=read_products%2Cread_orders` and can authorise the install

I'm then redirected back to the login screen 

The user record, complete with password, has been created at this point, and the app shows on the list of installed apps for the store.  I can also see _token stored in the session

If I enter my app url again I'm redirected to my authentication route `http://pw-shopify-app.ngrok.io/setup/authenticate` with status/message `419 Page Expired`

I can however reach the app, which appears to be installed and running correctly, by clicking through from the list of installed apps.  However, after a few reloads, I end up back on the login screen

I'm also getting an issue with billing, but will create a separate ticket

**Comment by osiset** [comment]
I bet your issue is more to do with ngrok. There's been many many issues similar in the past and ngork was the direct cause.

I just made a fresh install and had no issue through Heroku.

It keeping reloading tells me there's some sort of cookie or https issue.

**Comment by RandomWeasel** [comment]
Sorry, by 'after a few reloads' I meant after me having reloaded the page manually whilst developing.  

From what I can tell, the user is logged-in initially, but then within a very short duration is logged out (Auth::user() is null), and if the app is reloaded at this point, the login screen is shown.

I'll see if I can get a non-ngrok solution working and will update if there is still an issue - thanks for your help!

**Comment by osiset** [comment]
Sure, let me know how it works out.

**Comment by RandomWeasel** [comment]
Hi @osiset, unfortunately running without ngrok doesn't seem to have fixed the problem :(   

I've created a new issue with details to keep things cleaner https://github.com/osiset/laravel-shopify/issues/435
