### ISSUE TITLE
Fresh install is broken on Laravel 7.x

### ISSUE THREAD

**Issue by ncpope** [osiset/laravel-shopify#419]
## Expected Behavior

On a fresh install you should be able to install osiset/laravel-shopify without any errors using the install steps in the wiki.

## Current Behavior

There is a conflict during the migration process. 

## Failure Information

php artisan vendor:publish --tag=shopify-migrations && php artisan migrate
Unable to locate publishable resources.
Publishing complete.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.02 seconds)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (0.01 seconds)
Migrating: 2020_01_29_010501_create_plans_table
Migrated:  2020_01_29_010501_create_plans_table (0.01 seconds)
Migrating: 2020_01_29_230905_create_shops_table
Migrated:  2020_01_29_230905_create_shops_table (0.02 seconds)
Migrating: 2020_01_29_231006_create_charges_table

   Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `charges` add constraint `charges_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

      +34 vendor frames
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Steps to Reproduce

Just install the package as normal on a fresh install using 7.x

### How to fix

Option 1. Set the users id to increment using integers and not bigint
- $table->increments('id');

Option 2. Set the user_id type to a big int on the charges migration
- Current : $table->integer('user_id')->unsigned();
- Suggestion : $table->bigInteger('user_id')->unsigned();

**Comment by mtownsend5512** [comment]
[This pull request fixes that problem](https://github.com/osiset/laravel-shopify/pull/418)

**Comment by ncpope** [comment]
> This pull request fixes that problem

Looks good 👍

**Comment by ncpope** [comment]
I’ll just leave this issue open until it gets merged so that people know that it’s in progress

**Comment by Enmaboya** [comment]
I think this is because this package supports laravel 5.6, and it uses $table->increments('id').

so I think pull-request is inappropriate at this point, it will break backward compatibility.

It's much easier to change the field type in the users table or override the charges migration.

**Comment by osiset** [comment]
@ncpope Thank you!

Interesting, I recently installed on 7 and didnt hit this nor did the test case... might've been the database type?

Seems it was an undocumented change started in 5.8.

Pulling 7.x via Laravel installer, I see it now uses `$table->id();`, which is:

```php
    public function id($column = 'id')
    {
        return $this->bigIncrements($column);
    }
```

So yes, seems default is now bigIncrements... what I'll do is pull in your PR and add an if statement for less than 5.8.

**Comment by osiset** [comment]
Pulled in PR, and commit d4ceffb will detect Laravel version and do the applicable action.

I will await Github Action results, and release a patch tonight if that goes OK.

**Comment by osiset** [comment]
v11.0.1 should now solve this.
Thanks, re-open if still an issue, but seems you self-fixed it, thanks!
