### ISSUE TITLE
Per-user authentication requires more checks, leaking information of other user.

### ISSUE THREAD

**Issue by aledelgo** [osiset/laravel-shopify#422]
This happen in version 10.x but i've seen the v11.x code and dont think this problem has been resolved.

## Expected Behavior

having grant=per_user (online grant)
If i have 2+ accounts on shopify for the same store (suppose 2+ people share the same PC/browser during day or... one person is simply a malicious hacker), call it U1 and U2,  when i switch the account on shopify and access the APP, the app should recognize the shopify-session change (it could because the iframe of shopify contain the ?session param and it changes) and react accordingly, maybe resetting the laravel session, or raising an authentication problem.

## Current Behavior

The app do not reset any session.
if i FIRST access app with U1 laravel store U1 account (taken from shopify data) in the session,
then i switch shopify account to U2, access the app... and i see Laravel app show the U1 account is logged in (because this plugin isn't tracking the ?session param change in the iframe url)

Now the user U2 can act on behalf of U1
if U2 is only a collaborator and U1 is the OWNER this may represent a big problem.

## Failure Information

I see the ?session param is someway tracked as the middleware verify the correctness of hmac and session params on each request, but it DO NOT TRACK if the previous (last) verified ?session is the same of the current and the rest of the app couldn't refresh other session vars (like current user session).
I mean that apps that "bind" currently authenticated account (auth module of laravel) with currently authenticated account on shopify goes out of sync having a big security hole.

Pourpose to fix: Track each ?session authentication and Raise a Laravel EVENT from the ShopMiddleware when the ?session param change, this way the app could listen for it and decide to reset other session vars, switch the user etc...

### Steps to Reproduce

1) Make a view that show the content of ShopSession->getUser
2) have 2 accounts on one shop U1 (owner) and U2
3) login shopify with the U1 (owner) account on shopify and install/visit app, you see the view show your name
4) on the same browser login shopify with account 2 and enter the app: the view show the current user is THE OWNER (instead on the shopify bar you see the account is the last recent login)
5) additive proof, visit the view OUTSIDE prestashop (the current user is U1)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v10.x but is the same for 11.x
* Laravel Version: v6.x
* PHP Version: v7.4
* Using a toolset : Laradock

### Failure Logs

//none

**Comment by osiset** [comment]
Thank you for the report.

So to summarize.

+ Issue is not with offline token auth, issue is with per-user
+ Logging into one shop, and logging into another, we are seeing an issue where one user can see the other user's details?

**Comment by aledelgo** [comment]
> Thank you for the report.
> 
> So to summarize.
> 
> * Issue is not with offline token auth, issue is with per-user

Honestly, i've not tested the problem with the offline token, but i think would impact this case too, because the problem is that the "custom app session" and the "shopify session" are disconnected.

> * Logging into one shop, and logging into another, we are seeing an issue where one user can see the other user's details?

i've not tested this specific case but i think it applies too. 
i tested the case where 2 different user account login  the same shop on the same browser one after the other. the second user, in the app, sees details of the first user.

**Comment by osiset** [comment]
Ah same shop.

Ok, I'm not too sure what to do in this case. If you're on the same browser with the app open as two different users, a clash will happen.

I do not have control over the cookie naming/handling that Laravel does (well, its difficult to modify this behaviour).

We only get user information from the oauth process, its then stored in session cookies by Laravel.

If you go in as another user, and they go through the oauth process, I think this same session cookie is going to be overwritten, since its the same domain.

This is going to require some thought... I'm not sure what I can control here.

**Comment by aledelgo** [comment]
I think that responsibility about laravel-user and shopify-account synchronization stays on top of the app developer... not of your package. only the app-dev know if-what-when is right to delete current app session data.

the simplest solution is to track the ?session param received in the authentication middleware and emit an event to notify any change so that the app developer could listen for it and do something.

**Comment by osiset** [comment]
I think it should be part of the package as much as possible so its plug and forget :)
I'll see tonight on a test case and see what I can sniff from your notes and see if theres a way to detect and send them back through auth.

**Comment by osiset** [comment]
Alright so yes, it seems I'll need to check the `session` value after some testing.

I'll need to modify the AuthShopify middleware to support this.. store the session value, and if it changes, then re-send to auth.

**Comment by osiset** [comment]
I now have a fix in place, just need to do some tests.

**Comment by osiset** [comment]
Testing has gone fine. It now tracks the session token provided by Shopify.

If it changes, which it does when you logout, and login as a new user... then it re-auths and updates the user info.

Have not seen any issues in my testing so I will release a minor version tonight with these abilities.

As well, it also now tracks the expiration of the user token, if the time is expired, then it sends to re-auth as well.

**Comment by aledelgo** [comment]
great job osiset!
i'm patching my v10.x fork too... but neverminded the user token expiration... ;-)

**Comment by osiset** [comment]
Present in v11.1.0. Any issues please reopen.
