### ISSUE TITLE
Why in v11 shops table has been merged to native User table?

### ISSUE THREAD

**Issue by aledelgo** [osiset/laravel-shopify#423]
I was comparing the new package v11 with my v10 and i'm wondering why you merged the shop attributes in the native laravel User account.

**No complaining, just wondering about the reason.**

**I've not tested this**, but I think the way is working the v11 (as for the fact the email field of user is UNIQUE), make this plugin not acceptable for any ONLINE GRANT app neither for accounts that have multiple shops...

If i'm the owner of 2 stores, and i want to install the same app no both stores... the app will crash because when authorization will try to add 2 shops to the user table, both will have same email address... and the second will fail for the UNIQUE constraint.

On my side this make for me impossible the upgrade because, as **Shopify support multiple staff account for each shop** (and the same account may contribute to multiple shops), to me it is natural that shop and user entities should be isolated. (just my thought)

**Comment by osiset** [comment]
It was highly requested even when the package was young.

`name` is now the shop domain.
`email` is now `shop@(name)`.

You can only install the app once for a single shop, it will always be unique.

Does that answer your question?

**Comment by aledelgo** [comment]
Yes perfectly answered, thank you very much!

now i wonder why it was highly requested... 🤣🤣
this feature really make things hard for dev that have to develop an app that manage users too.

**Comment by osiset** [comment]
Great :) will close for you.

**Comment by fingersandmind** [comment]
@osiset Where does the storing of user to db takes  place? Is there any way that during creation of users, I can add another value?

**Comment by Kyon147** [comment]
> @osiset Where does the storing of user to db takes place? Is there any way that during creation of users, I can add another value?

Your best bet is just to use the AfterAutneucateJOb to add another field. 

The package was moved to the native users because it does make more sense, you can tie into the native authentication, WebSockets, channels and much more.

**Comment by osiset** [comment]
@fingersandmind  Since we use standard Users model, create an observer to watch created. Laravel has docs on this :)

**Comment by bogdanghervan** [comment]
I also wonder why this change came to be. This makes me choose not to upgrade from `ohmybrew/laravel-shopify:^6.0`.

**Comment by Kyon147** [comment]
It is said above your comment `Since we use standard Users model`

Moving over the standard User modal allows you better completeness with the internal working of Laravel and their Authentication for users. One big benefit is using the Auth guards for broadcasting events (good for websockets)

There is a pretty complete wiki for the migration, and although a little time consuming it is a lot of "find & replace" with some changes needed in your DB.

**Comment by adrianthedev** [comment]
Yes, I kind of agree this is not the way I'd go @osiset and @Kyon147.

> Moving over the standard User modal allows you better completeness with the internal working of Laravel and their Authentication for users.

👆 This is a hack in my oppinion. `User`s and `Shop`s are different entities that do different things. 
You increase the cognitive load by having to remember what the `email` field is to a "shop" (which is in fact a `User` model on the `users` table) and what a `password` is, etc. 
**You may not want to change the database in an existing app that needs to be extended to support Shopify**, or do *a lot of "find & replace"*.

> You can only install the app once for a single shop, it will always be unique.

You can still have this 👆 while splitting up the `User` and `Shop` models.

IMHO this package can be immensely improved (while keeping all the good things) if the `Shop` model is extracted separately and not get mixed in with authentication.
I've used [`shopify_app`](https://github.com/Shopify/shopify_app#authentication) quite a lot and quite extensively in an app where a `User` could log in as a user with whatever authentication method he chooses and have as many `Shop`s as he wanted.

I was quite sold on the ideea of using this package for Shopify when I saw the `shopify_app` "branding".

**Comment by osiset** [comment]
Too many downsides to having a new table. This won't be explored.

**Comment by adrianthedev** [comment]
I'm curious what are the many downsides. `shopify_app` does it like that. It supports multiple shops on the same user.

**Comment by amosmos** [comment]
Hi,

In continuation of this discussion, I have a question.
We ran into a situation where we need to run a command against all stores using our app.
We thought of looping through the Users models, but some of them are not shops but real users.
What is the right way to differentiate a user model who is a shop and a user model who is an actual user?
Is it just based on the 'shop@' email address? What if one of the users has an email address that starts with 'shop'?
Is there any other field that can tell us that?

Thanks,
Amos
