### ISSUE TITLE
Undefined property $capped_amount

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#425]
## Expected Behavior
will open the fare confirmation window

## Current Behavior
error:
Undefined property: Osiset\ShopifyApp\Services\ChargeHelper::$capped_amount

if you make the 'capped_amount' null field, then everything is fine.

### Steps to Reproduce
1) install the application
2) enable billing
3) add a tariff plan from the example
4) try to access the application
5) error
### Context

Package Version: v11.1.0
Laravel Version: v6.18.2
PHP Version: v7.2.2

### Failure Logs

message: "Undefined property: Osiset\ShopifyApp\Services\ChargeHelper::$capped_amount"
exception: "ErrorException"
file: "/home/user/public_html/testApp/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ChargeHelper.php"
line: 267

______________
and a separate issue:
is there an easy way to implement a change of tariff plan?
I did it through route redefinition, but it's not the best solution, to say the least.

**Comment by Enmaboya** [comment]
kind of figured out what the problem was.

Shopify api recurringapplicationcharge expects 'terms' but 'cappedTerms' comes in the request.

in vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ChargeHelper.php.

I've changed it temporarily for now:
        $transfer->cappedAmount = $isCapped ? **$this->capped_amount** : null;
        $transfer->cappedTerms = $isCapped ? **$this->terms** : null;

on .

        $transfer->cappedAmount = $isCapped ? **$plan->capped_amount** : null;
        $transfer->cappedTerms = $isCapped ? **$plan->terms** : null;


also in the createCharge function in vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php
I added:
   **$payload = $payload->toArray();
   $payload['terms'] = $payload['capped_terms'];**

        $response = $this->doRequest(
            ApiMethod::POST(),
            "/admin/{$typeString}s.json",
            [$typeString => **$payload**]
        );

Translated with www.DeepL.com/Translator (free version)

**Comment by osiset** [comment]
Please try v11.2.0
