### ISSUE TITLE
Billing Upgrade error

### ISSUE THREAD

**Issue by danbergan** [osiset/laravel-shopify#426]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Trying to upgrade a billing plan.   I used the link from the documentation:

`<a href="{{ route('billing', ['plan_id' => 2]) }}">Upgrade</a>`

I expected to be taken to the Shopify page to approve the charge.

## Current Behavior
Error:
Undefined variable: plan {"exception":"[object] (ErrorException(code: 0): Undefined variable: plan at /var/www/html/shopapp/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/GetPlanUrl.php:74)

It appears that this can be fixed by adding the following code to ShopifyApp/Actions/GetPlanUrl.php:

// If the plan is null, get a plan
if ($planId->isNull()) {
    $plan = $this->planQuery->getDefault();
}
else {
    $plan = $this->planQuery->getById($planId);
}

## Failure Information

`<a href="{{ route('billing', ['plan_id' => 2]) }}">Upgrade</a>`
Click the link, and the exception will appear.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Place the upgrade link in a view:
`<p><a href="{{ route('billing', ['plan_id' => 2]) }}">Upgrade</a></p>`
2. click on the link to upgrade the plan.
3. Exception occurs.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 11.1.0
* Laravel Version: 5.8.37
* PHP Version: 7.2.28
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Undefined variable: plan {"exception":"[object] (ErrorException(code: 0): Undefined variable: plan at /var/www/html/shopapp/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/GetPlanUrl.php:74)

**Comment by osiset** [comment]
Thank you will investigate this.

**Comment by osiset** [comment]
Believe I just solved this... will physically test

**Comment by osiset** [comment]
Please give v11.2.0 a go.

Also, noticed wiki was old... please do ` <p><a href="{{ route('billing', ['plan' => 2]) }}">Upgrade</a></p>`, remove the `_id` in plan.

Tested on live app and went well.

**Comment by danbergan** [comment]
Thanks.  I'll give v11.2.0 a try once it is up on Packagist.

**Comment by osiset** [comment]
Closing, if still an issue, reopen :)
