### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#432]
## Expected Behavior
normal post-request operation
## Current Behavior
error axios:
```
message: "The payload is invalid."
exception: "Illuminate\Contracts\Encryption\DecryptException"
```
error ajax:
`message: "CSRF token mismatch." (с)
`

### Steps to Reproduce
1) install the application
2) make any post request via ajax (in my case, react js and axios are used).
at the beginning, these requests will work as usual.
3) Click on the "View your online store" button and wait for the store to fully load. (You do not need to close the tab with the application).
4) After that they will return to the tab with the application and try to send the post request again.
5) get an error

### Context
Package Version: v11.2.0
Laravel Version: v6.18.2
PHP Version: v7.2.2

### Failure Logs

if you use jquery ajax:
message: "CSRF token mismatch."
exception: "Symfony\Component\HttpKernel\Exception\HttpException"
file: "/home/user/public_html/testApp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
line: 225

if you use jquery axios:
message: "The payload is invalid."
exception: "Illuminate\Contracts\Encryption\DecryptException"
file: "/home/user/public_html/testApp/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php"
line: 195

**Comment by Kyon147** [comment]
I am not using V11 yet but I know this problem happens on any version when you don't send the CRSF token in any response.

For Axios, you need to add it to every request so you can in your app.js file just do
```
window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest',
    'X-CSRF-TOKEN' : document.querySelector('meta[name="csrf-token"]').getAttribute('content')
};
```

A normal request just does the same in the AJAX call like so:

                    `$.ajax({
                        url: '',
                        type: 'POST',
                        data: {},
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (data) {
                        //Do something when successfully called.
                        },
                        dataType: 'json',
                    });`

**Make sure you have the token in the meta of course otherwise it won't work**

**Comment by Enmaboya** [comment]
> I am not using V11 yet but I know this problem happens on any version when you don't send the CRSF token in any response.
> 
> For Axios, you need to add it to every request so you can in your app.js file just do
> 
> ```
> window.axios.defaults.headers.common = {
>     'X-Requested-With': 'XMLHttpRequest',
>     'X-CSRF-TOKEN' : document.querySelector('meta[name="csrf-token"]').getAttribute('content')
> };
> ```
> 
> A normal request just does the same in the AJAX call like so:
> 
> ```
>                 $.ajax({
>                     url: '',
>                     type: 'POST',
>                     data: {},
>                     headers: {
>                         'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
>                     },
>                     success: function (data) {
>                     //Do something when successfully called.
>                     },
>                     dataType: 'json',
>                 });
> ```
> 
> **Make sure you have the token in the meta otherwise it won't work**

the meta has a csrf token, but these solutions do not work.

I looked at VerifyCsrfToken Middleware, after going to the store page - token becomes null

**Comment by Kyon147** [comment]
> I looked at VerifyCsrfToken Middleware, after going to the store page - token becomes null

Can you check to make sure the token is there as a meta tag on the page?

**Comment by Enmaboya** [comment]
> > I looked at VerifyCsrfToken Middleware, after going to the store page - token becomes null
> 
> Can you check to make sure the token is there as a meta tag on the page?

I just checked again,
csrf token is present on the page.

The problem is that after going to the store page the token changes and as a result the function tokensMatch() from VerifyCsrfToken middleware returns 

token, i display it in the console
![image](https://user-images.githubusercontent.com/32259003/77527224-31a86480-6ea5-11ea-8f97-62d8dbafc60d.png)

before store opening
![image](https://user-images.githubusercontent.com/32259003/77527553-c612c700-6ea5-11ea-8199-5dd9069a043f.png)

after store opening
![image](https://user-images.githubusercontent.com/32259003/77527616-e3e02c00-6ea5-11ea-8c36-e7e5fceda5ef.png)

**Comment by osiset** [comment]
I wouldn't even know where to begin with this, as I don't internally control any of the CSRF Laravel handles.

Does a standard POST work? My guess if your AJAX post is causing something to change for the shop's session running through the auth middleware.

**Comment by osiset** [comment]
Closing until more info provided, thanks

**Comment by stychos** [comment]
Same here with standard POST, blade's `@csrf` don't works for me, giving 419.

**Comment by stychos** [comment]
With absolutely any custom get / post arguments I am getting one of two "options":
- disable auth.shopify middleware and get no Auth()->api() object
- or, get Shopify authentication error (on get) or 419 (on post)

@osiset can you point me please, which more information I can gather to help?

**Comment by stychos** [comment]
Hm.. looks like it's Laravel-specified, same with a clear framework. Seems it is not likes to work in a frame (with the AppBridge).

**Comment by darrynten** [comment]
This should be re-opened, experiencing this problem

**Comment by moh-slimani** [comment]
the best solution I found is this
you need to change the `same_site` value in **config/session.php**.

like this

```
'same_site' => 'none',
'secure' => env('SESSION_SECURE_COOKIE'),
```

and set `SESSION_SECURE_COOKIE=true` in the **.env** file.

more info check this [youtube video](https://www.youtube.com/watch?v=GPz7onXjP_4)

**Comment by jhaineymilevis** [comment]
i have the same issue.

version:17.0
bridge embeded
Browser: chrome, incognit mode. turblo links enabled. 

my request is sending token, chek image; https://drive.google.com/file/d/1jO9-Al_UusRpT3EJViV0vwAC62oLziIH/view?usp=sharing

**Comment by sushilsth** [comment]
> any solution to this issue. I am still getting CORS issue after doing this.

'same_site' => 'none',
'secure' => env('SESSION_SECURE_COOKIE'),
