### ISSUE TITLE
Not Redirect to shopify Embeded

### ISSUE THREAD

**Issue by somin-parate** [osiset/laravel-shopify#434]
After installation screen its redirecting to me on this url instead of using domain
http://https/?hmac=e0a979ed0112ba0cdb0c68cf8c2ff3a5aedac602cbce2dc396f9a9f1b676c9cf&shop=development-reset-iv-hydration-therapy.myshopify.com&timestamp=1585133101

After installing unlistd app its redirect on above screen without my custom domain

**Comment by osiset** [comment]
No issues here. Fresh install.

Please record the URL you're sent to by Shopify and report back.

There should be a redirect param on the URL.

**Comment by osiset** [comment]
Closing to inactivity. Reopen if still issue.
