### ISSUE TITLE
Fails to redirect back to shopify store after install, does not remember logged in store

### ISSUE THREAD

**Issue by RandomWeasel** [osiset/laravel-shopify#435]
## Expected Behavior

After install (login screen, oAuth screen, billing screen), the app should redirect back to the shopify store page, with the newly-installed app displayed in shopifys iframe.

When re-visiting the app, the user should not have to re-enter the store domain / after re-entering the store domain, the app should be displayed

## Current Behavior / Steps to Reproduce

- Installing unlisted app from Partners dashboard
- After clicking 'install', the 'login' screen is shown.   (not within shopify)
    - Network shows a GET to `https://custom-peaks-uk.myshopify.com/admin/oauth/redirect_from_partners_dashboard?client_id=a1933619258faeb2f42bf8af849e0c24&signature=eyJleHBpcmVzX2F0IjoxNTg1MjEyMjg5LCJwZXJtYW5lbnRfZG9tYWluIjoiY3VzdG9tLXBlYWtzLXVrLm15c2hvcGlmeS5jb20iLCJjbGllbnRfaWQiOiJhMTkzMzYxOTI1OGZhZWIyZjQyYmY4YWY4NDllMGMyNCJ9--f9249da30e9aaf1464af44d5beaefbc9a8e0946d`
    - GET to `https://myapp.domain.com/?hmac=580e21cc65352ac5b21fc2f79a35e3a2ee8bb92906b42f487c5d8001f778035f&shop=custom-peaks-uk.myshopify.com&timestamp=1585211990`
    - GET to `https://myapp.domain.com/setup/login`

- after entering shop url and submitting, the oAuth screen is shown (within shopify frame
    - GET `https://myapp.domain.com/setup/authenticate`
    - GET `https://custom-peaks-uk.myshopify.com/admin/oauth/authorize?client_id=a1933619258faeb2f42bf8af849e0c24&scope=read_products%2Cread_orders&redirect_uri=https%3A%2F%2Fmyapp.domain.com%2Fsetup%2Fauthenticate`
- GET `https://custom-peaks-uk.myshopify.com/admin/oauth/request_grant?client_id=a1933619258faeb2f42bf8af849e0c24&redirect_uri=https%3A%2F%2Fmyapp.domain.com%2Fsetup%2Fauthenticate&scope=read_products%2Cread_orders`
- GET `https://custom-peaks-uk.myshopify.com/admin/oauth/request_grant?client_id=a1933619258faeb2f42bf8af849e0c24&redirect_uri=https%3A%2F%2Fmyapp.domain.com%2Fsetup%2Fauthenticate&scope=read_products%2Cread_orders`

- after clicking install on oAuth screen, the billing screen is shown (within shopify frame)
    - POST `https://custom-peaks-uk.myshopify.com/admin/oauth/grant`
    - GET `https://myapp.domain.com/setup/authenticate?code=d5f011c393bbd2dcb1b551749d797b3e&hmac=ae54616afcbd5c3210b6a9634ee36fe9f9af08bbc699de3b0856c65675b610c2&shop=custom-peaks-uk.myshopify.com&timestamp=1585212310`
   - GET `https://myapp.domain.com/`
   - GET `https://myapp.domain.com/setup/billing`
   - GET `https://custom-peaks-uk.myshopify.com/admin/charges/11897569378/confirm_recurring_application_charge?signature=BAh7BzoHaWRsKwhigCbFAgA6EmF1dG9fYWN0aXZhdGVG--c51b8e19cfdc1485b0e55729dcceb74c04cc1e71`
    - GET `Https://custom-peaks-uk.myshopify.com/admin/charges/11897569378/request_recurring_application_charge?signature=BAh7BzoHaWRsKwhigCbFAgA6EmF1dG9fYWN0aXZhdGVG--c51b8e19cfdc1485b0e55729dcceb74c04cc1e71`

- after accepting billing charge, the app's homescreen is displayed, but not within the shopify store iframe.  The url displayed in the browser is `https://myapp.domain.com` but it should be something like `https://my-store-name.myshopify.com/admin/apps/someotherstring`
    - POST https://custom-peaks-uk.myshopify.com/admin/charges/11897569378/confirm_recurring_application_charge
   - GET `https://custom-peaks-uk.myshopify.com/admin/charges/11897569378/request_recurring_application_charge?signature=BAh7BzoHaWRsKwhigCbFAgA6EmF1dG9fYWN0aXZhdGVG--c51b8e19cfdc1485b0e55729dcceb74c04cc1e71`
   - GET `https://custom-peaks-uk.myshopify.com/admin/tools/billing_action.json`
   - GET `https://myapp.domain.com/setup/billing/process/1?charge_id=11897569378`
   - GET `https://myapp.domain.com/`

I can navigate within the app at this point (outside of the iframe) with no issues

However if I then go to the Stores 'apps' page, and click on the newly installed app, I see the 'login' screen again.  If I re-enter the store domain and submit, I see `419 page expired`.  If I reload at this point, I'm back to the login screen, and so on. 

I did have a similar issue previously with the login screen reappearing, when running the app on localhost with an ngrok tunnel which we thought may have been the issue, however I now have the app running on a server and am accessing it without ngrok.
Running locally I was working around the issue by having removed the VerifyCsrfToken middleware from the kernel, so I'm not sure if this may be involved somehow?

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v11.1.0
* Laravel Version: v6.9.0
* PHP Version: v7.2.29
* Using a toolset (Docker, Laradock, Vagrant, etc.): no, running online and accessed directly by url

**Comment by RandomWeasel** [comment]
@osiset, apologies but it looks like this may have been an issue of my own making.  I found a stray auth middleware attached to my controller that I'd managed to miss.  Will continue debugging and close the issue if this does turn out to have been the source of all the problems (quite likely 🤦‍♀️ )

**Comment by osiset** [comment]
@RandomWeasel Sounds good, thank you. I have not been able to reproduce this on my clean 7 install, so if you find a clue, let me know. Will leave in-limbo for now until you report back.

**Comment by osiset** [comment]
Closing for now. Reopen if something is discovered.
