### ISSUE TITLE
Login Issue Redirected to Login with Unknown Error

### ISSUE THREAD

**Issue by ardnor** [osiset/laravel-shopify#436]
Hello, I installed a new Shopify app with the current version of laravel ^7.0 and this was the result.

![image](https://user-images.githubusercontent.com/11624294/77821818-0d0fef00-7128-11ea-82cb-ff6c20703107.png)

When I tried to check the home page and I can access the store name. So what happen when I log in? Is there any I missed in the configuration?

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1: Login page and login with the store
2. Step 2: But it was redirected to login page with Unknown Error
3. Step 3: I tried to check the home I can see the store name
4. Step 4: I tried to check your code with the above screenshot the "code" don't have value

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: ^11.1
* Laravel Version: ^7.0
* PHP Version: 7.3.7
* Using a toolset (Docker, Laradock, Vagrant, etc.): Windows, Xampp (the SSL was configured)

**Comment by ardnor** [comment]
I tried in production and it works.

**Comment by andrewscofield** [comment]
Just got this issue too and I figured out what it was. It boiled down to Shopify not allowing webhooks to be installed using 'localhost' or I'm sure any non-public domain. So the app is silently failing here: 

https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php#L66

Quickest solution that worked for me: open config/shopify-app.php and comment out the webhooks during local development.

**Comment by osiset** [comment]
Will mark as resolved for now.

Yes, no localhost, and must be https. As well, anything ngrok will probably error as well.

**Comment by andrewscofield** [comment]
But is there a way to get it to not run in local? Or what way should webhook installation be prevented on local development?

**Comment by osiset** [comment]
People have some success with ngork. Personally, I unit test what I can locally with fixture data, then deploy a Docker container to a staging environment to test with a web-accessible url.
