### ISSUE TITLE
Oauth error invalid_request: Could not find Shopify API application with api_key

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#437]
I build a simple Shopify app and test using ngrok and local machine.

Today when I upload my code to server I can install the app and I got the message:
Oauth error invalid_request: Could not find Shopify API application with api_key

https://www.screencast.com/t/NSKV7KwB

What could be the problem? The same code works well when I'm using ngrok and localhost

**Comment by Kyon147** [comment]
.env files are not pushed with git etc

So have you sorted your production env file? Sounds like you have not set the API_KEY in there.

**Comment by osiset** [comment]
As @Kyon147 pointed out, this is something on your side with the server.

If you find otherwise, please reopen.
