### ISSUE TITLE
Login Issue redirect to authenticate error

### ISSUE THREAD

**Issue by taiviemthoi** [osiset/laravel-shopify#439]
Related issue : https://github.com/osiset/laravel-shopify/issues/436
I debug and see the code = 0
and error
> TypeError
Argument 1 passed to Osiset\ShopifyApp\Storage\Observers\Shop::creating() must be an instance of Osiset\ShopifyApp\Contracts\ShopModel, instance of App\User given

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v11.2.0
* Laravel Version: 7.3.0
* PHP Version: 7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker, Laradock

**Comment by APdevelopments** [comment]
that's correct. thanks very much

**Comment by taiviemthoi** [comment]
I have used an older version (v10) and it works fine, maybe v11 is having a problem
