### ISSUE TITLE
Custom shopify app

### ISSUE THREAD

**Issue by odera89** [osiset/laravel-shopify#442]
Hi all,

I have a question. I just setup locally and with ngrok. All worked fine. I have just one problem. I want to use on custom app not public app. Can i? I got this screen when I want to authorize the store. https://www.dropbox.com/s/26afcj4fiupttsl/Screenshot%202020-04-07%2021.28.00.png?dl=0

I added manually the app to my store but my problem is that the Auth::user() not working. Maybe can I force to login or something like that?

Suggestions?

**Comment by awebartisan** [comment]
Hi, for custom apps you need to generate a unique link from Partner dashboard. From that link you will be able to install the app.

About the `Auth::user()`, what error you are getting? Need more info.

**Comment by odera89** [comment]
Yes yes. I generated it and is working welll. 

About the Auth:user() on shopify admin is working well. My problem was that I want to work on localhost and every time when I want to access the local URL, is redirecting to login.. Can I make a force login for local development? or what I need to do?

**Comment by awebartisan** [comment]
"Redirecting to login", by this do you mean "login of app" ?

Also, what does your local setup look like? are you using Laravel Valet?

**Comment by odera89** [comment]
yes the login screen of the app. here: https://www.dropbox.com/s/34o16h960kjefv5/Screenshot%202020-04-08%2008.27.43.png?dl=0

My local setup is the base Laravel 7. fresh install.

**Comment by awebartisan** [comment]
How are you serving your app? Are you using `php artisan serve` command to run your Laravel app? 

This could also happen if your cookies are not being set. Check in browser if cookies are being set.

**Comment by odera89** [comment]
im used without php artisan server.
I have these cookies setup - https://www.dropbox.com/s/fys4o2h2cwn0zhq/Screenshot%202020-04-08%2010.13.41.png?dl=0

**Comment by osiset** [comment]
Sorry, I do not support ngork.

Shopify has changed the rules for apps, yes. You now have to generate a link or install it to a development store.. its not ideal as it was before.

I recommend you Dockerize your setup, use a self-signed certificate with Nginx or Apache, and a ".local" domain name. This is what I current do for local development and works fine.
