### ISSUE TITLE
two Shopify stores using the same app at the same time will cause some bugs

### ISSUE THREAD

**Issue by wuxi889** [osiset/laravel-shopify#443]
Sorry, my english is poor.
In the same browser, two shopify stores using the same app at the same time will cause some bugs.
ex:
### 1. Reapply for authorization from shopify

![5 0MFT8RTN6IGKL13038Y4P](https://user-images.githubusercontent.com/29323350/78743314-da1ff380-7990-11ea-83c9-325f8d4d14d6.png)

### 2. laravel_session missing in request header cookie

Response header has set-cookie, **but it is invalid**

![K5P}8O3 QMGL542$A{88Q1J](https://user-images.githubusercontent.com/29323350/78743121-4d753580-7990-11ea-8b6d-7a3e86becaef.png)

**Comment by darrynten** [comment]
This is starting to become a bit of a problem. I have customers who manage multiple stores that use the same app and there has been some crossover, i.e. the wrong info got saved to the wrong store.

**Comment by nguyentvnhat** [comment]
> This is starting to become a bit of a problem. I have customers who manage multiple stores that use the same app and there has been some crossover, i.e. the wrong info got saved to the wrong store.

Hi @darrynten, can you more explain that issue, please?. I'm going to this package to sell in Shopify

**Comment by darrynten** [comment]
@nguyentvnhat xin chào bạn!

If you switch to using the JWT from Shopify and `auth.token` routes you will no longer experience this issue.

**Comment by LonnyX** [comment]
is this still a problem ?

**Comment by osiset** [comment]
Cleanup... Closing for now, cookies are removed in v17.0.0
Re-open if still and issue.
Thanks!
