### ISSUE TITLE
ONETIME charge does not contain "activated_on" attribute in API response

### ISSUE THREAD

**Issue by awebartisan** [osiset/laravel-shopify#444]
## Expected Behavior

"activated_on" attribute should only be for RECURRING charge.

## Current Behavior

"activated_on" attribute is also being checked for ONETIME Application charge also.

Attributes for Application Charge from Shopify API can be seen on below link:
[https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#create-2020-04](https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcharge#create-2020-04)

## Failure Information

`ErrorException`
`Undefined property: stdClass::$activated_on`

`$transfer->activatedOn = $response->activated_on ? new Carbon($response->activated_on) : Carbon::today();`
in **ActivatePlan.php** on line 131.

### Steps to Reproduce
1. Create a ONETIME charge plan
2. Try to activate this charge

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v11.1
* Laravel Version: v7.4.0
* PHP Version: v7.4
* Valet

**Comment by osiset** [comment]
Will be in tonights release, thanks!
