### ISSUE TITLE
How to manipulate to be created users when App is being installed

### ISSUE THREAD

**Issue by fingersandmind** [osiset/laravel-shopify#447]
#182  Expected Behavior

I can't seems to find a way to manipulate the user creation during app installation, using this package together with other platform and need to label every users what platform they belongs. Or am I just missing something? 

App being installed, during creation of the user(shop) need to have a way to describe what platform (in this case "shopify)

## Current Behavior
Did not found any or am I just missing something?

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: latest (v11.2)
* Laravel Version: v6.17.1
* PHP Version: v7.2.9

**Comment by Kyon147** [comment]
Sounds like you could use the AfterAuthenticateJob for this. 

The info is here: https://github.com/osiset/laravel-shopify/wiki/After-Authentication-Job

**Comment by fingersandmind** [comment]
@Kyon147 Hi! yes I've already tackled this section already, but idk where and what to do from there. Take me as a not expert with dealing jobs. Do you happen to find any example how to implement or logic inside the jobs? Would be very much grateful thanks in advance.

**Comment by fingersandmind** [comment]
Or how do I get $shop? was it automatically handled and no need to call the Jobs anywhere?

**Comment by Kyon147** [comment]
Just pass shop as a dependency to the Job

```
    public function __construct($shop)
    {
        //
        $this->shop = $shop;
    }
```

**Comment by fingersandmind** [comment]
@Kyon147 Thank you very much. I will try it, and closing it for now

**Comment by fingersandmind** [comment]
@Kyon147  Hi! Actually AfterAuthenticateJob is not the solution. What I want to know is where is the actual saving of shopify user to the database, so I can add another value and not run job everytime I authenticate. Would be very grateful if you'll response.

**Comment by fingersandmind** [comment]
@Kyon147 Hi! Why the job is not firing? I successfully authenticate my shop but Job is not firing.
