### ISSUE TITLE
Fresh install migrate fails on Laravel 5.8

### ISSUE THREAD

**Issue by aaronlp** [osiset/laravel-shopify#450]
## Expected Behavior

Initial migration or fresh migration succeeds without errors.

## Current Behavior

Initial or fresh migration fails due to an error creating a foreign key. Same behaviour as described in prior bug report https://github.com/osiset/laravel-shopify/issues/419

## Failure Information

Failure is due to Laravel 5.8 changing the user_id column type to bigIncrements. Version check implemented as fix for https://github.com/osiset/laravel-shopify/issues/419 incorrectly excludes Laravel 5.8 from the updated column type.

### Steps to Reproduce

Migrate on a fresh install of Laravel 5.8.*.

* Package Version: v11.3
* Laravel Version: v5.8
* PHP Version: v7.2

**Comment by aaronlp** [comment]
Raised PR https://github.com/osiset/laravel-shopify/pull/449 to address this issue.

**Comment by osiset** [comment]
Done, thanks, will be in tonights release.
