### ISSUE TITLE
Can't find `ShopifyApp` facade class 

### ISSUE THREAD

**Issue by xyyolab** [osiset/laravel-shopify#454]
I'm using the latest master branch version.
How can I do this? 
```    
$shop = ShopifyApp::shop();
$requests = $shop->api()->rest('GET', '/admin/api/2019-07/products.json')
```
I found an  aliase in composer.json, but `Osiset\ShopifyApp\Facades\ShopifyApp` class seems not exist.
I can't find it anywhere.
Thank you for your help in advance.

**Comment by xyyolab** [comment]
Oh, thanks, I think I found out how to do it!

**Comment by shawndreck** [comment]
@xyyolab How did you solve this, please? I am in the same situation but I have not a fixed.

**Comment by xyyolab** [comment]
Don't use ShopifyApp facade, just do like this!
```
$products = Auth::user()->api()->rest('GET', '/admin/api/2020-04/products.json')->body;
```
