### ISSUE TITLE
[2020-04] Status update: Please read

### ISSUE THREAD

**Issue by osiset** [osiset/laravel-shopify#455]
_Side note: I wish Github had an "announcement" or "forum" feature... this feels like an abuse of the issues feature but it the only form of communication I have to reach you all, sorry!_

Hello all,

I've had several emails this week asking about the open issues, which I would like to address.

Due to COVID-19... many companies are facing hard times. A range of things, but not limited to:

- Staff layoffs due to shortage of work
- No work due to deeming non-essential
- Extra work on people's plates due to less staff
- Shifts in core business activities to account for COVID
- Etc...

Unfortunately, there's a lot of extra on my plate the past couple of weeks. I am not ignoring the issues, please do not email and ask if I am 😃 , I am simply swamped with extra unforeseen work 😢 .

I plan on taking Wednesday and Thursday nights, as well as Sunday night to tackle the open issues. Please have patience, I am one person.

Thank you! ❤️ 🔧

**Comment by Kyon147** [comment]
I'll download a fresh package this week and try and help you tackle some issues and submit some PRs if I sort anything. 

Give me a shout if you need anything.

**Comment by Hujjat** [comment]
You're great man. Thank you for all the hard work putting for this awesome package. 

I'm currently recording a full course for free about your package. It's about 45 videos. Complete Shopify app development with Laravel. I'm not mentioning it for promotion or anything like that. Just want to say Thank you. : ) 

If anyone interested, I can share the full course link here. It's completely free. 

Thanks, @osiset for your great package.

**Comment by amosmos** [comment]
THANKS and be safe!!!

**Comment by jasontxf** [comment]
Thank you for working so hard on this package! I truly appreciate it!

Quick question, is version 11 production ready? I'm about to start a new Shopify app and not sure if I should use v10 or v11.

**Comment by osiset** [comment]
While things in work-life have been finally starting to settle out. I am starting to be able to have some time to focus back on the package, will close and de-pin this notice in a week if this stays the same.

Thanks for understanding.

**Comment by Adebayo120** [comment]
> You're great man. Thank you for all the hard work putting for this awesome package.
> 
> I'm currently recording a full course for free about your package. It's about 45 videos. Complete Shopify app development with Laravel. I'm not mentioning it for promotion or anything like that. Just want to say Thank you. : )
> 
> If anyone interested, I can share the full course link here. It's completely free.
> 
> Thanks, @osiset for your great package.

share link to your youtube channel please

**Comment by Hujjat** [comment]
Hey @Adebayo120 

Here is the playlist : [Shopify App with Laravel - Free Course](https://www.youtube.com/watch?v=DHKtoWrHMhI&list=PLB4AdipoHpxbE0ldfsNobTSZm2tUBW9GR)

Thanks
