### ISSUE TITLE
Feature: Uninstall removed webhooks

### ISSUE THREAD

**Issue by jasperpoppe** [osiset/laravel-shopify#456]
This is a feature request!

In the file `config/shopify-app.php` I added some webhooks to the `webhooks` key.
After a while, I deleted a webhook since I didn't need it anymore.

Now, the deleted webhook (in `config/shopify-app.php`) is still active and I'm receiving emails from Shopify with subject `Your webhook is failing`.

Is it possible to have a kind of sync for the webhooks?
Every time a shop logs into the app, the webhooks are added, but it would be nice if the old one's could be deleted too.

Thanks in advance!

**Comment by osiset** [comment]
@jasperpoppe I do not want to automatically control this, puts too much bias on the package to do this.

If you're looking to remove all webhooks, you can do this:

```php
use Osiset\ShopifyApp\Actions\DeleteWebhooks;

...

$action = $this->app->make(DeleteWebhooks::class);
$action($shop->getId());
```

Delete specific webhooks?

```php
$apiHelper = $shop->apiHelper();

// Get the webhooks
$webhooks = $apiHelper->getWebhooks();

foreach ($webhooks as $webhook) {
    if ($webhook->address === 'something' || $webhook->topic === 'something/something') {
         $apiHelper->deleteWebhook($webhook->id);
    }
}
```

**Comment by jasperpoppe** [comment]
Thanks @osiset for your explanation!
Much appreciate your work on this! 🙏
