### ISSUE TITLE
Yearly subscription?

### ISSUE THREAD

**Issue by danbergan** [osiset/laravel-shopify#457]
Our was rejected because our web site pricing page shows yearly subscriptions as well as monthly and we were not offering yearly subscriptions in our Shopify App.

I do not see any way of offering a yearly subscription with the Shopify RecurringBillingCharge API.  Am I missing something?  Does anyone know of a way to create a yearly recurring charge?

**Comment by osiset** [comment]
Shopify does not support this, sorry. It does per-month only.

**Comment by danbergan** [comment]
Thanks, that's what I thought.  It is very annoying to get an app rejected when the API doesn't even support it.
