### ISSUE TITLE
Reinstall app throw error exception when i reinstall app

### ISSUE THREAD

**Issue by wuxi889** [osiset/laravel-shopify#458]
After uninstall app and softdelete user by webhook, when i reinstall app, the page throw exception.

![image](https://user-images.githubusercontent.com/29323350/79558669-1bbe4600-80d7-11ea-9ad4-a88539930d62.png)

## Expected Behavior

when i reinstall app, the page  will no exceptions

## Current Behavior

Throw error exception:
Creating default object from empty value

![image](https://user-images.githubusercontent.com/29323350/79558468-c5e99e00-80d6-11ea-9ae6-4098e6ab53c9.png)

## Failure Information

My app/uninstalled webhook code

```php
<?php

namespace App\Jobs;

use App\Models\ShopifyUser;
use Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob as ShopifyAppUninstalledJob;
use Osiset\ShopifyApp\Objects\Values\ShopId;
use Osiset\ShopifyApp\Objects\Values\ShopDomain;
use Osiset\ShopifyApp\Contracts\Commands\Shop;

class AppUninstalledJob extends ShopifyAppUninstalledJob
{
    protected $shopId;

    public function __construct(ShopDomain $shopDomain, $data) {
        $shop = ShopifyUser::where('name', $data->domain)->first();

        if ($shop) $this->shopId = new ShopId($shop->id);
    }

    public function handle(Shop $shopCommand): bool
    {
        if ($this->shopId) {
            $shopCommand->clean($this->shopId);
    
            $shopCommand->softDelete($this->shopId);
            return true;
        }

        return false;
    }
}

```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. add `AppUninstalledJob` in App/Jobs
2. uninstall app
3. and reinstall app

**Comment by wuxi889** [comment]
use `php artisan vendor:publish --tag=shopify-jobs` will tip error

```php
<?php

namespace App\Jobs;

class AppUninstalledJob extends \Osiset\ShopifyApp\Jobs\AppUninstalledJob
{
}
```
**Error:** `\Osiset\ShopifyApp\Jobs\AppUninstalledJob is undefined`

**Comment by osiset** [comment]
I think you may have missed the last update. @wuxi889 

Make the file:

```php
<?php

namespace App\Jobs;

class AppUninstalledJob extends \Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob
{
}
```

Its missing the `Messaging\` namespace.

**Comment by wuxi889** [comment]
thank u, the problem is solved
