### ISSUE TITLE
unable to get all products

### ISSUE THREAD

**Issue by arslan308** [osiset/laravel-shopify#459]
$shop = ShopifyApp::shop();
    $requests = $shop->api()->rest('GET', '/admin/api/2019-07/products.json');

i am using these  too
use Osiset\ShopifyApp\Facades\ShopifyApp;
use Osiset\ShopifyApp\Models\Shop;

error is
'Osiset\ShopifyApp\Facades\ShopifyApp' not found

**Comment by Kyon147** [comment]
You need to use `Auth::user->api()`

**Comment by arslan308** [comment]
@Kyon147  does this work or i have to ise osiset basic-shopify-api

**Comment by awebartisan** [comment]
If you are using v11.* of package, you need to use `Auth::user()->api()`, read more about it here:
[https://github.com/osiset/laravel-shopify/wiki/Usage](https://github.com/osiset/laravel-shopify/wiki/Usage)

**Comment by arslan308** [comment]
I am using 7.*

**Comment by arslan308** [comment]
@awebartisan  i am new to shopify app, can you please guide me, i am using this package osiset/laravel-shopify and also this osiset/basic-shopify-api, which one is best and proffessionaly used

**Comment by awebartisan** [comment]
BasicShopifyAPI package is a base package, its only purpose is to make Shopify API calls. Whereas, this is Laravel package, built on top of that BasicShopifyAPI package. They are meant to be used together and not separately.

**Comment by osiset** [comment]
@awebartisan Is correct.

```php
/** @var \Osiset\ShopifyApp\Contracts\ShopModel $shop */
$shop = Auth::user();

$shop->api()->rest('GET', '/admin/products.json');
```

No need to pass version in the URL, use SHOPIFY_API_VERSION env for that... default its set to 2020-01.

**Comment by arslan308** [comment]
solved
