### ISSUE TITLE
When Installing app it wont redirect me to the billing page

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#460]
I', using library version 11.3, Larave 5.8 and PHP 7.3 and I  want to create a billable app so I add a plan like this in database:
https://www.screencast.com/t/FCfgEKQ2Op

this is my config:
```
'billing_enabled' => (bool) env('SHOPIFY_BILLING_ENABLED', true),
    'billing_freemium_enabled' => (bool) env('SHOPIFY_BILLING_FREEMIUM_ENABLED', false),
```

When I want to install the app everything is fine just after installing it won't redirect me to the billing Shopify screen. Why?

**Comment by osiset** [comment]
Is your route behind the billing middleware?
