### ISSUE TITLE
Prevent Cross-Site Tracking - Safari 13.1 endless loop

### ISSUE THREAD

**Issue by StefanNeuser** [osiset/laravel-shopify#461]
Hi everybody,

from time to time we still get endless loops reports when merchants try to use the embedded apps with Safari.

I found out, if you disable "Prevent Cross-Site Tracking" it works.

Here a screenshot of the shopify error notification and the safari setting:

<img width="789" alt="Screenshot 2020-04-19 at 20 14 25" src="https://user-images.githubusercontent.com/2176503/79696148-274a7200-827b-11ea-9dcf-947950f68f0b.png">
<img width="518" alt="Screenshot 2020-04-19 at 20 03 06" src="https://user-images.githubusercontent.com/2176503/79696150-29143580-827b-11ea-85ee-2f9c6e9bd31b.png">

We are using the the Package Version v10.3.1

Have a nice Sunday and stay healthy guys

**Comment by osiset** [comment]
The Chrome and Safari stuff lately is straight up annoying.

There we're many changes to v11 to assist with the stupid cookie issues. For v11, just tested on Safari and seems to work..

I am not sure what I can suggest for v10. v11 uses a cookie helper service, which forces the cookie to be proper for Chrome-like requirements.

When I get some breathing room, I'll come back to provide some suggestions. Please tag me if I don't come back by Tuesday morning..

![Annotation 2020-04-19 203552](https://user-images.githubusercontent.com/2420282/79702172-6e396700-827d-11ea-9bc6-2aae1ff8afe3.jpg)

**Comment by StefanNeuser** [comment]
Hi @osiset , did you have time debug this issue?

**Comment by osiset** [comment]
Shoot, sorry got tied up with work. I'll see what I can dig up.

**Comment by osiset** [comment]
Closing for now as I have no support for this in the code. I need to support ITP and other things, very frustrating. Keep an eye out for progress.
