### ISSUE TITLE
auth.shopify middleware

### ISSUE THREAD

**Issue by vicreto** [osiset/laravel-shopify#462]
Hi everybody,
and forgive me for my English and if i misunderstand something

auth.shopify middleware log in guest users if their redirected from shopify after installing the app
is this not gonna allow everyone giving a shop in the request to access all routes behind this middleware ?
i have try it ( from other browser ) without app-bridging and its allow me to get to the routes

**Comment by osiset** [comment]
Possible... I have added a check that if they're a guest, they must have valid HMAC. Hopefully doesn't affect anything too much.

**Comment by osiset** [comment]
11.5.0 has a fix in place

**Comment by vicreto** [comment]
> 11.5.0 has a fix in place

i've found another solution, thank you and good job
