### ISSUE TITLE
Hardcoding a Domain

### ISSUE THREAD

**Issue by polibou** [osiset/laravel-shopify#463]
Hello,  if I am using this package to create a custom backend tool for a single shopify site, what is the best way to hardcode in the domain?  Would I need to extend the authentication process somehow?

I am trying to avoid the need to enter the domain whenever it times out.  I am also user PERUSER grant mode if that matters.  As long as a user is logged into Shopify I would like to bypass the app's authentication.

Thanks for any help!

**Comment by Kyon147** [comment]
You should not need to enter the domain every time, only reauth by clicking on the app in the Shopify admin page.

Also by using Per User grant mode, the access for your app is only for a long as the user session is live for which means if you close the tab etc - you will need to log in again. Whereas offline mode sessions last a bit longer, plus your app will have access to background tasks by using the offline token.

There is no way to stay "logged in" permanently, Shopify does not allow it for security reasons. Hard coding the domain won't do anything as you will still need to go through the OAUTH once the current session has expired.

**Comment by polibou** [comment]
Hi Kyon147 thanks for the info.  So my app is not intended to be embedded in the Shopify admin, which means users will directly access it by the domain.  I'm currently using per user as it automatically tracks the individual users from Shopify.  For me to use offline mode, I would have to add additional logic to create and track additional users.  (I may do it at some point)

Given this scenario...what is happening is after a few hours the users are redirected to the login/install to reauthorize.  ![Screenshot (69)](https://user-images.githubusercontent.com/2907353/80297865-029f4000-873c-11ea-8db6-ae5e0d3deb5f.png) Which I understand as you state, since they can't be logged in permanently.  Can I just somehow bypass the input field and"hardcode" or pass along the domain to re-auth?  I would just like it to happen automatically and seamlessly since it will always be the same domain that will be accessed.  

The current flow of this package is fine, but for my use case I'm not intending to use it with multiple stores, so there isn't a need to request which stores need re-authorizing.  I would just like to always re-authorize xyz.com every time whenever the user session is no longer valid.

I know this is possible, I'm just still on a learning curve with Laravel and this package.  Any insight would be great!

**Comment by awebartisan** [comment]
Hi there. Just on top of my head, will it be secure?

For the sake of example, let's say you store that domain inside database, its only one record. So you just select first record and log that in. Or maybe in a config file you hard code the domain.

By any chance, someone has discovered your app and just visit the link and they will be logged in, right? 
Maybe I got it wrong. 

But authentication with Shopify, every time they want to use it, is there for a reason. Security.

**Comment by polibou** [comment]
Hi, actually the authentication process wouldn't change.  It would still authenticate with Shopify and you still need the proper credentials.  It would just skip the step where it ask what domain you want to authenticate with Shopify, because it would already be set.  The user still need to be logged into the matching Shopify account in order for the app to work.

Right now, once you enter your Shopify domain in the package, it will take you to the Shopify login if you are not already logged in.

**Comment by osiset** [comment]
The login page is mostly useless now with Shopify's new app restrictions for development apps. You now how to generate an install link for "custom apps" or install to a development store.

**Comment by polibou** [comment]
So I was finally able to figure it out by modify the core package.  Here it is in case anyone needs it...

In ShopifyApp/Http/Middleware/AuthShopify.php comment out the redirect to the login page as this is the step we are trying to eliminate.

```
    private function handleBadVerification(Request $request, ShopDomainValue $domain)
    {
        if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
            //return Redirect::route('login');
        }

        // Set the return-to path so we can redirect after successful authentication
        Session::put('return_to', $request->fullUrl());

        // Kill off anything to do with the session
        $this->shopSession->forget();

        // Mis-match of shops
        return Redirect::route(
            'authenticate.oauth',
            ['shop' => $domain->toNative()]
        );
    }
```

Also here in the oath request (/ShopifyApp/Traits/authController.php) is where the domain would be hard coded.  I will probably have it pulled from a config setting somewhere when finalized.
```
    public function oauth(Request $request, AuthorizeShop $authShop): ViewView
    {
        // Setup
        //$shopDomain = new ShopDomain($request->get('shop'));
        $shopDomain = new ShopDomain("my-shopify-site");
        $result = $authShop($shopDomain, null);

        // Redirect
        return $this->oauthFailure($result->url, $shopDomain);
    }
```

Now my question, is would it be possible to do this without changing the package's core files?

**Comment by polibou** [comment]
Closing this issue as my remaining questions are not specific to this package.
