### ISSUE TITLE
Upgrade guide v10 to v11

### ISSUE THREAD

**Issue by jasperpoppe** [osiset/laravel-shopify#464]
Hi @osiset,

I wrote a new page for the wiki: _Upgrade guide v10.x to v11.x_

Please review it here:
https://github.com/osiset/laravel-shopify/wiki/Upgrade-guide-v10.x-to--v11.x

I wrote this upgrade guide while I was upgrading an existing free public app. I had no plans nor charges.

This documentation is probably uncomplete, but every bit is helping I guess.

**Comment by osiset** [comment]
@jasperpoppe This is fantastic!! Yes, every bit helps.

I'll think this on the main wiki page, and pin this issue for a few weeks later today and lock it so its more visible to people.

**Comment by Kyon147** [comment]
This is good work 👍

**Comment by osiset** [comment]
Closing as wiki entry is very well.

**Comment by jasperpoppe** [comment]
Shouldn't you mention that page on the upgrading page?
https://github.com/osiset/laravel-shopify/wiki/Upgrading
