### ISSUE TITLE
cors issue when trying to access route

### ISSUE THREAD

**Issue by arslan308** [osiset/laravel-shopify#465]
Hi, I am using laravel to create app, when i have used script_tag to run js file on load then i need to send request to 1 of my routes, but i am facing cors issues, how can i solve this.??

Issues are:
1-  419 error  => when header not added
2- Request header field x-csrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

My second question is that how i can get x-csrf value in js file, because it runs when window loaded and on live store there is not csrf token.

**Comment by osiset** [comment]
Hi there,
This is more of a Laravel issue, there's many articles on how to pass CSRF via the JS and how to handle the CORS (Cors middleare, nginx, apache, etc).
