### ISSUE TITLE
AfterAuthenticate job not found error

### ISSUE THREAD

**Issue by AbdulRafay** [osiset/laravel-shopify#467]
Hi,

I am trying to wire up an after authenticate job in my shopify application. I have followed all steps as described [here](https://github.com/osiset/laravel-shopify/wiki/After-Authentication-Job)

My .env file has the following entry

`AFTER_AUTHENTICATE_JOB=\App\Jobs\AfterAuthenticateJob::class`

shopify-app.php looks like:

```
    'after_authenticate_job' => [

            [
                'job' => env('AFTER_AUTHENTICATE_JOB'), // example: \App\Jobs\AfterAuthenticateJob::class
                'inline' => env('AFTER_AUTHENTICATE_JOB_INLINE', true) // False = dispatch job for later, true = dispatch immediately
            ]

    ],
```

When i install my application to my dev store i get the following error:

![image](https://user-images.githubusercontent.com/614883/80543488-676eca80-89c8-11ea-9c3d-711330accb74.png)

kindly point out any steps that i might have missed.

**Comment by redransom** [comment]
Hi Abdul,
I had this same problem and got it to work when I changed the path to not include the ::class part of it. i.e. 

AFTER_AUTHENTICATE_JOB=\App\Jobs\AfterAuthenticateJob

I was then able to install. Now I will need to see if I can get it to call this job obviously.

**Comment by AbdulRafay** [comment]
Hello redransom,

Thank you that did solve the problem. You don't have to call it explicitly, osiset package will take care of it :)

Regards
