### ISSUE TITLE
Trying to get property 'name' of non-object (View:./resources/views/index.blade.php)

### ISSUE THREAD

**Issue by technocrat2050** [osiset/laravel-shopify#468]
Just after the installation I am getting this error

![image](https://user-images.githubusercontent.com/25361462/80566890-9a897c00-8a11-11ea-92d6-ca55c0fe40b2.png)

Please help, I am stuck here

Thanks in advance...

**Comment by jasperpoppe** [comment]
Have you logged in via `/login`?
Do you see a record in your database table `users`?
Do you see in your view `Auth::user()->name`? Or is there something else instead?

**Comment by technocrat2050** [comment]
thanks for the quick reply Jasper, You are right the user is not logged-in I am accessing public page with user. many thanks!

**Comment by mlgrozev** [comment]
Is this resolved?
