### ISSUE TITLE
after install i am getting below error

### ISSUE THREAD

**Issue by sunilit42** [osiset/laravel-shopify#470]
BadMethodCallException
Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()

Can you please help me on this?

**Comment by jasperpoppe** [comment]
Which version of the package are you using?
Make sure your "Shop" model is refering to `\App\User` and that this model has soft delete.

Also, a bit dirty, but when you got this error, just go back to the base url and everything is working 🙈 (That was my temporary solution at least)

**Comment by sunilit42** [comment]
Hello,

Using version ^11.4 for osiset/laravel-shopify
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)


i m new into laravel but checking into App\User model

**Comment by sunilit42** [comment]
Hello,

![image](https://user-images.githubusercontent.com/2923438/80730662-77e98700-8b27-11ea-969a-4556d2274f90.png)


now getting above error

**Comment by jasperpoppe** [comment]
Make sure your url is whitelisted for your app.
You can whitelist this in your Partner Account => Apps => Name of your app => App Setup => Urls => Whitelisted redirection URL(s).

Add over there your urls like:
```
https://localhost/
https://localhost/authenticate
```

**Comment by sunilit42** [comment]
do i need to add API details into config file as well?

**Comment by osiset** [comment]
@jasperpoppe Is correct. You need to add those URLs to your app config in partners dashboard.

You do not need to plug these values into .env or config/shopify-app.php, as the default fallbacks use this anyways.

Have you resolved your issue?

**Comment by yrk2yrk** [comment]
I managed to get it working by changing 

$shop = $this->shopQuery->getByDomain($shopDomain, [], true); to
$shop = $this->shopQuery->getByDomain($shopDomain, [], false);

in **AuthorizeShop.php**

**Comment by joeainsworth** [comment]
@sunilit42 how did you solve the original error? I am also getting this after a fresh install of laravel an this package.

**Comment by osiset** [comment]
Changing to false will not make re-installs correctly work.

**Comment by yrk2yrk** [comment]
Yes, I changed back that true. There were some other issues. Now it is working fine. Thanks.

**Comment by dhruv728462** [comment]
BadMethodCallException
Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()

Can you please help me on this?

How did you manage to resolve this? I am also getting this error.

**Comment by gordonchanhk** [comment]
@sunilit42  I encountered this when I didn't perform migration and database setup.
So you need to sort out the migration part first.
Hope this helps.

**Comment by tom-rice** [comment]
I encountered this when I forgot to update User.php as per the [installation guide](https://github.com/osiset/laravel-shopify/wiki/Installation) under **Models** 'You will need to modify your Laravel user model.'

**Comment by vishalknishad** [comment]
Replace your app/User.php by :

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Osiset\ShopifyApp\Contracts\ShopModel as IShopModel;
use Osiset\ShopifyApp\Traits\ShopModel;

class User extends Authenticatable implements IShopModel
{
    use Notifiable;
    use ShopModel;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

**Comment by rajdeeptayde** [comment]
Hello there i am also getting this error can you please help ,

**Illuminate\Database\Eloquent\Builder::throwBadMethodCallException
vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50**

The app was running properly this error encountered after i added the following library 
**caseyamcl/guzzle_retry_middleware**
