### ISSUE TITLE
Safari: isFreemium() on null

### ISSUE THREAD

**Issue by jasperpoppe** [osiset/laravel-shopify#475]
I got this error in Safari when I open a link with the `Billable` middleware attached.

```
Error: Call to a member function isFreemium() on null in /vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/Billable.php:50
```

In Google Chrome it works perfectly.

Do you have an idea if it has something to do with CORS?

**Comment by osiset** [comment]
Most likely its the stupid cookie stuff yeah. My guess is you're not detected as being logged in thus the user is null, thus isFreemium doesnt work. I am not too sure how to fix this at the moment.

**Comment by osiset** [comment]
Confirmed this is stupid cookie issues from browsers. I have no support for this at the moment, its my next initiative .. closing until I can add support.

**Comment by jasperpoppe** [comment]
See issue #522 as follow up

**Comment by nonick891** [comment]
I am having the same bug as mentioned TS but it is happened in every browser even on main page of the app.

Package version is:

`"osiset/basic-shopify-api": "^7.0",
 "osiset/laravel-shopify": "^10.3.1",`
