### ISSUE TITLE
Weird mix of repos?

### ISSUE THREAD

**Issue by amosmos** [osiset/laravel-shopify#476]
It looks like some versions of this repo (laravel-shopify) are actually snapshots of the basic-api repo, unless I'm missing something here. Here's an example: https://github.com/osiset/laravel-shopify/blob/22155b425180655645dff729f6262bfa715904bc/composer.json#L2

Is this a bug or is this on purpose? If it's on purpose how is it effecting upgrading the packge through composer? I want to upgrade but a bit afraid.

Thanks!
Amos

**Comment by Hujjat** [comment]
Hey @amosmos 

This ***Laravel-Shopify*** uses the ***basic-shopify-api*** package for accessing data in Shopify. Both of these packages are developed by the same author. 

You can use only ***basic-shopify-api*** package if you want to take care of auth, billing other features. 

When you access Shopify data using this app, it always uses ***basic-shopify-api*** package. 

There will be no issue if you upgrade it. 

Thanks.

**Comment by amosmos** [comment]
Hey @Hujjat  - thanks for responding.

I know about basic-shopify-api and use it in some projects as well.

The issue here is that somehow that package got mixed in this repository, as I showed in the example.

Thanks

**Comment by osiset** [comment]
@amosmos Where did you find this? May have been a mistake somewhere, but I see https://github.com/osiset/laravel-shopify/blob/master/composer.json#L2 is correct.

**Comment by amosmos** [comment]
Hey @osiset - Any chance you can remove the wrong tags?
It's v6.1.0 to v6.1.3.
It's messing our apps every time we upgrade our dependencies
