### ISSUE TITLE
Shopify Webhook Is not working i can see any webhook registered. 

### ISSUE THREAD

**Issue by somin-parate** [osiset/laravel-shopify#481]
I tried to follow the documentation of create webhook but its notthing happening. i can see ordercreatejobs.php file is created under jobs but handle will be blank function so i need to write code or something.

'webhooks' => [
            [
                'topic' => 'orders/create',
                'address' => 'https://shopify-reports.pineappledevelopment.com/public/webhook/orders-create'
            ],
    ],

Also how can i check that webhook will be registered?

**Comment by kartik7153** [comment]
I am also facing the same issue where I have added the webhook, but when I login in the app then webhook notification is not created.

**Comment by somin-parate** [comment]
@kartik7153 please define this way in shopify-app.php
'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'orders/create'),
	            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'https://shopify-reports.pineappledevelopment.com/public/webhook/orders-create')

**Comment by kartik7153** [comment]
What's the difference?

**Comment by somin-parate** [comment]
According to this package you need to define this way please try its working for me.

**Comment by kartik7153** [comment]
Other than you didn't need to add anything? Any permission scopes?

**Comment by somin-parate** [comment]
all the permission related to order and products are required

**Comment by somin-parate** [comment]
webhook is not working under subdirectory. is there something issue you are facing?

**Comment by jasperpoppe** [comment]
You probably haven't set a cronjob yet:
https://laravel.com/docs/7.x/scheduling

Add this line to your hosting:

```
* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1
```

**Comment by osiset** [comment]
Please provide more information if this is still an issue, checking just now, I had webhooks created.

The job to create the webhooks only fires on a fresh auth flow, when the user hits /authenticate route.

If you mis-configured or forgot to configure webhooks, delete all your cookies for the app's domain, go back to the app, click your app, and it should go through a new auth flow.

**Comment by mohinht** [comment]
Hello,

I'm facing issues to create GDPR mandatory Webhook.

I've registered this webhook for this GDPR mandatory Webhook. 1.shopify-app.php - https://prnt.sc/w9sytr 
2. app/job/ - https://prnt.sc/w9t063 (I've return response 200) - I want to just return 200 responses.
3. Also I've added a GDPR webhook to the app setup. https://prnt.sc/w9t18u

After adding this webhook, I'm getting this error. https://prnt.sc/w9c30f

Please help me

**Comment by mohinpatwary** [comment]
Hello,
I'm facing issues to create GDPR mandatory Webhook.

I've registered this webhook for this GDPR mandatory Webhook. 1.shopify-app.php - https://prnt.sc/w9sytr 
2. app/job/ - https://prnt.sc/w9t063 (I've return response 200) - I want to just return 200 responses.
3. Also I've added a GDPR webhook to the app setup. https://prnt.sc/w9t18u

After adding this webhook, I'm getting this error. https://prnt.sc/w9c30f

Please help me
