### ISSUE TITLE
Unable to get shop domain.

### ISSUE THREAD

**Issue by faisal-saeed-brainx** [osiset/laravel-shopify#485]
Hi, I have deployed the app in Production, and I continuously getting this error in logs. When I try to figure out then It seems to be working fine on my side. I am not able to catch this issue.

Please help me to catch and fix this. Your help will be really appreciated.

* Package Version: v10.3.1
* Laravel Version: v5.7
* PHP Version: v7.2

### Failure Logs

OhMyBrew\ShopifyApp\Exceptions\MissingShopDomainException
Unable to get shop domain.
<img width="848" alt="form" src="https://user-images.githubusercontent.com/36917658/81661331-66707b00-9455-11ea-83f2-1891b582e687.png">
<img width="659" alt="form2" src="https://user-images.githubusercontent.com/36917658/81661348-6b352f00-9455-11ea-9eb1-375bd9024ebd.png">

**Comment by Kyon147** [comment]
What error tool are you using? Check to see where the request came from.

This usually happens from bots trying access pages that don't exist.

**Comment by jasperpoppe** [comment]
Just to inform you that the package version v10 is deprecated.
Please see the wiki to upgrade from v10 to v11: https://github.com/osiset/laravel-shopify/wiki/Upgrading#10xx--1100

**Comment by faisal-saeed-brainx** [comment]
> What error tool are you using? Check to see where the request came from.
> 
> This usually happens from bots trying access pages that don't exist.

Thanks for your response, I am using sentry.io for real time logging

**Comment by faisal-saeed-brainx** [comment]
> v11

The upgradation from v10 to v11 is not so simple. It has a lot of architectural changes. I think It can be risky to migrate because the app has been working on a large number of active stores.

**Comment by faisal-saeed-brainx** [comment]
@Kyon147 Any Suggestionon, How can I investigate it?

Your help will be really appreciated. Thanks

**Comment by osiset** [comment]
@faisal-saeed-brainx Would need to know how they're accessing, this is coming from middleware checks.

Any path clues?

**Comment by Kyon147** [comment]
Hi both,

I get this on my apps and to be honest, I think it happens from due to bots randomly trying to access pages that don't exist. When looking at my error logs, I see it comes from someone trying /wp-admin etc.

By default, everything passes through the `auth.shop` route on pre-v11 so even if the page is a "404" you get the missing domain exception because it's not a Shopify request it throws that exception every time.

I've not seen this error actually be thrown properly i.e when a Shopify store tries to access, so I don't think there is a bug just a result of traffic not actually trying to auth to use the app.

**Comment by faisal-saeed-brainx** [comment]
Hi @Kyon147 

Thanks for the kind information. So, Is there any way to stop logging this issue, when the request comes form bot or 404 page? Is that make sense?

Thanks in advance.

**Comment by Kyon147** [comment]
You could look to see if the request is coming in from /login or authenticate to two main ways of getting into the app properly. If it is coming from elsewhere you could skip that exception and force a normal "404".

**Comment by faisal-saeed-brainx** [comment]
Hi @Kyon147

Thanks for your help. Now I am not getting this issue in my logs after adding MissingShopDomainException class in $dontReport as 
`protected $dontReport = [
        \OhMyBrew\ShopifyApp\Exceptions\MissingShopDomainException::class,
    ];` in Handler.php

Also added for redirection on MissingShopDomainException in Handler.php

`public function render($request, Exception $exception)
    {
        if ($exception instanceof \OhMyBrew\ShopifyApp\Exceptions\MissingShopDomainException) {
            return redirect()->route('login')->with('error', "Session Timed Out");
        }
        
        return parent::render($request, $exception);
    }`
