### ISSUE TITLE
Fatal Error when capped_amount is reached

### ISSUE THREAD

**Issue by StefanNeuser** [osiset/laravel-shopify#487]
Hi @osiset ,

when capped_amount is reached you will not have `usage_charge` property in the response what will end in a fatal-error.

https://github.com/osiset/laravel-shopify/blob/10540ce76d552d731304f0f0d3498f31b7b0b63f/src/ShopifyApp/Services/ApiHelper.php#L304

We solved it at the moment in the way:

```
        $this->response = $this->api->rest(
            'POST',
            "/admin/recurring_application_charges/{$currentCharge->charge_id}/usage_charges.json",
            [
                'usage_charge' => [
                    'price'       => $this->data['price'],
                    'description' => $this->data['description'],
                ],
            ]
        )->body;

        if (empty($this->response->usage_charge)) {
            return false; // capped_amount reached
        }

return $this->response->usage_charge;
```

**Comment by osiset** [comment]
Thanks for this report. I've implemented a fix for next release with a testcase and seems to pass fine in GH Actions.
