### ISSUE TITLE
Deceptive Site Ahead.

### ISSUE THREAD

**Issue by inazeem** [osiset/laravel-shopify#488]
Hi, 

I am having this weird issue on firefox and mobile devices. Chrome is fine but all other browser say this 'Deceptive site ahead.' I have lets encrypt SSL certificate installed. But I am not sure where this issue is coming. Is it happening to any others? It is a problem where I install this repository.
Here is the URL : https://app.e-nas.co.uk/login
<img width="1002" alt="Screenshot 2020-05-16 at 09 27 22" src="https://user-images.githubusercontent.com/3668379/82115002-0ed55680-9758-11ea-94da-171601b5ca5d.png">

**Comment by awebartisan** [comment]
I tested it on my local, obtaining Let's Encrypt SSL certificate using `valet secure`. 
I am facing this issue on Firefox.
Did you find a solution?

**Comment by osiset** [comment]
If you are simply visiting the page and getting this issue, its not to do with the package, this is an SSL issue, server issue, or domain was reported as spam.

**Comment by mlgrozev** [comment]
We are facing the same issue, we are using Cloudflare and AWS.

@osiset, do you have any ideas about why this could be happening?

<img width="1065" alt="Screenshot 2020-07-23 at 18 44 48" src="https://user-images.githubusercontent.com/788176/88307494-b0f35b00-cd14-11ea-8e88-972d07f9c959.png">

<img width="1290" alt="Screenshot 2020-07-23 at 17 42 21" src="https://user-images.githubusercontent.com/788176/88307503-b3ee4b80-cd14-11ea-9da2-4e4ece55eba8.png">

**Comment by osiset** [comment]
This has nothing to do with the package, it has to do with IPs and domains being flagged as spam. You'll need to resolve this outside.

**Comment by mlgrozev** [comment]
Thank you for the faste response, @osiset .

This domain and ip is used only for the Shopify application which is still in development. I doubt it was flagged as spam...

**Comment by osiset** [comment]
I've spun up new digital ocean servers before and had them flagged as spam. IPs float around, get reused, whole ranges are flagged as spam all the time.

**Comment by mlgrozev** [comment]
How did you resolve it with that ip? 

PS we have used that IP for 3-4 months now.

Strange behavior:(

**Comment by ncpope** [comment]
If the ip is an issue you can try creating new servers. Personally I would put the domain on cloudflare, that way your actual ip isn't exposed to Google or anyone else.

**Comment by ncpope** [comment]
By the way, when I access the site on Chrome/windows 10 I am not seeing the warning. Did you click on the "Request Review" button?

**Comment by mlgrozev** [comment]
The domain is on Cloudflare.

I might have some clue of what happened before the domain was flagged.

The store we installed the app on is password protected. I deleted all cookies and refreshed the page. Enter password screen was shown with a script tag on it and our js file. Could it be something related to this?

**Comment by osiset** [comment]
Honestly its hard to know what caused it, I've battled it before but a review ended up solving it.

**Comment by keidarcy** [comment]
Any update about this problem?
I'm in the same situation.

**Comment by osiset** [comment]
@keidarcy This is not a problem with the package. Its the server/IP being reported.

**Comment by keidarcy** [comment]
Is that possible to delete /home route?
I can't find how to do that in wiki
