### ISSUE TITLE
Invalid webhook signature.

### ISSUE THREAD

**Issue by jcbolor** [osiset/laravel-shopify#489]
I follow all the instruction from the wiki documentation and I added a webhook to capture events every after payment.

### Steps to Reproduce

1. Created a new job via php artisan shopify-app:make:webhook [name] [orders/paid].
2. Created a webhook from shop admin settings under Notification
3.  From Store admin Send test notification

I added Log::info in this file AuthWebhook.php. Line 35
Log::info('hmacLocal -> ' . $hmacLocal);
Log::info('hmac -> ' . $hmac);
Log::info('shop -> ' . $shop);

Result (hmac doesn't match): 
[2020-05-20 16:54:46] local.INFO: hmacLocal -> 5+/COHjFGIcoYfy8rE1aUDpBXRSlnFv+35WMr7OqGL8=
[2020-05-20 16:54:46] local.INFO: hmac -> IuB15RhAusbXjgirF8wm7f5Fv8ImRMHQEPsTkprjfHk=
[2020-05-20 16:54:46] local.INFO: shop -> jcbolor.myshopify.com

### Context
* Package Version: v11.5
* Laravel Version: v7.x
* PHP Version: v7.2

**Comment by jasperpoppe** [comment]
I don't know why the webhook signature is invalid, but isn't your webhook registered by the WebhookInstaller job, instead of creating a webhook via Shopify Admin?

If not, you should add this line to your hosting to run the cronjob:
```
* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1
```

See: https://laravel.com/docs/7.x/scheduling

**Comment by jcbolor** [comment]
I found the issue, my custom app has its own API_SECRET_KEY and for the webhook it has a diffrerent API_SECCRET_KEY. I made a temporary solution by adding another WEBHOOK_API_KEY from the shopify config then that is the one that I used on the **AuthWebhook.php** file. 

`$hmacLocal = createHmac(['data' => $data, 'raw' => true, 'encode' => true], $this->getConfig('api_webhook_secret'));`

**Comment by osiset** [comment]
Notifications setting in Shopify Admin is unreleated to app notifications. Will close, glad you found a solution though.

**Comment by Abhi0725** [comment]
In case the above comment isn't clear to anyone coming to this. Here's a thing: You shouldn't use admin notification to handle Webhook events. 

[Webhook events](https://shopify.dev/docs/admin-api/rest/reference/events/webhook?api[version]=2020-04)
[Admin Notifications](https://www.shopify.com/admin/settings/notifications)
