### ISSUE TITLE
Middleware Webhook for bulk action ( Hmac verification)

### ISSUE THREAD

**Issue by dpmika** [osiset/laravel-shopify#490]
Hi,
I'm having trouble creating Webhook for bulk action.

The "auth.webhook" middleware accepts only POST requests.

Instead "auth.proxy" generates a wrong HMAC.

I investigated a bit about why and found that when we have an array of parameters, such as "ids" in the bulk action, this must be in the following format before generating HMAC.

 **ids=["XXXXXXXX", "XXXXXXXXX"]**

For the moment they have managed to generate the right HMAC and then create the following middleware.

`
 
        public function handle(Request $request, Closure $next) {
        $query = $request->all();
        $signature = $query['signature'] ?? $query['hmac'] ?? null;
        $shop = NullableShopDomain::fromNative($query['shop'] ?? null);
        if (isset($query['signature'])) unset($query['signature']);
        if (isset($query['hmac'])) unset($query['hmac']);$data = [];
        foreach ($query as $key => $value) {
          $data[] = "{$key}=" . (is_array($value) ? '["' . implode('", "', $value) . '"]' : $value);
        }

        $data = implode('&', $data);

        $signatureLocal = hash_hmac('sha256', $data, $this->getConfig('api_secret'), false);

        if ($signature !== $signatureLocal || $shop->isNull()) {
            return Response::make('Invalid webhook signature.', 401);
        }

        // Login the shop
        $this->shopSession->make($shop);

        // All good, process proxy request
        return $next($request); }

`

I hope it can be useful to someone.

In any case, the middleware is integrated in the library or fixed.

Thanks

**Comment by rafaelsorto** [comment]
Thank you @dpmika , one year later and this solution still works. Thanks for sharing.
