### ISSUE TITLE
Problem while installing Shopify App

### ISSUE THREAD

**Issue by helix2020** [osiset/laravel-shopify#493]
## Failure Information
Hi, 
First of all, I want to thank you for your Shopify API Client.
However, I am having a problem while trying to install my App to the Shopify Store.

An error occurred during installation as below:

`This app can't be installed using this link. Contact the app developer for more information.
`
May you guys help me about this?

Thank you for your time, I'm looking forward to your response.

### Context

* Package Version: v11.5"
* Laravel Version: vX.Y.Z
* PHP Version: v7.2.5
* Using a toolset: Laradock, ngrok

### Failure Logs

![imageedit_0_6557530085](https://user-images.githubusercontent.com/65866610/82761208-39c74680-9df9-11ea-8e54-fbd6ad5beeac.jpg)

**Comment by awebartisan** [comment]
Hi, are you creating a "Custom" app? If link is expired, you can regenerate a new link in your partner dashboard.

**Comment by helix2020** [comment]
Hi @awebartisan,

I really appreciate your help and that was the reason. I have created an custom app so the link was expired and not allowed me to install.

Many thanks :)
