### ISSUE TITLE
Billing Screen is unauthenticated on install

### ISSUE THREAD

**Issue by RocketTechDev** [osiset/laravel-shopify#496]
## Expected Behavior

Shop installs the app
Shop accepts the app's permissions
Shop is presented with the billing screen to accept or decline

## Current Behavior

Shop installs the app
Shop accepts the app's permissions
Shop is redirected to the app login

## Failure Information

After installing the app, the browser is redirected to the /login screen. However, the shop is listed as a user in the database, and when I re-navigate to the shop admin, the app is listed. From there I can select the app an I am then re-redirected to the billing screen.

### Steps to Reproduce
Step 1
<img width="1643" alt="Timely-1" src="https://user-images.githubusercontent.com/24298903/83062351-66c46500-a056-11ea-9b85-23f1f3f0cc8a.png">

Step 2
<img width="1794" alt="Timely-2" src="https://user-images.githubusercontent.com/24298903/83062367-6a57ec00-a056-11ea-93f0-94ad735c582e.png">

Step 3 - Unauthenticated?
<img width="1716" alt="Timely-3" src="https://user-images.githubusercontent.com/24298903/83062406-78a60800-a056-11ea-9b56-086b061525c5.png">

Step 4- Back on the App listing:
<img width="1477" alt="Timely-4" src="https://user-images.githubusercontent.com/24298903/83062447-8cea0500-a056-11ea-8919-6a10bc28ef6c.png">

Step 5 - Billing is presented
<img width="1719" alt="Timely-5" src="https://user-images.githubusercontent.com/24298903/83062469-9c694e00-a056-11ea-8476-3528c694c30e.png">

Facing the same issue when installing from the shopify partners dashboard.

### Context

Routes:
```
Route::middleware(['auth.shopify', 'billable'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/{any}', function () {
        return view('app');
    })->where('any', '.*');

});
```

Doing a little digging - it looks like the domain is returning null in the auth.shopify middleware

```
 private function handleBadVerification(Request $request, ShopDomainValue $domain)
    {
        if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
            return Redirect::route('login');
        }
```

NGROK logs
```
GET /login                     200 OK                                                               
GET /billing                   302 Found                                                            
GET /                          302 Found                                                            
GET /authenticate              302 Found                                                            
GET /authenticate/oauth        200 OK                                                               
GET /                          302 Found 
```

Config:
```
SHOPIFY_BILLING_ENABLED=true
SHOPIFY_BILLING_FREEMIUM_ENABLED=false
```

* Package Version: ^11.5
* Laravel Version: ^7.0
* PHP Version: v7.2.5
* Vagrant, NGROK

**Comment by kartik7153** [comment]
For me it's not showing the billing page even after billing configurations are correct. 
Following this - https://github.com/osiset/laravel-shopify/wiki/Creating-a-Billable-App

**Comment by darrynten** [comment]
I've started experiencing this behaviour and I think it's contributing to some drop off in numbers

**Comment by ncpope** [comment]
> I believe this may be an issue with Shopify passing things around.
> 
> The login page will be deprecated. New apps with Shopify will not work with this method anymore, you must specify a custom app (installable on only one store with a link), or a public app (which can be installed on dev stores with a link).

Very interesting, this is my first time hearing about this. Is there a link with more info?

**Comment by jawb** [comment]
I have this same issue:
- Laravel 7
- Public app
- billable middleware on home route

When I install from partner portal I don't get accept charge screen I get redirected to login page. If I debug step by step and catch the $api['confirmation_url'] from GetPlanUrl.php then I can go to charge screen and things work normally.

**Comment by osiset** [comment]
I am unable to reproduce, this is quite annoying because I know its the new stupid browser stuff interfering is my guess.

Once the URL is obtained, Laravel is told to load a view file which uses JS to do a fullpage redirect to it.

Can you provide your full flow from partners page to error @jawb? As well as the browser used.

**Comment by jawb** [comment]
The flow is:
- Click install on store
- Get redirected to approval page, click install app (app is Public and unapproved)
- Get redirected to /login

This my home route:
Route::get('/', function () {
    return view('welcome');
})->middleware(['auth.shopify', 'billable'])->name('home');

When I remove 'billable' middleware it works. The issue is somewhere in billing process, as stated above if I go step by step in code, I can get the URL $api['confirmation_url'] from GetPlanUrl.php and paste in browser I get redirected to accept billing page in Shopify and it all works.

**Comment by osiset** [comment]
@jawb 

Hmm, fresh chrome install, no issues here of course (ugh).

Can you paste me your config/session.php, if you don't mind?

![Screencast at July 10th 2020 - 2 59 30 pm](https://user-images.githubusercontent.com/2420282/87182135-1d566f00-c2be-11ea-911e-3cd14b67678a.gif)

**Comment by jawb** [comment]
@osiset I have latest Chrome 83.0.4103.116, I just tested on Firefox and it works correctly, I cleared cache and application data in Chrome, still get redirected to login.
I will try Incognito to make sure it's a bug in Chrome and not some cache weirdness.

sessions.php is the default Laravel 7 config:

```
<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Session Driver
    |--------------------------------------------------------------------------
    |
    | This option controls the default session "driver" that will be used on
    | requests. By default, we will use the lightweight native driver but
    | you may specify any of the other wonderful drivers provided here.
    |
    | Supported: "file", "cookie", "database", "apc",
    |            "memcached", "redis", "dynamodb", "array"
    |
    */

    'driver' => env('SESSION_DRIVER', 'file'),

    /*
    |--------------------------------------------------------------------------
    | Session Lifetime
    |--------------------------------------------------------------------------
    |
    | Here you may specify the number of minutes that you wish the session
    | to be allowed to remain idle before it expires. If you want them
    | to immediately expire on the browser closing, set that option.
    |
    */

    'lifetime' => env('SESSION_LIFETIME', 120),

    'expire_on_close' => false,

    /*
    |--------------------------------------------------------------------------
    | Session Encryption
    |--------------------------------------------------------------------------
    |
    | This option allows you to easily specify that all of your session data
    | should be encrypted before it is stored. All encryption will be run
    | automatically by Laravel and you can use the Session like normal.
    |
    */

    'encrypt' => false,

    /*
    |--------------------------------------------------------------------------
    | Session File Location
    |--------------------------------------------------------------------------
    |
    | When using the native session driver, we need a location where session
    | files may be stored. A default has been set for you but a different
    | location may be specified. This is only needed for file sessions.
    |
    */

    'files' => storage_path('framework/sessions'),

    /*
    |--------------------------------------------------------------------------
    | Session Database Connection
    |--------------------------------------------------------------------------
    |
    | When using the "database" or "redis" session drivers, you may specify a
    | connection that should be used to manage these sessions. This should
    | correspond to a connection in your database configuration options.
    |
    */

    'connection' => env('SESSION_CONNECTION', null),

    /*
    |--------------------------------------------------------------------------
    | Session Database Table
    |--------------------------------------------------------------------------
    |
    | When using the "database" session driver, you may specify the table we
    | should use to manage the sessions. Of course, a sensible default is
    | provided for you; however, you are free to change this as needed.
    |
    */

    'table' => 'sessions',

    /*
    |--------------------------------------------------------------------------
    | Session Cache Store
    |--------------------------------------------------------------------------
    |
    | While using one of the framework's cache driven session backends you may
    | list a cache store that should be used for these sessions. This value
    | must match with one of the application's configured cache "stores".
    |
    | Affects: "apc", "dynamodb", "memcached", "redis"
    |
    */

    'store' => env('SESSION_STORE', null),

    /*
    |--------------------------------------------------------------------------
    | Session Sweeping Lottery
    |--------------------------------------------------------------------------
    |
    | Some session drivers must manually sweep their storage location to get
    | rid of old sessions from storage. Here are the chances that it will
    | happen on a given request. By default, the odds are 2 out of 100.
    |
    */

    'lottery' => [2, 100],

    /*
    |--------------------------------------------------------------------------
    | Session Cookie Name
    |--------------------------------------------------------------------------
    |
    | Here you may change the name of the cookie used to identify a session
    | instance by ID. The name specified here will get used every time a
    | new session cookie is created by the framework for every driver.
    |
    */

    'cookie' => env(
        'SESSION_COOKIE',
        Str::slug(env('APP_NAME', 'laravel'), '_').'_session'
    ),

    /*
    |--------------------------------------------------------------------------
    | Session Cookie Path
    |--------------------------------------------------------------------------
    |
    | The session cookie path determines the path for which the cookie will
    | be regarded as available. Typically, this will be the root path of
    | your application but you are free to change this when necessary.
    |
    */

    'path' => '/',

    /*
    |--------------------------------------------------------------------------
    | Session Cookie Domain
    |--------------------------------------------------------------------------
    |
    | Here you may change the domain of the cookie used to identify a session
    | in your application. This will determine which domains the cookie is
    | available to in your application. A sensible default has been set.
    |
    */

    'domain' => env('SESSION_DOMAIN', null),

    /*
    |--------------------------------------------------------------------------
    | HTTPS Only Cookies
    |--------------------------------------------------------------------------
    |
    | By setting this option to true, session cookies will only be sent back
    | to the server if the browser has a HTTPS connection. This will keep
    | the cookie from being sent to you if it can not be done securely.
    |
    */

    'secure' => env('SESSION_SECURE_COOKIE'),

    /*
    |--------------------------------------------------------------------------
    | HTTP Access Only
    |--------------------------------------------------------------------------
    |
    | Setting this value to true will prevent JavaScript from accessing the
    | value of the cookie and the cookie will only be accessible through
    | the HTTP protocol. You are free to modify this option if needed.
    |
    */

    'http_only' => true,

    /*
    |--------------------------------------------------------------------------
    | Same-Site Cookies
    |--------------------------------------------------------------------------
    |
    | This option determines how your cookies behave when cross-site requests
    | take place, and can be used to mitigate CSRF attacks. By default, we
    | will set this value to "lax" since this is a secure default value.
    |
    | Supported: "lax", "strict", "none", null
    |
    */

    'same_site' => 'lax',

];
```

**Comment by osiset** [comment]
Only difference I see with mine and yours is "same_site"... Mine is set to null. Can you give that a try?

**Comment by jawb** [comment]
I tried but it didn't change anything :/ I noticed Shopify redirects to http and not https, then https I think that's the issue.

<img width="1423" alt="Screen Shot 2020-07-10 at 19 22 12" src="https://user-images.githubusercontent.com/1163113/87186140-e2b2fd80-c2e2-11ea-87fb-f47b08bb237a.png">

**Comment by jawb** [comment]
@osiset that was it, I had to force https in Laravel $url->forceScheme('https'); https://therightsw.com/enforce-https-laravel/ works now, not sure why Laravel needs this when you define APP_URL with HTTPS!

**Comment by osiset** [comment]
@jawb Interesting.. this came up before on another ticket. I may add this to the wiki then.

@RocketTechDev Can you try this, and see if it resolves your issue?

**Comment by jawb** [comment]
@osiset Maybe Laravel uses some logic to pick http in local env, but since we use ngrok with https it tricks it. Still a buggy behavior IMO, APP_URL should determine the protocol.

Many thanks for your help.

**Comment by RocketTechDev** [comment]
@jawb @osiset that's fixed it for me. Awesome detective work!
