### ISSUE TITLE
Redirecting To Login Page While Accessing Some Other Routes

### ISSUE THREAD

**Issue by shailjasingh03** [osiset/laravel-shopify#498]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior
It should Redirect on pages as define in Route File.
```
Route::middleware(['auth.shopify'])->group(function() {
    // Products
    Route::view('/products','products');

    // Customers
    Route::view('/customers','customers');

    // Settings
    Route::view('/settings','settings');
});
```

```
@extends('shopify-app::layouts.default')

@section('content')
<p>Welcome To Dashboard</p>

@endsection

@section('scripts')
@parent

@if(config('shopify-app.appbridge_enabled'))
    <script type="text/javascript">
        var AppBridge = window['app-bridge'];
        var actions = AppBridge.actions;
        var TitleBar = actions.TitleBar;
        var Button = actions.Button;
        var Redirect = actions.Redirect;
        var titleBarOptions = {
            title: 'Welcome',
        };
        var myTitleBar = TitleBar.create(app, titleBarOptions);
    </script>
@endif
@endsection

```
```
@extends('shopify-app::layouts.default')

@section('content')
Products

@endsection

@section('scripts')
@parent

<script type="text/javascript">
    var AppBridge = window['app-bridge'];
    var actions = AppBridge.actions;
    var TitleBar = actions.TitleBar;
    var Button = actions.Button;
    var Redirect = actions.Redirect;
    var titleBarOptions = {
        title: 'Products',
    };
    var myTitleBar = TitleBar.create(app, titleBarOptions);

</script>
@endsection

```
## Current Behavior
After Loading app in Shopify Store, When I click on first time to any route it works fine, but at the very next moment when I click on any other route or even same route, it redirects me to Login i.e. Installation page.

However, App Works Fine outside Shopify store, By making force redirect false in App bridge

## Failure Information
Session Not Working Properly, or Middleware Not working Properly.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install app and make few Route
2. try Switching between those

### Context

* Package Version: v11.5
* Laravel Version: v7.12
* PHP Version: v7.3
* Using a toolset = Valet:

**Comment by pazuaf** [comment]
With Safari

**Comment by osiset** [comment]
@pazuaf Does this issue happen with Firefox?

**Comment by codingexpert01** [comment]
I am having the same issue on FIrefox it is working fine on Chrome

**Comment by osiset** [comment]
Cookie issue, merging into main. #522
