### ISSUE TITLE
Samesite cookie issue

### ISSUE THREAD

**Issue by faisal-saeed-brainx** [osiset/laravel-shopify#499]
It needs to be updated to support the SameSite cookie security changes made to Chrome 80.

## Failure Information

This app can't load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser, or contacting the developer to get support.

### Steps to Reproduce

It does not appear on all browsers, It appears on some versions of chrome.

* Package Version: v10.3.1
* Laravel Version: v5.7
* PHP Version: v7.2
* Environment: Production
* Hosted on digital ocean.

**Comment by markustripp** [comment]
In config/session.php set 

'secure' => env('SESSION_SECURE_COOKIE', true),
'same_site' => 'none',

Some older versions of Laravel have issues with this setting but it is fixed in recent versions. You have to upgrade your app to a more recent version of Laravel.

**Comment by faisal-saeed-brainx** [comment]
Hi @markustripp Thanks for your kind response. Let me try this

**Comment by nonick891** [comment]
Hi @markustripp, does the issue of old Laravel also affects laravel 6.18.20?

**Comment by osiset** [comment]
@faisal-saeed-brainx Did this solve your issue? I'd like to add it to the wiki if so.

**Comment by faisal-saeed-brainx** [comment]
@osiset I am on Laravel version 5.7 and also facing sometimes the same issue after implementing the @markustripp solution. Now I am going to upgrade my Laravel version to 6, And will update you after testing.

**Comment by faisal-saeed-brainx** [comment]
@osiset 

![image](https://user-images.githubusercontent.com/36917658/86911000-fe2bd600-c133-11ea-9963-2b8dced4573f.png)

I have tested on both laravel 5.7 and 6.18, the issue is happening on my side when I open the app in chrome incognito. Not sure for Laravel v7. But I will definitely check this issue on v7 for my staging environment and will let you know.

**Comment by osiset** [comment]
This is the stupid cookie issues from Chrome then... thanks for digging, closing for #522 thanks!

**Comment by spsarola** [comment]
> SESSION_SECURE_COOKIE

I did but still facing issue

**Comment by aakashprajapati1** [comment]
Hello Everyone, I have developing one shopify public app using laravel shopify. Run this app into the local server and using ngrok site running on https. After when I install the application into the development server then giving the error like this: The app couldn’t be loaded Can you please help me on this?
![Shopify](https://user-images.githubusercontent.com/80114426/110134958-fbcd6900-7df3-11eb-8e74-99eefb3401d0.png)

**Comment by rewaza** [comment]
Hey, I have same issue. Using Laravel Framework 8.34.0. Tried other browsers, incognito mode, clearing cookies but no success. Installed three different apps and created two different types of stores with shopify partners. Using ngrok https local server. When I try to access app url with different browsers, it shows correct page and then redirects to the store page showing below-mentioned error. When I try to open app from the store see same error and browser url is: https://humanovirtual.myshopify.com/admin/apps?app_id=5059257&oauth_error=same_site_cookies
Searched forums but no success. Could you please give me any hint? Thanks in advance.
![image](https://user-images.githubusercontent.com/55695740/112536059-70c60a00-8dc6-11eb-8bae-20f5ff379bab.png)

**Comment by spsarola** [comment]
@osiset please give a solution. I know you are a very kind personality

**Comment by osiset** [comment]
I currently don't have time to look into this with the new work I am 
focusing on, sorry.

**Comment by spsarola** [comment]
@osiset I hope you will get time soon I will be waiting for a solution right now I am using my own custom code for my app basically I have knowledge of core PHP just started to moving on laravel. because it have lot of packages which will reduce my efforts that why. Thanks for replying me

**Comment by Hashir1996** [comment]
@spsarola i'm also facing this issue and i have searched alot on internet and i think this is issue on google chrome end.

**Comment by mudassirali007** [comment]
same issue

**Comment by Hashir1996** [comment]
> same issue
i have solved this issue, let me know are you using shopify app bridge ?

**Comment by dipesh-rajak** [comment]
Hi @Hashir1996 , I have same issue and i am using shopify bridge. Please let me know the solution

**Comment by Hashir1996** [comment]
Hello, rajak yea sure i can help you
You only have to change one thing in your app bridge script and this is
app.remote, replace it with app.self

**Comment by dipesh-rajak** [comment]
I am using CDN for  app bridge script .

**Comment by Hashir1996** [comment]
I'm using script
