### ISSUE TITLE
Not sure if this is expected behavior, but ResponseAccess does not allow accessing array of objects with object notation

### ISSUE THREAD

**Issue by nmrdxt** [osiset/laravel-shopify#502]
When requesting a collection of objects (such as products, collections, pages, etc) - the returned response does indeed allow accessing the parent array with object notation, but not the children.

For example, for this request:

$products = $shop->api()->rest('GET', '/admin/products.json', []);

I can access the parent products with object notation: $products['body']->products,

But when looping through products, each must be treated as an array. For example:

$products['body']->products[0]->id would return an error.

If this is expected behavior, then upgrading from 11 to 12 might require a significant amount of refactoring for some. This should be mentioned in the 'Upgrading' section of the docs - this line in the documentation is misleading:

"Upgrading is simple, anything where you have $response->body->...., change to $response['body']->... or even to $response['body'][...]."

I hope this is not expected behavior and I'm missing something hehe

Thanks!

**Comment by osiset** [comment]
Oversight on my part, forgot to implement an iterator.

I just implemented a fix for this for basic-shopify-api v9.1.1, running composer update should grab both that version and patch for this library, thanks!.

**Comment by nmrdxt** [comment]
Fantastic!

Much appreciated!
