### ISSUE TITLE
Class auth.shopify does not exist

### ISSUE THREAD

**Issue by nasirkhttak** [osiset/laravel-shopify#503]
As I followed all the way to install this package into my laravel site.

After when I refresh my **home** https URL to redirect into Shopify Login page, but unluckily I am getting this issue: **Class auth.shopify does not exist**.

I am using the latest ver: "osiset/laravel-shopify": "^10.3"

Can you please help me with this?

**Comment by Kyon147** [comment]
@nasirkhttak `auth.shopify` is the v11+ package middleware.

If you are using v10 is is `auth.shop`

**Comment by nasirkhttak** [comment]
> 
> 
> @nasirkhttak `auth.shopify` is the v11+ package middleware.
> 
> If you are using v10 is is `auth.shop`

Oh, thanks, this was the issue, but now after updating to auth.shop, now it giving me this error:
**"Unable to get shop domain"**

Any idea about this?

**Comment by jasperpoppe** [comment]
Also after signing in with `/login` too?

**Comment by osiset** [comment]
I mentioned in another ticket but /login will be removed in future versions, its not supported anymore by Shopify.
