### ISSUE TITLE
How to access associated_user_scope in job

### ISSUE THREAD

**Issue by yrk2yrk** [osiset/laravel-shopify#506]
I am trying to access associated_user_scope using job queue after the app is installed. I kept the API access type as 'PERUSER' (Online access mode). However, I am not able to access the additional scopes sent by Shopify API during authentication as per this link: https://shopify.dev/tutorials/authenticate-with-oauth#step-1-get-the-clients-credentials

What parameters do I need to add in after authentication job to access these additional parameters? I am using v12.

**Comment by osiset** [comment]
Trying to understand here.

- You use PERUSER auth mode
- You have an AfterAuthenticate job and want to access the user object?

**Comment by yrk2yrk** [comment]
Yes, thats exactly what I want to do.

**Comment by osiset** [comment]
The user data is stored in session, not the database.
Does your job run inline (sync), or background?

**Comment by yrk2yrk** [comment]
Yes, I am trying access the data from session to store in database. My job runs inline.

**Comment by osiset** [comment]
Ah, ok.

I'd have to look into this... maybe something this would work inside the job:

Inside the job, at top, add `use Osiset\ShopifyApp\Services\ShopSession`;

Inside the `handle(` function argument list, add `, ShopSession $session`.

Inside the handle function, add:
```php
$user = $shopSession->getUser();
```

See if you're able to grab it then, you can also directly access it via `Session::get('shopify_user');` as a test.

**Comment by yrk2yrk** [comment]
Ok, thank you. I will try this and update here.

**Comment by yrk2yrk** [comment]
There are two issues. First, I am getting response with this method but it is missing some parameters. Here is what I get:

array (
  'id' => 56128405664,
  'first_name' => 'name',
  'last_name' => 'lastname',
  'email' => 'email@gmail.com',
  'account_owner' => false,
  'locale' => 'en-US',
  'collaborator' => false,
  'email_verified' => true,
)

As per Shopify documentation, it should return data in below format:


{
  "access_token": "f85632530bf277ec9ac6f649fc327f17",
  "scope": "write_orders,read_customers",
  "expires_in": 86399,
  "associated_user_scope": "write_orders",
  "associated_user": {
    "id": 902541635,
    "first_name": "John",
    "last_name": "Smith",
    "email": "john@example.com",
    "email_verified": true,
    "account_owner": true,
    "locale": "en",
    "collaborator": false
  }
}


Second issue: 
When I change the method to PERUSER it doesn't store shop's permanent access token in database. But when I change it to Offline it does. PERUSER method is breaking my app functionality because of this. What could be the reason?

**Comment by osiset** [comment]
The structure you get with getUser is extactly from Shopify, if you compare the fields in associated_user for your example, they;'re the same. Scope is something I am missing to include though.

Per user doesn't store in database because the database is for the permanent token, per-user is session based.

**Comment by yrk2yrk** [comment]
Thanks for the clarification.

**Comment by arvesolland** [comment]
Could I ask for clarification here please?
If I switch from OFFLINE to PERUSER, is there not a way to get and save a permanent access token for the store in addition to getting the individual users access token for the session? The offline token would be needed to perform the background jobs etc
