### ISSUE TITLE
Block third-party cookies issue

### ISSUE THREAD

**Issue by RuchitaCrawl** [osiset/laravel-shopify#511]
Hi, Thanks for this awesome package.

## Expected Behavior

Shopify app work properly even when third party coockies are block .https://prnt.sc/t7f9jw

## Current Behavior

App not working properly, app is going for login page continously. 

### Failure Logs

It appear in chrome latest 83.0.4103.116 version only

* Package Version: 11.4
* Laravel Version: 7.0
* PHP Version: v7.3.13
* OS: Linux Mint 19.2

 'secure' => env('SESSION_SECURE_COOKIE', true),
 'same_site' => 'none',

 I also set above configurations, still it not working.

**Comment by osiset** [comment]
This package does not have support to ask for the test cookie. Its been on my radar but something I havent had time to dig into as it requires a lot of flow rework and honestly browsers are becoming a pain to constantly support for.

I am attempting to begin some code next week to look into this but unfourtunately this work will take a nice while.. closing for now until I can add support for this.
