### ISSUE TITLE
Issue with shop/redact webhook

### ISSUE THREAD

**Issue by Jamesking56** [osiset/laravel-shopify#513]
## Expected Behavior

`shop/redact` webhook attaches successfully

## Current Behavior

Error occurs (as captured by Sentry):

```
GuzzleHttp\Exception\ClientException: Client error: `POST https://homeboat.myshopify.com/admin/webhooks.json` resulted in a `422 Unprocessable Entity` response: {"errors":{"topic":["Invalid topic specified: shop\/redact. Topics allowed: app\/uninstalled, collections\/create, colle (truncated...)
```

## Failure Information

Bit of an odd one, I've only seen this captured via Sentry by a Shopify staff member who was reviewing my app. I'm wondering if their test store doesn't support that webhook?

### Steps to Reproduce

No idea :shrug: 

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v12.0.0
* Laravel Version: v6.17.1
* PHP Version: v7.4
* Using a toolset (Docker, Laradock, Vagrant, etc.): Live on a cPanel shared host

### Failure Logs

Not sure what you need here

**Comment by osiset** [comment]
You do not use webhook config feature for the gdpr endpoints. Shopify doesn't connect with them that way. You simply setup the webhook job to match the endpoint.

IE: App/Jobs/ShopRedactJob.php

And in your partner dashboard the link to your GDPR for Shop Redact would be https://you.com/webhook/shop-redact
