### ISSUE TITLE
My user model doesn't have 'Name' field...

### ISSUE THREAD

**Issue by johnvoncolln** [osiset/laravel-shopify#514]
Pardon my lack of knowledge - this will be my first time creating an app for Shopify.

When doing a first install of the app to a dev store from the partner portal of Shopify, my laravel app throws me an SQL error asking for the name field, but I have this separated into two fields: first_name and last_name - any ideas what to do in this case?

Secondly, is this normal behavior where you create a user account from Shopify side?  What if a user already has an account on my laravel app and just wants to connect their shopify account?  Is there a way to have this as the default behavior?

**Comment by johnvoncolln** [comment]
After playing around with Shopify for a few hours, I'm wondering if there is a way to override the user creation part of the auth process?  I want my users to do the auth part from my laravel app, while logged in.  If not, no biggie as I've already pieced something together using Socialite.

**Comment by osiset** [comment]
If you have modded your user model to be two fields then you need to modify the package to support this. Creation via Socialite is something people have asked for but it honestly makes no sense to me for normal Shopify app development, unless I'm missing something.

Thanks!
