### ISSUE TITLE
cannot get Shopify domain name and access token in the controller

### ISSUE THREAD

**Issue by sandymandy01** [osiset/laravel-shopify#515]
**Issue 1:** 
I have used ngrok to code from local.
After the auth page I expect billing page but the page is redirected to /login page. Than I closed the chrome tab and again tried to open the app and then only it was redirected to billing.

**Issue 2:**
For "osiset/laravel-shopify": "^12.0".
Can anyone help me to get shopify domain and access token in the controller to use rest api  i.e $api->rest('GET', '/admin/shop.json');

I'm new to osiset. Please help to solve these two issue. 
Thank you.

**Comment by osiset** [comment]
Please use template.
