### ISSUE TITLE
Call to a member function getId() on null AppUninstalledJob.php

### ISSUE THREAD

**Issue by raghavrangani** [osiset/laravel-shopify#518]
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null in /home/zealous/staging.apps.zealousweb.com/shopify/multipleformbuilder/vendor/osiset/laravel-shopify/src/ShopifyApp/Messaging/Jobs/AppUninstalledJob.php:70

**Comment by Kyon147** [comment]
Without more detail, this is hard to debug.

From the looks of it, you are calling "getId" on an object which does not have that function. Please can you show us your code in more detail to see what you are doing and if it is a bug with the package or note.

**Comment by raghavrangani** [comment]
@Kyon147 

This error occured when AppUninstalledJob called.

**Comment by osiset** [comment]
```php
        // Get the shop
        $shop = $shopQuery->getByDomain($this->domain);
        $shopId = $shop->getId();
```

Is the relevant code.

The header from webhook should be sending: `X-Shopify-Shop-Domain` (`$request->header('x-shopify-shop-domain')`).

Is this the only time it happened? Maybe Shopify had a bug which didn't send the header?

**Comment by Kyon147** [comment]
@osiset Just a little update, I have seen this happen when the Shop has already been cleaned, i.e does not have a `password`, `plan_id` and `deleted_at`.

I've not looked into it any further but just came across it while updating one of my apps from v10.3 ( I KNOW OLD) to v17 and needed to change the old AppUninstalledJob. Also updated the migration guide as well to make it clearer is some steps.

If the error happens again I'll try and narrow it down a little more.
