### ISSUE TITLE
Unable to Get Store Front Rest Api list.

### ISSUE THREAD

**Issue by sammy-parate** [osiset/laravel-shopify#521]
I am trying to get store front access token list by using admin api provided by shopify. But its not allowing me to retrieve those.

I am using this article https://shopify.dev/docs/admin-api/rest/reference/access/storefrontaccesstoken?api[version]=2020-07#index-2020-07

Api to get
 /admin/api/2020-07/storefront_access_tokens.json

I am trying by this way https://prnt.sc/td6tpt

## Expected Behavior

i want response to be like this https://prnt.sc/td6uqt

**Comment by osiset** [comment]
Please use template and reopen. As well, include the current response from your code.
