### ISSUE TITLE
Logs Issue

### ISSUE THREAD

**Issue by helix2020** [osiset/laravel-shopify#523]
## Failure Information

Hi guys,

I'm having problems with logs while Shopify API returns any error or issue. 
In BasicShopify API, if there is an error is the log function to save, but I checked that nothing is saved in my log file.

May you help me, if I missed to configure it somewhere?

### Context

Package Version: v11.5"
Laravel Version: v7.0
PHP Version: v7.2.5
Using a toolset: Laradock, ngrok

**Comment by osiset** [comment]
Hi @helix2020 

Can you provide steps for what causes the error?

If you "see" no errors, its probably in logs/laravel.log

**Comment by helix2020** [comment]
Hi @osiset,

that didn't cause the error but I wanted to log my error in my custom log. In BasicShopifyAPI it checked if is set logger, to save them in logger instance. 
So, this solution solved my problem:

`$api->setLogger(... your logger instance ...);`

Thank you :)
