### ISSUE TITLE
Scripttag job is not dispatching

### ISSUE THREAD

**Issue by sultan220595** [osiset/laravel-shopify#525]
## Expected Behavior
Scripttag api and webhooks are not executing.

## Current Behavior
I think scripttags and webhook script is not executing even after I did the correct configuration in config/shopify-app.php.

Is there any other steps involved.

**Comment by osiset** [comment]
Please fill out the issue template.

**Comment by Kyon147** [comment]
Are you using a tunnellike ngrok? There are lots of issues around using tunnels when trying to fire webhooks and tags. They can sometimes work and sometimes not.

We also need more information to be able to give you any more assistance.

**Comment by osiset** [comment]
Closing for lack of info and no template.
