### ISSUE TITLE
Auth middleware for API

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#526]
How can I change authentification behavior? 
I am developing API where I use osiset package.
I need api to return unauthorized instead HTML form.
Is there a way to do it with this package? Or any recommendations?

As I can see we have: /vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php
where we have private: handleBadVerification() method, where we have redirect to login page: `return Redirect::route('login');`

In case there is no better ways, I have a backup plan to extend AuthShopify and override handleBadVerification method, but it's private and I can't do that

**Comment by osiset** [comment]
You're asking if theres an ability to instead of redirection to /login, to go somewhere else?

**Comment by sergeyantonuk** [comment]
I need it for the API, so it has to return 401 Unauthorized status instead redirect to login page

**Comment by osiset** [comment]
I am in the works of working on a method for this right now as login method is deprecated on Shopify.

I will include this with next update, which will throw an exception which you can catch in Laravel.

**Comment by darrynten** [comment]
@sergeyantonuk can you see if the new JWT support resolves your problem?
