### ISSUE TITLE
(Not an issue) Not clear as to how the charges are updated

### ISSUE THREAD

**Issue by nmrdxt** [osiset/laravel-shopify#527]
Hello!

Not 100% clear on how and when recurring charges are updated. I'm noticing that the billing_on column does not update for all users, and I wonder whether the charges are only updated when users go through the authentication process (when they need to log in).

Since Shopify does not provide webhooks for charge updates, I wonder whether a scheduled job is required to make sure the user charges are indeed updated - and if so, have you considered implementing one in the package? I understand there are million other requests in line, so totally fine if it's not on the to-do list :)

Thank you for a fantastic solution!

**Comment by osiset** [comment]
@nmrdxt Correct. This package simply logs the charge, but doesn't actively update it since there's no easy method to do that.

Its best to create a scheduled job to run every day, or every week, and grab the active charges in the database, and use the API to check their status.

Off the top of my head, something like this to get each shop's charge and check it's status..

```php
use Osiset\ShopifyApp\Services\ChargeHelper;
use Osiset\ShopifyApp\Objects\Values\ChargeReference;
use App\User;

// ...

$chs = resolve(ChargeHelper::class);
$shops = User::all();
foreach ($shops as $shop) {
  $plan = $shop->getPlan();
  if ($plan === null) {
     // No plan, skip
     continue;
  }

  // Get the charge entry from database, set it to the charge helper
  $charge = $chs->chargeForPlan($plan->getId(), $shop);
  $chs->useCharge($charge->getReference());

  // Get the charge data from API
  $chargeData = $chs->retrieve($shop);

  // Now you can do $chargeData['status'] or something similar to check it's status
}
```

Let me know if something like that works.

**Comment by nmrdxt** [comment]
Hey,

Thank you for your response and for including an example - very helpful.

I'll go the scheduled job route and use your example as a starting point.

Thanks.

**Comment by osiset** [comment]
[Wiki entry added](https://github.com/osiset/laravel-shopify/wiki/Checking-Charge-Status)
