### ISSUE TITLE
Script tag is not work using 10.3.1 version

### ISSUE THREAD

**Issue by JDSHINDE** [osiset/laravel-shopify#528]
Hi @osiset  currently i am using 10.3.1 package and it's working fine before with this version, but suddenly my script tag not work for new installation.   

'scripttags' => [
            
            [
                'src' => env('SHOPIFY_SCRIPTTAG_1_SRC','https://example.com/js/shortcode.js')
                'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
                'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
            ],
    ],

* Package Version: 10.3.1
* PHP Version: 7.2.0

**Comment by JDSHINDE** [comment]
@osiset is this issue related to using old version?

**Comment by osiset** [comment]
I do not know. You will need to confirm the job is firing.

**Comment by JDSHINDE** [comment]
@osiset yes there is problem with my queue drive that's why job is not working, now the script tag is working
