### ISSUE TITLE
change guzzle's timeout option

### ISSUE THREAD

**Issue by Jack-Bazarian** [osiset/laravel-shopify#530]
How can i change the timeout option on guzzle? by default it is set to 10 seconds. It is possible to change it with options on the Basic api package but no access from laravel-shopify. 

Please advise.

**Comment by osiset** [comment]
See [this](https://github.com/osiset/Basic-Shopify-API#passing-additional-request-options). Any issues, please open in that repo, thanks!

**Comment by Jack-Bazarian** [comment]
Thank You!
