### ISSUE TITLE
Stuck in loop to /login route

### ISSUE THREAD

**Issue by bodanu** [osiset/laravel-shopify#531]
![image](https://user-images.githubusercontent.com/13087899/87466755-8243f900-c61f-11ea-9f4d-d014f6c5d95c.png)

##  Expected Behavior

After user/dev installs the app it should redirect to the "home" route if everything checks out. 

## Current Behavior

App works locally using ngrok as a tunnel, but when uploading to heroku, after instalation, the data is stored in the database, but instead of going to the "home" route, it gets stuck in a loop to the /login route. If I enter the shop name, it returns a 419 code.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Followed each step from the wiki to set everything up
2. Create new Heroku app
3. Create procfile for heroku ( web: vendor/bin/heroku-php-apache2 public/ ) 
4. Place heroku url and heroku_url/authenticate in the app setup ( app url and whitelist redirect url )
5. Install the app

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v12.0
* Laravel Version: v7.20
* PHP Version: v7.4

**Comment by osiset** [comment]
This is most likely related to the browser cookie issue. Which browser are you using, and does it happen on others?

**Comment by bodanu** [comment]
It is clearly related to cookies. Managed to make it work this morning. Going to retrace every step and post it here later. Maybe it will help.

**Comment by osiset** [comment]
Figured. If you feel its truly cookie related, theres a master issue we’re merging these types of tickets into.

Its quite hard to solve this issue, which we’re woking on.

**Comment by helix2020** [comment]
Hi, 

I'm having the same issue, even when I clear cookies, it redirects to log in again. Meanwhile, if I write any other route then it seems to work!!

Have you found a solution?

**Comment by bodanu** [comment]
@helix2020 I believe other routes are working, maybe, because they do not use the auth or billable middleware, thus work without cookies, I presume.

So, to retrace the steps:
Most of the info I found is present in #367 

- Installed [jenssegers/agent](https://github.com/jenssegers/agent)

- Created [this middleware](https://gist.github.com/jedimdan/e6c78a2665f788eda9a3e3f3b4e1f982) and added it to global middlewares

- Changes in config/session.php: ( not sure if necessary, but worked right after I did them )
'path' => '/', to 'path' => '/;SameSite=None; secure', ( not sure if it has any effect with this version of Laravel )
'secure' => env('SESSION_SECURE_COOKIE'), to 'secure' => env('SESSION_SECURE_COOKIE', true),
'same_site' => 'lax', to 'same_site' => 'none',

- Tested on Chrome & Safari and it seems to work. At least for now

App is hosted on heroku

**Comment by helix2020** [comment]
Hi @bodanu,

I follow the steps but it doesn't work!!!
Now stuck in the authenticate with the message: **419 Page Expired**
As well, It removes the secure URL to insecure. FYI, I'm working in my local server so I'm using **ngrok**.

**Comment by helix2020** [comment]
Hi @osiset,

is this adjustment now in the current version of the package, or should I need to update the package?
Because I'm still having problems with the login and I'm not having access in other routes as well.

Thank you :)

**Comment by osiset** [comment]
@helix2020 Theres no update right now.

**Comment by osiset** [comment]
#522
