### ISSUE TITLE
Info request about migration from OhMyBrew package

### ISSUE THREAD

**Issue by francescomalatesta** [osiset/laravel-shopify#533]
Hi there! First of all, thanks for your job on this package :)

I stumbled upon this package thanks to the deprecation warning from Composer. I am trying to understand the amount of job I have to do to upgrade my app to this package but I didn't find anything related to an upgrade checklist.

Am I missing something? Would like to know more about it :) 

Thanks!

**Comment by osiset** [comment]
@francescomalatesta Not sure I follow... what deprecation warning?

**Comment by francescomalatesta** [comment]
This one: https://packagist.org/packages/ohmybrew/laravel-shopify

**Comment by ncpope** [comment]
@francescomalatesta - @osiset changed his name from `ohmybrew` to `osiset`. It is the same package that was just renamed. I think it happen around the 10.x release.

**Comment by francescomalatesta** [comment]
LOL my bad! Thanks @ncpope
