### ISSUE TITLE
I am unable to install my shopify app on other live stores ,

### ISSUE THREAD

**Issue by Abhay-Pansuriya** [osiset/laravel-shopify#534]
**### I am getting this issue when i try to install this in live store .**
![image](https://user-images.githubusercontent.com/60358550/87986564-e91f5180-cafa-11ea-926d-57fc1fb33ca3.png)

**### 

> And also got this error in my development stores.

**

![Screenshot_1](https://user-images.githubusercontent.com/60358550/87986699-1835c300-cafb-11ea-8392-e8c3215b0942.png)

Please help me its urgent..

**Comment by Abhay-Pansuriya** [comment]
I am getting this issue 

![image](https://user-images.githubusercontent.com/60358550/87986388-b1180e80-cafa-11ea-9092-1742e369f2d9.png)

**Comment by osiset** [comment]
Please use template.
