### ISSUE TITLE
Authentication error 

### ISSUE THREAD

**Issue by deepakroy11** [osiset/laravel-shopify#535]
Getting below error during app installation.

GuzzleHttp\Exception\ClientException
Client error: `POST https://deroy-theme-app.myshopify.com/admin/oauth/access_token` resulted in a `400 Bad Request` response:
https://simple-wishlist.test/authenticate?code=d422372968fe1ff0369ceca20cbb5194&hmac=0369aefe2eb0a0e3b8ff00276dfd91f7cfc8875656cf5f75973d44deea4933ee&shop=deroy-theme-app.myshopify.com&timestamp=1595496677

**Comment by osiset** [comment]
Please fill in template.
