### ISSUE TITLE
Change shopify app url to separated frontend

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#537]
How can I change url which I can see in the iframe on the home page of my app?
Since I use package to develop my own API, frontend part is separated, so I need to point Shopify App to it after installation.

**Comment by osiset** [comment]
You need to control this yourself. The app url and whitelist urls need to remain. So off the top of my head, I am not sure, you can probably do a redirect once they land on the home path.

**Comment by sergeyantonuk** [comment]
Ok, thank you!
