### ISSUE TITLE
Billing screen not show on shopify store

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#540]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The billing page should appear in Shopify app when I enable billing in the config(shopify-app.php)
I enable billing according to documentation: https://github.com/ohmybrew/laravel-shopify/wiki/Creating-a-Billable-App
## Current Behavior

The billing page is not showing in Shopify app it is directly installed my app on the store without any payment.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set these parameters in your config(shopify-app.php):
SHOPIFY_BILLING_ENABLED=1 
SHOPIFY_BILLING_FREEMIUM_ENABLED=0
SHOPIFY_BILLING_REDIRECT=/billing/process  (default)

2. Create Plan in your `plans` table
INSERT INTO plans (`type`,`name`,`price`,`capped_amount`,`terms`,`trial_days`,`test`,`on_install`,`created_at`,`updated_at`) VALUES
('RECURRING','Test Plan',5.00,10.00,'Test terms',7,FALSE,1,NULL,NULL);
3. Reinstall your app

### Context
* Package Version: v12.1.0
* Laravel Version: v7.21.0
* PHP Version: v7.2.24

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by osiset** [comment]
Have you added 'billable' middleware to your route?

**Comment by sergeyantonuk** [comment]
yes, 
`Route::get('/', 'HomeController@index')->middleware(['auth.shopify', 'billable'])->name('home');`

**Comment by osiset** [comment]
I am unable to reproduce hmm, the shop is not set as grandfathered or freemium accidently in database?

**Comment by sergeyantonuk** [comment]
Fixed.
@osiset the problem was in redirects to http but not https,  so I had to force https in Laravel $url->forceScheme('https')
like here https://github.com/osiset/laravel-shopify/issues/496
Thank you.

**Comment by mbejda** [comment]
I had a similar issue and http to https was not the problem. 
I was not able to get the billable middleware to fire. I resolved the issue by adding the following to the homepage.

```php
 $shop = $this->shopSession->getShop();
            dd($shop->isFreemium(), $shop->isGrandfathered(), $shop->plan);
            if (! $shop->isFreemium() && ! $shop->isGrandfathered() && ! $shop->plan) {
                // They're not grandfathered in, and there is no charge or charge was declined... redirect to billing
                return Redirect::route(getShopifyConfig('route_names.billing'), $request->input());
            }
```
and it worked.
