### ISSUE TITLE
app/uninstalled webhook is not dispatched when the app uninstalled

### ISSUE THREAD

**Issue by hameed-kurla** [osiset/laravel-shopify#548]
I have enabled the webhooks  in config as below and its not working as expected AppUninstalledJob  is not dispatched.

'webhooks' => [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
            'address' => env('APP_URL') . '/webhook/app-uninstalled')
        ],
    ],

## Expected Behavior

When the app is uninstalled expected to dispatch AppUninstalledJob and the should softdelete the shop in the User table

## Current Behavior

When the app is installed WebhookInstaller job is dispatched with the payload as below and registered the app/uninstalled webhook successfully, however upon uninstalling the app from the store the AppUninstalledJob  is not dispatched.

Payload:
{"uuid":"f6142955-a188-4b78-9026-bf8c2c125f84","displayName":"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"maxExceptions":null,"delay":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller","command":"O:49:\"Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller\":11:{s:9:\"\u0000*\u0000shopId\";O:39:\"Osiset\\ShopifyApp\\Objects\\Values\\ShopId\":1:{s:6:\"\u0000*\u0000int\";i:1;}s:23:\"\u0000*\u0000createWebhooksAction\";O:40:\"Osiset\\ShopifyApp\\Actions\\CreateWebhooks\":1:{s:12:\"\u0000*\u0000shopQuery\";O:38:\"Osiset\\ShopifyApp\\Storage\\Queries\\Shop\":2:{s:8:\"\u0000*\u0000model\";s:15:\"App\\Models\\User\";s:6:\"config\";a:27:{s:5:\"debug\";b:0;s:17:\"manual_migrations\";b:0;s:9:\"namespace\";N;s:13:\"job_namespace\";s:10:\"\\App\\Jobs\\\";s:6:\"prefix\";s:0:\"\";s:17:\"appbridge_enabled\";b:1;s:17:\"appbridge_version\";s:1:\"1\";s:8:\"app_name\";s:18:\"Cogent Shopify App\";s:11:\"api_version\";s:7:\"2020-01\....................

## Failure Information

AppUninstalledJob is not dispatched on uninstalling the app.

### Steps to Reproduce

1. Install app to Shopify store
2. Uninstall app from Shopify store

User table deleted_at not set

### Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v12.0
* Laravel Version: v7.0
* PHP Version: v7.3.8
* Using a toolset: Laravel Homestead on windows

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by bravemaster619** [comment]
@hameed-kurla Did you wait for several minutes? Here is my log:

```log
webserver    | 172.22.0.1 - - [19/Aug/2020:08:07:36 +0000] "GET /scripttags/dummy.js?shop=sanas-test-store.myshopify.com HTTP/1.1" 304 0 "https://sanas-test-store.myshopify.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
app          | 172.22.0.4 -  19/Aug/2020:08:13:15 +0000 "POST /index.php" 201
webserver    | 172.22.0.1 - - [19/Aug/2020:08:13:19 +0000] "POST /webhook/app-uninstalled HTTP/1.1" 201 5 "-" "Shopify-Captain-Hook"
```

`2020:08:07:36` is the last request time, i.e. almost the time I have uninstalled the app.

Uninstall hook is called approx. 6 minutes later. This is not related to this repository, that's the way shopify works.

**Comment by Kyon147** [comment]
Also, are you testing the webhooks via ngrok or some sort of proxy? They can be very temperamental when trying to use them in this setup.

**Comment by osiset** [comment]
Closing.
