### ISSUE TITLE
https://unpkg.com/@shopify/app-bridge not loading

### ISSUE THREAD

**Issue by andreuka** [osiset/laravel-shopify#550]
## Current Behavior

https://unpkg.com/@shopify/app-bridge not loading, JavaScript is broken.

**Comment by Kyon147** [comment]
It's a problem with unpgk itself as all the npm packages I use across various things are broken. 

Closing for now.

**Comment by andreuka** [comment]
@Kyon147 Agree, but is not good idea to have ability to host scripts locally?

**Comment by Kyon147** [comment]
It could make sense to host it as part of the overall package but @osiset might have made it take the CDN version for a reason such as keeping the package agnostic as possible. You could add it to your own apps by default without too much issue to host it. 

So will assign this to him to see if it is worth moving forward with it for a future release or not.

**Comment by osiset** [comment]
The CDN is default yes. It would be unwise for me to package it with this repo, it won't integrate with mix correctly.

You can override the main layout with your own and use your own method, I've done this recently as well.

**Comment by Kyon147** [comment]
Closing this for now as unpkg is back up.
