### ISSUE TITLE
Reinstallation error

### ISSUE THREAD

**Issue by jabarrioss** [osiset/laravel-shopify#562]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

the application should be able to install without problems

## Current Behavior

When I store owner tries to reinstall the app, he is redirected to this error screen.

![Screenshot](https://jabarrioss.com/assets/img/error_app.png)

## Failure Information

I made this app for a customer, and he forgot to change the test flag in the plans table (that is the reason why we are re-installing the app in some stores), I just wanted to mention this detail in case it has any relevance.

Edit: The reinstalation process works properly in my local development with ngrok, and with heroku

### Steps to Reproduce

1. Uninstall the app
2. Reinstall the app

### Context

* Package Version: v11.1
* Laravel Version: v7.0
* PHP Version: v7.2.5

**Comment by darrynten** [comment]
I have run into this in the past!

I also didn't have any problems locally.

I think it not appearing locally might have something to do with being logged into the backend on _any_ of your stores while working on the app, even though the app is not installed on the store.

Try logging out of everything completely, login to _just_ the store it is uninstalled on and try again.

Keen for feedback.

**Comment by jabarrioss** [comment]
After try and error over and over again I wrote the api keys in the shopify-app.php file and that didn't work but in my local setup I wrote the api keys in the .env file, so I wrote the api keys in the .env file in my server and the error was gone, the app was already in production so we were not expecting the issue to happen, so we tried everything until it worked, thanks to reply by the way
