### ISSUE TITLE
Laravel App Proxy downloading file instead of rendering liquid in Shopify

### ISSUE THREAD

**Issue by punitchawla19** [osiset/laravel-shopify#564]
I m trying with this code example. but Proxy file download instead of rendering liquid in Shopify. Working fine with ngrok, When I m trying with server then getting this issue. 

Route::get('/proxy', function () {
   return response("Hello, world! {{'now' | date: '%s' }}")->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');

Please help me about this issue.

Thanks!!

**Comment by darrencraig** [comment]
Have you configured the proxy in the app? Liquid templates won't render in the Admin area. App proxies must be configured to use a proxy URL, or the file will download - 

https://shopify.dev/tutorials/display-data-on-an-online-store-with-an-application-proxy-app-extension

**Comment by punitchawla19** [comment]
I have already configure app proxy url via online store extension. By proxy
url download the file from laravel liquid response.

**Comment by darrynten** [comment]
I've noticed weird things happening with apps that call app proxy endpoints after they are uninstalled but are still calling the proxy due to leftover code in the theme.

Have you perhaps uninstalled the app from your dev store?

**Comment by osiset** [comment]
This is not a package issue. Every time this issue has come up in the past it has turned out to be a misconfiguration on the server.

I don't have much information else to provide on this. If you search for proxy in the issues you may find some solutions.

**Comment by punitchawla19** [comment]
Can you please let me know about the what is configuration on server for
this issue.

**Comment by osiset** [comment]
Theres several posts on Google about it. I believe Nginx required a small update. Will close for now, this is not a package thing.
