### ISSUE TITLE
remove old shops table migration

### ISSUE THREAD

**Issue by mddickens** [osiset/laravel-shopify#565]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Error free migration when creating a Shops table

## Current Behavior

Migration fails because of old database migration at vendor/osiset/laravel-shopify/src/ShopifyApp/resources/database/migrations/2020_01_29_230905_create_shops_table.php. Shop information was moved to users table , but migration file still exists at the above path and interferes with creating a shops table for my app's use

## Failure Information

Error message as follows:

Cannot declare class CreateShopsTable, because the name is already in use at /var/www/html/pv-app/database/migrations/2020_09_01_213755_create_shops_view.php:6) vendor/osiset/laravel-shopify/src/ShopifyApp/resources/database/migrations/2020_01_29_230905_create_shop_table.php:class CreateShopsTable extends Migration

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Try to create a Shops table and execute migrate:fresh

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v12.1.0
* Laravel Version: v7
* PHP Version: v7.4.9
* Using a toolset (Docker, Laradock, Vagrant, etc.): None

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by osiset** [comment]
No issues here, I think you've added your own migration file additionally?

The package has no 2020_09_01_213755_create_shops_view.php file.

If you're trying to modify the users table and add your own information, you can not use the same class name, you would need to use `class CreateShopsViewTable` or something similar.

**Comment by mddickens** [comment]
At the time, I was trying to create a shops table and it was apparently conflicting with the migration in the package. I've since gone to defining a database "shops" view over the users table to substitute for the actual shops table and that works fine. I really meant that perhaps that migration file should be removed now that you've removed the table anyway.

**Comment by osiset** [comment]
Ah I see. I think the root issue was my bad, I modded the original migration file to use users. I should've added a new migration to delete the table, and another to create the mods to users.

I'll close for now :)
