### ISSUE TITLE
redirect to login page after selecting the tariff plan

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#566]
## Expected Behavior

redirect to the application after selecting the tariff plan

## Current Behavior

after choosing a tariff, a redirect to the login route is made.

### Steps to Reproduce

1. enable freemium mode
2. select tariff plan
3. redirect to login 

### Context

* Package Version: v12.1
* Laravel Version: v6.18.38
* PHP Version: 7.2.2

in AuthShopify middleware after choosing a tariff plan
only charge_id comes to $request and user authorization is reset.

### Failure Logs

**AuthShopify - handle - dd($next($request):**
  Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function isFreemium() on null in file /home/user/public_html/testProject/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/Billable.php on line 50

**Comment by osiset** [comment]
You're most likely experiencing the cookie issue that others are based on this information.
