### ISSUE TITLE
the /login page installation does not work

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#567]
## Expected Behavior

redirect to the application installation page in shopify

## Current Behavior

after entering a domain and clicking on the "install" button, you will be returned to the /login page. 

## Failure Information

__invoke methon in AuthenticateShop always returns "false".
and only if I quickly add dump after clicking on "install" will I get "completed" back.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create new laravel project
2. install shopify package
3. install from /login page

If this is the first installation then redirect will take place, but after clicking on "Install unlisted app" redirect to /login will also take place

### Context

Package Version: v12.1
Laravel Version: v6.18.38
PHP Version: 7.2.2

**Comment by osiset** [comment]
The login page is being killed off.

What you seem to be experiencing is the cookie issue that others are experiencing, not exactly anything to do with the package, just new browser mechanics we have to work around.
