### ISSUE TITLE
Route for single page application not working properly.

### ISSUE THREAD

**Issue by leninsheikh** [osiset/laravel-shopify#568]
I am trying to add route for single page application like this.
```
Route::get('/{vue_capture?}', function () {
    return view('welcome');
})->where('vue_capture', '[\/\w\.-]*')->middleware(['auth.shopify'])->name('home');
```
## Expected Behavior
it should load welcome.blade.php

## Current Behavior
its totally ignoring my route and going back to a route specified in 
> \vendor\osiset\laravel-shopify\src\ShopifyApp\resources\routes.php  ( line number 23)

**what is the purpose of this route?** if i remove that route  my code is working as expected  . 

## Work around (not the best solution)
because i cant remove the code from  package source, I have to write the route twice like this:
```
Route::get('/', function () {
    return view('welcome');
})->middleware(['auth.shopify'])->name('home');

Route::get('/{vue_capture?}', function () {
    return view('welcome');
})->where('vue_capture', '[\/\w\.-]*')->middleware(['auth.shopify'])->name('home');
```

**Comment by osiset** [comment]
There's nothing I can do in this case I don't believe unless I welcome in a config option to turn it off somehow. Auto-discover is handling when to inject the package's defined routes.

Your work around is fine, as reference, I done similar just last month for a Polaris/React setup.

```php
// Home landing page for the app
Route::middleware(['auth.shopify', 'billable'])->group(function () {
    // /*
    Route::view('/{path?}', 'pages.admin')
        ->where('path', '.*')
        ->name('home-alt');

    // /
    Route::view('/', 'pages.admin')->name('home');
});
```

Where pages.admin was my "welcome".

I'll close this for now, as theres nothing I can actually do right now, but if a config option would be helpful I can try and see about incorporating such an item in.
