### ISSUE TITLE
nothing in docs about using this with a private app

### ISSUE THREAD

**Issue by stryker007** [osiset/laravel-shopify#584]
Hi,

There is nothing in the docs to suggest how you use laravel-shopify with a private app?  obviously when I log in it attempts to authenticate with oauth which is not supported in private apps.

How do I bind laravel-shopify to a private app essentially skipping the login procedure?

**Comment by mrwhale** [comment]
If you don't need all the Shopify features of this package, then you can use the API that this package is built ontop of

https://github.com/osiset/Basic-Shopify-API#private-api

**Comment by osiset** [comment]
The package is not designed to work that way. If you're making an app for a single merchant, simply create a "Custom App" in the partner dashboard, this way it can only be installed on that store. Set your permissions/scopes, and you're good to go. You can install the app like normal.
