### ISSUE TITLE
How can we use permanent token once app is authenticated?

### ISSUE THREAD

**Issue by skygaurav** [osiset/laravel-shopify#585]
@osiset 
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I dont want app to authenticate again and again. I have restored offline token in my db now I want to access api. How can I do tha?

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by osiset** [comment]
Doesn't work that way. If you're unauthenticated (no cookies or session) you're sent through Shopify oauth process, the result is a new token. This also helps when you update access scopes, as the shop will be asked to confirm the changes.

**Comment by skygaurav** [comment]
Thanks for reply. May I know how to configure webhooks? I want to know the process.

**Comment by Kyon147** [comment]
Please read the wiki as most of it is all in there. https://github.com/osiset/laravel-shopify/wiki/Creating-Webhooks

**Comment by skygaurav** [comment]
After doing above I am not able to get the data from webhook. I have created webhook for customers/update, customers/delete, customers/create. Please help me

**Comment by osiset** [comment]
@skygaurav This is not a help forum unfortunately. This is for issues only. Github has not enabled Discussion boards for all projects yet as its still in beta.

My guess is your webhook job has not fired. Try logging into the app via incognito to trigger the full flow again. You may not also have a queue worker running. Theres many things to look for.
