### ISSUE TITLE
TypeError while installing the app.

### ISSUE THREAD

**Issue by DenisYakimchuk** [osiset/laravel-shopify#590]
Does anyone meet this kind of error while installing the app?
`Argument 2 passed to Osiset\ShopifyApp\Actions\AfterAuthorize::Osiset\ShopifyApp\Actions\{closure}() must implement interface Osiset\ShopifyApp\Contracts\ShopModel, null given, called in /vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/AfterAuthorize.php on line 84 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 2 passed to Osiset\\ShopifyApp\\Actions\\AfterAuthorize::Osiset\\ShopifyApp\\Actions\\{closure}() must implement interface Osiset\\ShopifyApp\\Contracts\\ShopModel, null given, called in /vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/AfterAuthorize.php on line 84 at /vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/AfterAuthorize.php:54)`

It appears randomly so there's no any specific flow to reproduce.

Package: 12.1
Laravel 7.25
PHP 7.4 (also the same for 7.3)

**Comment by DenisYakimchuk** [comment]
After dozen of reinstall I made an assumption the issue was caused due to the delay of clearing the shop info in DB. If you try to reinstall the app right after deleting you will get this error in some cases(if  soft delete haven't finished yet)

**Comment by osiset** [comment]
@DenisYakimchuk Your issue is resolved?

**Comment by DenisYakimchuk** [comment]
Actually no, I guess some additional check is need to be implemented here but I'm not sure what exactly to check yet. @osiset have you try to reproduce the issue? It can be pretty much tricky.

**Comment by DenisYakimchuk** [comment]
As workaround I've added additional checks if $shop is not null to ShopifyApp/Actions/AfterAuthorize.php if the package.

Here's the entire file code:

`<?php

namespace Osiset\ShopifyApp\Actions;

use Osiset\ShopifyApp\Contracts\Queries\Shop as IShopQuery;
use Osiset\ShopifyApp\Contracts\ShopModel as IShopModel;
use Osiset\ShopifyApp\Objects\Values\ShopId;
use Osiset\ShopifyApp\Traits\ConfigAccessible;

/**
 * Run after authentication jobs.
 */
class AfterAuthorize
{
    use ConfigAccessible;

    /**
     * Querier for shops.
     *
     * @var IShopQuery
     */
    protected $shopQuery;

    /**
     * Setup.
     *
     * @param IShopQuery $shopQuery The querier for the shop.
     *
     * @return self
     */
    public function __construct(IShopQuery $shopQuery)
    {
        $this->shopQuery = $shopQuery;
    }

    /**
     * Execution.
     * TODO: Rethrow an API exception.
     *
     * @param ShopId $shopId The shop ID.
     *
     * @return bool
     */
    public function __invoke(ShopId $shopId): bool
    {
        /**
         * Fires the job.
         *
         * @param array      $config The job's configuration.
         * @param IShopModel $shop   The shop instance.
         *
         * @return bool
         */
        $fireJob = function (array $config, IShopModel $shop): bool {
            $job = $config['job'];
            if (isset($config['inline']) && $config['inline'] === true) {
                // Run this job immediately
                $job::dispatchNow($shop);
            } else {
                // Run later
                $job::dispatch($shop)
                    ->onQueue($this->getConfig('job_queues')['after_authenticate']);
            }

            return true;
        };

        // Get the shop
        $shop = $this->shopQuery->getById($shopId);

        if ($shop !== null) {
            return false;
        }
        
        // Grab the jobs config
        $jobsConfig = $this->getConfig('after_authenticate_job');

        if (isset($jobsConfig[0])) {
            // We have multi-jobs
            foreach ($jobsConfig as $jobConfig) {
                // We have a job, pass the shop object to the contructor
                if ($shop !== null) {
                    $fireJob($jobConfig, $shop);
                }
            }

            return true;
        } elseif (isset($jobsConfig['job'])) {
            // We have a single job
            if ($shop !== null) {
                return $fireJob($jobsConfig, $shop);
            }
            
            return false;
        } else {
            // We have no jobs
            return false;
        }
    }
}
`

**Comment by osiset** [comment]
Sorry, been tied up. I think this is related to the cookie issue if null is coming through instead of a shop.
