### ISSUE TITLE
 webhook is triggered after a long time

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#591]
hi!
webhook orders/create is triggered about 30 seconds after the order is placed, sometimes even longer. 
it breaks my application.

Are the delays caused by any settings or is it a problem in shopify?

* Package Version: v12.1
* Laravel Version: v6.18.38
* PHP Version: v7.2.5
* Using a toolset (Docker, Laradock, Vagrant, etc.):

**Comment by squatto** [comment]
I would be _very_ wary of depending on timing for webhooks. There are way too many factors that can cause them to be delayed. Network latency or outages anywhere between your server and Shopify's servers, your server having an outage, Shopify's servers having an outage...the list goes on and on. You're going to be running into this kind of issue *a lot* if you build in a hard dependency on short webhook delivery timeframes.

As they say at the very bottom of [this page](https://shopify.dev/tutorials/manage-webhooks):

>Your app should not rely solely on receiving data from Shopify webhooks. Since webhook delivery is not always guaranteed, you should implement reconciliation jobs to periodically fetch data from Shopify.

You may not even _receive_ a webhook for an order, and you need to be ready for that.

**Comment by Kyon147** [comment]
My process with webhooks is to get instant response but something that could as Squtto says can be lost.

You should always be polling for information you need and the API is built for this by using the "since_last_id" as an example in orders.

This way you can combine the two to have a decent "real time" response backed up with the polling to check for any missing orders.
