### ISSUE TITLE
Osiset\ShopifyApp\Exceptions\MissingShopDomainException

### ISSUE THREAD

**Issue by vmbcarabbacan** [osiset/laravel-shopify#594]
I am getting MissingShopDomainException upon running the app. This is a fresh laravel 8.6.0

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 13.0
* Laravel Version: 8.6.0
* PHP Version: 7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.):

**Comment by bassem-shoukry** [comment]
same issue

**Comment by extfoxDusan** [comment]
Same issue here

**Comment by bassem-shoukry** [comment]
Any updates

**Comment by Princeallan** [comment]
Same issue

**Comment by bnski** [comment]
Yeah... same issue.

**Comment by bnski** [comment]
I found some temporary relief by making the following changes to my Session config:

```
'secure' => true,
'same_site' => 'none',
```

**Comment by extfoxDusan** [comment]
> I found some temporary relief by making the following changes to my Session config:
> 
> ```
> 'secure' => true,
> 'same_site' => 'none',
> ```

Does not work for me. It's the same as before.

**Comment by tameemahmad** [comment]
getting same error

**Comment by tameemahmad** [comment]
this is the issue with latest version of laravel now i installed laravel 7 and then follow the docs and app is running

**Comment by MohammadLareeb** [comment]
@tameemahmad mine is not working even after a fresh installation of laravel 7. How did you make it work?

**Comment by awebartisan** [comment]
In `v13.0` , Login route and view has been removed. `Home` route expects a `myshopify` domain which is missing. So you would have to implement the Login view yourself to get `myshopify` domain and then send it to `Home` route.

**Comment by MohammadLareeb** [comment]
@awebartisan How to implement login functionality?  Please, If you can guide me that would be great for me and others too.

**Comment by awebartisan** [comment]
Not tested but following steps will do:

- Create a `/login` route
- Create a `login.blade.php` with a form. Input with `name="shop"` to get the `.myshopify.com` domain of a store and a submit button which will submit the form to `home` route of your app.
- Add `auth` middleware along with `auth.shopify` to your `home` route. This will redirect user to login page that you created.

Hope it helps.

**Comment by shota** [comment]
In my case, redirection to http:// scheme URL cause this problem. Adding forceScheme line to app/Providers/AppServiceProvider.php fixes this problem.

```
    public function boot()
    {
        \URL::forceScheme('https');
    }
```

I think it's because I use ngrok for make redirection URL https. HTTP_X_FORWARDED_PROTO header value is 'https' but laravel8 doesn't use the value. I hope this helps

**Comment by mohinpatwary** [comment]
Hello @awebartisan,
I've created login.blade.php here.
![image](https://user-images.githubusercontent.com/24967072/95604866-fd2f7b00-0a79-11eb-9b4d-a55ddbf4aa06.png)

Also, I've added auth.shopify in the middleware. 
![image](https://user-images.githubusercontent.com/24967072/95605059-3cf66280-0a7a-11eb-9d45-8256f91aaab3.png)

Can you please guide me, What code will I add in login.blade.php? I am new to the laravel.

Thanks in advance

**Comment by sunil209** [comment]
Having the same issue with Laravel 8. Can any one please guide. I am new with Laravel. 


![image](https://user-images.githubusercontent.com/4804763/96373101-eb3f8d80-1187-11eb-8661-0aafdf334c06.png)

**Comment by sunil209** [comment]
Hi @awebartisan,

I followed the steps as you had suggested

Create a /login route
Create a login.blade.php with a form. Input with name="shop" to get the .myshopify.com domain of a store and a submit button which will submit the form to home route of your app.
Add auth middleware along with auth.shopify to your home route. This will redirect user to login page that you created.

After adding these -- 
https://laravel.test/login 
by filling the shop name it is redirecting me to the shopify properly and after installing the app when I am redirecting back to  https://laravel.test/authenticate where It is just rotating rotating ... I have checked shopify-app.php  looks something missing.

Can you please suggest

**Comment by awebartisan** [comment]
Hi @sunil209 , what does your `App Url` and `Allowed redirection URL(s)` look like in App setting on partner dashboard?

**Comment by sunil209** [comment]
Hi @awebartisan ,

Below is screenshot of APP url  and Allowed redirections

![image](https://user-images.githubusercontent.com/4804763/96459664-fce46c00-123f-11eb-87d3-91fa5c49be1f.png)

**Comment by awebartisan** [comment]
@sunil209 it would be better to open a separate issue for this. With `shopify-app.php` file contents and other appropriate information.

**Comment by sxzero** [comment]
> this is the issue with latest version of laravel now i installed laravel 7 and then follow the docs and app is running

I'm ussing "laravel/framework": "^7.24" but I still have the same error.

**Comment by sxzero** [comment]
> In `v13.0` , Login route and view has been removed. `Home` route expects a `myshopify` domain which is missing. So you would have to implement the Login functionality yourself to get `myshopify` domain and then send it to `Home` route.
> 
> Or
> 
> Hit your app url like: `https://example.com/home?shop=shop.myshopify.com` by passing `shop` parameter in query string.

I hit direct to https://domain.local?shop=shop.myshopify.com and it works! Thanks,

```json
"laravel/framework": "^7.24"
"osiset/laravel-shopify": "^14.0"
```

**Comment by gnanakeethan** [comment]
Guys, I got this sorted out. 

You need to apply "auth" middleware after "auth.shopify", 

use the login form to send the "shop" parameter to the home. @sunil209 follow the code of @mohinpatwary, add "auth" to the list of middlewares applied. 

```php
Route::get('/', function () {
    return view('welcome');
})->middleware(['auth.shopify','auth'])->name('home');
```

auth middleware will redirect to the login route you configure. I hope you are clear about the basics of laravel. 

@awebartisan this can be little bit documented.

**Comment by gnanakeethan** [comment]
Hi, Sorry for the wrong comment earlier. 

This issue has to be sorted with two routes. 

in web.php (routes)
```php
Route::get('/', function () {
    return view('welcome');
})->middleware(['auth', 'auth.shopify'])->name('home');
Route::get('/shop', function () {
    return redirect()->route('home');
})->middleware(['auth.shopify'])->name('shop');
```
login blade
```blade
<form method="GET" action="{{ route('shop') }}">
```

I hope this helps.  

@awebartisan I hope this can be documented in the installation.

**Comment by osiset** [comment]
@gnanakeethan Feel free to make a wiki entry for others.

**Comment by masix** [comment]
Hi, first of all. Thanks to @osiset for his awesome job. You saved us a lot of time in Shopify apps development :pray:. 

The problem with @gnanakeethan solution (which is working fine) is that it doesn't solve the main problem, which is when we access the `/shop` route directly we will get the same error. the best solution is to catch the exception and redirect to the login page (get ride of the error completely). For that we must not use the `auth` middleware, just `auth.shopify`, because they do the same thing in different ways, so there will be a conflict if both used (Unless you handle them separately). 

For me this is what i did.

In web.php (routes)
```php
Route::get('/login', function () {
    if (Auth::user()) {
        return redirect()->route('home');
    }
    return view('login');
})->name('login');

Route::middleware(['auth.shopify'])->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('home');

    // Other routes that need the shop user
});
```

In login.blade.php
```php
<form method="GET" action="{{ route('home') }}">
   <input type="text" name="shop"/>
   <button type="submit">Submit</button>
</form>
```

In app/Exceptions/Handler.php
```php
public function render($request, Throwable $exception)
{
    if ($exception instanceof MissingShopDomainException) {
        return Redirect::secure('login');
    }

    return parent::render($request, $exception);
}
```

And finally, don't forget the tip from @shota (not mandatory), which well help in local development using `ngrok`or `localtunnel` to always have https scheme.
In app/Providers/AppServiceProvider.php
```php
public function boot()
{
    URL::forceScheme('https');
}
```

I hope this helps if the @gnanakeethan solution doesn't sweet your needs.

**Comment by kantsverma** [comment]
I tried everything but still the same issues for Laravel 8 :( . I am facing the issues only in case i am not logged to shopify admin if i am already logged in its working fine.

**Comment by masix** [comment]
@kantsverma just make sure that you have a route named 'login' (which is public, doesn't have any middleware) in routes, and the render function in your ExceptionHandler. if the error still persist, you can share with me a basic project that has the problem and i will check it for you.

**Comment by kantsverma** [comment]
@masix  i followed the all steps you mentioned except the last one In app/Providers/AppServiceProvider.php. But does not work for me let me try once again. Then i will let you know

**Comment by kantsverma** [comment]
After spending few hours i fixed the issues.  Please follow the steps
1) In case of not verifyHmac  it go to class AuthShopify to call method handle
2) Where this is called return $this->handleBadVerification($request, $domain);
3) Inside method handleBadVerification() if call the   mean no auth so it call  class MissingShopDomainException and this class is empty and nothing handled inside class
if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
            throw new MissingShopDomainException();
} 
4) Please replace below snippets inside method handleBadVerification() and it will work fine
        if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
			return redirect()->route('login'); // fix the bugs to rediec to login page if auth emtpty
            //throw new MissingShopDomainException();
 }

**Comment by osiset** [comment]
Need logs and a step by step of how to reproduce.

**Comment by Dwhyte** [comment]
Everything works as normal for me. Keep everything the same based on the https://github.com/osiset/laravel-shopify/wiki/Installation guide.  

I'm using Laravel v8

!! Just make sure to create a development store in your https://partners.shopify.com/ account.  

When you create an app, go back into the main home page of your app and scroll down to the bottom.   
Select "Test your app".  Then hit "Select Store".  

At that point, either create a development store if you haven't done so already and select "install app" on the far right of your selected created store.     

You will reach another page telling you to finally install your app into your development store.

Watch this video and follow along carefully. - https://www.youtube.com/watch?v=7U_skSqlI1E&list=PLB4AdipoHpxbE0ldfsNobTSZm2tUBW9GR&index=2&t=437s

Hope this helps anyone who is stuck.

**Comment by jasontxf** [comment]
Thanks @Dwhyte I didn't know we could test directly from Shopify Partner page!

Here's the position of the button if anyone is wondering!

<img width="945" alt="Screenshot 2020-12-04 at 2 00 41 PM" src="https://user-images.githubusercontent.com/1124731/101127793-409d0480-3639-11eb-87bc-06e98e08fe83.png">

**Comment by mooezz999** [comment]
@Dwhyte Thanks man it worked

**Comment by makhchan** [comment]
> Everything works as normal for me. Keep everything the same based on the https://github.com/osiset/laravel-shopify/wiki/Installation guide.
> 
> I'm using Laravel v8
> 
> !! Just make sure to create a development store in your https://partners.shopify.com/ account.
> 
> When you create an app, go back into the main home page of your app and scroll down to the bottom.
> Select "Test your app". Then hit "Select Store".
> 
> At that point, either create a development store if you haven't done so already and select "install app" on the far right of your selected created store.
> 
> You will reach another page telling you to finally install your app into your development store.
> 
> Watch this video and follow along carefully. - https://www.youtube.com/watch?v=7U_skSqlI1E&list=PLB4AdipoHpxbE0ldfsNobTSZm2tUBW9GR&index=2&t=437s
> 
> Hope this helps anyone who is stuck.

@Dwhyte  The installation & login to store works fine, issue is when you navigate to other routes, it takes you back to login page *MissingShopDomainException*.
@mooezz999  @jasontxf is navigation to other pages works fine for you ?

My case am connected to the app on store, I move to products page it works, 2nd time I click any link it shows the exception MissingShopDomainException

**Comment by mooezz999** [comment]
@makhchan Sadly I’m stuck with the redirecting issue at the moment. Tried chrome, firefox and opera didn’t solve the problem.

**Comment by Dwhyte** [comment]
@makhchan @mooezz999 I was able to replicate the same issue when I have the "forceRedirect" set to false in the default.blade.php file script section. 

![Screen Shot 2020-12-26 at 5 04 59 PM](https://user-images.githubusercontent.com/2172177/103162369-bc641a00-47bd-11eb-941a-91b9e44b444f.png)


Once that is "false", I have my test app running outside my shopify store via ex: myshopifyapp.test in chrome browser, and also still viewing the test app inside the shopify store instance as well in another tab separate tab.  I do get redirected to Osiset\ShopifyApp\Exceptions\MissingShopDomainException error page when both app instances are open, and I'm viewing the same page/route in both apps. One of the apps will send an MissingShopDomainException error.  

This is all I could reproduce on my side.  So I just pick which one I want to development in, or set "forceRedirect" to true to just have your local app address redirect to your shopify store app and use that instead.

**Comment by mooezz999** [comment]
@Dwhyte  Where did you get this default.blade.php code from? Can you send me the code in default.blade.php please?

**Comment by Dwhyte** [comment]
@mooezz999 you already have it. All you need to do is run this command in your app terminal -  php artisan vendor:publish

then select the number option for "shopify-views". This will generate a vendor folder in your views directory with all those blade files. :)

**Comment by makhchan** [comment]
I'm also stuck with the redirect issue.
I think it is due to missing _$shop_ param on one of **input**, **header** or **referer**, which cause _$domain_ to be null

vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:68
```
    public function handle(Request $request, Closure $next)
    {
        // Grab the domain and check the HMAC (if present)
        $domain = $this->getShopDomainFromData($request);
        ....
```

And That cause the _MissingShopDomainException_ :
vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:337

```
    private function handleBadVerification(Request $request, ShopDomainValue $domain)
    {
        if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
            throw new MissingShopDomainException();
        }
        ....
```
Hope someone can do a PR for this one soon, @osiset  will appreciate your support on this, really blocked many developers as I see.

**Comment by osiset** [comment]
So is this only happening when you click on a route inside your app?

**Comment by yasir-naseer-tetralogicx** [comment]
My app is working just fine in chrome browser. if i click a route inside app it redirects me to expected page without any issues, but as soon as i move to some other browser like firefox and i click some route within it is throwing the same exception. (I'm using  "osiset/laravel-shopify": "15.*" )

**Comment by osiset** [comment]
@yasir-naseer-tetralogicx 

So if I understand.

**Chrome**: You open app... all is fine. You click on a route inside the app... all is fine.

**Firefox**: You open app... all is fine. You click on a route inside the app... error shows.

Is that correct?

**Comment by yasir-naseer-tetralogicx** [comment]
@osiset yes this is right, its happening on firefox for me

**Comment by RedaMakhchan** [comment]
I confirm for **FF**, I didn't test on **chrome** will do and see if it is working fine and confirm back here.
But for **FF** just navigating inside app to different route cause the issue, yes I confirm.

**Comment by raihan004** [comment]
> Hi, first of all. Thanks to @osiset for his awesome job. You saved us a lot of time in Shopify apps development 🙏.
> 
> The problem with @gnanakeethan solution (which is working fine) is that it doesn't solve the main problem, which is when we access the `/shop` route directly we will get the same error. the best solution is to catch the exception and redirect to the login page (get ride of the error completely). For that we must not use the `auth` middleware, just `auth.shopify`, because they do the same thing in different ways, so there will be a conflict if both used (Unless you handle them separately).
> 
> For me this is what i did.
> 
> In web.php (routes)
> 
> ```
> Route::get('/login', function () {
>     if (Auth::user()) {
>         return redirect()->route('home');
>     }
>     return view('login');
> })->name('login');
> 
> Route::middleware(['auth.shopify'])->group(function () {
>     Route::get('/', function () {
>         return view('welcome');
>     })->name('home');
> 
>     // Other routes that need the shop user
> });
> ```
> 
> In login.blade.php
> 
> ```
> <form method="GET" action="{{ route('home') }}">
>    <input type="text" name="shop"/>
>    <button type="submit">Submit</button>
> </form>
> ```
> 
> In app/Exceptions/Handler.php
> 
> ```
> public function render($request, Throwable $exception)
> {
>     if ($exception instanceof MissingShopDomainException) {
>         return Redirect::secure('login');
>     }
> 
>     return parent::render($request, $exception);
> }
> ```
> 
> And finally, don't forget the tip from @shota (not mandatory), which well help in local development using `ngrok`or `localtunnel` to always have https scheme.
> In app/Providers/AppServiceProvider.php
> 
> ```
> public function boot()
> {
>     URL::forceScheme('https');
> }
> ```
> 
> I hope this helps if the @gnanakeethan solution doesn't sweet your needs.

this one solve the issues for me

**Comment by RedaMakhchan** [comment]
@raihan004 the above code just redirects to login page in case of MissingShopDomainException, it doesn't fix the real issue,  why we face MissingShopDomainException when navigating on the app..
I face this issue on both Chrome and FireFox. windows + ubuntu.

**Comment by RedaMakhchan** [comment]
@osiset 
For _getShopDomainFromData_, exactly INPUT, HEADER & REFERER options.

- First load just after login :
> **INPUT** is filled with info
> **HEADER** is null
> **REFERER** is null

- First navigation to different route : 
> **INPUT** is null
> **HEADER** is null
> **REFERER**  is filled this time

- 2nd navigation : 
> **INPUT** is null
> **HEADER** is null
> **REFERER** is null

I think also it is related to lost a session where this info are searched for..

**Comment by makhchan** [comment]
Looking more into the issue, Single Page applications will not have this issue.

Some related (old) subjects : 

- https://github.com/Shopify/shopify_app/issues/204#issuecomment-255139164
- https://community.shopify.com/c/Shopify-APIs-SDKs/Embedded-App-Expiring-Sessions/m-p/303110/highlight/true#M14909

Getting **hmac** from cookies or custom session can be a solution.

**Comment by osiset** [comment]
Hmm I think the issue may be pulling the domain from the data. If they are logged in, I should pull the domain from the user model...

@RedaMakhchan Are you able to confirm if the user is logged in on your first and second navigation?

If you open src/ShopifyApp/Http/Middleware/AuthShopify.php and at line 84 (blank line), add:

`Log::info(json_encode($this->shopSession->getShop()))`.

If the user session is still active, the log should show, and in that case, the error lies there in trying to pull from data when it should pull from the user model first, then data as a secondary.

**Comment by makhchan** [comment]
@osiset I confirm, I can see user object on 1st time, 2nd one (when i move to new route) it shows `null`, and 3rd navigation `MissingShopDomainException`

Logs : 
```
[2020-12-30 16:06:57] local.INFO: {"id":1,"name":"****.myshopify.com","email":"shop@****.myshopify.com","email_verified_at":null,"created_at":"2020-12-25T13:33:41.000000Z","updated_at":"2020-12-30T10:41:19.000000Z","shopify_grandfathered":0,"shopify_namespace":null,"shopify_freemium":0,"plan_id":null,"deleted_at":null}  
[2020-12-30 16:07:02] local.INFO: null  
[2020-12-30 16:07:39] local.ERROR:  {"exception":"[object] (Osiset\\ShopifyApp\\Exceptions\\MissingShopDomainException(code: 0):  at ***/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:342)
[stacktrace]
...

```

**Comment by osiset** [comment]
Hmm thanks. Ill try to reproduce.

**Comment by osiset** [comment]
Though my testing I can confirm this is a cookie issue. The cookie is never set.

I've tried to quickly debug this by:

1. Creating a middleware to check for a test cookie
2. If test cookie is not existing, redirect full-page to a path and set the test cookie
3. Redirect back to app

I can see the samesite test cookie is set, however, when going back into the app, cookies are not there and browser warns of a third party attempting to set cookies.

I'll close this for #522 ... I do not have a solution for this right now, I need help on this, but at least I'm able to reproduce.

**Comment by sagar-itt** [comment]
>  \URL::forceScheme('https');

URL import package name?

**Comment by KevinSHansen** [comment]
Anything new on this?

Still got the issue.
Osiset\ShopifyApp\Exceptions\MissingShopDomainException

**Comment by sagar-itt** [comment]
On browser you cannot run directly.
For this you have to first login with store account and then open our app.
One more thing that in current app I'm using my local url so if you want to use this then please set your ngrox https urla via the devwloper partners account

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by haseebbutt1999** [comment]
> > Everything works as normal for me. Keep everything the same based on the https://github.com/osiset/laravel-shopify/wiki/Installation guide.
> > I'm using Laravel v8
> > !! Just make sure to create a development store in your https://partners.shopify.com/ account.
> > When you create an app, go back into the main home page of your app and scroll down to the bottom.
> > Select "Test your app". Then hit "Select Store".
> > At that point, either create a development store if you haven't done so already and select "install app" on the far right of your selected created store.
> > You will reach another page telling you to finally install your app into your development store.
> > Watch this video and follow along carefully. - https://www.youtube.com/watch?v=7U_skSqlI1E&list=PLB4AdipoHpxbE0ldfsNobTSZm2tUBW9GR&index=2&t=437s
> > Hope this helps anyone who is stuck.
> 
> @Dwhyte The installation & login to store works fine, issue is when you navigate to other routes, it takes you back to login page _MissingShopDomainException_.
> @mooezz999 @jasontxf is navigation to other pages works fine for you ?
> 
> My case am connected to the app on store, I move to products page it works, 2nd time I click any link it shows the exception MissingShopDomainException

Same my issue, are you getting any solution about this issue?

**Comment by rewaza** [comment]
> > > Everything works as normal for me. Keep everything the same based on the https://github.com/osiset/laravel-shopify/wiki/Installation guide.
> > > I'm using Laravel v8
> > > !! Just make sure to create a development store in your https://partners.shopify.com/ account.
> > > When you create an app, go back into the main home page of your app and scroll down to the bottom.
> > > Select "Test your app". Then hit "Select Store".
> > > At that point, either create a development store if you haven't done so already and select "install app" on the far right of your selected created store.
> > > You will reach another page telling you to finally install your app into your development store.
> > > Watch this video and follow along carefully. - https://www.youtube.com/watch?v=7U_skSqlI1E&list=PLB4AdipoHpxbE0ldfsNobTSZm2tUBW9GR&index=2&t=437s
> > > Hope this helps anyone who is stuck.
> > 
> > 
> > @Dwhyte The installation & login to store works fine, issue is when you navigate to other routes, it takes you back to login page _MissingShopDomainException_.
> > @mooezz999 @jasontxf is navigation to other pages works fine for you ?
> > My case am connected to the app on store, I move to products page it works, 2nd time I click any link it shows the exception MissingShopDomainException
> 
> Same my issue, are you getting any solution about this issue?

Same issue. Stuck on error: Osiset\ShopifyApp\Exceptions\MissingShopDomainException

**Comment by sagar-itt** [comment]
Hi
When you hit from browser then you get this error but if you will hit from admin panel then you will not get any error.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by makhchan** [comment]
Hello everyone,

I faced this issue also, and I did fix by setting `same_site` param to `none` at the end of **config/session.php**

```
    /*
    |--------------------------------------------------------------------------
    | Same-Site Cookies
    |--------------------------------------------------------------------------
    |
    | This option determines how your cookies behave when cross-site requests
    | take place, and can be used to mitigate CSRF attacks. By default, we
    | will set this value to "lax" since this is a secure default value.
    |
    | Supported: "lax", "strict", "none", null
    |
    */

    'same_site' => 'none',
```

Happy coding.

**Comment by squatto** [comment]
Rather than changing your app's cookie settings, you can instead just trigger a redirect (or do anything you want) whenever `MissingShopDomainException` is thrown.

In `app/Exceptions/Handler.php` in the `register()` method, register the exception as renderable and then put whatever your handling code is in the callback.

For example, in my app I am redirecting to a route that displays a message to the user letting them know that their login can't be verified, and instructing them to reload our app from their Shopify admin:

```php
public function register(): void
{
    // redirect to the "unable to verify your login" error message
    $this->renderable(function (MissingShopDomainException $e) {
        return redirect()->route('apps.shopify.no-auth');
    });
}
```

One important thing to remember is that the user is _not_ authenticated when they access the route that you redirect them to, so you will need to register the route _without_ the `auth.shopify` middleware. I would recommend that you also register the route without the `itp` middleware, since you don't need to worry about ITP at that point.

I manually register all of the app routes (instead of letting the package register them) and I've broken them into separate files, but I'll put this here in case anybody is curious how to accomplish what I said in the previous paragraph:

```php
Route::middleware('web')
     ->group(function () {
         // the user isn't logged in
         require base_path('routes/apps/shopify/no-auth.php');

         Route::middleware('itp')
              ->group(function () {
                  require base_path('routes/apps/shopify/itp.php');

                  Route::middleware('auth.shopify')
                       ->group(function () {
                           // ...authenticated app routes...
                       });
              });
     });
```

You will also need to make sure that your views recognize that the user isn't logged in and don't attempt to display shop info, user info, etc. You can do that with [`@auth ... @endauth` and `@guest ... @endguest`](https://laravel.com/docs/8.x/blade#authentication-directives)

**Comment by rewaza** [comment]
Thank you all. When I solved this issue, I faced another one (same site issue) I moved app from local server to heroku and everything works fine. Thanks.

**Comment by devotmane** [comment]
Thanks a lot @oayoub84  it worked for me

**Comment by arnedeutscher** [comment]
> 
> 
> Hi, first of all. Thanks to @osiset for his awesome job. You saved us a lot of time in Shopify apps development 🙏.
> 
> The problem with @gnanakeethan solution (which is working fine) is that it doesn't solve the main problem, which is when we access the `/shop` route directly we will get the same error. the best solution is to catch the exception and redirect to the login page (get ride of the error completely). For that we must not use the `auth` middleware, just `auth.shopify`, because they do the same thing in different ways, so there will be a conflict if both used (Unless you handle them separately).
> 
> For me this is what i did.
> 
> In web.php (routes)
> 
> ```
> Route::get('/login', function () {
>     if (Auth::user()) {
>         return redirect()->route('home');
>     }
>     return view('login');
> })->name('login');
> 
> Route::middleware(['auth.shopify'])->group(function () {
>     Route::get('/', function () {
>         return view('welcome');
>     })->name('home');
> 
>     // Other routes that need the shop user
> });
> ```
> 
> In login.blade.php
> 
> ```
> <form method="GET" action="{{ route('home') }}">
>    <input type="text" name="shop"/>
>    <button type="submit">Submit</button>
> </form>
> ```
> 
> In app/Exceptions/Handler.php
> 
> ```
> public function render($request, Throwable $exception)
> {
>     if ($exception instanceof MissingShopDomainException) {
>         return Redirect::secure('login');
>     }
> 
>     return parent::render($request, $exception);
> }
> ```
> 
> And finally, don't forget the tip from @shota (not mandatory), which well help in local development using `ngrok`or `localtunnel` to always have https scheme.
> In app/Providers/AppServiceProvider.php
> 
> ```
> public function boot()
> {
>     URL::forceScheme('https');
> }
> ```
> 
> I hope this helps if the @gnanakeethan solution doesn't sweet your needs.

This works for me. But instead `$exception instanceof MissingShopDomainException` i used `$exception instanceof \Osiset\ShopifyApp\Exceptions\MissingShopDomainException` for functionality.

**Comment by AryanKumar** [comment]
If you are using larave 8 and want to handle the exception "MissingShopDomainException" then you can handle this exception using handler.php in laravel.

Go to app->Exceptions->Handler and write below code:

use Osiset\ShopifyApp\Exceptions\MissingShopDomainException;
use Illuminate\Support\Facades\Redirect;

and inside function register write:
	$this->renderable(function(MissingShopDomainException $e){
		return Redirect::to('https://www.shopify.com/in/login');
	});

This will redirect to the shopify login page when anyone will try to hit the base url without login.
