### ISSUE TITLE
Add "home" route name to config

### ISSUE THREAD

**Issue by squatto** [osiset/laravel-shopify#595]
Is there any reason that the "home" route name *couldn't* be added to the config? I already have a route named `home` and all of my app's routes are `app.*`. However, I currently can't tell this package to use `app.home` as the home route.

I'm happy to submit a PR if there aren't any reasons that this shouldn't work. There are only 3 references to the "home" route in the entire codebase so it should be a pretty simple change for me to make.

Thanks!

**Comment by squatto** [comment]
Actually, after looking through the entire routes file, I think that it would actually be better to add a config option for the [route group's name prefix](https://laravel.com/docs/8.x/routing#route-group-name-prefixes). Similar to the way we can already set the route prefix, this would allow us to further customize our app's routing, specifically to avoid collisions.

Again, I would be happy to PR this change.

**Comment by darrynten** [comment]
I'm trying to refactor out the entirety of the `resources/views` and the `resources/routes.php` files so that I can swap the current request/response cookie-centric setup with my own javascript and resources to enable easy SPA support with the new Shopify JWT functionality.

A variant of this might be useful to me because I essentially want to only load 1 single bootstrap 'home' view.

**Comment by osiset** [comment]
#598 will allow for excluding routes to be registered and allow you to setup your own.

**Comment by osiset** [comment]
Feature is merged to allow for disabling internal routes. Will be available as a patch release later today.

**Comment by squatto** [comment]
Thanks for the changes to allow disabling internal routes @osiset - that's a big help! Along with that change, this issue suggests being able to define the names of the routes, to help avoid collisions with existing routes (especially "home"). Is that something that you're anticipating adding? I'd be happy to PR the change if you'd like.

Thanks!

**Comment by squatto** [comment]
I'm thinking something along these lines...

Add this to the config:

```php
return [
    // ...

    'route_names' => [
        'home'                 => env('SHOPIFY_ROUTE_HOME', 'home'),
        'authenticate'         => env('SHOPIFY_ROUTE_AUTHENTICATE', 'authenticate'),
        'authenticate_oauth'   => env('SHOPIFY_ROUTE_AUTHENTICATE_OAUTH', 'authenticate.oauth'),
        'billing'              => env('SHOPIFY_ROUTE_BILLING', 'billing'),
        'billing_process'      => env('SHOPIFY_ROUTE_BILLING_PROCESS', 'billing.process'),
        'billing_usage_charge' => env('SHOPIFY_ROUTE_BILLING_USAGE_CHARGE', 'billing.usage_charge'),
        'webhook'              => env('SHOPIFY_ROUTE_WEBHOOK', 'webhook'),
    ],

    // ...
];
```

Then wherever a route name is referenced, the config value would be used instead.

For example, this:

```php
return Redirect::route(
    'authenticate.oauth',
    ['shop' => $domain->toNative()]
);
```

Would become this:

```php
return Redirect::route(
    config('shopify-app.route_names.authenticate_oauth'),
    ['shop' => $domain->toNative()]
);
```

The route registration in `routes.php` would use the config values too, of course.

Again, I'd be happy to make this entire change if you're good with the concept. Thanks!

**Comment by osiset** [comment]
@squatto Feel free to submit a PR yup, there's a built-in config trait as well which can easy up accessing the route names in controllers and services

```
use ConfigAccessible;

// ...

$this->getConfig('route_names.authenticate_oauth');
```

**Comment by squatto** [comment]
@osiset I submitted PR #603 to add custom route naming support 👍🏻
