### ISSUE TITLE
Add route domain config option

### ISSUE THREAD

**Issue by squatto** [osiset/laravel-shopify#596]
My app routes are registered like this:

```php
Route::domain(env('SHOPIFY_APP_DOMAIN'))
     ->as('app.')
     ->middleware('web')
     ->group(base_path('routes/shopify-app.php'));
```

In particular, my app's routes are served from a separate domain that is being served by the same codebase. However, the routes in this package are all being registered outside of that domain (for obvious reasons). Could an optional config option be added that defines the domain for the routes?

Another option would be to add a config option `manual_routes` that - similar to `manual_migrations` - allows us to define the routes ourselves.

I would be happy to PR either of these changes.

Thanks!

**Comment by osiset** [comment]
This has been brought up before in another issue. I am adding a config to ignore internal routes.

**Comment by osiset** [comment]
Closing for older ticket #595
