### ISSUE TITLE
Migration error if `users` already has soft deletes

### ISSUE THREAD

**Issue by squatto** [osiset/laravel-shopify#597]
If your `users` model already uses soft deletes, the migration throws an error because it attempts to add them again. Also, rolling back the migration will drop soft deletes, which may not be what someone actually wants.

One possible way I can think of to remedy this would be with a config setting that says to add/remove soft deletes in the migration or not.

## Expected Behavior

Migration runs successfully

## Current Behavior

Migration fails because the `deleted_at` column already exists

## Failure Information

```
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'deleted_at' (SQL: alter table `users` add `shopify_grandfathered` tinyint(1) not null default '0', add `shopify_namespace` varchar(255) null, add `shopify_freemium` tinyint(1) not null default '0', add `plan_id` int unsigned null, add `deleted_at` timestamp null)
```

### Steps to Reproduce

1. Add soft deletes to the `users` model
2. Run package migrations

### Context

* Package Version: v13.0.0
* Laravel Version: v7.28.3
* PHP Version: v7.4.6

### Failure Logs

N/A

**Comment by osiset** [comment]
Thanks, I'll have to look into a config option.

**Comment by spspasov** [comment]
@osiset I'd be willing to work on that if you don't have the time for it.

**Comment by osiset** [comment]
`if (!Schema::hasColumn('users', 'deleted_at')) {` can be used. I can do an update later for this.

**Comment by osiset** [comment]
Merged, closing.
