### ISSUE TITLE
Webhook is failing

### ISSUE THREAD

**Issue by helix2020** [osiset/laravel-shopify#600]
Shopify Notification:

> Your webhook for orders/create at https://name-of-domain/webhook/orders-create  has been removed on 2020-10-10 19:27:44 UTC because it's failing to return a successful response.

I have used the WebhookController of the package and it returns 201 response. 

Based on this link **https://shopify.dev/tutorials/manage-webhooks**, it said that webhook should send 200 OK response. Any response outside of the 200 range, including 3XX HTTP redirection codes, indicates that you did not receive the webhook.

What is the reason that is effecting to fail a webhook? May it be the 201 response or any other issue!

Looking forward to your help!

Regards

### Context

* Package Version: v11.5
* Laravel Version: v7.0
* PHP Version: v7.2.5
* Using a toolset (Docker, Laradock, Vagrant, etc.): Laradock

**Comment by osiset** [comment]
I note you're using Laradock. How would the webhooks work? That's a local setup.

**Comment by helix2020** [comment]
Locally I am using **ngrok* (https)
However, I have forgotten to write that actual project is set up in **GoDaddy** (https). Thus, the issue comes from GoDaddy domain and hosting.

**Comment by osiset** [comment]
[See the wiki ](https://github.com/osiset/laravel-shopify/wiki/ngrok) on this, ill close for now.

**Comment by helix2020** [comment]
Hi @osiset,

as far as I concerned the webhook is failing because of the delay in response whether the Order has more than 5 items is a timeout.
I tried to change this part of code:
`$jobClass::dispatch(
            new ShopDomain($request->header('x-shopify-shop-domain')),
            $jobData
        );`

to set as 
`$jobClass::dispatchAfterResponse(
            new ShopDomain($request->header('x-shopify-shop-domain')),
            $jobData
        );`

But I'm receiving again a warning email for the webhooks that failed because of timeout response.

Is there any way how to manage to return a Response within 5 seconds?

Hope I was clear, and looking to your help!
Regards!

**Comment by osiset** [comment]
I’ve had orders with 10-20 items come through just fine. This seems like some other issue. I can’t see how a few KBs of JSON data would be more than 5 seoncds.
