### ISSUE TITLE
MissingShopDomainException when trying to install with safari

### ISSUE THREAD

**Issue by codingphasedotcom** [osiset/laravel-shopify#602]
Expecting to see the application redirect back to the embedded app view on shopify.

**SAFARI**
After pressing the install unlisted app I get the error of **MissingShopDomainException**
I checked to see if the store is in the Users Table and it's there.
So then went back to the store dashboard on shopify and checked if the app got installed and it did...
Also the app works just fine when I clicked inside of it.
So I'm guessing the issue is somewhere after installing it's not getting the shop domain.

Now what's interesting is that the app works fine on chrome, and firefox

* Package Version: v13.0
* Laravel Version: v7.28.3
* PHP Version: v7.4
* Using a toolset (Docker, Laradock, Vagrant, etc.):

**Comment by osiset** [comment]
#522
