### ISSUE TITLE
Update a Theme Asset

### ISSUE THREAD

**Issue by cpatgo** [osiset/laravel-shopify#605]
Hi There,

I need help with regards to updating an existing theme asset. Pretty sure I'm doing it wrong but can you provide me with the correct one. Here's how I'm using it.

```
$shop = Auth::user();
$request = $shop->api()->rest('PUT', '/admin/themes/83541819447/assets.json', ['query' => "asset:{'key': 'snippets/test.liquid', 'value': 'testing 2020' }"]);
```

Can you provide me with the correct way on doing this using the sample above. Thanks

**Comment by darrynten** [comment]
You're looking for something like this:

```php

$response = $this->api()->rest(
    'PUT', '/admin/themes/83541819447/assets.json', [
        'asset' => [
            'key' => 'snippets/test.liquid',
            'value' => 'testing 2020',
        ]
    ]
);
```

**Comment by cpatgo** [comment]
@darrynten Thanks. It worked!
