### ISSUE TITLE
Error in change annual charge from interface

### ISSUE THREAD

**Issue by JosephAlonzo** [osiset/laravel-shopify#606]
## Expected Behavior

Change plan from user interface with annual period of time

## Current Behavior

I get this error message 

"message:"Variable $lineItems of type [AppSubscriptionLineItemInput!]! was provided invalid value for 0.plan.appRecurringPricingDetails.interval (Field is not defined on AppRecurringPricingInput)"

## Failure Information

I get the error in the ApiHelper.php in the function "createChargeGraphQL" in this line 
 $lineItems: [AppSubscriptionLineItemInput!]!

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Using a ANNUAL plan in interval
2. I used this html < p >< a href="{{ route('billing', ['plan' => 2]) }}">Upgrade< /a >< /p >

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version:  "^12.0"
* Laravel Version:^7.0
* PHP Version: "^7.2.5",
* Using a toolset (Valet.):

**Comment by JosephAlonzo** [comment]
I change my shopify version  and thats work, because in the previous shopify version there are not interval in AppRecurringPricingInput :+1:

**Comment by Enmaboya** [comment]
> I change my shopify version and thats work, because in the previous shopify version there are not interval in AppRecurringPricingInput

hello!
What did you mean by "change my shopify version"?

**Comment by JosephAlonzo** [comment]
Hello, i defined my shopify versión in the .env file
