### ISSUE TITLE
MissingShopDomainException when not opening store

### ISSUE THREAD

**Issue by panjigemilang** [osiset/laravel-shopify#607]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

nothing errors.

## Current Behavior
```
Osiset\ShopifyApp\Exceptions\MissingShopDomainException
vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:343
```
## Failure Information

This errors occurs when opening the apps without going to the Shopify store apps.

### Steps to Reproduce

1. opening the laravel apps. ex: `https://example.com/laravel-shopify`
2. errors occured.

This errors will not occurs if I open the store from partners.shopify, and then go to apps tab, and click the selected apps, and then reopening laravel apps from another tab then the errors gone.

### Context
```
        "php": "^7.2.5",
        "laravel/framework": "^7.24",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.4",
        "osiset/laravel-shopify": "^13.1"
```

**Comment by gnanakeethan** [comment]
You need to supply "shop" parameter to the routes in which the auth.shopify middleware applies. You can achieve this by adding "auth" middleware and getting the "shop" parameter using the login screen. I assume you do not use the regular login screen.
