### ISSUE TITLE
'Unable to verify Signature' error after authentication

### ISSUE THREAD

**Issue by yrk2yrk** [osiset/laravel-shopify#608]
## Expected Behavior

Did a fresh install. On authentication the app should show welcome screen.

## Current Behavior

After authentication, I am getting unable to verify signature error.

## Failure Information

Osiset\ShopifyApp\Exceptions\SignatureVerificationException
Unable to verify signature.

### Steps to Reproduce

Do a fresh install of v.14.0 on Laravel 7.24.8

### Context

* Package Version: v14.0
* Laravel Version: v7.24.8
* PHP Version: v7.2

**Comment by osiset** [comment]
Are you sure your API keys are correct, are you using nginx or docker?

**Comment by yrk2yrk** [comment]
@osiset thanks, yes the API keys did not get saved due to some reason. I have updated it and now its working fine. 
Thank you so much. :)
