### ISSUE TITLE
Status 2020-10-29

### ISSUE THREAD

**Issue by osiset** [osiset/laravel-shopify#610]
Hey all,

I still can not enable discussions on this repo, so I am resorting to a pinned issue for now. I've had several emails from people.

I am currently going through a time consuming divorce and my free time has been limited the past few weeks. I plan to get to some of your issues on Sunday. The ITP cookie issues, I am still working on a solution for this on my borrowed Mac, but the whole flow is still giving me an issue currently... I am running into an issue with multiple redirects and it dies, but I plan to dedicate more time to this on Sunday.

Thanks everyone.

**Comment by awebartisan** [comment]
Hey Tyler, thank you for the time you spend on this package. Really appreciate it 🙏🏼
