### ISSUE TITLE
possible tiny fix?

### ISSUE THREAD

**Issue by amosmos** [osiset/laravel-shopify#611]
Shouldn't this call go to /admin/api/version and not just /admin?

https://github.com/osiset/laravel-shopify/blob/a1d6371d7c641ce4bf4b13d74c5f46114435c058/src/ShopifyApp/Services/ApiHelper.php#L255

I assume /admin is working since the user is actually logged in (otherwise he wouldn't be able to install the app anyway), but I think it's better to use the documented endpoint (see here: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#create-2020-10)

Hope this helps,
Thanks,
Amos

**Comment by osiset** [comment]
@amosmos Feel free to issue a PR if you've fixed it. Yes, the documented endpoint didn't have /api always, I have not gotten around to updating it :) but the calls will remain to work.

**Comment by osiset** [comment]
Actually, no needed. I realized it calls the /api anyways. Line 126 of AuthRequest.php of Basic-Shopify-API, does a regex replace of /admin/api or /admin to /admin/api/[version]. So we're all good!

**Comment by amosmos** [comment]
Great! Thanks!
