### ISSUE TITLE
Issue after installation with Laravel 8

### ISSUE THREAD

**Issue by kouloughli-hemza** [osiset/laravel-shopify#613]
## Expected Behavior

Normal installation ,

## Current Behavior

While installing using composer , and right after artisan package:discover --ansi it throws an error saying : 
` array_merge(): Expected parameter 1 to be an array, null given`
the responsible file for the error is  : 
`vendor/osiset/laravel-shopify/src/ShopifyApp/Traits/ConfigAccessible.php:23`

* Package Version: v14.0
* Laravel Version: Laravel Framework 8.13.0
* PHP Version: 7.3.12

if fixed it by checking if  : `Config::get('shopify-app') != null`
if you want i can create PR

**Comment by osiset** [comment]
@kouloughli-hemza Please make a PR 👍

**Comment by sharik709** [comment]
@osiset i'm gonna make a PR for this. I also need this package to work with laravel 8. Thanks for building the package :)

**Comment by osiset** [comment]
Fixed in master.
