### ISSUE TITLE
App got rejected due to it hasn't implemented authentication through OAuth correctly and can't be reinstalled

### ISSUE THREAD

**Issue by jithinjoyj4** [osiset/laravel-shopify#614]
## Expected Behavior

Oauth installation page when reinstalling the app
## Current Behavior
When reinstalling the app it directly go to app url skipping oauth page with scope permission and shows this message 

"There’s no page at this address Check the URL and try again, or use the search bar to find what you need.".

i think its cookie related, some times when i switch stores to reinstall it works

## Failure Information
App got rejected due to this issue

Your app hasn't implemented authentication through OAuth correctly and can't be reinstalled. Review our OAuth documentation and see this screenshot https://screenshot.click/20-11-82695-90787.png for additional details.3

iam new to shopify and laravel any suggestion would be really helpful, Thanks

![shooath](https://user-images.githubusercontent.com/57803136/98366006-4e229700-2059-11eb-8cf8-aad9e901ea76.png)

* Package Version:13.1
* Laravel Version: 8.0
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):aws server

**Comment by jithinjoyj4** [comment]
Uninstalled Job fixed it

**Comment by jithinjoyj4** [comment]
Uninstalled Job is not working now, shop is not getting soft deleted on uninstall which causing the page not found issue when reinstalling, the job was working fine i dont know what happened

**Comment by osiset** [comment]
I have just tested this, nothing not working here. It takes a couple mins for the job to come in.

**Comment by jmanzo** [comment]
I fixed this issue by just running `php artisan migrate:refresh --seed`. Seems like my issue was that there was old data stored on my database. I'm working on a development app. 🛑  Don't run this command if you're working over a production app.

**Comment by mudassirali007** [comment]
### Issue

If you cancel on the installation page it will not show the install page the second time.


### Reproduce Steps:

1. Goto Oauth Page and select **Cancel**. It will create an entry in the Database in users with the 'remember_token' column as NULL 

<img width="499" alt="Capture" src="https://user-images.githubusercontent.com/54500326/148445662-21db12f3-8406-45be-becc-5ace23fc1547.PNG">



2. Then if you again go to the Oath Page again it will show this message. 


<img width="570" alt="Capture2" src="https://user-images.githubusercontent.com/54500326/148444736-da92d885-3d7d-465f-873d-ad004f34d5d4.PNG">
