### ISSUE TITLE
Using Package as Rest API with separate Reactjs frontend

### ISSUE THREAD

**Issue by kouloughli-hemza** [osiset/laravel-shopify#615]
Hello and thank you for the great package,
i see in the last changeLog that you added JWT support , and was wondering if someone used the package as REST API and used separate front end (Reactjs) for the app,
can you please demonstrate how you achieved the installation process and authentication? 

thank you in advance

**Comment by osiset** [comment]
This is more a discussion based thing, I haven't had time to push out a wiki entry yet for this. See the #601 for some tips.

**Comment by darrynten** [comment]
@kouloughli-hemza here's an example frontend I made with Vue - https://github.com/UnicornGlobal/laravel-shopify-vue
