### ISSUE TITLE
Problem with sending get request with parameters

### ISSUE THREAD

**Issue by syncmaster** [osiset/laravel-shopify#616]
Hello I have a problem with sending a GET parameters to the shopify api and get the list of orders. 
So I will explain it with more details.
If I send a request like this 
`$response = $shop->api()->rest('GET', '/admin/orders.json')['body'];` 
everything is work properly and I get all paid orders, but I want to receive a list of all orders from the shop so I need to send a parameter `status=any` to the request to receive all orders.
but I don't know how to send parameter to the request 
I tried: 
`$response = $shop->api()->rest('GET', '/admin/orders.json', ['query' => 'status=any'])['body'];` 
`$response = $shop->api()->rest('GET', '/admin/orders.json', ['query' => ['status' => 'any']])['body'];` 
`$response = $shop->api()->rest('GET', '/admin/orders.json', ['query' => 'status:any'])['body'];` 
without success, I want a example how to send a one or more GET parameters to the shopify api 
Thanks in advance.

**Comment by osiset** [comment]
Your second example is the correct one...

`$response = $shop->api()->rest('GET', '/admin/orders.json', ['query' => ['status' => 'any']])['body'];`

Debugging the request from Guzzle, it's forming this for a URL:

```
*  SSL certificate verify ok.
> GET /admin/api/unstable/orders.json?status=any HTTP/1.1
Host: wulfare.myshopify.com
```

So its correctly sending this, there is nothing on my end to do.
