### ISSUE TITLE
Script Tag not getting created

### ISSUE THREAD

**Issue by alexWaterfront** [osiset/laravel-shopify#617]
Hi, 

I have set everything up and working fine except the script tags. I have put the correct src and followed through the instructions but it just doesn't seem to create one. Tried checking at the jobs and looks like they are not even running. Can you please guide me where i might be wrong?

'scripttags' => [
        [
            'src' => env('SHOPIFY_SCRIPTTAG_1_SRC', 'https://sandbox.waterfront.digital/js/usp_bar.js'),
            'event' => env('SHOPIFY_SCRIPTTAG_1_EVENT', 'onload'),
            'display_scope' => env('SHOPIFY_SCRIPTTAG_1_DISPLAY_SCOPE', 'online_store')
        ],
    ],

*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

For the script to get dispatched :)

## Current Behavior

The script isn't getting created i am checking the shopify api using insomnia tool 

## Failure Information

The script isn't getting created i am checking the shopify api using insomnia tool 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Populate the script tags with the necessary information as above
2. Load the app brwose around its pages
3. Script not installed

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: latest one
* Laravel Version: 8.13.0
* PHP Version: 7.4 (ea-php74) 
* Using a toolset (Docker, Laradock, Vagrant, etc.): No

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by osiset** [comment]
How do you know the jobs are not running, are you using Laravel Queue?

**Comment by alexWaterfront** [comment]
Yes and i also don't see the script getting created. I am not sure if i have to do anything more than populating the script tags in the shopify app config

**Comment by osiset** [comment]
Default is for the jobs to be sent to the queue, not run instantly. I'm not sure what happens if you're not running something to process the jobs. If you change the config to make it run instantly, via inline = true then see if it works
________________________________

**Comment by alexWaterfront** [comment]
I changed it and no it doesn't work. How can i process the queue for the script tags to be send, all i want is for a script tag to get created on app install.

**Comment by osiset** [comment]
@alexWaterfront I need logs of the error to find out why it failed for you.

**Comment by osiset** [comment]
Closing for lack of info, reopen if still an issue.
