### ISSUE TITLE
Installed APP on store and redirecting on page getting the AUTH issue

### ISSUE THREAD

**Issue by princejassi** [osiset/laravel-shopify#618]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Click on any page after app installed it will not show the login page again.

## Current Behavior

APP is successfully installed the first time it is showing the user id. if we have refresh/redirect to any other page AUTH user id is not showing and redirect to the Shopify login page. let me share the screenshots:

Step1: http://prntscr.com/vmueum

Step2: http://prntscr.com/vmuhn7

Step3: http://prntscr.com/vmuieh

Please check and let me know the solutions for this.

Thanks

**Comment by masix** [comment]
Can you share with as your routes ?

**Comment by princejassi** [comment]
@masix please check the router file code.

`<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app.home');
})->middleware(['auth.shopify'])->name('home');

Route::get('changeSettings', 'UserController@changeSettings')->name('changeSettings');
Route::get('manageCredentials', function () {
    return view('app.manage-credentials');
})->name('manageCredentials');

Route::get('thank-you', function () {
    return view('app.thank-you');
})->name('thank-you');

Route::get('cancelled', function () {
    return view('app.cancelled');
})->name('cancelled');

Route::get('failed', function () {
    return view('app.failed');
})->name('failed');

Route::post('manageCredentials', 'UserController@manageCredentials')->name('manageCredentials');
Route::get('orderHistory', 'UserController@orderHistory')->name('orderHistory');
Route::post('paymentSuccess', 'DashboardController@paymentSuccess')->name('paymentSuccess');

Route::get('getOrderDetails', 'DashboardController@getOrderDetails')->name('getOrderDetails');
Route::get('getOrders', 'DashboardController@getOrders')->name("getOrders");
Route::get('paygopay', 'DashboardController@paygopay')->name("paygopay");
Route::get('testmail', 'MailtestController@testmail')->name('testmail');
`

Please check and let me know if you need anything else.

Thanks

**Comment by JohnMaple** [comment]
local.ERROR: Unknown error {"userId":11,"exception":"[object] (Osiset\\ShopifyApp\\Exceptions\\ApiException(code: 0): Unknown error at /var/www/shopify-tracking-app/backend/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php:434)
[stacktrace]
#0 /var/www/shopify-tracking-app/backend/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php(354): Osiset\\ShopifyApp\\Services\\ApiHelper->doRequest(Object(Osiset\\ShopifyApp\\Objects\\Enums\\ApiMethod), '/admin/webhooks...', Array)
#1 /var/www/shopify-tracking-app/backend/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/CreateWebhooks.php(80): Osiset\\ShopifyApp\\Services\\ApiHelper->createWebhook(Array)
#2 [internal function]: Osiset\\ShopifyApp\\Actions\\CreateWebhooks->__invoke(Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#3 /var/www/shopify-tracking-app/backend/vendor/osiset/laravel-shopify/src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php(68): call_user_func(Object(Osiset\\ShopifyApp\\Actions\\CreateWebhooks), Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#4 /var/www/shopify-tracking-app/backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\\ShopifyApp\\Messaging\\Jobs\\WebhookInstaller->handle()
#5 /var/www/shopify-tracking-app/backend/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/shopify-tracking-app/backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))

Q:How to solve this problem？

**Comment by osiset** [comment]
#522
