### ISSUE TITLE
Shopify app not working in safari

### ISSUE THREAD

**Issue by RuchitaCrawl** [osiset/laravel-shopify#622]
Hi @osiset  ,
Thanks for this awesome package.

My app is working fine in chrome and firefox, but it's not working in safari even if i enable or disable cookies.

It continous redirecting me to login page or return 419 status.

**Excepted Behaviour**
If browser is facing cookie issue then app should not be load and user should get the message on app listings page "This app can't be load due to an issue with browser cookies"

PHP Version: 7.3
Package Version: "osiset/laravel-shopify": "^12.1"
Laravel Version: 7.29

Thank You :)

**Comment by osiset** [comment]
#522
