### ISSUE TITLE
CarrierService callback and auth.shopify middleware don't play together

### ISSUE THREAD

**Issue by mediastrategi-main** [osiset/laravel-shopify#625]
## Expected Behavior

When Shopify calls my callback, the middleware should fill in with the correct shop for the user.

## Current Behavior

Right now it fails with MissingShopDomainException.

## Failure Information

The information is in the header, but auth.shopify does not look at the correct header information.
The headers Shopify sends looks like this for me (in the callback):
`array (
  'host' => 
  array (
    0 => 'my-app-server.com',
  ),
  'user-agent' => 
  array (
    0 => 'Ruby',
  ),
  'content-length' => 
  array (
    0 => '766',
  ),
  'accept' => 
  array (
    0 => '*/*',
  ),
  'accept-encoding' => 
  array (
    0 => 'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
  ),
  'content-type' => 
  array (
    0 => 'application/json',
  ),
  'x-forwarded-for' => 
  array (
    0 => '**.***.***.*',
  ),
  'x-forwarded-proto' => 
  array (
    0 => 'https',
  ),
  'x-shopify-hmac-sha256' => 
  array (
    0 => 'hmac-key',
  ),
  'x-shopify-shop-domain' => 
  array (
    0 => 'my-dev-store.myshopify.com',
  ),
  'x-shopify-timeout' => 
  array (
    0 => '10000',
  ),
)  `

But in the code in 'auth.shopify' it looks for this:
`$shop = $request->header('X-Shop-Domain');`

Basically all the header lookups in auth.shopify are wrong here? Does it differ when shopify uses the callback?
This callback is for the CarrierService rest-api which fetches the shipping rates I have available.

I tried the JWT auth.token middleware but I'm not sure I understand it correctly. Either way shopify doesn't seem to send me any token for it to work. I assume I might need to get JWT to work to also get my app to work later on? I have allowed shopify cookies in my browser so I can work on it with the auth.shopify middleware.
Not sure JWT works in this scenario either?

The app uses the TALL-stack (Tailwindcss, Alpine.js, Laravel, Livewire) so I don't really have any frontend javascript framework, it's all backend.

### Steps to Reproduce

1. Setup CarrierService and point to an API-endpoint of your choice under routes/api.php
2. Set 'auth.shopify' as middleware for the API-endpoint in your app.
3. Try to load the checkout in your dev store. You won't get any results from your callback since it fails as described here.

### Context

* Package Version: v15.0.0
* Laravel Version: v8.16.1
* PHP Version: 7.4.12
* Using a toolset (Docker, Laradock, Vagrant, etc.): just 'artisan serve' and ngrok

### Failure Logs

Nothing more than the exception because it misses the piece in the header which actually contains it.

edit: Updated version to v15.0.0 which released yesterday. Still the same issue though. And updated laravel version.

**Comment by mediastrategi-main** [comment]
Logic tells me auth.* should not be used for callbacks. So I've removed it and am manually fetching the correct header for the shopify domain. Then I use the ShopSession to have the correct shop logged in so I can fetch right data.

Is this the proper way to do it? What about all other callbacks from Shopify to my app?

**Comment by osiset** [comment]
You wouldn't use middleware for the carrier service or anything frontend facing for API. Get the shop info from headers, and do what you need this way.
