### ISSUE TITLE
How to retrieve products from multiple collection with 1 REST API call

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#626]
Currently I'm using this code to retrieve products from single collections:

`   $requests = $shop->api()->rest('GET', '/admin/api/2020-01/products.json', ['limit' => 250, 'fields' => 'id,title,variants,image,options,handle', 'collection_id' => $catalog->collection]);`

but the problem is because I need now to get products from multiple collections so I have more collections IDs... I also have multiple vendors and multiple product_type data

Any way to filter in the request?

**Comment by osiset** [comment]
If you need to get from multiple collections, then you'd need to make more API calls. You may want to look into graph and see if something can you there. The underlying API package simply passes data to Shopify's endpoints, it doesn't do any filtering and what not.
