### ISSUE TITLE
Library have issues

### ISSUE THREAD

**Issue by kantsverma** [osiset/laravel-shopify#628]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior
Osiset\ShopifyApp\Exceptions\MissingShopDomainException:  in file /home/development/public_html/generosity/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php on line 341
Please describe the behavior you are expecting.
Its not rendering the app to store page return the error 
## Current Behavior

Please describe the current behavior?
I try to debug it i think i solved it by making some changes in Middleware/AuthShopify.php  but that does not fix it

## Failure Information

Please help provide information about the failure if this is a bug.
In case of public access any public route it return error 
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1 Install Laravel 
2. Step 2 Install Lib and by following all steps mentioned in install tab 
3. Install app and app successfully working and redirect to app  
4) If we hit the Laravel url manually in other browser where i am not login to app. it through error 
ERROR : Osiset\ShopifyApp\Exceptions\MissingShopDomainException:  in file /home/development/public_html/generosity/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php on line 341
Then i debug it and do below steps but did not work , It successfully redirect the error screen to login page but that is not solution.

( * )  In case of not verifyHmac it go to class AuthShopify to call method handle
( * ) Where this is called return $this->handleBadVerification($request, $domain);
( * ) Inside method handleBadVerification() if auth is empty so it call class MissingShopDomainException and this class is empty and nothing handled inside class
if ($domain->isNull()) {
// We have no idea of knowing who this is, this should not happen
throw new MissingShopDomainException();
}
( * ) Please replace below snippets inside method handleBadVerification() and it will work fine
if ($domain->isNull()) {
// We have no idea of knowing who this is, this should not happen
return redirect()->route('login'); // fix the bugs to rediec to login page if auth emtpty
//throw new MissingShopDomainException();
}

### Context
Mainly issues is with below method    throw new MissingShopDomainException();

   private function handleBadVerification(Request $request, ShopDomainValue $domain)
    {
        if ($domain->isNull()) {
            // We have no idea of knowing who this is, this should not happen
            throw new MissingShopDomainException();
        }

        // Set the return-to path so we can redirect after successful authentication
        Session::put('return_to', $request->fullUrl());

        // Kill off anything to do with the session
        $this->shopSession->forget();

        // Mis-match of shops
        return Redirect::route(
            $this->getConfig('route_names.authenticate.oauth'),
            ['shop' => $domain->toNative()]
        );
    }

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v15.0.0
* Laravel Version: 8.16.1
* PHP Version: 7
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs
Osiset\ShopifyApp\Exceptions\MissingShopDomainException:  in file /home/development/public_html/generosity/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php on line 341

#0 /home/development/public_html/generosity/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(78): Osiset\ShopifyApp\Http\Middleware\AuthShopify->handleBadVerification(Object(Illuminate\Http\Request), Object(Osiset\ShopifyApp\Objects\Values\NullShopDomain))
#1 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Osiset\ShopifyApp\Http\Middleware\AuthShopify->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#10 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#19 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#22 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/development/public_html/generosity/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/development/public_html/generosity/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /home/development/public_html/generosity/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#37 /home/development/public_html/generosity/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#38 /home/development/public_html/generosity/index.php(21): require_once('/home/developme...')
#39 {main}
Please include any relevant log snippets or files here.

**Comment by kantsverma** [comment]
I also try it with Laravel 7.3 but facing the same issues. 

While configuration and migrating  face below error 

$ php artisan vendor:publish --tag=shopify-migrations && php artisan migrate
Unable to locate publishable resources.
Publishing complete.

**Comment by osiset** [comment]
Its not meant to be accessed directly from the browser, you would access it from the store's app section.

**Comment by kantsverma** [comment]
> Its not meant to be accessed directly from the browser, you would access it from the store's app section.

Its working fine from store app but how i can render the changes to store theme ?

**Comment by osiset** [comment]
@kantsverma Im not sure I understand what you're talking about, can you explain what youre trying to accomplish.
