### ISSUE TITLE
ANNUAL interval gives exception for recurring plan, EVERY_30_DAYS works

### ISSUE THREAD

**Issue by jithinjoyj4** [osiset/laravel-shopify#633]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Plan with ANNUAL interval working without any exception like EVERY_30_DAYS interval 
## Current Behavior

ANNUAL interval gives exception for recurring plan, plan with interval EVERY_30_DAYS is working without any exceptions
## Failure Information

![image_2020_12_01T11_07_17_644Z](https://user-images.githubusercontent.com/57803136/101171549-ecf4e000-3665-11eb-9aad-62632c3b7261.png)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v13.1
* Laravel Version: v8.0
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.): aws server

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Enmaboya** [comment]
> _For bug reporting only! If you're posting a feature request or discussion, please ignore._
> 
> ## Expected Behavior
> Plan with ANNUAL interval working without any exception like EVERY_30_DAYS interval
> 
> ## Current Behavior
> ANNUAL interval gives exception for recurring plan, plan with interval EVERY_30_DAYS is working without any exceptions
> 
> ## Failure Information
> ![image_2020_12_01T11_07_17_644Z](https://user-images.githubusercontent.com/57803136/101171549-ecf4e000-3665-11eb-9aad-62632c3b7261.png)
> 
> ### Context
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> 
> * Package Version: v13.1
> * Laravel Version: v8.0
> * PHP Version: vX.Y.Z
> * Using a toolset (Docker, Laradock, Vagrant, etc.): aws server
> 
> ### Failure Logs
> Please include any relevant log snippets or files here.

in config/shopify-app.php
change api_version to 2020-10

**Comment by khiconit** [comment]
Same issue

**Comment by sddocs** [comment]
> Same issue

As I wrote above.
The problem is in the settings of your application, not the package.

in config/shopify-app.php
change api_version to 2020-10

You may also need to change the version of the api you are using in the shopify application.

**Comment by Enmaboya** [comment]
> Same issue

As I wrote above.
The problem is in the settings of your application, not the package.

in config/shopify-app.php
change api_version to 2020-10

You may also need to change the version of the api you are using in the shopify application.

**Comment by jithinjoyj4** [comment]
@Enmaboya thanks for the replay, i haven't tried your solution yet, the app live with monthly plan but i'll work on it soon for annual plan and other updations.
@khiconit did you fix the issue by changing api_version please comment your result

**Comment by osiset** [comment]
Thanks for responding with your fix, in your case yes, its the API version :) reopen if still an issue.
