### ISSUE TITLE
[Question] I have created plan I want to implement on products

### ISSUE THREAD

**Issue by MGhufranKhalil** [osiset/laravel-shopify#634]
### [Question] I have created plan I want to implement on products

I have created some plans and want to implement them on products and charge against the plans one time or recurring. 
please let me know if I can do this process, if yes then help me how can I do that.

TIA

**Comment by MGhufranKhalil** [comment]
@osiset @Kyon147 @lucasmichot  please help

**Comment by osiset** [comment]
@MGhufranKhalil Move this to the new discussions tab. Please dont call out maintainers unless absolutely needed.
