### ISSUE TITLE
Can't download this repo for Shopify laravel app development

### ISSUE THREAD

**Issue by zek7rom** [osiset/laravel-shopify#636]
## Expected Behavior

After I run the command "composer require osiset/laravel-shopify, I'm expecting this package to be downloaded and  installed within my project directory.

## Current Behavior

When I run this command I get this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - funeralzone/valueobjects 0.4.5 requires php ^7.1.0 -> your php version (8.0.0) does not satisfy that requirement.
    - osiset/laravel-shopify v15.1.0 requires funeralzone/valueobjects ^0.4.5 -> satisfiable by funeralzone/valueobjects[0.4.5].
    - Root composer.json requires osiset/laravel-shopify ^15.1 -> satisfiable by osiset/laravel-shopify[v15.1.0].

## Failure Information

Please help provide information about the failure if this is a bug.

* Package Version: v15.1.0
* Laravel Version: vX8.12
* PHP Version: v8.0.0
* Using a toolset (Docker, Laradock, Vagrant, etc.):

**Comment by zek7rom** [comment]
I'm going to close this because I found a solution

**Comment by osiset** [comment]
PHP 8 is not supported yet in testing. Due to other packages we pull in, namely the value objects. Theres a open PR.

**Comment by djnorrisdev** [comment]
> I'm going to close this because I found a solution

@zek7rom It would have been helpful if you put your workaround here so others like myself could solve this issue without rolling back the php version.
