### ISSUE TITLE
11.3 version problem with yearly plans

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#637]
Hi,

I'm using 11.3 version and i create a yearly plan - add interval field in database and put value ANNUAL

I got few subscibers but i got info fromShopify team that plan is not yearly its monthly.

I need to know from which version is support for annual billing plans?

How i can convert now my subscribers from monthly to annual plan.

To which version i need to upgrade?

Its a big problem now for me

Please help. Its urgent because i will start receiving negative reviews.

* Package Version: v11.3
* Laravel Version: v5.8
* PHP Version: v7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by APdevelopments** [comment]
ANy ideas how to solve that problem? From which version there is support for ANNUAL plans?

**Comment by osiset** [comment]
v12.1.0 introduced annual support from a contributor.

**Comment by APdevelopments** [comment]
@osiset What about ONE-TIME payments? Also, support from that version?
