### ISSUE TITLE
osiset/laravel-shopify issue with laravel 8.17.2

### ISSUE THREAD

**Issue by harshadcmr** [osiset/laravel-shopify#638]
For developing standalone  plugin with **Laravel 8.17.2**

## Expected Behavior
Redirection to welcome template

## Current Behavior

 The application redirecting to 'http://appdomain/authenticate/oauth?shop=shopdomain'.
 I think the below method throw new MissingShopDomainException();

private function handleBadVerification(Request $request, ShopDomainValue $domain)
{
if ($domain->isNull()) {
// We have no idea of knowing who this is, this should not happen
throw new MissingShopDomainException();
}

    // Set the return-to path so we can redirect after successful authentication
    Session::put('return_to', $request->fullUrl());

    // Kill off anything to do with the session
    $this->shopSession->forget();

    // Mis-match of shops
    return Redirect::route(
        $this->getConfig('route_names.authenticate.oauth'),
        ['shop' => $domain->toNative()]
    );
}  

 
### Context

* Package Version: current version
* Laravel Version: 8.17
* PHP Version: 7.4

**Comment by zek7rom** [comment]
Yeah mines is throwing the same error, the weirdest thing is that I managed to get it up and running on my dev store but when I ran my project on the localhost I got this error 
![Screenshot 2020-12-15 020045](https://user-images.githubusercontent.com/22615697/102181970-759b2980-3e79-11eb-8034-7c0d447094c0.png)

![Screenshot 2020-12-15 020045](https://user-images.githubusercontent.com/22615697/102181945-6b792b00-3e79-11eb-8bf6-801df2f6f3d8.png)

Yeah I'm not sure whats going on, I hope we get a solution soon

**Comment by ecartchat** [comment]
> For developing standalone plugin with **Laravel 8.17.2**
> 
> ## Expected Behavior
> Redirection to welcome template
> 
> ## Current Behavior
> The application redirecting to 'http://appdomain/authenticate/oauth?shop=shopdomain'.
> I think the below method throw new MissingShopDomainException();
> 
> private function handleBadVerification(Request $request, ShopDomainValue $domain)
> {
> if ($domain->isNull()) {
> // We have no idea of knowing who this is, this should not happen
> throw new MissingShopDomainException();
> }
> 
> ```
> // Set the return-to path so we can redirect after successful authentication
> Session::put('return_to', $request->fullUrl());
> 
> // Kill off anything to do with the session
> $this->shopSession->forget();
> 
> // Mis-match of shops
> return Redirect::route(
>     $this->getConfig('route_names.authenticate.oauth'),
>     ['shop' => $domain->toNative()]
> );
> ```
> 
> }
> 
> ### Context
> * Package Version: current version
> * Laravel Version: 8.17
> * PHP Version: 7.4

We also facing the same issue now. It would be great if anyone can answer the  solution

**Comment by harshadcmr** [comment]
> For developing standalone plugin with **Laravel 8.17.2**
> 
> ## Expected Behavior
> Redirection to welcome template
> 
> ## Current Behavior
> The application redirecting to 'http://appdomain/authenticate/oauth?shop=shopdomain'.
> I think the below method throw new MissingShopDomainException();
> 
> private function handleBadVerification(Request $request, ShopDomainValue $domain)
> {
> if ($domain->isNull()) {
> // We have no idea of knowing who this is, this should not happen
> throw new MissingShopDomainException();
> }
> 
> ```
> // Set the return-to path so we can redirect after successful authentication
> Session::put('return_to', $request->fullUrl());
> 
> // Kill off anything to do with the session
> $this->shopSession->forget();
> 
> // Mis-match of shops
> return Redirect::route(
>     $this->getConfig('route_names.authenticate.oauth'),
>     ['shop' => $domain->toNative()]
> );
> ```
> 
> }
> 
> ### Context
> * Package Version: current version
> * Laravel Version: 8.17
> * PHP Version: 7.4


Issue solved by replacing misplaced .htaccess file. 
Please suggest for the development of Shopify non-embedded applications using osiset library
