### ISSUE TITLE
Error in documentation proxies htaccess

### ISSUE THREAD

**Issue by andthink** [osiset/laravel-shopify#647]
When download liquid file problem happens in app proxy i tried the fix in htaccess with

```
# Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule !^/?myproxy* ^ %1 [L,R=301]
```

as stated in the wiki

## Expected Behavior

The website gives http response 200 and the proxy app returns my content

## Current Behavior

The apache webserver gives a 500 error with log showing

`/var/www/html/public/.htaccess: RewriteRule: bad flag delimiters`

## Failure Information

Documentation error

### Steps to Reproduce

Just setup an apache server and paste the wiki rewrite rule in its htaccess

### Context

* Server version: Apache/2.4.6 (CentOS)
* Laravel Version: 8
* PHP Version: 7.2
* Using a toolset (Docker):

### Failure Logs

`/var/www/html/public/.htaccess: RewriteRule: bad flag delimiters`

**Comment by osiset** [comment]
Resolved.

**Comment by sandeshpaudyal** [comment]
I'm also getting this issue. Can anyone let me know how can I resolve it?

**Comment by osiset** [comment]
I resolved the syntax error for htaccess. Downloading is not a package issue.
