### ISSUE TITLE
App Not redirected to authenticate

### ISSUE THREAD

**Issue by sandeeppangeni** [osiset/laravel-shopify#659]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I have set up app to a domain : https://domainname.cartbrain.net/
and give a redirection urI with : https://domainname.cartbrain.net/authenticate

## Current Behavior

When I try to install the App, it is redirected to domain with hmac and timestamp with error message
It appears you don't have
permission to access this page.
403 Error. Forbidden.

### Steps to Reproduce
- Install the laravel
- And followed all the step according to wiki

**Comment by osiset** [comment]
Please show a screenshot. This sounds like something from Shopify not the package.

**Comment by sandeeppangeni** [comment]
![image](https://user-images.githubusercontent.com/37801127/105121435-36a56700-5afc-11eb-9d93-f8665416ff41.png)

![image](https://user-images.githubusercontent.com/37801127/105122068-a0724080-5afd-11eb-961f-dcd77334c6a9.png)

**Comment by litalboa** [comment]
I have the same issue

**Comment by NESTEROVILYASERGEEVICH** [comment]
I have the same issues with installation.

**Comment by osiset** [comment]
The only 403 error in the library comes from JWT implementation. If you're not using JWT, then this is a server issue. @sandeeppangeni can you confirm what you're doing?

**Comment by LHongy** [comment]
@osiset , Hello, I change my middleware from 'auth.shopify' to 'auth.token' to use the JWT implementation. 
Now when I try to install the app on a new store, its not redirecting to the install page, it redirects to:

https://example.myshopify.com/admin/apps/c8dfgdfg0813ff9db9585c7116057764/?hmac=0ecb20543b8dfgdfg15fa7651a82f8b2d1cbdfsfsdf2s9effc5a&shop=example.myshopify.com&timestamp=1611737799,

and the pages says 'no page at this address'. Any help please?

**Comment by nguyentvnhat** [comment]
@sandeeppangeni  It's the same your issue right now

**Comment by nguyentvnhat** [comment]
hi @sandeeppangeni please double-check the SHOPIFY_API_REDIRECT variable in the env. It should be https://domainname.cartbrain.net/authenticate

**Comment by pontifex** [comment]
For a while got a same issue. Solution in my case was simple, I just missed to add middleware ```auth.shopify``` on my "home" routing setting inside ```web.php``` file. Config after fix below:
```
Route::get('/', [ShopifyController::class, 'index'])->middleware(['auth.shopify'])->name('home');
```

**Comment by ricwong** [comment]
I have the same issue, followed all steps and authenticate page is not found

**Comment by mudassirali007** [comment]
I have the same issue, the app is redirecting and say on same site cookie issue, Page cannot be loaded
![image](https://user-images.githubusercontent.com/54500326/122179920-64bb8700-cea1-11eb-8dec-174a903cf983.png)
