### ISSUE TITLE
[Question] Correct way of creating link to other app sub-pages

### ISSUE THREAD

**Issue by rajaneeshdwivedi** [osiset/laravel-shopify#661]
Not sure if this is a bug or a lack of understanding on my part, but I have an app with multiple pages each with their own URL accessed through a sidebar menu:
```
https://mydomain.com/appname/
https://mydomain.com/appname/A
https://mydomain.com/appname/B
```

My menu links to the other pages like this: 
`https://mydomain.com/appname/B?shop=storename.myshopify.com`
and I have all three URLs in the Allowed Redirection URL(s) setting of the app.

Everything works fine and when I click one of the other links it loads within the shopify admin's app iframe very quickly. But a second click redirects and reloads the entire page through the auth, which it does properly, but shouldn't be reauthenticating every other request.

My question is: should I be creating the link differently, maybe supplying hmac/session/timestamp request params manually with the link, or is there something else I'm doing wrong, or is this a bug? 

I thought this might be related to the [ongoing ITP issue](https://github.com/osiset/laravel-shopify/issues/522) but I'm seeing the same behaviour on Chrome and Safari.

## Expected Behavior

Would expect the new page to load each request without reauthenticating

## Current Behavior

The request is reauthenticating every other request

## Failure Information

When logging the incoming params at each request they alternate between:
 (
  'hmac' => '7f1099**********************************************************************45dd1',
  'locale' => 'en',
  'new_design_language' => 'true',
  'session' => 'a34cd********************************************************************7b499',
  'shop' => 'shopname.myshopify.com',
  'timestamp' => '1611224227',
)  

and an empty array
(
)

### Steps to Reproduce

1. Start with basic installation
2. Create routes like so:
```
Route::group(['prefix' => 'appname', 'middleware'=>'auth.shopify'], function() {
	Route::get('/', 'StoreController@index')->name('home');
	Route::get('A', 'StoreController@A');
	Route::get('B', 'StoreController@B');
});
```
3. Add links in each of the three corresponding views to the other views:
```
<a href="/appname?shop={{$shop->name}}">Home</a>
<a href="/appname/A?shop={{$shop->name}}">A</a>
<a href="/appname/B?shop={{$shop->name}}">B</a>
```

### Context

* Package Version: v15.1.1
* Laravel Version: v8.12.3
* PHP Version: v7.3.23
* Using a toolset: local apache

**Comment by osiset** [comment]
Most likely the ITP issues yes which will have a fix shortly.

**Comment by osiset** [comment]
#522 in my testing of this report, thanks.

**Comment by Abdelrahman-Medhat** [comment]
Find any solution ?
