### ISSUE TITLE
cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#669]
I need to fetch all products from stores.
I write a code that fetches all products but sometimes I got the error: true and message:

**cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)**

Why? And How to solve that problem?
Again, it happens sometimes not all the time...

**Comment by osiset** [comment]
No, this could be a number of reasons this happens, but its not specific to the package, this is a network issue. You may need to pass custom Guzzle arguments to have a more verbose debug output show up.

**Comment by APdevelopments** [comment]
Can you please help me? How to pass custom Guzzle arguments? How to increase timeout seconds?

**Comment by osiset** [comment]
Edit `shopify-app.php` config, look for `api_init`, and for the value you'd do something like:

```
use Osiset\BasicShopifyAPI\Options;
use Osiset\BasicShopifyAPI\BasicShopifyAPI;
use function Osiset\ShopifyApp\getShopifyConfig;

// ....

'api_init' => function (Options $opts) {
            $ts = getShopifyConfig('api_time_store');
            $ls = getShopifyConfig('api_limit_store');
            $sd = getShopifyConfig('api_deferrer');

            // Custom Guzzle options
            $opts->setGuzzleOptions(['connect_timeout' => 30.0]);
           
            return new BasicShopifyAPI(
                $opts,
                new $ts(),
                new $ls(),
                new $sd()
            );
},
```

**Comment by osiset** [comment]
Given this is a network issue, I will close for now unless there's something concrete to point to this package or the underlying API package. Thanks!

**Comment by myw-ben** [comment]
I am facing this same issue on one of my installs. It basically tracks back to the Guzzle timeout being too short.

In "basic-shopify-api/src/Osiset/BasicShopifyAPI/Options.php" the "timeout" option in the GuzzleOptions is set to 10 seconds. This timeout just needs updating a little.

To test the theory, I have manually altered that file so the timeout is now 90 seconds, and the error disappears. 

Not quite sure how to alter this for production, as the code listed above with the "api_init" had no impact.

**Comment by myw-ben** [comment]
For anyone facing this issue, a modified version of the code above seems to do the trick:

```
use Osiset\BasicShopifyAPI\Options;
use Osiset\BasicShopifyAPI\BasicShopifyAPI;

'api_init' => function (Options $opts) {
        $ts = config('shopify-app.api_time_store');
        $ls = config('shopify-app.api_limit_store');
        $sd = config('shopify-app.api_deferrer');

        // Custom Guzzle options
        $opts->setGuzzleOptions(['timeout' => 90.0]);
       
        return new BasicShopifyAPI(
            $opts,
            new $ts(),
            new $ls(),
            new $sd()
        );
    },
```

**Comment by APdevelopments** [comment]
Hi, Thank you very much!

Where to put this code? In controller? 

before class declare ?

**Comment by myw-ben** [comment]
> Hi, Thank you very much!
> 
> Where to put this code? In controller?
> 
> before class declare ?

You put it in the config/shopify-app.php file. The imports go at the top, then search for 'api_init' and. update with the code above

**Comment by mitulgolakiya** [comment]
@myw-ben Thank you for the solution. But while using this code with Laravel Jobs, it gives error,

`Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Clos
ure' is not allowed`

Is there any other solution to increase the timeout?

**Comment by ClaraLeigh** [comment]
@mitulgolakiya try creating a static function somewhere then doing something like this:
`    'api_init' => '\App\Providers\AppServiceProvider::shopifyApiClosure',`

**Comment by bretto36** [comment]
> @mitulgolakiya try creating a static function somewhere then doing something like this: ` 'api_init' => '\App\Providers\AppServiceProvider::shopifyApiClosure',`

Thanks @mitulgolakiya . 

Also nice to spot a fellow Gold Coaster in here

**Comment by aqsa3030** [comment]
hello, I'm using my own API which is place on my local server, and when i use the link i got this error ->
cURL error 28: Operation timed out after 30012 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:8000/api/posts1

**here is the code;**
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class TestController extends Controller
{

    function getApi(){

      $response= Http::get('http://localhost:8000/api/posts1');
      dd($response->()) ;
    }
}

**Comment by tbiinfotech** [comment]
After implementing all above mentioned feedback. I am still getting same error.
