### ISSUE TITLE
Update prices for current subscriptions

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#670]
My monthly subscription plan starts from $9.99 and I have many stores on that plan. How to change prices to affect all stores not only new installs...

If I simply change the price in the database to $11.99 it will affect all stores to start paying 11.99 or they will still pay?

How to change my price to current subscriptions?

**Comment by osiset** [comment]
You would need to present the existing stores with a prompt when they hit the homepage of your app to accept the new charge. You'd forward them to the billing plan route if they accept, where they will go through the standard process of accepting the plan.

**Comment by osiset** [comment]
Information above should help, feel free to open something in Discussions as well.
