### ISSUE TITLE
Osiset\ShopifyApp\Exceptions\MissingShopDomainException

### ISSUE THREAD

**Issue by tohir87** [osiset/laravel-shopify#672]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Current Behavior

Please describe the current behavior?
<img width="828" alt="Screenshot 2021-01-27 at 11 11 59" src="https://user-images.githubusercontent.com/7491611/105983363-881b9c00-6090-11eb-911e-6156e9801d4b.png">

## Failure Information

Can't access the login screen. Just cloned a new installation and having same problem. Please does anyone have an idea of what is wrong?

**Comment by osiset** [comment]
There is no longer a login screen. You need to access the app through the stores apps.

**Comment by tohir87** [comment]
Thank you
