### ISSUE TITLE
PERUSER vs OFFLINE auth

### ISSUE THREAD

**Issue by arvesolland** [osiset/laravel-shopify#684]
If I switch from OFFLINE to PERUSER, is there not a way to get and save a permanent access token for the store in addition to getting the individual users access token for the session? The offline token would be needed to perform the background jobs etc

The Shopify docs states that you could use both auth modes if applicable:
https://shopify.dev/concepts/about-apis/authentication#api-access-modes

But I'd assume this would mean the app would first have to get an offline token upon install and store that in the db, and then do another request to get the user based access token?

**Comment by osiset** [comment]
Currently theres no support for both at same time. I could change this so if no offline token exists, it forces the auth method to be offline (this will just assume its a first-time install), then, it'll fall back to the auth method you've set (per user).

I can put a patch in for this.

**Comment by osiset** [comment]
@arvesolland Are you sure this is not working? Ill have to run a physical test but:

```php
        // Access/grant mode
        $grantMode = $shop->hasOfflineAccess() ?
            AuthMode::fromNative(getShopifyConfig('api_grant_mode', $shop)) :
            AuthMode::OFFLINE();

        $return['url'] = $apiHelper->buildAuthUrl($grantMode, getShopifyConfig('api_scopes', $shop));
```

This is what builds the auth URL.

So if no offline access exists, it forces the mode to offline (assumes a new installation), which would get the offline token.

**Comment by osiset** [comment]
Actually I think I found the reason for this. The password initially is empty, not null. I'll account for this and run a unit test, push a patch, thanks!

**Comment by daluisgarcia** [comment]
How can I access to the OFFLINE token? I am building an API which will send the products info from a desktop app to the Shopify API and there is not any Shopify Auth process between. Actually I am getting this error when making a request using Laravel Http basic requests:

<pre><code>[API] Invalid API key or access token (unrecognized login or wrong password)</code></pre>

I searched for it and the problem may be I am not giving the auth token, but I dont know how to get it :( What do you recommend me to do?

**Comment by osiset** [comment]
If you're sending HTTP requests from a DESKTOP app to LARAVEL, then this is something custom you'll need to implement. You can send over whatever means to identify the shop.

Once you know the shop, then the offline token will be the password field in users table.

```php
$shop = User::where('name', '=', 'some shop.myshopify.com');
$shop->api->rest('GET', ....);
```
