### ISSUE TITLE
POS Support

### ISSUE THREAD

**Issue by ws-shirakawa** [osiset/laravel-shopify#685]
## Expected Behavior
I want to execute the API of the developed shopify app server from the embedded POS app of the extension of the shopify pos app.

## Current Behavior
I ran the API from the embedded POS app, but I get an authentication error.

## Failure Information
I'd like to provide some information, but the Shopify pos app doesn't see the javascript console, so I don't know the detailed error.

### Steps to Reproduce
1.  Set the API source on the application server. Here is the middleware to authenticate.
['middleware' => ['auth.shopify']]

2.  Shopify pos app extension embedded POS app management POS link added

3.  Launch shopify POS and add an embedded POS app

4. From the embedded app Call the API of.

5. Authentication cannot be cleared. Not executed.

It can be executed by executing it from the application screen of the store management screen. Is there POS-only authentication? I would be grateful if you could teach me how to set up authentication.

**Comment by osiset** [comment]
I have not tested this package with POS software. I currently have no time to investigate this at the moment.

**Comment by ws-shirakawa** [comment]
Thank you for your reply.
I understand.

**Comment by osiset** [comment]
Will keep open to address when I can

**Comment by darrynten** [comment]
I'll work on it if someone sends me a POS

**Comment by Kyon147** [comment]
POS does work with the app (I've been using it on a recent project) so closing this now.
