### ISSUE TITLE
Unable to verify signature

### ISSUE THREAD

**Issue by daluisgarcia** [osiset/laravel-shopify#687]
Hi to everyboy!! Yesterday I installed this repo into a laravel project I have from my job, I got a "same-site cookies" error I could not solve yesterday so I left it there. Today I came to see what I can do and acctually I am getting this error:

<pre><code>
Osiset\ShopifyApp\Exceptions\SignatureVerificationException
Unable to verify signature.
</code></pre>

Yesterday I did not get it, I could not find any solution so I come here asking for help :(

* Package Version: v16.0
* Laravel Version: v8
* PHP Version: v7.3
* Using Ngrok to simulate SSL certificate

**Comment by apurbajnu** [comment]
I am facing the same error

**Comment by osiset** [comment]
Are you getting the screen which asks you to enable cookies? Whats the flow of getting to this error?

**Comment by daluisgarcia** [comment]
The problem is solved for me now. I made the basic installation and the webhooks intallations too on laravel homestead and it worked pretty good. Seems to be a environment problem

**Comment by gbrits** [comment]
The above really doesn't help anyone with the same issue. I am getting this error, my Nginx is set up right and I'm still having no success.

**Comment by therealdb** [comment]
@gbrits Not sure if you figured it out - but that exception will throw is the hmac can't be verified - almost always this is that the api key/secret in your env don't match against the app in your Shopify partner account for that app. Hope that helps.

**Comment by richpeck** [comment]
Once you've updated the `.env` file with the correct API credentials, make sure you refresh the artisan cache (`php artisan optimize`) to make them readable. This was the problem I had.
