### ISSUE TITLE
shopify app not working on localhost (Osiset\ShopifyApp\Exceptions\MissingShopDomainException)

### ISSUE THREAD

**Issue by Ronak-maker** [osiset/laravel-shopify#688]
Hey, @osiset 
I have installed the fresh laravel 8 and laravel-shopify package for developing a Shopify app. I did the all setting according to the GitHub wiki. in Shopify, my app is working fine, but on localhost, I get the error "Osiset\ShopifyApp\Exceptions\MissingShopDomainException". can I run the app on localhost as well?

route.php file:- 
`Route::get('/','ProductsController@view')->middleware(['auth.shopify'])->name('home');`

products.blade.php file:-
```
@extends('shopify-app::layouts.default')

@section('content')
    <router-view></router-view>
@endsection

@section('scripts')
    @parent

    <script type="text/javascript">
        var AppBridge = window['app-bridge'];
        var actions = AppBridge.actions;
        var TitleBar = actions.TitleBar;
        var Button = actions.Button;
        var Redirect = actions.Redirect;
        var titleBarOptions = {
            title: 'Products',
        };
        var myTitleBar = TitleBar.create(app, titleBarOptions);
    </script>
@endsection
```
i have copied the defult.blade.php file in `views\vendor\shopify-app\layouts`.
I am on windows and working on xampp. please help

**Comment by osiset** [comment]
You need to be using a domain and an SSL. Local development, you can use something like Laradock and configure Nginx to use a self-signed cert, for something like laravel-test.local

**Comment by ncpope** [comment]
@Ronak-maker you can also simulate a shopify login event by adding the `shop` param to your url

`http://localhost?shop=demoshop.myshopify.com` and that will trigger the oauth process and login you in to the app.

**Comment by Ronak-maker** [comment]
Hey, thanks for the reply. I will try the above solution. thanks

**Comment by Ronak-maker** [comment]
> @Ronak-maker you can also simulate a shopify login event by adding the `shop` param to your url
> 
> `http://localhost?shop=demoshop.myshopify.com` will trigger the oauth process and log you in to the app.

I tried this solution, but it gives me a error like "Not Found" and "The requested URL was not found on this server." my URL is `https://localhost/authenticate/oauth?shop=license-service-manager.myshopify.com`

**Comment by osiset** [comment]
@Ronak-maker You can not use localhost like that. You'll need to setup a local domain and self sign a certificate.

See this page for more information which has some contributions from people on what to do: https://github.com/osiset/laravel-shopify/wiki/Developing-Locally

**Comment by Ronak-maker** [comment]
I already make a virtual URL for localhost, now I need a self-sign certificate. I am on windows pc. can you help me with how can I setup that, because I don't have any idea about Docker setup. in the documentation which method I have to follow the "Docker Method" or "Docker Setup (Basic)"?

**Comment by osiset** [comment]
Sorry I don't provide any support for helping setup app environments. There's many tutorials online for Laradock, Valet, etc.

**Comment by Ronak-maker** [comment]
okay, thank you for your support. I really appreciate that.

**Comment by m4mehdi** [comment]
You can use ngrok which could help you to creating https on localhost. It is very easy and useful

**Comment by osiset** [comment]
Ngrok however has given people a lot of issues with webhooks, but it's fine for display of app

**Comment by Ronak-maker** [comment]
i am already using ngrok for developing an app on Shopify, on localhost, it gives me an error 400 `Oauth error invalid_request: The redirect_uri is not whitelisted` .

**Comment by osiset** [comment]
Thats an issue with your app setup in partner dashboard. Please close if your issue is not code related which it seems not, this can be moved to Discussions tab for community help :)
