### ISSUE TITLE
Exception Missing or invalid client secret 

### ISSUE THREAD

**Issue by m4mehdi** [osiset/laravel-shopify#690]
*After Updating package and settin .env file with Secret Key and Api Key and running going to test shop error occur"Exception Missing or invalid client secret". Error occures in vendor\osiset\basic-shopify-api\src\Osiset\BasicShopifyAPI\Clients\Rest.php:67
and it means it doesn't know secret key. Considering problem of giving secret key from .env file I put it in 'client_secret' => $this->getOptions()->getApiSecret(), here manually but after running repeatedly testing goes to login page!!!!!!!

**Comment by osiset** [comment]
Template needs to be filled.

**Comment by m4mehdi** [comment]
Where should I fill it? I used a dev store for testing the code

**Comment by osiset** [comment]
See ISSUE_TEMPLATE.md in root of repo
