### ISSUE TITLE
Exception Missing or invalid client secret  with filled Template

### ISSUE THREAD

**Issue by m4mehdi** [osiset/laravel-shopify#691]
I filled the template. I added the secret key and app key. But the error Exception
Missing or invalid client secret was appeared. It means the secret key is not recognized. I put it write in Rest.PHP but it didn't work. 

<img width="830" alt="1" src="https://user-images.githubusercontent.com/18750432/107662286-6250e280-6c9f-11eb-8b2e-e44f362dafa8.png">

![image](https://user-images.githubusercontent.com/18750432/107661949-05552c80-6c9f-11eb-9e95-009e93265d9e.png)

**Comment by osiset** [comment]
The issue template needs to be filled out. Please edit your original post.

**Comment by m4mehdi** [comment]
OK
