### ISSUE TITLE
Exception Missing or invalid client secret 

### ISSUE THREAD

**Issue by m4mehdi** [osiset/laravel-shopify#692]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

I use the osiset as a template for App and I used https://github.com/Hujjat/Shopify-Laravel-App code which is based on your package. I added APP_KEY and APP_SECRET. Login page get the store name and sent the details of app to store. It is expected that after verifying the secret key in server the app would be installed in store and be saved in database. But after sending details to store the url https://www.serverdomain.com/authenticate?code=10e65c061d90300adee1b282f6979005&hmac=a806b411d04c4c9348a44fdcd63c479f8cc6979540059d45238b37d5de1a4c71&shop=shopname.myshopify.com&timestamp=1613070802
is returned with error  Exception Missing or invalid client secret. It means in Rest.php secret_key is not resolved. I write the string of secret key manually in this function on line 54 for temporary mitigating this step, but the server goes to login page again.  

Osiset\BasicShopifyAPI\Clients\Rest::requestAccess
vendor/osiset/basic-shopify-api/src/Osiset/BasicShopifyAPI/Clients/Rest.php:67

            'json' => [

                'client_id'     => $this->getOptions()->getApiKey(),

                'client_secret' => $this->getOptions()->getApiSecret(),

                'code'          => $code,

            ]

        ];

 

        try {

            $response = $this->getClient()->request(

                'POST',

                $url,

                $data

            );

        } catch (ClientException $e) {

            $body = json_decode($e->getResponse()->getBody()->getContents());

            throw new Exception($body->error_description);

        }

 

        return $this->toResponse($response->getBody());

    }

 

    /**

     * {@inheritDoc}

     */

    public function getAuthUrl($scopes, string $redirectUri, string $mode = 'offline'): string

    {

this is my web.php

Route::middleware(['auth.shopify'])->group(function () {

    Route::get('/', function () {
        $shop = Auth::user();

        $settings = Setting::where("shop_id", $shop->name)->first();

        return view('dashboard', compact('settings'));

    })->name('home');

    Route::get('wishlists', "WishlistController@index")->name('wishlists');

    Route::view('/products', 'products');
    Route::view('/customers', 'customers');
    Route::view('/settings', 'settings');

    Route::post('configureTheme', "SettingController@configureTheme");

});
I use domain with SSL and 
Osiset/laravel-shopify (v12.1.0)
Osiset/basic-shopify-api (v9.1.4): Extracting archive
Laravel Version: 7.30.4
PHP :7.4.14 
Using Apache and SSL, Mysql on linux server

<img width="830" alt="1" src="https://user-images.githubusercontent.com/18750432/107688688-2af12e80-6cbd-11eb-9038-dbae26d6cc5f.png">

**Comment by osiset** [comment]
Have you setup your env vars? Seen config/shopify-app.php for details

**Comment by m4mehdi** [comment]
I thought  it get the variable from .env file. I didn't put anything in this file 'api_key' => env('SHOPIFY_API_KEY', ''),

**Comment by osiset** [comment]
Yes, are the environment variables set? Sounds like they are not

**Comment by savchukoleksii** [comment]
@m4mehdi Also you can try to clear config cache using `artisan cache:clear` to apply env variables.

**Comment by ncpope** [comment]
@m4mehdi try filling in the .env settings. If you are still having issues post the relevant areas of your config/shopify-app.php && .env files here for people to help you.

**Comment by m4mehdi** [comment]
It solved the resolving but I still have issue in saving setting that is related to https://github.com/Hujjat/Shopify-Laravel-App for saving activated theme in database. I wrote an issue for this on the link.

**Comment by osiset** [comment]
@m4mehdi  If your original issue is solved, please close :)
