### ISSUE TITLE
The application drops out of the iframe with a fresh install

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#699]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Install App:

- go to partners.shopify.com->Apps->Click on AppName->Test your app->Select Store->Install App
- After click on Install App will a window appears with a list of different scopes and different install information
- After this -> press Install App btn
- After this Subscription page will be appear -> press on the Approve subscription button
- After this App will be installed and index page of my App should be appear in iframe.

## Current Behavior

Install App:

- go to partners.shopify.com->Apps->Click on AppName->Test your app->Select Store->Install App
- After click on Install App will a window appears with a list of different scopes and different install information
- After this -> press Install App btn
- After this Subscription page will be appear -> press on the Approve subscription button -> this redirect me to the index page of my App in the same tab without shopify menu(not in iframe).
But actually App is installed and working well when I open my app from my store-> Apps->My-App.

## Failure Information

As I understand, osiset package redirected to home page after billing/process, so Shopify should open it in Iframe.

I tried do force redirect it to the url of my App( https://' .$shopName . '/admin/apps/' .  strtolower(env('SHOPIFY_APP_NAME')) , but shopify app name can sometimes consist of application name and Id(my-app-7), something like: 
https://my-shop1.myshopify.com/admin/apps/my-app-7
so, I can't know exactly the url of my application

We are not use AppBridge on the our frontend part.

So, how can I fix this issue?

### Steps to Reproduce

- go to partners.shopify.com->Apps->Click on AppName->Test your app->Select Store->Install App
- After click on Install App will a window appears with a list of different scopes and different install information
- After this -> press Install App btn
- After this Subscription page will be appear -> press on the Approve subscription button -> this redirect me to the index page of my App in the same tab without shopify menu(not in iframe).

### Context

Package Version: v12.0.1
Laravel Version: v7.19.1
PHP Version: v7.2.24

**Comment by PhiloNL** [comment]
I've experienced the same but resolved it by enabling AppBridge. Just add the following to your blade file:

```
@if(\Osiset\ShopifyApp\getShopifyConfig('appbridge_enabled'))
    <script
        src="https://unpkg.com/@shopify/app-bridge{{ \Osiset\ShopifyApp\getShopifyConfig('appbridge_version') ? '@'.config('shopify-app.appbridge_version') : '' }}"></script>
    <script>
        var AppBridge = window['app-bridge'];
        var createApp = AppBridge.default;
        var app = createApp({
            apiKey: '{{ \Osiset\ShopifyApp\getShopifyConfig('api_key') }}',
            shopOrigin: '{{ Auth::user()->name }}',
            forceRedirect: true,
        });
    </script>

    @include('shopify-app::partials.flash_messages')
@endif
```

This will redirect back to Shopify when your application is not in a iframe.

**Comment by osiset** [comment]
AppBride is required as thats what handles redirecting it back into the iframe.

**Comment by sergeyantonuk** [comment]
Thank you guys!
I added those AppBridge code to my index page and this works as expected!
