### ISSUE TITLE
Webhook created after app installation does not synch with shopify

### ISSUE THREAD

**Issue by ahmet2106** [osiset/laravel-shopify#702]
Hey,

I just started a new project and tried to install a new webhook.
Installation with artisan, Job creation, everything fine.
But it newer synched with Shopify, so `CreateWebhooks ` Action is newer called.

I checked the Webhooks per API, which was empty.
Tried to write the [function](https://github.com/osiset/laravel-shopify/blob/d351c39edfc5398e7a7e7e5ef0a84ac4faa488fa/src/ShopifyApp/Actions/CreateWebhooks.php#L42) myself and calling it manually, then everything worked fine.

Maybe its only working while installation?

**Comment by osiset** [comment]
The function to write webhooks only fires when a full authentication happens. I've just tried this on my install and it fired correctly.

**Comment by ahmet2106** [comment]
Ok I just tried to analyze the code. Is it true that APP Url (Frame) has to be `/authenticate`?
This fires the Webhook.

**Comment by ahmet2106** [comment]
Solved after changing the Frame App URL to `/authenticate` instead of any other.
