### ISSUE TITLE
High memory usage & duration during app installation.

### ISSUE THREAD

**Issue by clydesantiago** [osiset/laravel-shopify#703]
## Expected Behavior

Optimize query for faster installation of App.

## Current Behavior

When you have 100,000+ users, installation process slows down because of redudant query.

### Steps to Reproduce

1. Use https://laravel.com/docs/8.x/telescope for monitoring requests.
2. Install Shopify App on you shopify
3. Inspect queries on Laravel Telescope

### Context

We are currently using ^12.0 of osiset/laravel-shopify. We also tried upgrading to latest version. The result is the same.

* Package Version: ^16.0
* Laravel Version: ^7.0
* PHP Version: 7.4
* Vagrant

### Failure Logs
Memory usage is 449 MB and Duration is 11 seconds because of query below. Note: this is 100,000+ users
<img width="944" alt="Screenshot at Feb 25 16-58-01" src="https://user-images.githubusercontent.com/31274021/109128720-b6bd8d00-778a-11eb-8a95-f2a63474d383.png">

![image](https://user-images.githubusercontent.com/31274021/109127670-a5c04c00-7789-11eb-827c-167885c3f346.png)

**Comment by clydesantiago** [comment]
@osiset pull request for the fix https://github.com/osiset/laravel-shopify/pull/705

**Comment by osiset** [comment]
Thank you, merged. Will push a patch.
