### ISSUE TITLE
Can any one tell me which code is executed for inserting records in user table when user install the app and record is inserting in user table.Which file execute this code?

### ISSUE THREAD

**Issue by Engr-Waleed-Saddique** [osiset/laravel-shopify#704]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by osiset** [comment]
Please use discussions, this is not an issue :)

But... Osiset\ShopifyApp\Storage\Commands\Shop::make is what inserts the shop. This invoked by Osiset\ShopifyApp\Actions\AuthorizeShop::__invoke which is invoked by Osiset\ShopifyApp\Traits\AuthController::oauth

Happens on a full oauth flow.

If you're looking to modify the data, you should use an observer.

**Comment by Engr-Waleed-Saddique** [comment]
I am very glad to see your email. Thank you  so much for your support and
reply.I spent many hours to find it but all in vain you solve my problem.
Again Thanks.
Regards,
Waleed Saddique
