### ISSUE TITLE
Is this package supported for annual billing? 

### ISSUE THREAD

**Issue by mohinpatwary** [osiset/laravel-shopify#708]
Is this package supported for annual billing? If not, I can run the Graphical API for annual billing. But how do I manage the database backend with the existing package billing system?

* Package Version: 15.1
* Laravel Version: 7.0.0
* PHP Version:  ^7.2.5|^8.0

**Comment by osiset** [comment]
Yes, annual billing is supported. Search code for "annual" you'll see things for PlanInterval::ANNUAL.

So you setup your plan in the database, and for the interval field, set it to "2".
