### ISSUE TITLE
Add script tag after installation but the old user didn't accept write_script_tag scope

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#710]
I need to add a script tag from my server but from the first version that scope wasn't in the config file...

SO I add it now, and the new user will accept 'write_script_tag' , but how to force old users to accept the same because they already installed app? 

They need to uninstall and install again or there is some more elegant way?

**Comment by osiset** [comment]
You could add a field called "upgraded" to your users table.

Either make a middleware, or do a check when they land on the homepage of your app.

Middleware method... you'd check if upgrade is not yet set, if it isent, then redirect to /authenticate with the shop query param.

Homepage method... display a notice to the customer that they need to click a button to upgrade permissions, if they click it, reidrect to /authenticate with the shop query param.

Force them back through the full authentication flow essentially.

Please move to discussions for any more questions.
