### ISSUE TITLE
facing 302 redirect error

### ISSUE THREAD

**Issue by Ali1094** [osiset/laravel-shopify#715]
![Screenshot from 2021-03-04 10-36-41](https://user-images.githubusercontent.com/80024169/109917161-a94a5a80-7cd6-11eb-88ab-4e8b3c005cba.png)
I'm getting this error when submitting a form using ajax or a normal request. It's working fine on '/' route but when I created a new route then this issue occurs. Please help me out...

**Comment by osiset** [comment]
Issue template required. Please reopen with template used.
