### ISSUE TITLE
Cancel an app subscription

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#716]
Does this package have some functionality for cancel subscription for the current store?
As Shopify documentation says: When a merchant uninstalls your app, their app subscription will automatically canceled.
But I need to cancel the subscription by the request of the merchant. For example, the user cancels the subscription by clicking on the button and continues to use the application.
Thank you in advance!

### Context

Package Version: v12.0.1
Laravel Version: v7.28.4
PHP Version: v7.2.24

**Comment by osiset** [comment]
Use discussions tab :)

```php
use Osiset\ShopifyApp\Actions\CancelCurrentPlan;

# ...

$cpa = resolve(CancelCurrentPlan::class);
$cancelled = $cpa($shop->getId());

if ($cancelled) {
    $shop->plan_id = null;
    $shop->save();
}
```

**Comment by sergeyantonuk** [comment]
Sorry, wrong tab.
Thank you for you help, and for great package!
