### ISSUE TITLE
Can I change wiki documents freely?

### ISSUE THREAD

**Issue by TanisukeGoro** [osiset/laravel-shopify#718]
I found mistakes in documents ([App Proxy](https://github.com/osiset/laravel-shopify/wiki/App-Proxies)).

```
### Proxy Controller

`php artisan make:controller AppProxy`

This will create a file `AppProxy.php` in `app/Http/Controllers`.

### Route Entry

Open `app/routes/web.php` and create a new GET entry to point to the newly created controller.

Route::get('/proxy', 'AppProxyController@index')->middleware('auth.proxy');
```

`php artisan make:controller AppProxy` command is generated `AppProxy` class, but  actually has been used `AppProxyController` class.
I think it is necessary to unify to either one.
Can I update the documents freely?
Is there a way to report before the change?

**Comment by osiset** [comment]
Yes you're able to change :)
