### ISSUE TITLE
Getting 302 error on form submit

### ISSUE THREAD

**Issue by Ali1094** [osiset/laravel-shopify#719]
![Screenshot from 2021-03-04 10-36-41 (1)](https://user-images.githubusercontent.com/80024169/110093008-1126a100-7dbc-11eb-95f1-365afdbf312d.png)
Please help me out. I'm getting 302 error when redirect to another route and submitting my form it gives 302 redirect error. But on '/' route everything would be fine. 
I'm using default.blade.php template located in vendor->shopify-app->layouts

![Screenshot from 2021-03-05 13-58-40](https://user-images.githubusercontent.com/80024169/110092561-8a71c400-7dbb-11eb-82ec-70461b655789.png)
![Screenshot from 2021-03-05 13-58-47](https://user-images.githubusercontent.com/80024169/110092579-8d6cb480-7dbb-11eb-90cf-393aa70ad117.png)
In first screen shot route there is a query string attached with the route but in the second one there is only route is showing. I think that is the issue, please help me out.

**Comment by osiset** [comment]
Please move to discussions, this would not be a bug :)
