### ISSUE TITLE
null $shop parameters in config_api_callback

### ISSUE THREAD

**Issue by andthink** [osiset/laravel-shopify#723]
Expected Behavior

parameter $shop is present in request in config_api_callback

## Current Behavior

Apps breaks because $shop is null

## Failure Information

I can't manage different store in config_api_callback

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

In admin use config_api_callback to determine different apikeys, sometimes the $shop variable is not defined when changing page.

Proposed PR

#722

**Comment by osiset** [comment]
@andthink Thanks for the PR, I had to make a couple modifications to have it pass some tests, allowing null values. If you'd like to give the master branch a try via updating composer entry to "dev-master", and seeing if this solves your issue. If so, I'll update contributors file with your username, and release a patch :)

**Comment by andthink** [comment]
Seems everything ok! Thanks
