### ISSUE TITLE
Milti-level get array breaks authentication

### ISSUE THREAD

**Issue by slv-lr** [osiset/laravel-shopify#724]
Hi

I've had problems with multi-level arrays in GET requests.

When I was using DataTables it is generating multi-level arrays like:
```https://*****.******.**/api/orders?draw=1&columns[0][data]=0&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=1&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=2&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=3&columns[3][name]=&columns[3][searchable]=true&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=4&columns[4][name]=&columns[4][searchable]=true&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=5&columns[5][name]=&columns[5][searchable]=true&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&start=0&length=10&search[value]=&search[regex]=false&prev=&next=&_=1615062243420```

This type of url leads to following error:
```
[2021-03-06 20:34:46] dev.ERROR: Array to string conversion {"userId":1,"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/html/_apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:250)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/_apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(250): implode()
#2 /var/www/html/_apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(298): Osiset\\ShopifyApp\\Http\\Middleware\\AuthShopify->Osiset\\ShopifyApp\\Http\\Middleware\\{closure}()
#3 /var/www/html/_apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(316): Osiset\\ShopifyApp\\Http\\Middleware\\AuthShopify->getData()
#4 /var/www/html/_apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(71): Osiset\\ShopifyApp\\Http\\Middleware\\AuthShopify->getShopDomainFromData()
#5 /var/www/html/_apps/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Osiset\\ShopifyApp\\Http\\Middleware\\AuthShopify->handle()
```

Line 250 of AuthShopify.php contains:
`$verify[$key] = is_array($value) ? '["'.implode('", "', $value).'"]' : $value;`
When I've changed to:
`$verify[$key] = is_array($value) ? json_encode($value) : $value;`
Authorization works fine.

You need to patch lines 277 and 291 as well in the same meaner.

Please let me know it this path can be applied.

**Comment by osiset** [comment]
Who is sending the query data? The validation should only be triggered if hmac exists.

**Comment by slv-lr** [comment]
I have page where displaying data gathered from Shopify store. To get this data user needs to be authenticated already.
On each request I need to verify if my client has valid (Shopify) sesson.
Generally problem is when your request has multi-dimension array in URL and using 'auth.shopify' as middleware.

**Comment by osiset** [comment]
There's no HMAC. So I am not sure why its bothering to check your data. This may be an oversight I'll have to look into.

**Comment by slv-lr** [comment]
I haven't got time to deep dive into your code so can't help here.

To reproduce it should be enough set in routes/web.php:
`Route::any('/api/orders', [OrdersController::class, 'api'])->middleware('auth.shopify');`
and then create simple controller.
Then try to make request with double dimension array like:
`https://*****.******.**/api/orders?draw=1&columns[0][data]=0`

In case of any questions I will gladly answer.

**Comment by osiset** [comment]
So the issue seems to be stemming from getShopDomainFromData, which calls getData, which is trying to parse your query string. 

[This previous comment](https://github.com/osiset/laravel-shopify/issues/593#issuecomment-714457665) may help, I'll try to massage this code into it and test. But I still need it to work for [bulk actions](https://community.shopify.com/c/Shopify-Apps/Hmac-Verification-for-Bulk-Actions/m-p/590611/highlight/true#M18504).

Thanks for the report, I'll see what I can manage to mangle up and possible have you test it out on a new branch if you like.

**Comment by slv-lr** [comment]
I think my approach can work if you need flat structures. This way you need to check if json_decode result and according to output (array or false) treat this accordingly.
In other hand why imploding whole input?
You can preserve structure "as is" and imploding somewhere else. Only when needed and for known structures only.

**Comment by osiset** [comment]
@slv-lr Update your composer to use "dev-bugfix/593", this contains a fix which should work for you, if you could verify that would be great. I can not do a physical test until later this week.

**Comment by slv-lr** [comment]
@osiset I need to prepare test env for this. I will give you result in ~24h.
Thanks for quick fix!

**Comment by osiset** [comment]
No problem. I added a unit test for nested arrays on query input and it came out with an error. I think what I additionally need to modify is to split up looking for the shop and the data. Right now both run through the same function. In your case its needless, since we just need the shop and data is not important since were not verifying it.

If your test result goes ok, I'll implement one last patch to split this up... this way the data won't be touched if theres no HMAC to verify against.

**Comment by slv-lr** [comment]
Hey, I've found time window and made dirty patch by temporary exchanging just laravel-shopify directory.
Unfortunately patch not working as expected. I still get error:
`[2021-03-08 21:14:59] dev.ERROR: Array to string conversion {"userId":3,"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/html/_dev-apps/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php:375)`
On the first step you are still trying implode multi-dimensional array:
```
 $formatValue = function ($val): string {
            return is_array($val) ? '["'.implode('", "', $val).'"]' : $val;
        };
```
which cause same error as in initial bug report.

**Comment by osiset** [comment]
Give the branch another try, I've tried a request similar to your query and worked well. I've change the code to ignore data unless hmac is present.

**Comment by osiset** [comment]
Thanks, it'll be fine now since I'm ignore data when hmac is not 
present. Thanks for the check, I'll release a patch for this later 
today.
