### ISSUE TITLE
App Proxy Invalid proxy signature.

### ISSUE THREAD

**Issue by MGhufranKhalil** [osiset/laravel-shopify#725]
## Invalid proxy signature.
I am getting Invalid proxy signature. error on using app proxy

here is my ajax:

$.ajax({ 
        url:"https://sneakersurgeapp.test/proxy",
        type: "GET"
  }).done(function(data) {
        console.log(data); 
  });
  
here is my app proxy setting
![image](https://user-images.githubusercontent.com/26011483/110324677-1ee85a80-8038-11eb-9a61-5e2c021fd85d.png)

here is my route
 Route::get('/proxy', [
    'uses' => 'App\Http\Controllers\CollectionProductsController@getCollectionProducts',
    'as' => 'proxy.test'
])->middleware(['cors','auth.proxy']) ;

please help

**Comment by osiset** [comment]
You wouldn't send a AJAX request to proxy. Proxy is used to display a page on the Shopify store. It will verify the request came from Shopify and then display your view.

**Comment by MGhufranKhalil** [comment]
I am sending ajax from frontstore to laravel app.. isnt this possible?

my app url: https://sneakersurgeapp.test

**Comment by osiset** [comment]
So if /proxy is the route you use to display your view on the store... then you'd need to make another route to handle your AJAX requests.

/proxy => validates request from Shopify, displays your view on the shop

Make a new route /proxy/something, where you can send your AJAX requests to there, without the auth.proxy middleware.

**Comment by MGhufranKhalil** [comment]
I am unable to understand please look 

Laravel:
App URL : https://sneakersurgeapp.test
Route I have create : https://sneakersurgeapp.test/proxy 
```
Route::get('/proxy', [
'uses' => 'App\Http\Controllers\CollectionProductsController@getCollectionProducts',
'as' => 'proxy.test'
])->middleware(['cors','auth.proxy']) ;
```

Shopify 
Store URL: https://sshk-store.myshopify.com/
Proxy : https://sshk-store.myshopify.com/apps/proxy

my ajax
```
$.ajax({
url:"https://sneakersurgeapp.test/proxy",
type: "GET"
}).done(function(data) {
console.log(data);
});
```

please correct my where I am wrong I will be really thankful

**Comment by osiset** [comment]
You dont send an AJAX request to your proxy URL.

Proxy page is for validation of the request from Shopify, and if validated, it will send back a view to Shopify.

I'm not sure you're understanding what proxy pages do. This is not a package issue from what I see, please move to discussions tab for help :)
