### ISSUE TITLE
The app couldn’t be loaded

### ISSUE THREAD

**Issue by aakashprajapati1** [osiset/laravel-shopify#726]
Hello

I have developed one Shopify public app using Laravel Shopify. Run this app into the local server and using ngrok site running on HTTPS. After when I install the application into the development server then giving an error like this: The app couldn’t be loaded

![Shopify](https://user-images.githubusercontent.com/80114426/110435511-1b58e000-80d9-11eb-8632-1166e3ae86be.png)

**Comment by osiset** [comment]
Please use issue template and re-open. Additionally, theres several issues with ngrok, which may be your issues. More than likely several redirects are happening.
