### ISSUE TITLE
shopify cart empties when proxy page loads

### ISSUE THREAD

**Issue by tzookb** [osiset/laravel-shopify#729]
## Expected Behavior

the cart to persist after our proxy page loads.
Only on firefox and safari.

## Current Behavior

- add item to the cart
- checking `site.com/cart.js`
- I see the item in the cart
- moving to a diff page in the site
- my proxy script loads (even when its blank)
- the cart is empty

### Context

* Package Version: v10.3.1
* Laravel Version: v6.0
* PHP Version: v7.3

## Important To mention:

- our proxy page does nothing related to cart or cookies
- Ill even say we just loaded the proxy page as empty page

**Comment by tzookb** [comment]
thanks @osiset 

thats was a known issue from Shopify.
So for other people:

- if your proxy goes through a 301 to get to your page
- the cookie will reset

**example:**

this is the file loaded =>
store.myshopify.com/apps/yourapp/file.js

the real store domain is:
store.com

so the request will redirect to with 301:
store.com/apps/yourapp/file.js

but now the cookies will reset of firefox and safari.

to prevent  that, make sure to load the **real** store domain and not the shopify one.

**Comment by Sanjay-100** [comment]
@tzookb     I have same issue how I can add the shipping rate checkout page Check the dynamic based on address or logistic providers . thanks in advance for the help
