### ISSUE TITLE
Generic error at creating webhook when shopify returns a detailed error

### ISSUE THREAD

**Issue by gabtorr** [osiset/laravel-shopify#745]
## Expected Behavior

Return the exact error returned by Shopify.

## Current Behavior

Getting ApiException and Unknown error. This happens because the Shopify error is an array and not a string. I had to modify the package code to know what was going on. If anyone is facing this issue, check the app scopes.

## Failure Information

I followed the steps of the tutorial to develop a webhook in order to get the orders from the shop. Doesn't return anything debugable, and throws ApiException and Unknown error. 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

- Just follow the [oficial tutorial](https://github.com/osiset/laravel-shopify/wiki/Creating-Webhooks).
- My webhook config is:
```
"topic": "orders/create",
"address": "https://myappname.ngrok.io/webhook/orders-create/"
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0.4
* Laravel Version: v8.32.1
* PHP Version: v7.3

### Failure Logs

```
"body" => array:1 [▶️
    "topic" => array:1 [▶️
      0 => "Invalid topic specified: orders/create. Does it exist? Is there a missing access scope? Topics allowed: app/uninstalled, collections/create, collections/delete, collections/update, products/create, products/delete, products/update, shop/update, app_purchases_one_time/update, app_subscriptions/update ◀️Invalid topic specified: orders/create. Does it exist? Is there a missing access scope? Topics allowed: app/uninstalled, collections/create, collections/delete, ▶️"
    ]
  ]
```

**Comment by osiset** [comment]
There's no error handling on creating the webhooks, I can put this on backlog but its not a priority right now, thanks for the report!

**Comment by osiset** [comment]
GraphQL is now used for webhook sin v17, closing for clean up for now. But if still an issue, re-open.
