### ISSUE TITLE
Getting Unknown Error while installing an App

### ISSUE THREAD

**Issue by nithinkashyapn** [osiset/laravel-shopify#752]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

1. After Billing Screen Redirect to App and then into iframe

## Current Behavior

1. After Billing Screen getting redirected to an error screen with below error

```
Osiset\ShopifyApp\Exceptions\ApiException
Unknown error 
```

## Failure Information

App is failing to redirect into Shopify app. If I go back to the main domain, it gets redirected into the app.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install App into development store with any webhook attached in `shopify-app.php` file. Only uninstall webhook is there in the array. Also the app is hosted on shared hosting and served with HTTPS.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0
* Laravel Version: v8.34.0
* PHP Version: v7.4.15
* Using a toolset (Docker, Laradock, Vagrant, etc.): Laravel App hosted on Shared Hosting

### Failure Logs

Logs can be found here - https://flareapp.io/share/17xZldam (Nothing sensitive - test application, data will be purged)

![image](https://user-images.githubusercontent.com/29030918/112762403-21c5e200-901d-11eb-8762-974264247101.png)

**Comment by darrynten** [comment]
Can you provide a dump of the response that gets returned? Something like `dd($response);` after line 439

**Comment by nithinkashyapn** [comment]
Hey @darrynten, I figured it out.

The environmental variables were not being set properly for the web-hook. This was throwing an error. Once i fixed it it started working.
