### ISSUE TITLE
Missing Shop Domain exception

### ISSUE THREAD

**Issue by osamashamim7** [osiset/laravel-shopify#753]
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

After virtual hosting running it for the first time 
it shows missingdomaineceptionerror

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0
* Laravel Version: v8.12
![Capture21](https://user-images.githubusercontent.com/73819302/112835429-4ddb7480-90aa-11eb-8cf7-115ccc750e71.JPG)

* PHP Version: v7.3
* using composer

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by darrynten** [comment]
Try `AuthToken` middleware with a JWT instead.

**Comment by Enmaboya** [comment]
You have http.
Shopify requires https.

You can add the following script to the layout, for example
```
<script>
    if (window.location.protocol != "https:") {
        window.location.protocol = "https";
    }
</script>
```

**Comment by osamashamim7** [comment]
Hi,

 I added this script in the welcome blade but no success.


Thank You

**Comment by brucelee90** [comment]
Try to enter your URL with parameter ?shop=[your-app-name].myshopify.com

I think that's what the middleware is looking for

**Comment by mumer96** [comment]
Try 
if($this->app) {
    \URL::forceScheme('https');
}
in you AppServiceProvider boot method

**Comment by diacu** [comment]
It has nothing to do with the https. The documentation is outdated and actually there is no login page. As @brucelee90 said, you need a `?shop=[your-shop-name].myshopify.com` parameter in url.

**Comment by osiset** [comment]
Cleanup... Closing for now, cookies are removed in v17.0.0
Re-open if still and issue.
Thanks!
