### ISSUE TITLE
Migrate app from Shopify App Bridge 1.x to Shopify App Bridge 2.0

### ISSUE THREAD

**Issue by lulzash** [osiset/laravel-shopify#756]
A new search parameter called `host` has been introduced with the release of App Bridge 2.0.

Getting notification from shopify - Please update the apps to App Bridge 2.0.
Version of App Bridge lower than 1.x which will be removed from Shopify on Jan 1, 2022.

**Comment by darrynten** [comment]
Can you post the whole notice?

**Comment by lulzash** [comment]
> Can you post the whole notice?

https://shopify.dev/changelog/easdk-being-removed-and-embedded-apps-must-migrate-to-app-bridge

**Comment by lulzash** [comment]
> Can you post the whole notice?

https://shopify.dev/changelog/easdk-being-removed-and-embedded-apps-must-migrate-to-app-bridge

**Comment by mikeastral** [comment]
On the Shopify App forum a Shopify Rep. replied that during this week the Shopify App platform will start using the new "host" parameter on redirect. (It seems that after releasing App bridge 2 this param was somehow missing )

Does any body knows what would be the short procedure for supporting App Bridge 2 before May 1th? ... Or is there any chance to get a new version of this Laravel extension before May 1th?

**Comment by mikeastral** [comment]
I implemented a quick workaround for dealing with the new 'host' param.
I noted that the param will be loaded in the Request object after launching the APP from 'admin' site.

So in the controller that is handling the lading page I did the following:

        $params = $request->all();
        $host = session('shopifyHost');  //Just in case the host was already set

        if(isset($params["host"])){
            session(['shopifyHost' => $params['host']]);  //Setting the host if it is present in the params
        }else{
            if($host == null){
                $url = "https://".$shop->name.'/admin/apps/'.env("SHOPIFY_API_KEY");
                logger("redirect because there was no host..."); // force a redirect for getting the new host param on start
                return redirect()->away($url);
            }
        }


Then, on the bridge configuration I pass the host value from session:

    <script>
        var AppBridge = window['app-bridge'];
        var createApp = AppBridge.default;
        var app = createApp({
            apiKey: '{{ config('shopify-app.api_key') }}',
            **host: '{{ session('shopifyHost') }}',**
        });
    </script>

This solution might cause CSP issues but you can create a middleware for adding the following header to every incoming request, by adding this line to the response:

`$response->header( 'Content-Security-Policy', 'frame-ancestors '.$shop);`

**Comment by pengbo37877** [comment]
change the config does not work for me
`'appbridge_version' => env('SHOPIFY_APPBRIDGE_VERSION', '2')`
I have the same issue

**Comment by pengbo37877** [comment]
`'appbridge_version' => env('SHOPIFY_APPBRIDGE_VERSION', '2.0.3')`
works for me

**Comment by osiset** [comment]
@mikeastral Not sure I'm following, shouldn't @pengbo37877 suggestion work fine? Or is there backend changes needed?

**Comment by osiset** [comment]
Given ENV setting exists, we should be fine. Closing for now.

**Comment by squatto** [comment]
As of right now I have an app running on production that has been approved by Shopify. It is using AppBridge version "2":

```
>>> config('shopify-app.appbridge_version')
=> "2"
```

**Comment by filipembcruz** [comment]
Hi everyone,

Someone knows how I solve this? Where Can I put this configuration?

**Requirements that must be met before initial screening**
App must set security headers to protect against clickjacking.
Your app must set the proper frame-ancestors content security policy directive to avoid clickjacking attacks. The 'content-security-policy' header should set frame ancestor to frame-ancestors https://cambridgetestshop.myshopify.com https://admin.shopify.com.

More information [here](https://shopify.dev/apps/store/security/iframe-protection)

@mikeastral Can you put more details? Thanks

**Comment by damquanghieu** [comment]
> Hi everyone,
> 
> Someone knows how I solve this? Where Can I put this configuration?
> 
> **Requirements that must be met before initial screening** App must set security headers to protect against clickjacking. Your app must set the proper frame-ancestors content security policy directive to avoid clickjacking attacks. The 'content-security-policy' header should set frame ancestor to frame-ancestors https://cambridgetestshop.myshopify.com https://admin.shopify.com.
> 
> More information [here](https://shopify.dev/apps/store/security/iframe-protection)
> 
> @mikeastral Can you put more details? Thanks
I have the same error as you, can someone help me

**Comment by liambolling** [comment]
I have this issue as well

**Comment by damquanghieu** [comment]
> I have this issue as well

I fixed this error.
I was add Content-Security-Policy', 'frame-ancestors in header
example:
 return response()->view('index')->header( 'Content-Security-Policy', 'frame-ancestors '.Auth::user()->name);

**Comment by filipembcruz** [comment]
@damquanghieu yes it works. I solved it putting the code below above your app.blade.php html (or any layout base) and works too.

```
<?php
  header("Content-Security-Policy: frame-ancestors https://".auth()->user()->name);
?>
```

**Comment by spars123** [comment]
> @damquanghieu yes it works. I solved it putting the code below above your app.blade.php html (or any layout base) and works too.
> 
> ```
> <?php
>   header("Content-Security-Policy: frame-ancestors https://".auth()->user()->name);
> ?>
> ```

Hello, 
In which file we have to add this? 

When we are adding the above code in my shopify php file, it is throwing error.
Can you please help me to solve this.
