### ISSUE TITLE
Call to a member function getInterval() on null

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#761]
I'm using Laravel 5.8 and laravel-shopify v12.0

The problem I got is:
The store is on a paid plan and uninstalls app so recurring charged cancelled but when decide to install the app again he got the error:
**Call to a member function getInterval() on null**

How to fix that problem?
I have "interval" column on both - "plans" and "charges" table in the database ...

**Comment by simontryathome** [comment]
Hi osiset,

First of all, thank you very much for such amazing work.
I am using your app almost everything working very smoothly.

**Problem** 
I am trying to create a billing URL and at that time i got this error.

I have added 0 on on_install in the database plan. so now when i try to install the app it will be redirected to the may setting area and this error happening.

![image](https://user-images.githubusercontent.com/96615983/147343640-7ec55c1e-ea49-4fb9-9968-11b0932762fa.png)

i am using ngrok.

can you please let me know why this happens application working with on_install = 1 perfectly .

Thank you

**Comment by APdevelopments** [comment]
I think that problem could be solved if add value 1 to freemium column in table 'users' ?
