### ISSUE TITLE
Shopify App has been rejected in review

### ISSUE THREAD

**Issue by vicky92727** [osiset/laravel-shopify#763]
Hi,
I've followed each step in the documentation but after submitting the app for review I got.
Your app hasn't implemented authentication through OAuth correctly and can't be reinstalled. Review our OAuth documentation and see this screenshot for additional details. We were redirected to this error when trying to reinstall the app.

I've implemented uninstall web hook also but don't know what's the issue is.

**Comment by ihateonions-uk** [comment]
What was in the screenshot? We need to see the error they received. It does sound like an uninstall problem and probs hasn't fired the Webhook hence adding the date to deleted_at column and cleared the password etc.

**Comment by vicky92727** [comment]
Hi @ihateonions-uk  here is the screenshot, https://screenshot.click/13-01-18197-66133.png

**Comment by ihateonions-uk** [comment]
This is todo with the uninstall job / Webhook not firing. When this is fired you should see the deleted_at in the users table given a date, and the password will be removed too.

I would suggest checking the Webhook is set up correctly and make sure to run php artisan vendor:publish --tag=shopify-jobs. I had a similar issue last month and it was a case of not setting up the Webhook correctly.

And ive just tested this on my current dev app and its working fine.

**Comment by vicky92727** [comment]
Okay sure, let me debug the webhook

**Comment by vicky92727** [comment]
Hi @ihateonions-uk  I've followed each step at this link [https://github.com/osiset/laravel-shopify/wiki/Installation#uninstalled-job-recommended](url) I've checked there is a job in app/Jobs folder AppUninstalledJob.php with content 
`<?php

namespace App\Jobs;

class AppUninstalledJob extends \Osiset\ShopifyApp\Messaging\Jobs\AppUninstalledJob
{
}
`
and this is the response of command 
`php artisan vendor:publish --tag=shopify-migrations`
`Copied Directory [/vendor/osiset/laravel-shopify/src/ShopifyApp/resources/database/migrations] To [/database/migrations]
Publishing complete.` but still it's not trigering the uninstall webhook, 
Whenever I manually set the password and deleted_at Null then app can be reinstalled.

**Comment by mohinht** [comment]
HI @vicky92727 ,
Shopify APP must required JWT session token based authentication. https://shopify.dev/changelog/all-embedded-apps-submitted-for-app-review-are-required-to-adopt-session-tokens

This package Owner already working on it. #744 

Thank you!

**Comment by vicky92727** [comment]
Hi @mohinht can we have a timeline when it'll be production-ready so that we can use it in our app to resubmit for approval?

**Comment by NirajSavaliya** [comment]
@vicky92727 

I think you need to enable the webhook option in the shopify-app.php config file

![www](https://user-images.githubusercontent.com/8054426/119657909-23a7f800-be4a-11eb-92c2-8ee022aacebb.png)

**Comment by vicky92727** [comment]
Hi @Niraj,  I've enabled this webhook, and after installation of the Shopify app it's showing this in created webhooks but whenever I uninstall the app this webhook not triggering to set deleted_at in the Users table.

**Comment by vicky92727** [comment]
Hi @squatto, I've tried your CURL request and got 404 not found error

**Comment by squatto** [comment]
The webhook handler route isn't being registered, it would seem. Run this command and paste the output:

`php artisan route:list --path="webhook/{type}"`

If it doesn't match any routes, try this one:

`php artisan route:list --path=webhook`

**Comment by squatto** [comment]
You _should_ get something like this when the webhook handler route is being registered correctly:

```
+--------+--------+----------------+---------+-------------------------------------------------------------+-----------------------------------------------+
| Domain | Method | URI            | Name    | Action                                                      | Middleware                                    |
+--------+--------+----------------+---------+-------------------------------------------------------------+-----------------------------------------------+
|        | POST   | webhook/{type} | webhook | Osiset\ShopifyApp\Http\Controllers\WebhookController@handle | api                                           |
|        |        |                |         |                                                             | Osiset\ShopifyApp\Http\Middleware\AuthWebhook |
+--------+--------+----------------+---------+-------------------------------------------------------------+-----------------------------------------------+
```

**Comment by vicky92727** [comment]
Hi @squatto, after running the above command I'm getting this response see attached

`php artisan route:list --path="webhook/{type}"`

![image](https://user-images.githubusercontent.com/16666080/119946326-f1b0a600-bfaf-11eb-8560-0d2b3b8722f5.png)

and if I run this command  `php artisan route:list --path=webhook` then I'm getting below response 
![image](https://user-images.githubusercontent.com/16666080/119946662-4f44f280-bfb0-11eb-976e-d8492c196fa7.png)

**Comment by vicky92727** [comment]
Hi @squatto could you please look into it and let me know what I'm doing wrong? I've posted the response of commands that you asked me to run in the previous comment.

**Comment by squatto** [comment]
@vicky92727 Did you manually register the `webhook/app-uninstalled` route? That should be removed. You shouldn't have any webhook routes showing up in the route list that will be handled by the package (that's what the `webhook/{type}` route is for).

Laravel uses the first matching route, so what is happening is that when `webhook/app-uninstalled` is accessed, your manually-registered route is being used instead of the package's. Once you remove the manually-registered route, the `curl` command I gave you in [#744](https://github.com/osiset/laravel-shopify/issues/744#issuecomment-848954320) should give the correct response ("Invalid webhook signature.")

Let me know if that does it!

**Comment by vicky92727** [comment]
Hi @squatto, I was testing it that's why I've created routes manually, now I've removed them, and below is the result of the above command `php artisan route:list --path=webhook`
![image](https://user-images.githubusercontent.com/16666080/120052503-16079380-c03f-11eb-8dc9-ba2389fe4247.png)

but still, I'm getting a 404 File not found error

**Comment by squatto** [comment]
Does the `api/delwebhook` route work correctly?

**Comment by vicky92727** [comment]
Yes it deletes all webhooks from Shopify.

**Comment by squatto** [comment]
OK that rules that out. Can you get into Tinker (run `php artisan tinker`) and run this?

```php
config('shopify-app.webhooks')
```

Feel free to blank out your hostname, if you want.

**Comment by vicky92727** [comment]
Hi @squatto, the result of the above command is as follows
![image](https://user-images.githubusercontent.com/16666080/120074919-91f1f200-c0b8-11eb-84eb-bf9b885ef4cc.png)

**Comment by vicky92727** [comment]
Hi @squatto, the result of the above command is as follows
![image](https://user-images.githubusercontent.com/16666080/120074967-ccf42580-c0b8-11eb-8bd3-8d2ff8d4eafb.png)

**Comment by vicky92727** [comment]
Hi @squatto, I just resolved the issue of uninstallation of the app with your help, basically, the issue was subdomain and I've to add public folder rule to the .htaccess file to avoid 404 not found error.

**Comment by vicky92727** [comment]
Thanks everyone for your help to solve this issue especially @squatto

**Comment by squatto** [comment]
Sorry for the delay in responding @vicky92727, I've been on vacation. I'm really glad that you were able to get it resolved! Nice work!
