### ISSUE TITLE
App isn't redirect to store after install on store. return 404

### ISSUE THREAD

**Issue by HardikVansia** [osiset/laravel-shopify#764]
Hi @osiset 

can you please check this?
https://yourdomain.com/?shop=yourstore.mysopify.com

It must be redirected to Shopify admin. and it's working previously. But it stops working after the update.

![image](https://user-images.githubusercontent.com/79184458/115831476-44d28e80-a42f-11eb-9e72-061e7502acd0.png)

![image](https://user-images.githubusercontent.com/79184458/115657037-dbca1880-a353-11eb-9cfc-d02bcb47a1d1.png)

**Comment by HardikVansia** [comment]
Issue related to the app bridge version 2 host parameter.

**Comment by nikhilchaudhary70** [comment]
Hi, @HardikVansia Have you got the solution for this?
I'm also facing the same issue.
Any help would be really appriciate?
