### ISSUE TITLE
Version 15.0, How to check API Limit for GraphQL

### ISSUE THREAD

**Issue by veed76** [osiset/laravel-shopify#765]
Hi @osiset 

In version 10, we were able to check API limit using this code  `$shop->api()->getApiCalls('graph', 'left');` I have another app which was using version 15.0, so in 15.0 how can I check the API limit? Can you please help me on this? 

Thank you.

**Comment by osiset** [comment]
See Basic-Shopify-API package on my repos.

`$client->getLimitStore()`, will return the data you're inquiring about :)
