### ISSUE TITLE
Does this package allow multiple user accessing same app at same time

### ISSUE THREAD

**Issue by spsarola** [osiset/laravel-shopify#766]
I don't know my method of asking is valid or not however Please forgive me if I am using the wrong method. :)

## It should be allow multiple user at same time
I want to make a shopify app I so your library which is too help full for all the developer who want to make shopify app.
I am just wondering about is this package allow me multiple user at same time accessing the my app.
my app concept is like app will be open in the separate window also merchant have installed the app for his multiple stores.
so in that case I think this package allow one store at time as per my study of few days. 
would you please clear me does this package such kind of functionality or not.

Thanks for your valuable time and for a good lib for shopify app development

:)

**Comment by osiset** [comment]
Currently, yes with v17. Shopify session tokens are used. Closing for now :)
