### ISSUE TITLE
Weird authentication behaviour when reopening embed

### ISSUE THREAD

**Issue by copvampire** [osiset/laravel-shopify#767]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Clicking the application after install, it should appear like any other embed application.

## Current Behavior

After installing a fresh installation, using the wiki as a guide, I get a weird redirect behaviour when visiting the app after installation process.  [Video link](https://app.blisk.io/screenRecords/shared/fa16d82d-ab13-402d-bb45-e70b8c8666b7)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install laravel
2. Followed all the step according to wiki

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0.6
* Laravel Version: v8.38.0
* PHP Version: v7.4.15

**Comment by osiset** [comment]
Issue due to cookies and ITP, this has been removed in v17 in favour for JWT.
Closing for now, but re-open if still an issue.
