### ISSUE TITLE
BadMethodCallException Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()

### ISSUE THREAD

**Issue by Sanjayavidbrio** [osiset/laravel-shopify#769]
## Expected Behavior

Please describe the behavior you are expecting.
app not installing on store 

## Current Behavior
app installing getting an error

2. try to access localhost  http://127.0.0.1:8000/
 Osiset\ShopifyApp\Exceptions\MissingShopDomainException
http://127.0.0.1:8000/

Please describe the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug.

BadMethodCallException
Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1  
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 
* Laravel Version: Laravel Framework 8.38.0
* PHP Version: 7.4.3 
* Using a toolset (Docker, Laradock, Vagrant, etc.):   PHP artisan serve and ngrok  for public UR

### Failure Logs

Illuminate\Database\Eloquent\Builder::throwBadMethodCallException
vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50

            $pattern = '~^Call to undefined method (?P<class>[^:]+)::(?P<method>[^\(]+)\(\)$~';

 

            if (! preg_match($pattern, $e->getMessage(), $matches)) {

                throw $e;

            }

 

            if ($matches['class'] != get_class($object) ||

                $matches['method'] != $method) {

                throw $e;

            }

 

            static::throwBadMethodCallException($method);

        }

    }

 

    /**

     * Throw a bad method call exception for the given method.

     *

     * @param  string  $method

     * @return void

     *

     * @throws \BadMethodCallException

     */

    protected static function throwBadMethodCallException($method)

    {

        throw new BadMethodCallException(sprintf(

            'Call to undefined method %s::%s()', static::class, $method

        ));

    }

}

 
![image](https://user-images.githubusercontent.com/78072091/116274222-17277580-a7a0-11eb-9b7f-80339993132d.png)

**Comment by squatto** [comment]
Without a stack trace I'm not 100% sure, but I would guess that your `User` model isn't using soft deletes. The migration that comes with this package adds soft deletes to the table, but you then have to add `use SoftDeletes;` to the `User` class yourself.

1. Does your `users` table have the `deleted_at` field?
2. Is your `User` model using the `SoftDeletes` trait?

**Comment by Sanjayavidbrio** [comment]
@squatto  thanks for your help that issue fixed now 


Model/user.php

```
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Osiset\ShopifyApp\Contracts\ShopModel as IShopModel;
use Osiset\ShopifyApp\Traits\ShopModel;

class User extends Authenticatable implements IShopModel
{
    use HasFactory, Notifiable;
    use ShopModel;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}


```


migration xxxx---create_users_table.php


```<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}


```.

but still, the app shows the laravel welcome page   do you any suggestion for that

**Comment by Sanjayavidbrio** [comment]
output


![image](https://user-images.githubusercontent.com/78072091/116964596-939ee480-acc9-11eb-996a-ab4718cbdeb0.png)

**Comment by osiset** [comment]
Your original issue appears solved. Will close for now. Thanks!
