### ISSUE TITLE
Undefined property: stdClass::$usage_charge

### ISSUE THREAD

**Issue by JDSHINDE** [osiset/laravel-shopify#770]
hi @osiset  @Jamesking56  I have setup my usage charge in app but when i go for update then it will showing this error in package

![Screenshot_24](https://user-images.githubusercontent.com/46311508/116523252-aa24f480-a8f3-11eb-8264-c1f44632c7e4.png)
version
"php": "^7.4.0",
"ohmybrew/basic-shopify-api": "^6.1.2",
"ohmybrew/laravel-shopify": "10.3.1"

**Comment by Enmaboya** [comment]
version 10.3.1 is no longer supported.

In general, check the table of tariff plans and the data you have recorded there
