### ISSUE TITLE
Failed to execute postMessage after continue in ITP

### ISSUE THREAD

**Issue by raibhuwan** [osiset/laravel-shopify#773]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

I was going through ITP and  when i click on continue button after allowing the cookies, the page should redirect to the home page successfully.
## Current Behavior

But the page loads to the fullpage_redirect.blade.php view with black screen and then there occurs error at the console.
## Failure Information
I receive following error at the console.
Failed to execute 'postMessage' on 'Window': Invalid target origin 'https://' in a call to 'postMessage'.

I checked the code and there was only ##window.location.href = '{!! $redirect !!}'; code, which only redirects but the ITP Middleware handler needs a Request object which provides shop domain url. 
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the app in a browser with third party cookie disabled
2. Click continue in the window of ITP ask view

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 16.0.6
* Laravel Version: 7.2.5
* PHP Version: 8

### Failure Logs

Here is a screenshot
https://snipboard.io/EJy3k2.jpg

**Comment by osiset** [comment]
Cleanup... Closing for now, cookies/ITP are removed in v17.0.0
Re-open if still and issue.
Thanks!
