### ISSUE TITLE
Shopify App has been rejected in review due to third party cookie

### ISSUE THREAD

**Issue by raibhuwan** [osiset/laravel-shopify#781]
Hi,
I've used ITP for enabling the third party cookie, but seems that shopify doesn't let the embedded app to use the cookie and rejected my app and replied to use session token. I don't have much idea about those token, can anyone help me with this, i need my app to be accepted.

**Comment by hassantahir01** [comment]
Yeah, this is the most common issue with embedded apps built in Laravel, The only way is to build the app as SPA or use session ID as query string in the URL for a cookieless session. There is one library available for cookieless session i-e https://github.com/kevinsimard/laravel-cookieless-session but this is outdated and not working as expected.If anybody has already resolved this issue, please share his script with others.

**Comment by Enmaboya** [comment]
tokens are implemented in the "feature/cookieless" branch

**Comment by raibhuwan** [comment]
i have implemented in the "feature/cookieless" branch but i got the following error
**[previous exception] [object] (ReflectionException(code: -1): Class \"Osiset\\ShopifyApp\\Services\\ShopSession\" does not exist at /srv/users/euvattracker/apps/euvattracker/vendor/laravel/framework/src$**

When i checked the code i dont see the ShopSession class, and i also remove the composer caches, can anyone give me some directions.

**Comment by raibhuwan** [comment]
i just implemented the feature/cokkieless branch, but there seems to be problem while installing the app, the shopify shop simply redirects to the home page and then the token page, oauth page doesnt appear, i have the app url "https://{shopdomain}/", what should i change it to?

**Comment by hassantahir01** [comment]
@Enmaboya , I've implemented this branch code into Shopify app, it authenticates correctly but on redirect to other URL, the session again destroys.FYI, I'm not using turbo links in the app

**Comment by hassantahir01** [comment]
@raibhuwan ,you might need to check target URL in Milldware cal VerifyShopify.php file at line #264

**Comment by LonnyX** [comment]
is this ready to be merged to master?

**Comment by osiset** [comment]
Cleanup... Closing for now, cookies are removed in v17.0.0
Re-open if still and issue.
Thanks!
