### ISSUE TITLE
All store getting test charge

### ISSUE THREAD

**Issue by sandeshpaudyal123** [osiset/laravel-shopify#782]
Hi, 
I could not make a discussion so I created an issue for this. 
How can I let the development store install My app as a test charge after going to production and apply a charge to the live store . 
I can only find a way either to allow the only live store to install or apply test charges to all stores.  Please help.
Thank you.

**Comment by myw-ben** [comment]
You would just pass it in the routes files, just like any other middleware. So in your routes file you can add on the specific middleware that you create

**Comment by sandeshpaudyal123** [comment]
Hi @myw-ben  do you have the sample code that we need to write inside the middleware and to collaborate that with the osiset normal app flow?  That would be a great help.
