### ISSUE TITLE
Apps not installling after uninstalled

### ISSUE THREAD

**Issue by rrakhmit** [osiset/laravel-shopify#788]
## Current Behavior
![Screenshot 2021-05-16 005007](https://user-images.githubusercontent.com/5842272/118375003-b0e48480-b5e0-11eb-9d2e-a48f681d3774.png)

Fist install from partner account working perfectly. I am using sqlite also checked user table inserted correct data. 

Now after remove the apps, When i tried to install its authenticated successfully and welcome page coming,  But after redirect to shopify site above page is coming also the apps not listed on apps list.

Also checked the db user table not updated with deleted_at. 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Uninstall apps
2. Again try to install apps
3. After authenticate it will show welcome page
4. After redirect to shopify admin panel from welcome page the above scrnshot comes up and apps not showing on apps list

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0
* Laravel Version: v8.0
* PHP Version: v7.4.7

**Comment by rrakhmit** [comment]
When i remove that user row from user table then it will works again.

**Comment by Enmaboya** [comment]
use [hook](https://github.com/osiset/laravel-shopify/wiki/App-Uninstall-Handling)

**Comment by rrakhmit** [comment]
@Enmaboya Thanks for you reply.

Hooks already there, i used same code structure for two apps only endpoints and apis informations are different, first application work perfectly but somehow 2nd apps are not

**Comment by sergeyantonuk** [comment]
Hi @rrakhmit 
this issue was discussed earlier, you need to use Uninstalled Job (see wiki https://github.com/osiset/laravel-shopify/wiki/Installation#uninstalled-job-recommended) for automatic user deletion after the app has been uninstalled.
Also, webhooks will not work when ngrok has been changed or you have issues with laravel queue driver.

**Comment by lucasmichot** [comment]
@rrakhmit - could your issue be solved ?
If so can you close this issue ?

**Comment by rrakhmit** [comment]
i will check and let you know. Thanks for you enquiry.

*Rajib Kumar Rakhmit*
*PHP Web Developer*
***@***.***, ***@***.***
+88 01736 212121

**Comment by baberuth22** [comment]
Removing the user doesn't fix it for me.   It seems like the JWT auth is cached or something.
