### ISSUE TITLE
Error Call to a member function api() on null / Call to undefined method stdClass::api()

### ISSUE THREAD

**Issue by vessivanov** [osiset/laravel-shopify#792]
Hello,

I've installed the plugin and I followed the instructions for installation.

Now, I received the following error when I call the api method:

```
Error
Call to undefined method stdClass::api()
```
My user model:

```
use Osiset\ShopifyApp\Contracts\ShopModel as IShopModel;
use Osiset\ShopifyApp\Traits\ShopModel;

class User extends Authenticatable implements IShopModel
{
    use Notifiable, ShopModel;
...
```

My controller:

```
    public function themeUpdate(ShopvoteShops $shopvoteShop, $request = null)
    {
        $user = DB::table('users')->first();
        $shopvoteShop = ShopvoteShops::where('url', $user->name)->first();
        $shop = Auth::user();

        $response = $user->api()->rest('GET', '/admin/script_tags.json');
```

Basically, the instances User and Auth everytime are empty and I can't call for example `$shop->api()`, because `
Error
Call to a member function api() on null.
`

I will be glad to hear how to fix this issue. 

Thank you!

**Comment by mrwhale** [comment]
Are you able to dump the `$user` and/or `$shop` variables to see whats in there? 

If they are coming up null I'd recommend checking your databases `users` table to see if its actually being stored
