### ISSUE TITLE
After a billing success, How can I do run an operation?

### ISSUE THREAD

**Issue by mohinht** [osiset/laravel-shopify#798]
Hello,
After a billing success, I would like to try a snippet injection. Any idea, how can I do this?

Than kyou!

**Comment by mrwhale** [comment]
Assuming you want to inject some Javascript into the customers store after they successfully subscribe to your app, you would use the Shopify ScriptTag API endpoint to do this https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag

Or there is a helper in this app https://github.com/osiset/laravel-shopify/blob/940340a7bd5aab46a23bbdcad935ad310faf26b1/src/ShopifyApp/Services/ApiHelper.php#L188

**Comment by osiset** [comment]
Please move to discussions tab :)
