### ISSUE TITLE
how to save extra shop data into user table using osiset laravel shopify while installing app

### ISSUE THREAD

**Issue by thebleshbanz** [osiset/laravel-shopify#823]
Hello there,
i want to store extra shop data into user table using laravel-shopify. can you explain the how to store shop data?

**Comment by thebleshbanz** [comment]
Hello there,
still i didn't get solution about how to store shop data in user table while installation, anyone can help me to solve out this problem.

thanks in advance

**Comment by thebleshbanz** [comment]
how Package will add the shop with their domain and token to the database?

refference : https://github.com/osiset/laravel-shopify/wiki/Shop-Installation-and-Authentication-Process#fresh-shop

**Comment by Enmaboya** [comment]
use AfterAuthenticateJob, for example:

https://pastebin.com/xtxUUjje
https://pastebin.com/gg8Mpk25

I.e. the data can be retrieved using:
_$this->shop->api()->rest('GET', '/admin/shop.json')['body']->shop;_
Then you can do whatever you want with it.

**Comment by osiset** [comment]
Please move to discussions tab :)

**Comment by thebleshbanz** [comment]
thanks for your contributions, i am happy.
