### ISSUE TITLE
Route [] not defined

### ISSUE THREAD

**Issue by litalboa** [osiset/laravel-shopify#857]
![image](https://user-images.githubusercontent.com/19529643/124126303-36ce6900-da83-11eb-8ba0-56671fe99d5e.png)

after upgrading from v.16 to v.17 i am trying to install the app and getting this message. any thoughts on how to solve this?

**Comment by osiset** [comment]
Without a stack trace it work or be hard to find out. It's possible it's your config/shopify.php file? There's new routes and route names, I'm wondering if there's the issue.

**Comment by chris-geelhoed** [comment]
Check that your routes names config in `config/shopify-app.php` is up to date. Should be:

```
    /*
    |--------------------------------------------------------------------------
    | Route names
    |--------------------------------------------------------------------------
    |
    | This option allows you to override the package's built-in route names.
    | This can help you avoid collisions with your existing route names.
    |
    */
    'route_names' => [
        'home'                 => env('SHOPIFY_ROUTE_NAME_HOME', 'home'),
        'authenticate'         => env('SHOPIFY_ROUTE_NAME_AUTHENTICATE', 'authenticate'),
        'authenticate.token'   => env('SHOPIFY_ROUTE_NAME_AUTHENTICATE_TOKEN', 'authenticate.token'),
        'billing'              => env('SHOPIFY_ROUTE_NAME_BILLING', 'billing'),
        'billing.process'      => env('SHOPIFY_ROUTE_NAME_BILLING_PROCESS', 'billing.process'),
        'billing.usage_charge' => env('SHOPIFY_ROUTE_NAME_BILLING_USAGE_CHARGE', 'billing.usage_charge'),
        'webhook'              => env('SHOPIFY_ROUTE_NAME_WEBHOOK', 'webhook'),
    ],
```

**Comment by agalmame** [comment]
I had the issue... ! just deleted shopify-app.php in config folder then php artisan vendor:publish --tag=shopify-config

**Comment by osiset** [comment]
I'll update the upgrade doc, thanks

**Comment by ohmygoobness** [comment]
This is because of route naming, you should name '/' route as 'home'
