### ISSUE TITLE
Unable to create a POST request to the server

### ISSUE THREAD

**Issue by yasir-naseer-tetralogicx** [osiset/laravel-shopify#858]
I installed a fresh laravel 7 application along with latest version (17) of osiset package, start with a basic post request to the server using a form and i am getting 

The GET method is not supported for this route. Supported methods: POST.

Here is my form and routes

 <form action="{{ route('save.name') }}" method="POST">
        <input type="text" placeholder="name.." name="name">
        <button type="submit">Save</button>
 </form>

Route::post('/save','HomeController@save')->name('save.name')->middleware(['verify.shopify']);

However if i remove the new verify.shopify middleware and submit the form, im not getting this error, but in that case i am unable to get the authenticated user(shop) as Auth::user() reutrns null.

I have also disabled the VerifyCsrfToken as suggested in documentation

**Comment by osiset** [comment]
Have you added the {{ @sessionToken }} Blade directive to your form?
