### ISSUE TITLE
How to load AppBridge actions on the view

### ISSUE THREAD

**Issue by nithinkashyapn** [osiset/laravel-shopify#865]
Hey,

I recently updated the `SHOPIFY_APPBRIDGE_VERSION` to `2.0.3` and then I started getting this error

```
Uncaught ReferenceError: actions is not defined
```

Upon checking where it is getting called I saw this - 

![Screenshot from 2021-07-06 07-42-31](https://user-images.githubusercontent.com/29030918/124532269-d39b5880-de2d-11eb-9486-286f6f89261a.png)

How do i define and pull AppBridge actions so that the error goes away?

**Comment by Enmaboya** [comment]
did you add before that?

const AppBridge = window['app-bridge'];
const actions = AppBridge.actions;

const Toast = actions.Toast;

**Comment by nithinkashyapn** [comment]
I believe it is getting pulled in from the `flash_messages` partial. I see that appbridge is loaded in the network console but I still get the error.

**Comment by osiset** [comment]
@nithinkashyapn It's defined [here](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php#L29), and used in the flash_messages template.

I recently tested some flash messages out and had no issue. If you're using a custom layout file that doesn't extend the package's layout, then you'll need to add the JS setup from appbridge into your layout.

**Comment by nithinkashyapn** [comment]
Hi @osiset, I have extended the package layout. My `welcome.blade.php` looks like this - 

```
@extends('shopify-app::layouts.default')

@section('styles')
  // CDN for bootstrap
@endsection

@section('content')
  // some HTML
@endsection

@section('scripts')
  // some scripts
@endsection
```

**Comment by osiset** [comment]
@nithinkashyapn interesting. Do you see the app bridge code if you view source?

**Comment by nithinkashyapn** [comment]
yes, the appbridge code is visible. The appbridge CDN is loaded. Also if I disable the appbridge loading via environment variable then the error disappears

**Comment by osiset** [comment]
Can you paste the surrounding JS from view-source so I can confirm the variables are setup... blur anything out you need to.

**Comment by Kyon147** [comment]
Closing old ticket, reopen if still an issue.
