### ISSUE TITLE
Issue on fresh install after upgrading to 17.0

### ISSUE THREAD

**Issue by BrandonR-16** [osiset/laravel-shopify#867]
## Expected Behavior

When doing a fresh install of a laravel embedded app, it should direct to the install page with permissions.

## Current Behavior

After upgrading to 17.0, fresh install opens install page but shows this error message:

![Screenshot from 2021-07-06 10-40-49](https://user-images.githubusercontent.com/87021431/124610293-c474d480-de46-11eb-9b8f-3c8c4cf404e5.png)

### Steps to Reproduce

1. Click "Install App on Development Store"
2. Complete authentication
3. Then I get redirected to the install page but it's saying that there is no page at this address.

Note that in the path there is "/token?" after "/authenticate". I'm not sure if this is the way it's supposed to be or not.

### Context

* Package Version: v17.0

**Comment by Enmaboya** [comment]
you do not use the "uninstalled hook",
or it is not working for you.

[read the documentation](https://github.com/osiset/laravel-shopify/wiki/Installation#uninstalled-job-recommended)

**Comment by BrandonR-16** [comment]
I don't believe I would need the Uninstalled Hook in this situation as it's a fresh install on a development store. I didn't Uninstalled then re-install so it shouldn't use the webhook.

**Comment by BrandonR-16** [comment]
Anyone have an update on this? Probably just something small I'm missing but I can't figure it out at all. No matter what, when the user tries to install it says "There's no page at this address" instead of the install/permissions page. Any help would be great :)

**Comment by BrandonR-16** [comment]
@Enmaboya do you have any other possible solutions?

**Comment by squatto** [comment]
@BrandonR-16 Have you verified that the package's routes are registered properly? Also, are you hosting the app somewhere or running it locally?

**Comment by BrandonR-16** [comment]
@squatto how exactly do you verify the package routes? And the app is being hosted on an EC2 Instance with Apache. Thanks for your reply!

**Comment by BrandonR-16** [comment]
Just solved the issue by myself. Turns out I had an extra entry in the database for the development store I was trying to install on. I deleted that store from the database and tried the install again, and it worked. Issue will be closed now.

**Comment by squatto** [comment]
@BrandonR-16 I'm glad that you were able to work it out 👍🏻
