### ISSUE TITLE
Get User information in Controller , session error

### ISSUE THREAD

**Issue by ingalesachin7** [osiset/laravel-shopify#869]
Auth::user() in the controller,
getting an error: Session token is malformed.
I am using react Js to call the controller function. 

Please suggest the solution

**Comment by osiset** [comment]
Please provide how you're talking to the controller (XHR, Axois, jQuery, etc).
Please provide if you see the token with the request.

**Comment by ingalesachin7** [comment]
In React Js file,

```
 const producturl = '/api/getproductlist';
 axios.post((`${producturl}`, { })
 .then((response) => {
setSuccess('Get the data');
})
 .catch(() => {
     setError('Sorry, ubable to fetch data');
    });
  }
```
 Request while calling API 
![Request](https://user-images.githubusercontent.com/5120513/125106170-f6af5c00-e0fc-11eb-8154-491b07b0f6db.png)

**Comment by osiset** [comment]
I don't see the token hmm.

If you view source on your page, do you see code for setting up window.sessionToken?

**Comment by ingalesachin7** [comment]
I view source no any code for setting up window.sessionToken.....

**Comment by osiset** [comment]
[This is what sets the header](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/partials/token_handler.blade.php#L37)

Your Bearer is null in your request... any errors in console?

**Comment by ingalesachin7** [comment]
No Console error related to session token , 
![Console](https://user-images.githubusercontent.com/5120513/125560107-298a03d2-d74f-40ca-b7d8-c556cab7f96d.png)

**Comment by osiset** [comment]
May be a similar issue to #895

**Comment by cvikenzi** [comment]
Hello,
in default react class, before you call any other ajax, just call **await axios.get('/authenticate/token')**
You can use it for example in componentDidMount.

**Comment by osiset** [comment]
Ah... @ingalesachin7 are you trying to do an AJAX call before the sessionToken is available?

**Comment by ingalesachin7** [comment]
Thanks, @cvikenzi  for the suggestion,

I have called getting session tokens using await axios.get('/authenticate/token'), but missing to pass into the header in API call.
Now I am able to get the successful token and getting 200 responses from API.
Thanks, @osiset for this wonderful library.

**Comment by cvikenzi** [comment]
Hello @ingalesachin7 ,
can you please try if this solution is working for you also in safari browser?
In firefox and chrome (also incognito) i have no problem, but in safari axios calls not working for me.
Thanks for check.
