### ISSUE TITLE
Field 'endpoint' doesn't exist on type 'WebhookSubscription'

### ISSUE THREAD

**Issue by Latonna** [osiset/laravel-shopify#870]
I have upgraded to 17.0.0 for Removal of dependency on cookies,
I installed a webhook AppUninstalledJob  my shopify-app.php
![Snip - vl1 - shopify-app php PhpStor](https://user-images.githubusercontent.com/43789782/124713060-b6878800-df08-11eb-802b-72c5b89b6377.png)
and when i try installing app i get this error - Field 'endpoint' doesn't exist on type 'WebhookSubscription',
 after refresh  - Missing auth url. Help me, thanks
![Snip - Field 'endpoint' doesn't exist on type 'WebhookSubscription' - Google Chrome](https://user-images.githubusercontent.com/43789782/124916245-20805a00-dffb-11eb-9fc4-c32b48959afe.png)

**Comment by squatto** [comment]
What version of the Shopify API are you using? You can find out by getting the value of `config('shopify-app.api_version')`.

For example, you can get it in the Tinker shell:

```
$ php artisan tinker
>>> echo config('shopify-app.api_version')
2021-01
```

**Comment by Latonna** [comment]
hello. thanks for the answer, 
![Snip - devstasr@dev ~ www vl1 devstasr m wdgtest com public_html](https://user-images.githubusercontent.com/43789782/125032663-f8463900-e096-11eb-8e9a-034a016f2aaf.png)

**Comment by Latonna** [comment]
> What version of the Shopify API are you using? You can find out by getting the value of `config('shopify-app.api_version')`.
> 
> For example, you can get it in the Tinker shell:
> 
> ```
> $ php artisan tinker
> >>> echo config('shopify-app.api_version')
> 2021-01
> ```
спасибо большое, я поменяла версию в своем файле shopify-app.php на 2021-01, и ошибка пропала

**Comment by squatto** [comment]
You're very welcome! I'm glad that did the trick.
