### ISSUE TITLE
Navigating to different page throws InvalidArgumentException

### ISSUE THREAD

**Issue by BrandonR-16** [osiset/laravel-shopify#871]
## Current Behavior

When navigating between pages of my Shopify Embedded App, an InvalidArgumentException is thrown saying that you "Can only instantiate this object with a string.". Thrown on the "/authenticate" route so I assume I've done something wrong with the session tokens, as it was working smoothly before the upgrade to 17.0.

Any help would be appreciated!

![Screenshot from 2021-07-07 14-26-55](https://user-images.githubusercontent.com/87021431/124803837-fb72e500-df2f-11eb-9e45-43e76628d4fa.png)

### Steps to Reproduce

1. Navigate to different page on embedded app, and the error is thrown.

### Context

* Package Version: v17.0

**Comment by andreuka** [comment]
same here is safari

**Comment by BrandonR-16** [comment]
I'm using Firefox and Chromium and it's throwing the exception on both.

**Comment by andreuka** [comment]
> I'm using Firefox and Chromium and it's throwing the exception on both.

Do you using turbolinks?

**Comment by BrandonR-16** [comment]
No I'm not at the moment.

**Comment by andreuka** [comment]
> No I'm not at the moment.

seems like new version not works without turbolinks

**Comment by BrandonR-16** [comment]
> > No I'm not at the moment.
> 
> seems like new version not works without turbolinks

Oh really? I'm hoping not to have to switch my whole project around.

**Comment by andreuka** [comment]
> > > No I'm not at the moment.
> > 
> > 
> > seems like new version not works without turbolinks
> 
> Oh really? I'm hoping not to have to switch my whole project around.

Also ajax not works if you not used bearer token.

**Comment by BrandonR-16** [comment]
> > > > No I'm not at the moment.
> > > 
> > > 
> > > seems like new version not works without turbolinks
> > 
> > 
> > Oh really? I'm hoping not to have to switch my whole project around.
> 
> Also ajax not works if you not used bearer token.

Interesting. The issue in the ticket is strange as it only occurs when certain things are done. I can navigate to different pages fine most of the time, but if I do a function on the homepage, then try to navigate to a separate page, it throws this error. Not sure what's causing it.
