### ISSUE TITLE
Billing page not showing on install

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [osiset/laravel-shopify#886]
* Package Version: 17
* Laravel Version: 8
* PHP Version: 8
* Vagrant

I am trying to add billing to my app (which is not in producting yet btw).

I followed all steps as said in this link
https://github.com/osiset/laravel-shopify/wiki/Creating-a-Billable-App

I added one plan to the database, which has on_install set to true.
However, the billing page just never shows up. I click to install the app, it installs, and goes directly to the home page.
I am testing on a development store btw (idk if that makes a difference).

env vars: 
SHOPIFY_APP_PREFIX=shop
SHOPIFY_BILLING_REDIRECT=shop/billing/process
SHOPIFY_BILLING_ENABLED=1
SHOPIFY_BILLING_FREEMIUM_ENABLED=0

**Comment by diego-lipinski-de-castro** [comment]
I was looking at the billable middleware, and i see that it checks if the shop has a plan, and when you are using a test store, it actually comes with a plan

<img width="1021" alt="Screen Shot 2021-07-10 at 23 40 11" src="https://user-images.githubusercontent.com/29608698/125181137-2c754300-e1d8-11eb-9f96-5f481de5c067.png">

**Comment by diego-lipinski-de-castro** [comment]
I am jst fucking retarded. I literally just forgot the last and most important part: using the middleware.

**Comment by ncpope** [comment]
> I am jst fucking retarded. I literally just forgot the last and most important part: using the middleware.

🤣 this is the funniest thing I've seen on GitHub.
