### ISSUE TITLE
Update deprecated fields in package.

### ISSUE THREAD

**Issue by RuchitaCrawl** [osiset/laravel-shopify#887]
Hi, Thanks for this awesome package.

## Expected Behavior

REST API should work smoothly without deprecated fields

## Current Behavior

App showing deprecated fields in shop REST API

### Failure Logs

Showing attached screenshot error for deprecated field "force_ssl" which i have not used in my app. but i found this value in "vendor/osiset/basic-shopify-api/test/fixtures/rest/admin__shop.json" https://prnt.sc/1ahm4i8.

* Package Version: 12.1
* Laravel Version: 7.24
* PHP Version: v7.3.13
* OS: Linux Mint 19.2

**Comment by osiset** [comment]
This has nothing to do with the package.

"force_ssl" is part of the test fixures.

What Shopify is complaining about would need more info.

**Comment by APdevelopments** [comment]
Does someone solve this issue?

**Comment by Kyon147** [comment]
Closing old ticket. Re-open if an issue.
