### ISSUE TITLE
[Question] Accessing the shop domain without middleware

### ISSUE THREAD

**Issue by pangiras** [osiset/laravel-shopify#907]
First of all I would like to thank you for letting out this awesome package to aid in shopify app development. I know that after implementing the package we can access the current shop using Auth::user() , but that is only when the user is authenticated using the middleware. I want to access the current shop outside the middleware. To further clarify below is my configuration.

**Routes as defined in api.php**

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
}); // This uses middleware 
Route::post('shippingrate',[SettingController::class,'processAPIcall']); // This do not use middleware 

As you can see the shippingrate route is not using any middleware, as shippingrate is supposed to be a public endpoint where the visitor to website can send shipping rate request at checkout.

**This is how the controller looks.**

namespace App\Http\Controllers;
use App\Models\Customer;
use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\APIHelpers;

class SettingController extends Controller

{
 public function processAPIcall(Request $request)

    {
         // I want to access the current shop here. 
        
    }
}`

Any help will be greatly appreciated. Please excuse me if the question is dumb as I am new to laravel. 

Best Regards,
Angiras

**Comment by osiset** [comment]
Please use the discussions tab for non-issues :)

I recently did some shipping rates. The request should contain the shop from Shopify in the payload if you decode it.. I can't remember if its part of the JSON or a header, but its there. You can then query the shop with the model or using ShopQuery in the package.

If you're still having issues, open a discussion :)
