### ISSUE TITLE
Auth::user() seems to be not working in v17 (AfterAuthenticateJob)?

### ISSUE THREAD

**Issue by hamzasgd1** [osiset/laravel-shopify#909]
![Auth](https://user-images.githubusercontent.com/14020985/126118529-d435a09c-ada0-45a9-bfba-08a1c37d3334.PNG)

**Comment by arpit-golakiya** [comment]
Hello. @hamzasgd1 

You can try this

    public function __construct($shopDomain)
    {
        $this->shopDomain = $shopDomain['name'];
    }

public function handle()
    {
        $shop = User::where('name', $this->shopDomain)->firstOrFail();
    }

**Comment by osiset** [comment]
It won't be available due to the request, if you're running it inline. Use shopdomain.

**Comment by osiset** [comment]
```php
<?php namespace DummyNamespace;

use stdClass;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Osiset\ShopifyApp\Objects\Values\ShopDomain;
use Osiset\ShopifyApp\Storage\Queries\Shop as ShopQuery;

class DummyJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Shop's myshopify domain
     *
     * @var ShopDomain|string
     */
    public $shopDomain;

    /**
     * The webhook data
     *
     * @var object
     */
    public $data;

    /**
     * Create a new job instance.
     *
     * @param string   $shopDomain The shop's myshopify domain.
     * @param stdClass $data       The webhook data (JSON decoded).
     *
     * @return void
     */
    public function __construct($shopDomain, $data)
    {
        $this->shopDomain = $shopDomain;
        $this->data = $data;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle(ShopQuery $shopQuery)
    {
        // Convert domain
        $this->shopDomain = ShopDomain::fromNative($this->shopDomain);

        // Get the shop
        $shop = $shopQuery->getByDomain($this->shopDomain);

       // Your code
    }
}
```

Something like this should work fine. I'll close for now if no other issues :)

**Comment by hamzasgd1** [comment]
@osiset @arpit-golakiya Thanks

**Comment by abubakar0101** [comment]
> ```
> <?php namespace DummyNamespace;
> 
> use stdClass;
> use Illuminate\Bus\Queueable;
> use Illuminate\Queue\SerializesModels;
> use Illuminate\Queue\InteractsWithQueue;
> use Illuminate\Contracts\Queue\ShouldQueue;
> use Illuminate\Foundation\Bus\Dispatchable;
> use Osiset\ShopifyApp\Objects\Values\ShopDomain;
> use Osiset\ShopifyApp\Storage\Queries\Shop as ShopQuery;
> 
> class DummyJob implements ShouldQueue
> {
>     use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
> 
>     /**
>      * Shop's myshopify domain
>      *
>      * @var ShopDomain|string
>      */
>     public $shopDomain;
> 
>     /**
>      * The webhook data
>      *
>      * @var object
>      */
>     public $data;
> 
>     /**
>      * Create a new job instance.
>      *
>      * @param string   $shopDomain The shop's myshopify domain.
>      * @param stdClass $data       The webhook data (JSON decoded).
>      *
>      * @return void
>      */
>     public function __construct($shopDomain, $data)
>     {
>         $this->shopDomain = $shopDomain;
>         $this->data = $data;
>     }
> 
>     /**
>      * Execute the job.
>      *
>      * @return void
>      */
>     public function handle(ShopQuery $shopQuery)
>     {
>         // Convert domain
>         $this->shopDomain = ShopDomain::fromNative($this->shopDomain);
> 
>         // Get the shop
>         $shop = $shopQuery->getByDomain($this->shopDomain);
> 
>        // Your code
>     }
> }
> ```
> 
> Something like this should work fine. I'll close for now if no other issues :)

I will do this same in my controller but it give error as shown in below

"Unresolvable dependency resolving [Parameter #0 [ <required> $shopDomain ]] in class App\Http\Controllers\SetupController"

**Comment by abubakar0101** [comment]
kindly help me how can I use auth()->user() in my controller
