### ISSUE TITLE
Call to a member function getDomain() on null

### ISSUE THREAD

**Issue by v1nk0** [osiset/laravel-shopify#912]
A have a fresh install of Laravel and Laravel Shopify.
When I visit the app root-url, I get:
Call to a member function getDomain() on null

## Expected Behavior
App to show a login/authenticate page

## Current Behavior
Error: Call to a member function getDomain() on null

## Failure Information
vendor/osiset/laravel-shopify/src/Traits/AuthController.php:32

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.
1. Install laravel
2. Install Laravel Shopify and set configuration
3. Visit app-root (/)

### Context
* Package Version: 17.1.0
* Laravel Version: 8.50.0
* PHP Version: 7.4

### Failure Logs
[2021-07-20 11:00:31] local.ERROR: Call to a member function getDomain() on null {"exception":"[object] (Error(code: 0): Call to a member function getDomain() on null at /var/www/html/vendor/osiset/laravel-shopify/src/Traits/AuthController.php:32)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Osiset\\ShopifyApp\\Http\\Controllers\\AuthController->authenticate()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#36 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#38 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#43 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 /var/www/html/server.php(21): require_once('...')
#45 {main}
"}

**Comment by osiset** [comment]
When you say you visit the root url, are you visiting it via the admin/apps or direct access

**Comment by v1nk0** [comment]
In this case I directly access to app (not through Shopify)
I remember (at least from prior versions) that this would show a page where you can enter your .myshopify.com URL and get access to the app.

**Comment by osiset** [comment]
There is no such login page anymore. App must be accessed through the apps
page on the admin. You can add a login screen through by having an error
handler assigned to the missing domain exception.

**Comment by shaarifsabah** [comment]
Facing same issue while accessing the shop home route that is defined in osiset wiki inside Shopify?What should I do
![Screenshot (73)](https://user-images.githubusercontent.com/58669957/127455442-7a11ded1-0cfd-4fc0-8752-c5929b00fbbf.png)
.

**Comment by osiset** [comment]
You can't use root domain to access the app. Has to be through the admin panel.

**Comment by josemilioz** [comment]
I get the same error the guys above when accessing the ngrok link directly.
I know @osiset said that you can't use root domain access, but this error I get when trying to test the app is even more ambiguous
![Screen Shot 2021-08-03 at 16 41 53](https://user-images.githubusercontent.com/6752748/128083697-5ebc5ea6-438f-4f1c-bea8-36bb4e4b2d8c.png)

**Comment by v1nk0** [comment]
@josemilioz did you change the App URL in the App Setup to be the ngrok-URL as well?

**Comment by shaarifsabah** [comment]
> @josemilioz did you change the App URL in the App Setup to be the ngrok-URL as well?

Yes I have applied Ngrok-Url in app setup and also in my project I have also created apps before this update but now facing issues.

**Comment by bojan-samar** [comment]
I get the same issue as @josemilioz

**Comment by burfbari** [comment]
@josemilioz a workaround is - try deleting the shop record from the users table and retry.

**Comment by josemilioz** [comment]
@burfbari after some reloading procedures on the browser it started to work again. But it's intermittent. I don't know if it's me, my connection or maybe it's because i'm on the free tier of ngrok.

**Comment by tal7aouy** [comment]
I have the same error 
`  Call to a member function getDomain() on null
`

**Comment by bojan-samar** [comment]
@tal7aouy check to make sure a record does not exist in your users database. If it does, delete and try again.

**Comment by tal7aouy** [comment]
@bojan-samar  there is no record in users, unfortunately i delete and try again , the same error .

**Comment by therealdb** [comment]
This is happening for me as well - it's no longer pushing the `MissingShopDomainException` when trying to access /authenticate endpoint directly (with no shop parameter) - since the exception isn't being thrown, there is no way to capture and redirect to login.

**Comment by therealdb** [comment]
It's not pretty, but one workaround is adding this to the Handler render method:
```
if ($exception->getMessage() == "Call to a member function getDomain() on null") {
    return redirect()->route('login');
}
```

**Comment by burfbari** [comment]
@therealdb does a 'login' route exist?

**Comment by therealdb** [comment]
> @therealdb does a 'login' route exist?

@burfbari In my project it does, but you could just do the redirect
```
if ($exception->getMessage() == "Call to a member function getDomain() on null") {
    return redirect('/login');
}
```

**Comment by SkullDark1** [comment]
The solution for this issue all need to change the route to URL::tokenRoute follow [here ](https://github.com/osiset/laravel-shopify/wiki/Authentication-Process#links-routing-and-forms) and you will not get an error getdomain() and for those who are using ngrok you will need to add this function in `AppServiceProvider`

`public function boot()
    {
        URL::forceScheme('https');
    }`

**Comment by Stereotip42** [comment]
@osiset +1

**Comment by AwaiX728** [comment]
> Facing same issue while accessing the shop home route that is defined in osiset wiki inside Shopify?What should I do ![Screenshot (73)](https://user-images.githubusercontent.com/58669957/127455442-7a11ded1-0cfd-4fc0-8752-c5929b00fbbf.png) .

did you get any solution

**Comment by therealdb** [comment]
@HaseebAkbar102 @AwaiX728 I provided a workaround above: https://github.com/osiset/laravel-shopify/issues/912#issuecomment-913193392

My actual fix was merged already, so I'm guessing it will be available in a patch release at some point.

**Comment by ryp-legalshield** [comment]
I had this same problem on a fresh install - well...  I used an older nginx conf file!  This turned out to be the problem.  

Check your server conf  file and make sure it has the '?query_string' part!
`		location / {
			try_files $uri $uri/ /index.php?$query_string;
		}`

**Comment by rypwalters** [comment]
I had this same problem on a fresh install - well... I used an older nginx conf file! This turned out to be the problem.

Check your server conf file and make sure it has the '?query_string' part! 
`		location / {
			try_files $uri $uri/ /index.php?$query_string;
		}`

**Comment by adrianmihaila** [comment]
If you use ngrok for testing your app, you need to overwrite an ENV var SHOPIFY_API_REDIRECT with the ngrok.io/authenticate URL.

**Comment by nakarimi** [comment]
@adrianmihaila thanks that was the missing part not just by ngrok, I had another https hosted, but need to add **SHOPIFY_API_REDIRECT** to my .evn
