### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by dhaval1573** [osiset/laravel-shopify#915]
I was upgrade 15.1 to 17

after submiting form with post method get this error

![Screenshot_196](https://user-images.githubusercontent.com/87801393/126603749-5ce28470-786d-4492-a2d3-fa710461388c.png)
![Screenshot_197](https://user-images.githubusercontent.com/87801393/126603820-96c342e1-a11e-442a-9145-0f91d8e6edb0.png)

**Comment by enmaboya** [comment]
I don't think this error has anything to do with the Shopify integration

**Comment by ohmygoobness** [comment]
I got the same error, /authenticate/token forwards all post as get requests, try Route::any or Route::match(['get', 'post'])

**Comment by LonnyX** [comment]
This is a real issue.
In fact it looks like all POST route are being redirected to the same route but as GET.

**Comment by LonnyX** [comment]
This is a real issue.

I found a workaround for now. just add this line inside your form:

```php
    <input type="hidden" name="token" value="{{ request('token') }}">
```

**Comment by osiset** [comment]
It shouldn't be forwarding for a good token. request(token) is not a solution as the token will be stale quickly.

**Comment by LonnyX** [comment]
> It shouldn't be forwarding for a good token. request(token) is not a solution as the token will be stale quickly.

@osiset You are right, but, be aware that the token is already revealed. 

Just try this:
`<a href="#">Hover and see the link behind</a>`

![image](https://user-images.githubusercontent.com/10662320/126780688-3f3230bc-9c2c-4b32-8e3e-4b573647d2d4.png)


Also, It looks like there is a lot of popular apps that have this issue. The token is somewhere on the source/link and if you try to open on incognito, authentication is bypassed.
But, that doesn't mean the fix is not necessary

**Comment by osiset** [comment]
The JS is all frontend. The token will always be available for anyone. I'm not sure what you're expecting? The very nature of AppBridge you have to use their public facing API to fetch a token right on the page. There's simply nothing I can do for that.

 CSRF has to be disabled as Laravel uses the user session to create the value, but that value changes, both things are out of my control.

**Comment by LonnyX** [comment]
Oops, I thought you was trying to hide the token. Idk why I read "stole" instead of "stale" in your comment

Anyway, do you have an alternative instead of the hidden input?

**Comment by osiset** [comment]
There is no alternative to the input. Only other way is tacking on the token to the form action or to use an AJAX submission and pass the token in the header. There's nothing wrong with using the token as it is.. form, query param, header... its all still visible and thats fine.

It should not be passing through the token route through, I am not having an issue on my post forms. @dhaval1573 I want to rule out a stale token... do you have more logs than above? If you view source on your form token, watch it for a couple minutes, do you notice Chrome flash the DOM on the token (update it)?

**Comment by Kyon147** [comment]
Closing as old ticket.
