### ISSUE TITLE
500 error on session generatation

### ISSUE THREAD

**Issue by ingalesachin7** [osiset/laravel-shopify#918]
when app loads first time session token working but
switch to another page and call session token using 
 await Http.get('/authenticate/token'); then 500 error
trying to get property 'name' of non-object (View: \vendor\osiset\laravel-shopify\src\resources\views\layouts\default.blade.php)

I am using react js at UI for routing,

**Comment by ingalesachin7** [comment]
@osiset Can you help....

**Comment by ihateonions-uk** [comment]
I have the same problem, have done for a while and cannot resolve it. Ive opened a couple of tickets about this and not got any answer to it yet, I'm still looking. For reference on one of the tickets I opened about this, #892

**Comment by osiset** [comment]
I'm swamped with work atm, I can't look at this right atm sorry.

**Comment by faisal-saeed-brainx** [comment]
@ihateonions-uk @ingalesachin7 
Did you guys find any help?

**Comment by ingalesachin7** [comment]
@osiset Can you please help regarding this issue...

**Comment by faisal-saeed-brainx** [comment]
Hi,

I have just used this 
`href="{{ route('route-name', ['shop' => Auth::user()->name]) }}"`

instead of
`href="{{ URL::tokenRoute('route-name') }}`

and Its working fine for me.

**Comment by ingalesachin7** [comment]
The question is related to ....How to call in React Js or Ajax in multiple pages?

**Comment by faisal-saeed-brainx** [comment]
@ingalesachin7 Have you disabled the CSRF Token Verification?

**Comment by ingalesachin7** [comment]
Yes.. The first time it the token working and getting the shop info, but when we switch to page and try to call function not getting the refresh token

await Http.get('/authenticate/token');
Authorization: `Bearer ${window.sessionToken}`
 in Dashboard page function

but it does not get working in after we switch to dashboard to getlist page

**Comment by faisal-saeed-brainx** [comment]
How you are switching to other page?

**Comment by ingalesachin7** [comment]
Using React Routes

**Comment by Kyon147** [comment]
Closing stale issue.
