### ISSUE TITLE
Ignoring installation the first time, will cause an installation failure next time

### ISSUE THREAD

**Issue by bougsid** [osiset/laravel-shopify#919]
## Expected Behavior

When the user tries to install the app for the first time (before clicking the install button), a user record will be created on DB with an empty password, if the user ignores the installation (Did not click install), and come back later to install the app he should be redirected to the install page again to click the Install button and authorize the app.

## Current Behavior

If the user ignores the installation for the first time and comes back later to install the app, he will get a Shopify error page (There’s no page at this address).

## Failure Information

I did some investigation,  I think the issue is related to the **checkPreviousInstallation** method on **VerifyShopify** middleware, this function only checks if the record is presented on DB, and didn't check if the password is there or not, because an empty password means installation not completed yet, the user should be redirected to install page again.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Visit https://domain.com/?shop=yourshop.myshopify.com to install the app for the first time.
2. You will be redirected to the installation page, just ignore and close it.
3. Visit again https://domain.com/?shop=yourshop.myshopify.com, a Shopify error page will be presented.

### Context

"osiset/laravel-shopify": "^17.0.0",
"laravel/framework": "^8.0",
* Laradock

**Comment by osiset** [comment]
Will look into this.

**Comment by yasir-naseer-tetralogicx** [comment]
My app got rejected by shopify due to this issue, they did the same steps as mentioned above and they got the same issue for installation. kindly look into this

**Comment by heeeydex** [comment]
Created a PR https://github.com/osiset/laravel-shopify/pull/933

**Comment by clydesantiago** [comment]
@osiset @yasir-naseer-tetralogicx you can close this task now.

**Comment by bougsid** [comment]
@osiset any idea when the next release will be?

**Comment by Kyon147** [comment]
Closing as this issue should be fixed now.
