### ISSUE TITLE
Target class [auth.shop] does not exist.

### ISSUE THREAD

**Issue by daviTKEES** [osiset/laravel-shopify#920]
I am Trying to Create My First Shopify App Using Laravel, But I am Stuck in this error.

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [auth.shop] does not exist.
```

my web.php file is like that:

```
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->middleware(['auth.shop'])->name('home');
and the version is "osiset/laravel-shopify": "^17.1"
```

someone could help me?

**Comment by muhammadasfar** [comment]
@daviTKEES Hi, 

For osiset/laravel-shopify version 17, you have to use `verify.shopify` in your middleware. 

For routing see this [package wiki link](https://github.com/osiset/laravel-shopify/wiki/Installation#routing)

**Comment by osiset** [comment]
@daviTKEES correct on above comment, where did you see code like this? I'd like to update the wiki if that's where it came from

**Comment by tkeesdevs** [comment]
> @daviTKEES correct on above comment, where did you see code like this? I'd like to update the wiki if that's where it came from

I saw here https://www.youtube.com/watch?v=0SF0S2wn3cM

**Comment by muhammadasfar** [comment]
@tkeesdevs It's better to follow this package's [Wiki doc](https://github.com/osiset/laravel-shopify/wiki) instead of tutorials as @osiset and contributors are updating this wiki doc with every release.

**Comment by tkeesdevs** [comment]
> @tkeesdevs It's better to follow this package's [Wiki doc](https://github.com/osiset/laravel-shopify/wiki) instead of tutorials as @osiset and contributors are updating this wiki doc with every release.

Yeah, I agree, I was trying to learn about installing the App, but I decided to finish the video and I got this problem, to be honest, I read the doc after and got the solution, but I am very grateful for the help and very excited with the progress I am having now.

**Comment by Kyon147** [comment]
Closing as related to pre-v17.
