### ISSUE TITLE
Flash Data missing

### ISSUE THREAD

**Issue by mattias** [osiset/laravel-shopify#921]
## Expected Behavior

Flash data is available for the request it was created for

## Current Behavior

Flash data is empty

## Failure Information

I can see that in the token route it does a reflash for the flash data and even if the token route is not hit, I never get my flash messages. This in turn cause me to never get any error message from $request->validated(). 

InertiaJS uses the onError callback to set errors, but it never gets there. All requests are now triggering onSuccess even if there are errors.

I'm wondering if it's just me that has this, if it perhaps depends on InertiaJS? I know sessions won't work since it changes for each request, but flash messages should be available for that specific session since it is created for it. So I'm not sure why no flash messages are working.

I can however create flash messages in the share() method of the HandleInertiaRequests middleware and have it available.
But a flash message added anywhere else is not available there either, so I can't retrieve flash data and add it there, it has to be specifically created in the method.

### Steps to Reproduce

1. Create a form which validates the request
2. Cause a validation error in the form and post
3. JavaScript gets "onSuccess" intead of "onError" like it used to in v16

### Context

* Package Version: v17.1.0
* Laravel Version: v8.52.0
* PHP Version: v7.4.16
* InertiaJS
* lando toolset

### Failure Logs

No logs available.

**Comment by jeshtan** [comment]
This is expected as Inertia doesn't return 422 error, instead it redirect to the original form page, check [here](https://inertiajs.com/validation) for more details.

**Comment by mattias** [comment]
> This is expected as Inertia doesn't return 422 error, instead it redirect to the original form page, check [here](https://inertiajs.com/validation) for more details.

Because of the version 17 update? This was working fine before in v16 of laravel-shopify.

My idea of a workaround which I will try is to intercept the automatic response laravel creates when validating, and instead do my own redirect and fill in the "errors" variable for Inertia.

Has anyone else using Inertia solved form validation in v17 yet?

**Comment by osiset** [comment]
v16 uses cookies and Laravel sessions
v17 does not use these, thus flash data is passed over instead.

**Comment by LonnyX** [comment]
@osiset so there is no way to flash data or validate forms ? Because both are based on session and now, it looks like session is renewed on every request that mean flashed data (even the validator data) are lost

**Comment by markovic-nikola** [comment]
@LonnyX Have you resolved the issue?
I'm having trouble getting validation errors after upgrading to v17.

**Comment by LonnyX** [comment]
@markovic-nikola let's say I found a way to bypass it. Not sure how @osiset will fix this issue...

What I did, instead of redirecting back with flashed data (remember v17 is session less), you should just use the same view with your `$errors`

```php
public function show(Request $request, $errors = [], $success = '')
{
    return view('dashboard', compact('errors', 'success'));
}

public function store(Request $request)
{
    // don't use $request->validate() because it'll try to redirect()->back()
    $validator = Validator::make($request->all(), [
        'type' => 'required',
        'source' => 'required|in:google,yahoo',
    ]);
    if ($validator->fails()) {
        return $this->show($request, collect($validator->messages()->get('*'))->flatten());
    }

    // ... your logic 

    $this->show($request, [], 'Success message'); // don't use redirect()
}
```

It's ugly but it works

**Comment by tbruckmaier** [comment]
Thank you @LonnyX, seems the only way to do it right now.

Just a little enhancement, you can still use the `Session` facade if there is no redirect, so the `show()` method can stay the same and does not need the extra parameters. Also form builders like https://github.com/glhd/aire work that way (since they access the session variables directly)

```php
use Illuminate\Support\Facades\Session;
use Illuminate\Support\ViewErrorBag;
...

public function show(Request $request)
{
    return view('dashboard');
}

public function store(Request $request)
{
    // don't use $request->validate() because it'll try to redirect()->back()
    $validator = Validator::make($request->all(), [
        'type' => 'required',
        'source' => 'required|in:google,yahoo',
    ]);
    if ($validator->fails()) {
        Session::put('errors', (new ViewErrorBag)->put('default', $validator->errors()));
        return $this->show($request;
    }

    // ... your logic 
    Session::put('success', 'all done');
    return $this->show($request); // don't use redirect()
}
```
Or with using FormRequests:
```php
// controller
use App\Http\Requests\StoreRequest;
use Illuminate\Support\Facades\Session;

...

public function show(Request $request)
{
    return view('dashboard');
}

public function store(StoreRequest $request)
{
        if (!Session::has('errors')) {
            // ... your logic 
            Session::put('success', 'all done');
        }
        return $this->show($request);
}

// FormRequest
namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\ViewErrorBag;

class StoreRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            // validation rules
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        Session::put('_old_input', $this->validationData());
        Session::put('errors', (new ViewErrorBag)->put('default', $validator->errors()));
    }
}

```

**Comment by markovic-nikola** [comment]
I decided to switch to AJAX form submission, since I don't have a lot of code to refactor.

**Comment by Kyon147** [comment]
Closing as a solution has been found 👍

**Comment by garhbod** [comment]
Alternative solution so you don't have to do custom validation logic. Catch the `ValidationException` with laravel and respond with JSON then add an axios interceptor on the front end to receive it.

Add the below to the `register` method of `app/Exceptions/Handler.php`
```php
    public function register()
    {
        ...
        
        $this->renderable(function (ValidationException $exception, $request) {

            if ($request->headers->get('X-Inertia')) {
                return $this->invalidJson($request, $exception);
            }

            return $this->convertValidationExceptionToResponse($exception, $request);
        });
    }
```

Then on the javascript side of thing
```javascript
    window.axios.interceptors.response.use(
        (response) => {
            return response;
        },
        (error) => {
            if (error.response?.status === 422 && error.response?.config?.headers['X-Inertia']) {

                // DO WHAT YOU WANT WITH THE ERROR HERE LIKE ADDING THE ERRORS TO THE PAGE PROPS...
                usePage().props.errors = error.response?.data?.errors;

                return Promise.resolve(error);
            } else {
                return Promise.reject(error);
            }
        }
    );
```
