### ISSUE TITLE
UnInstalled WebHook not fire. How to check it work?

### ISSUE THREAD

**Issue by duykhoa87** [osiset/laravel-shopify#922]
I already registered Uninstalled Webhook when install all below:
```
SHOPIFY_WEBHOOK_1_TOPIC=app/uninstalled
SHOPIFY_WEBHOOK_1_ADDRESS=https://domain/webhook/app-uninstalled
```

```
"webhooks" => array:1 [▼
        0 => array:10 [▼
          "id" => 1056783499426
          "address" => "https://domain/webhook/app-uninstalled"
          "topic" => "app/uninstalled"
          "created_at" => "2021-07-28T10:53:37+07:00"
          "updated_at" => "2021-07-28T10:53:37+07:00"
          "format" => "json"
          "fields" => []
          "metafield_namespaces" => []
          "api_version" => "2021-01"
          "private_metafield_namespaces" => []
        ]
      ]
```
But I dont see any job in jobs table. Is there any way to check that?

**Comment by osiset** [comment]
Run a get API call to /admin/webhooks.json, see if your endpoints are listed. If they are, then they'll work.

**Comment by peking2008** [comment]
"address" => "https://domain/webhook/app-uninstalled"   replace your  app  domain.

**Comment by osiset** [comment]
@duykhoa87 Did you see any results?

**Comment by burfbari** [comment]
I suggest you have a look at the `laravel.log`
`/storage/logs` 
from an exception that might be firing. 
At least, looking at the logs helped me... I found out that I had missed creating the `Job `
`App/Jobs/AppUninstalledJob`
although I had enabled it in `config/shopify-app.php`

**Comment by Kyon147** [comment]
Closing as a stale issue but usually testing with a tunneling service like ngrok is the best way to go.
