### ISSUE TITLE
Missing auth url - MissingAuthUrlException

### ISSUE THREAD

**Issue by KevinSHansen** [osiset/laravel-shopify#926]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The app should install but it doesnt get a URL return

## Current Behavior

Its returns MissingAuthUrlException when it tries to return the shop shop.

## Failure Information

Stack trace:

{
    "class": "Osiset\\ShopifyApp\\Exceptions\\MissingAuthUrlException",
    "message": "Missing auth url",
    "code": 0,
    "file": "/var/www/html/vendor/osiset/laravel-shopify/src/Traits/AuthController.php:47",
    "trace": [
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:254",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:197",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.p

### Steps to Reproduce

When installing the app. Ive updated from 16 to 17 and since then it returns this error

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17
* Laravel Version: 8.52.0

**Comment by osiset** [comment]
See my comment in 908

**Comment by kaya-mikail** [comment]
Did anyone resolved this problem? Tried to fix it multiple times. On former attempts i used ngrok but now switched to laravel-windows and have the same issue. "Missing auth url".
The information about the shop is stored in the database except the password.
Tried both with auth and without auth installation.

**Comment by KevinSHansen** [comment]
Sadly not yet. Still struggling with this. @kaya-mikail

**Comment by KevinSHansen** [comment]
It does indeed save everything in the DB, just not the token.

Im using the newest shopify-app config, and changed the webhooks to use GraphQL topics, but nothing solved the problem.

**Comment by kaya-mikail** [comment]
I don't understand why this problem suddenly occurs. 
We tried to install the app on a development store directly from the Partner Dashboard.
I am coming to the OAuth screen wehere I have to grant access for the app. 
Before I give permission to the app, I can see that in the database the information about the shop is inserted except "password" column. This one is empty.
After clicking Install app it redirects me and the app error is displayed (not in iframe, it is a whole page).

The point this gets weird is that I installed a fresh laravel with this shopify package and it worked without any problem. This was 6 or 7 days ago.
Since then nothing changed in the package but I am facing this problem. Tried to install with fresh laravel project a couple of times - also on other computers - but without success. 
I was always using ngrok. Also when on former installation where it worked well.
Can anyone give me a hint about that?

**Comment by enmaboya** [comment]
Can I ask you to create a **new** laravel application and try to reproduce this error there?
and then upload this app to githab and share the link.

then i think i could help you

**Comment by kaya-mikail** [comment]
I uploaded on our google drive in zip archive. 
Here is the link:
[](https://drive.google.com/file/d/1uasiXkQF_TRG5FwMwrwwDwKaREJPJ8wK/view?usp=sharing)

Im very excited about your review.

**Comment by kaya-mikail** [comment]
**PROBLEM SOLVED!**

The problem seems to be on working / testing local.
We set up an nginx server today on a vserver. Now everything work fine.

**Comment by KevinSHansen** [comment]
> **PROBLEM SOLVED!**
> 
> The problem seems to be on working / testing local with ngrok or valet-windows.
> We set up an nginx server today on a vserver. Now everything work fine.

So the error was happening because of your development enviroment?

**Comment by osiset** [comment]
Please close if solved, thanks :)

**Comment by KevinSHansen** [comment]
Sadly i havent solved this yet. Will be closed when its solved.

**Comment by KevinSHansen** [comment]
I just noticed following:

Before hitting /authenticate it receives a status 302 from /admin/oauth/grant (shopify). And then its redirected to authenticate with a status 500 and it throws the MissingAuthUrlException.

**Comment by KevinSHansen** [comment]
Problem found. 

1. Update migration (needed column with updated password)
2. Post routes cant be within middleware to auth
3. Changed tokenRedirect everywhere.

**Comment by mudassirali007** [comment]
@KevinSHansen can you explain? I am not able to solve the issue at fresh install.

**Comment by haseebbutt1999** [comment]
> Problem found.
> 
> 1. Update migration (needed column with updated password)
> 2. Post routes cant be within middleware to auth
> 3. Changed tokenRedirect everywhere.

thanks working for me !

**Comment by inazeem** [comment]
> > Problem found.
> > 
> > 1. Update migration (needed column with updated password)
> > 2. Post routes cant be within middleware to auth
> > 3. Changed tokenRedirect everywhere.
> 
> thanks working for me !

I am having the similar issue what did you do to solve it? Please help

**Comment by zainakramimage** [comment]
I am also getting the same error. 
[
![Screenshot 2022-08-20 110210](https://user-images.githubusercontent.com/87980343/185731409-f4cbe8e6-14d5-4991-9d3e-f887e24b5391.png)
](url)

please help me I have no idea how to fix this.

**Comment by zainakramimage** [comment]
After wasting 4 to 5 hours it was APP_URL issue in .env file if you are using the ngrok then your APP_URL = 'ngrok_url' then it will work.
