### ISSUE TITLE
about WebhookController.php line 27

### ISSUE THREAD

**Issue by peking2008** [osiset/laravel-shopify#930]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

 $jobData = json_decode($request->getContent(),true);

## Current Behavior

current:
 $jobData = json_decode($request->getContent());

### Context

如果不直接转化成数组，后期在job里调用非常麻烦。为什么不直接让他转化成数组呢？

**Comment by osiset** [comment]
I am not sure what you're asking or what your issue is, can you explain?

**Comment by peking2008** [comment]
> I am not sure what you're asking or what your issue is, can you explain?

eg.xxxJob.php:

`public function __construct($shopDomain, $data)
{
  $this->shopDomain = $shopDomain;
**//this $data is stdclass not a array**
  $this->data = $data;
}

public function handle()
{
**//if like this use is error.you must invert to array by stdclass**
$this->data['orders']['edgs']['id'];


  $user = User::where('name', $this->shopDomain)->firstOrFail();
  // do stuff here
}
`

**Comment by peking2008** [comment]
I am sorry.
I am English is very poor

**Comment by osiset** [comment]
Write your issue in your native language, and Google Translate it to
English, might help.

**Comment by diego-lipinski-de-castro** [comment]
I think he wants $data to be an array instead of an stdClass by default.

**Comment by peking2008** [comment]
> 我认为他希望 $data 默认是一个数组而不是 stdClass 。

Yes,you are right!

**Comment by peking2008** [comment]
> I think he wants $data to be an array instead of an stdClass by default.

Yes,you are right!

**Comment by diego-lipinski-de-castro** [comment]
to be honest I kinda agree with him, I always need to encode and decode so I can log the received information properly. But thats up to the author

**Comment by Kyon147** [comment]
As this is not an issue and it is quite old, going to close it.
