### ISSUE TITLE
Reinstalling the app keeps getting free trial.

### ISSUE THREAD

**Issue by clydesantiago** [osiset/laravel-shopify#942]
When a user installed the app, they get a 3-day free trial. Can someone help me please why customers keep getting a 3-day free trial when they reinstall the app?

When they uninstalled the app on the first day and then reinstalled it on 4th day, they should get charged instead of claiming another 3-day free trial right?

https://ibb.co/nLwk9JM

**Comment by enmaboya** [comment]
you can override the billing controller, in particular in the GetPlanUrl action you can add a check, e.g.

        // Get the plan
        $plan = $planId->isNull() ? $this->planQuery->getDefault() : $this->planQuery->getById($planId);

        if ($shop->plan) {
            $plan->trial_days = null;
        }

**Comment by Kyon147** [comment]
Closing this as it is an old ticket, reopen if you still have the issue on the latest version.
