### ISSUE TITLE
Not redirect to home route after authenticated the app

### ISSUE THREAD

**Issue by sandyrewa** [osiset/laravel-shopify#943]
## Expected Behavior

After successful authenticated app should redirect to home route
https://shopname.com/admin/apps/8e70e1ac2ef9c145dab4f001b504baee/appname/?shop=shopname.com&target=%2F%3Fhost%3Dc2YtZGVtby1vbmUubXlzaG9waWZ5LmNvbS9hZG1pbg

## Current Behavior

After successful authenticated app redirect to this URL 
https://shopname.com/admin/apps/8e70e1ac2ef9c145dab4f001b504baee/appname/authenticate/token?shop=shopname.com&target=%2F%3Fhost%3Dc2YtZGVtby1vbmUubXlzaG9waWZ5LmNvbS9hZG1pbg

But it should redirect to the URL
https://shopname.com/admin/apps/8e70e1ac2ef9c145dab4f001b504baee/appname/?shop=shopname.com&target=%2F%3Fhost%3Dc2YtZGVtby1vbmUubXlzaG9waWZ5LmNvbS9hZG1pbg

I'm using old version of API v16.0 into the another app and its working properly and redirected to the home route 

### Context

* Package Version: v17.1
* Laravel Version: v8.54
* PHP Version: v8.0

**Comment by enmaboya** [comment]
you are redirected to authenticate/token to get an access token.

v17 will not work without this.

**Comment by sandyrewa** [comment]
@enmaboya Ok, but not redirect to the home screen, I mean the welcome page is not visible after redirect on this page. how can I redirect to the home page route?

**Comment by Kyon147** [comment]
Hi @sandyrewa 

You have set up your web.php correctly? Can you provide more detail into the issue you are facing.

**Comment by sandyrewa** [comment]
Hi @Kyon147 
Thanks for your reply, I have set up routes on web.php properly, and now it's working on the server but not working on localhost, getting the infinite redirect on localhost which related to #962

**Comment by Kyon147** [comment]
Hi @sandyrewa 

As @enmaboya mentioned, v17 uses JWT tokens and that `authenticate/token` route is what grabs the token. It needs to happen on every page change to make sure we have a valid token.

Do you still have the issue?

**Comment by Kyon147** [comment]
Closing stale issue, reopen if problem persists.
