### ISSUE TITLE
Session in Safari browser - Issue

### ISSUE THREAD

**Issue by KevinSHansen** [osiset/laravel-shopify#950]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

The app is working perfect in Chrome with session, but as soon as i open the app in Safari the user isnt authorized. 

## Current Behavior

Auth is never set in Safari and Shopify have been denying the app for this before.

## Failure Information

Using v17.0.1 and updated everything to use Sessions.

### Steps to Reproduce

Updated to v17.0.1 and followed the upgrade guide.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.0.1
* Laravel Version: v8.12
* PHP Version: v8
* Using a toolset (Docker, Laradock, Vagrant, etc.): Kubernetes (nginx)

### Failure Logs
`{
    "class": "Facade\\Ignition\\Exceptions\\ViewException",
    "message": "Attempt to read property \"name\" on null (View: /var/www/html/vendor/osiset/laravel-shopify/src/resources/views/layouts/default.blade.php)",
    "code": 0,
    "file": "/var/www/html/vendor/osiset/laravel-shopify/src/resources/views/layouts/default.blade.php:33",
    "trace": [
        "/var/www/html/vendor/osiset/laravel-shopify/src/resources/views/layouts/default.blade.php:33",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:107",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:108",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:58",
        "/var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php:35",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:61",
        "/var/www/html/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php:37",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php:139",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php:122",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php:91",
        "/var/www/html/vendor/osiset/laravel-shopify/src/resources/views/auth/token.blade.php:45",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:107",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:108",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:58",
        "/var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php:35",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:61",
        "/var/www/html/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php:37",
        "/var/www/html/ve`

**Comment by enmaboya** [comment]
1) you are not using the right middleware (verify.shopify)
2) you haven't updated the connected appbridge in default.blade.php 
and you haven't added blade templates to update the token.

**Comment by Kyon147** [comment]
Fixed in #956
