### ISSUE TITLE
Upgrading from 15 to 17 version authenticate/token request not work

### ISSUE THREAD

**Issue by aakashprajapati1** [osiset/laravel-shopify#952]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior
Successfully work authenticate token request.

## Current Behavior
I have followed the upgrading guide from this link https://github.com/osiset/laravel-shopify/wiki/Upgrading

## Failure Information
https://user-images.githubusercontent.com/80114426/130210687-ac827e4c-5cda-40aa-8687-3989b800f99b.png

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.1.0
* Laravel Version: v8.55.0
* PHP Version: v7.4.22
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.
https://user-images.githubusercontent.com/80114426/130210687-ac827e4c-5cda-40aa-8687-3989b800f99b.png

**Comment by jaspreetAxt** [comment]
Same issue I am facing with Laravel 8 and latest version of this library

**Comment by enmaboya** [comment]
1) you are not using the right middleware (verify.shopify)
2) you haven't updated the connected appbridge in default.blade.php 
and you haven't added blade templates to update the token.

**Comment by aakashprajapati1** [comment]
Hello @enmaboya 

Thanks, I have followed this document: https://github.com/osiset/laravel-shopify/wiki/Upgrading

I have done the changes regarding middleware but for the blade templates can you please provide the link where I can find it.

**Comment by aakashprajapati1** [comment]
Hello @enmaboya 

Thanks, I have updated the new blade files and working fine for me.

**Comment by amosmos** [comment]
I have the same issue, I assume it is because my config has appbridge_enabled=false so app bridge isn't being loaded in the token request view - is that correct?
