### ISSUE TITLE
Logged in user not checked in VerifyShopify middleware

### ISSUE THREAD

**Issue by bastos71** [osiset/laravel-shopify#957]
## Expected Behavior

Log in once, then stay logged without having to request / validate a token.

## Current Behavior

On each request, the verification of "logged in user" is not triggered soon enough, resulting in a 302 redirect on each request , from `/my-request` to `/my-request?token=vfzrkofgelg,e...`

Possible linked issue : #915

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Connect to the application
2. Navigate to the routes defined in the laravel apps
3. Open your browser Network console, you will see 302 redirects

### Context

For information i'm working on an integration between `backpack/crud` and `osiset/laravel-shopify` packages.

* Package Version: v17.1.0
* Laravel Version: v8.54.0
* PHP Version: 8.0.9
* Using a toolset (Docker, Laradock, Vagrant, etc.): local docker compose environment

## Fix proposal

In the `VerifyShopify` middleware, update the `handle` method to take care sooner of the user logged in

```diff
        // ...
        $tokenSource = $this->getAccessTokenFromRequest($request);
        if ($tokenSource === null) {
+            if ($request->user()) {
+               return $next($request);
+            }

            //Check if there is a store record in the database
            return $this->checkPreviousInstallation($request)
                // Shop exists, token not available, we need to get one
                ? $this->handleMissingToken($request, $next)
                // Shop does not exist
                : $this->handleInvalidShop($request);
        }
        // ...
```

**Comment by Kyon147** [comment]
As the v17 uses JWT tokens you do need to get a token on every request as they expire after 120 seconds. This is not an bug but expected behavior.

**Comment by Kyon147** [comment]
Having a little look into this, we might need to do more work to the auth - as this only looks to see for a user that is currently logged in but the JWT tokens expire after two mins. So there would be a case, were we have a user but not a valid token and this would break. 

Going to close this issue for now.
