### ISSUE TITLE
Event triggered after billing updates

### ISSUE THREAD

**Issue by jasontxf** [osiset/laravel-shopify#958]
Hello, is there any way to trigger an event when billing has been updated? 

This way, we can include our own logic (like updating user's quota)  when they changed to a different plan. 

Seek your consideration :)

**Comment by Kyon147** [comment]
You could use the "Event" and "Listener" functions in Laravel. You'd need to intercept whenever your billing logic runs. If you are using the packages built in logic, then you'd need to probably add some additional custom work outside the scope of this package into it in the same way.
