### ISSUE TITLE
scripttags not install after installed the app

### ISSUE THREAD

**Issue by pengbo37877** [osiset/laravel-shopify#963]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

Please describe the current behavior?

## Failure Information

`[2021-09-04 18:51:17] local.ERROR: Trying to access array offset on value of type float {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type float at /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php:59)
[stacktrace]
#0 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php(59): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '/Users/pengbo/C...', 59, Array)
#1 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php(29): Osiset\\BasicShopifyAPI\\Middleware\\RateLimiting->handleRest(Object(Osiset\\BasicShopifyAPI\\BasicShopifyAPI))
#2 /Users/pengbo/Code/ant-trust-platform/vendor/caseyamcl/guzzle_retry_middleware/src/GuzzleRetryMiddleware.php(149): Osiset\\BasicShopifyAPI\\Middleware\\RateLimiting->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#3 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/UpdateRequestTime.php(38): GuzzleRetry\\GuzzleRetryMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/UpdateApiLimits.php(31): Osiset\\BasicShopifyAPI\\Middleware\\UpdateRequestTime->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/AuthRequest.php(85): Osiset\\BasicShopifyAPI\\Middleware\\UpdateApiLimits->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Osiset\\BasicShopifyAPI\\Middleware\\AuthRequest->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#13 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync('POST', Object(GuzzleHttp\\Psr7\\Uri), Array)
#14 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(135): GuzzleHttp\\Client->request('POST', Object(GuzzleHttp\\Psr7\\Uri), Array)
#15 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(147): Osiset\\BasicShopifyAPI\\Clients\\Rest->Osiset\\BasicShopifyAPI\\Clients\\{closure}()
#16 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/BasicShopifyAPI.php(423): Osiset\\BasicShopifyAPI\\Clients\\Rest->request('POST', '/admin/script_t...', Array, Array, true)
#17 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php(490): Osiset\\BasicShopifyAPI\\BasicShopifyAPI->rest('POST', '/admin/script_t...', Array)
#18 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php(194): Osiset\\ShopifyApp\\Services\\ApiHelper->doRequest(Object(Osiset\\ShopifyApp\\Objects\\Enums\\ApiMethod), '/admin/script_t...', Array)
#19 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Actions/CreateScripts.php(78): Osiset\\ShopifyApp\\Services\\ApiHelper->createScriptTag(Array)
#20 [internal function]: Osiset\\ShopifyApp\\Actions\\CreateScripts->__invoke(Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#21 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Messaging/Jobs/ScripttagInstaller.php(63): call_user_func(Object(Osiset\\ShopifyApp\\Actions\\CreateScripts), Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#22 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller->handle(Object(Osiset\\ShopifyApp\\Actions\\CreateScripts))
#23 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#28 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#29 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#30 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller), false)
#32 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#33 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#34 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#36 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#37 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#38 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#39 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#40 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#41 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#42 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#43 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#44 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#45 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#46 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#47 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#48 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#49 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#50 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#54 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#55 /Users/pengbo/Code/ant-trust-platform/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#56 {main}
"} 
`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: ^17.1
* Laravel Version: ^8.54
* PHP Version: ^7.3|^8.0
* Using a toolset (Docker, Laradock, Vagrant, etc.): Vagrant

### Failure Logs
`[2021-09-04 18:51:17] local.ERROR: Trying to access array offset on value of type float {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type float at /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php:59)
[stacktrace]
#0 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php(59): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '/Users/pengbo/C...', 59, Array)
#1 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/RateLimiting.php(29): Osiset\\BasicShopifyAPI\\Middleware\\RateLimiting->handleRest(Object(Osiset\\BasicShopifyAPI\\BasicShopifyAPI))
#2 /Users/pengbo/Code/ant-trust-platform/vendor/caseyamcl/guzzle_retry_middleware/src/GuzzleRetryMiddleware.php(149): Osiset\\BasicShopifyAPI\\Middleware\\RateLimiting->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#3 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/UpdateRequestTime.php(38): GuzzleRetry\\GuzzleRetryMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/UpdateApiLimits.php(31): Osiset\\BasicShopifyAPI\\Middleware\\UpdateRequestTime->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Middleware/AuthRequest.php(85): Osiset\\BasicShopifyAPI\\Middleware\\UpdateApiLimits->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Osiset\\BasicShopifyAPI\\Middleware\\AuthRequest->Osiset\\BasicShopifyAPI\\Middleware\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#13 /Users/pengbo/Code/ant-trust-platform/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync('POST', Object(GuzzleHttp\\Psr7\\Uri), Array)
#14 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(135): GuzzleHttp\\Client->request('POST', Object(GuzzleHttp\\Psr7\\Uri), Array)
#15 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(147): Osiset\\BasicShopifyAPI\\Clients\\Rest->Osiset\\BasicShopifyAPI\\Clients\\{closure}()
#16 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/basic-shopify-api/src/BasicShopifyAPI.php(423): Osiset\\BasicShopifyAPI\\Clients\\Rest->request('POST', '/admin/script_t...', Array, Array, true)
#17 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php(490): Osiset\\BasicShopifyAPI\\BasicShopifyAPI->rest('POST', '/admin/script_t...', Array)
#18 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Services/ApiHelper.php(194): Osiset\\ShopifyApp\\Services\\ApiHelper->doRequest(Object(Osiset\\ShopifyApp\\Objects\\Enums\\ApiMethod), '/admin/script_t...', Array)
#19 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Actions/CreateScripts.php(78): Osiset\\ShopifyApp\\Services\\ApiHelper->createScriptTag(Array)
#20 [internal function]: Osiset\\ShopifyApp\\Actions\\CreateScripts->__invoke(Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#21 /Users/pengbo/Code/ant-trust-platform/vendor/osiset/laravel-shopify/src/Messaging/Jobs/ScripttagInstaller.php(63): call_user_func(Object(Osiset\\ShopifyApp\\Actions\\CreateScripts), Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Array)
#22 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller->handle(Object(Osiset\\ShopifyApp\\Actions\\CreateScripts))
#23 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#28 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#29 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#30 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller), false)
#32 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#33 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#34 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Osiset\\ShopifyApp\\Messaging\\Jobs\\ScripttagInstaller))
#36 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#37 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#38 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#39 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#40 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#41 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#42 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#43 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#44 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#45 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#46 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#47 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#48 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#49 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#50 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /Users/pengbo/Code/ant-trust-platform/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#54 /Users/pengbo/Code/ant-trust-platform/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#55 /Users/pengbo/Code/ant-trust-platform/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#56 {main}
"} 
`

**Comment by therealdb** [comment]
I'm getting this same error - just did an update, but haven't tried rolling it back yet. I get the same error on the script tag and webhook jobs

**Comment by therealdb** [comment]
@pengbo37877 The issue was introduced in v10.0.4 of the basic-shopify-api repo. If you explicitly require the `osiset/basic-shopify-api` repo at v10.0.3 in your project, it should solve the problem.
