### ISSUE TITLE
Call to the API route not landing on the Controller

### ISSUE THREAD

**Issue by burfbari** [osiset/laravel-shopify#974]
Sorries in advance if this is not related to the package...

This is how my API call looks like

```
fetch('/api/payme?customer='+customer, 
{
    headers: new Headers({
        'Authorization': 'Bearer ' + session_token
    }),
    method: 'GET'
})
```

The Fetch seems alright to me with 200

![Screenshot (56)](https://user-images.githubusercontent.com/52349056/133223428-6ae5b934-ef7e-4253-bb63-7e5f76eea233.png)

For some reason the request is not landing on the Controller. What am I missing here?

**Comment by burfbari** [comment]
When I use POST, I see the below in console:-

`POST | https://4fac-2401-4900-1f3a-3638-68e5-f115-d599-8c66.ngrok.io/payme` gives a 302

and

`GET | https://4fac-2401-4900-1f3a-3638-68e5-f115-d599-8c66.ngrok.io/authenticate/token?shop=tg-test-app-store.myshopify.com&target=/payme` which gives a 200

**Comment by Kyon147** [comment]
Hi @burfbari 

This does not seem to be an issue with the package.

Closing it for now, but if you feel that it is please provide more information.
