### ISSUE TITLE
How to get rid of loading screen on GET, POST reqeust in version 17.1 and replace it with custom loader

### ISSUE THREAD

**Issue by SkullDark1** [osiset/laravel-shopify#981]
Greetings, I have been trying to add a loader in my Shopify app, the loader was working fine in ver16, but when I updated to version 17.1, it is replaced with the loading screen which comes with the package, is there any way I can customize it, or show my own loader. 

![Screenshot 2021-09-18 150544](https://user-images.githubusercontent.com/73682305/133905903-05471556-b5ee-4c6f-b01a-ae6b5a2c2196.png)

**Comment by enmaboya** [comment]
https://github.com/osiset/laravel-shopify/blob/master/src/resources/views/auth/token.blade.php
![image](https://user-images.githubusercontent.com/32259003/133923359-d79781e1-9e7b-4460-8ce8-6374f836e812.png)

**Comment by SkullDark1** [comment]
Thanks!!
