### ISSUE TITLE
Can't call endpoint with any type of query params

### ISSUE THREAD

**Issue by testusernameASH** [osiset/laravel-shopify#982]
Hi,

I'm trying to use this method with this endpoint: 

`$orders = $shop->api()->rest('GET', '/admin/api/2021-07/orders.json?limit=5');`

I added the query param `?limit=5` for pagination purposes but the app crashes every time I add any kind of query params.

`Error: Allowed memory size of 134217728 bytes exhausted`.

The same issue exists with `?status=any`.

Works fine without the query params and I can also get the response directly from Shopify using postman.

**Comment by goranculibrk** [comment]
Had the same problem until I realized that the query parameters are passed and third argument in `rest()` method.

The correct way to send query params would be: 

`$orders = $shop->api()->rest('GET', '/admin/api/2021-07/orders.json', [ 'limit' => 5 ]);`
`$orders = $shop->api()->rest('GET', '/admin/api/2021-07/orders.json', [ 'status' => 'any' ]);`
