### ISSUE TITLE
Its showing skeleton even i am not using app bridge

### ISSUE THREAD

**Issue by ShexiTech** [osiset/laravel-shopify#983]
Hi, 

i am using osiset 17.1. i set appbridge_enabled as false but its showing me loading screen. its looks like app is getting stuck on `authntication\token` for non embeded Apps.

Note: when i convert it to embeded app then it works fine

## Expected Behavior

its should show the basic laravel view.

## Current Behavior

its showing me loader view
## Failure Information

Please help provide information about the failure if this is a bug.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: 17.1
* Laravel Version: 7
* PHP Version: 7.3
* Using a toolset (Docker, Laradock, Vagrant, etc.): vagrant

### Failure Logs
![Screenshot_4](https://user-images.githubusercontent.com/45964661/134495520-fbba5f1c-d59f-44e7-8b89-728fb402983a.png)

**Comment by ItsGageH** [comment]
Non-app-bridge is not currently supported in v17 as referenced in issue #929
