### ISSUE TITLE
Unintall webhook not working give domain name empty error

### ISSUE THREAD

**Issue by kashif-sol** [osiset/laravel-shopify#985]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

When we uninstall app then a webhook trigger that delete data from db.

## Current Behavior

Now when I have uninstalled the app then get an error 
 Can only instantiate this object with a string. {"exception":"[object] (InvalidArgumentException(code: 0): Can only instantiate this object with a string. at /home/u102134945/domains/webtechfixers.com/public_html/dotlogexapp/vendor/funeralzone/valueobjects/src/Scalars/StringTrait.php:49)

osiset/laravel-shopify/src/Messaging/Jobs/AppUninstalledJob.php(72): Osiset\\ShopifyApp\\Objects\\Values\\ShopDomain::fromNative(NULL)
 
This gives domain name NULL

JUST install app then uninstall app data not deleted and in log get above error

**Comment by mahmoodch107** [comment]
this is not  an Asset\ShopifyApp issue,

Please double check if your app_url is correct?

Your current app_url is:  webtechfixers.com
<http://webtechfixers.com/public_html/dotlogexapp/vendor/funeralzone/valueobjects/src/Scalars/StringTrait.php:49>
I think this is not correct.

the uninstall webhook url might be:  https://webtechfixers.com/
webhook/app-uninstalled

**Comment by mahmoodch107** [comment]
if you are facing issue. contact us to resolve it.

**Comment by kashif-sol** [comment]
if my webhook URL was wrong then it should not trigger it means webhook URL
is fine so that webhook trigger

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RishabhTayal** [comment]
Any solution for this? I am also facing this issue. domain is coming as empty.
