### ISSUE TITLE
Trying to send data from product page to Laravel

### ISSUE THREAD

**Issue by dhanacodem** [osiset/laravel-shopify#986]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Need to send some data and store it on Laravel via API

## Current Behavior

When click it, response is shop data mismatching and sometimes getting CROS issue.

## Failure Information

Getting issue shop data mismatching while calling axios api.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. ...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
Hi @dhanacodem 

Can you please fill out the rest of the form, with your package version etc

**Comment by Kyon147** [comment]
Closing as not heard back in a long time.
