### ISSUE TITLE
Regarding non embedded app using Laravel & VueJs in Shopify

### ISSUE THREAD

**Issue by roguestack** [osiset/laravel-shopify#987]
Dear Team

Greetings..!!

Actually, I am working on a project for a Shopify app where I using Laravel as backend and VueJs as front end stack and stuck badly at 2 points for which I need your assistance. Honestly, believe me, I have gone through various resources and have contacted a lot of people but it's bad luck only. hence I have approached you with hope to find suitable solution.

let me try and explain the issue as much as possible. 

1. I have set up Shopify app using Laravel and Vue Js using your link. It's working fine using ngrok environment but it's opening up inside shopify admin however my requirement is to open up the app in another window.Hence, i went through few resource and found out that i have to Disable the Embedded app option inside app set up in shopify store and set forceDirect option to false inside osiset\laravel-shopify\src\resources\views\auth\fullpage_redirect.blade.php. Afterwards, I am getting my app open in new window but it came with new error as follows:

![image_2021_09_28T06_15_35_000Z](https://user-images.githubusercontent.com/87008197/135613567-ce28c491-1ada-4406-8d38-0ec3f36aa49d.png)

2. again i went through few blogs for resolution and got advised me to comment the below entire block in comment in following image
 
![image_2021_09_28T07_20_11_372Z (1)](https://user-images.githubusercontent.com/87008197/135613481-48c79351-ffd0-4f5a-890d-65bd572f90e1.png)

![image](https://user-images.githubusercontent.com/87008197/135613657-ebbe7764-b784-4cc7-a36f-904be396c548.png)

now my page is getting open in new window without error but screen is blank and not able to see anything

![image_2021_09_28T09_26_55_560Z (1)](https://user-images.githubusercontent.com/87008197/135613426-ec19e9bb-9b0f-4215-957d-5ad1638e999e.png)

I am stuck since few days badly due to this issue and can't move further for development. I need your assistance to resolve this issue. I know you must be busy with your responsibility but being developer i am asking for help so please try your best for the same.

I have attached my code your testing purpose.
https://drive.google.com/file/d/1jEtORn7etXgn_pFtDU18VhtBkbByONy6/view?usp=drive_web

best regards,
Jay Patel

**Comment by roguestack** [comment]
> I came here to post the same question.
> 
> I just ran across the same problem with React.
> 
> Do you have any updates on this?

No Bro...it seems there are very few developers who try and run non-embedded app in shopify. I have gone through all resources so far and none of them have any clue on how to run non-embedded app developed in Laravel + Vue/React. All Developers prefer it run inside shopify admin.

no one in community is active...just spectators only.....

**Comment by Aryanhasanzadeh** [comment]
Hello friends, did anyone find a solution on how to open the program on another page? 

i'm using laravel with livewire i have 2 problem 
first auth session expire after any event call by livewire
Second, the project must open in a new page and the project is very slow inside the iframe 

@brucelee90 @roguestack 
you can help me ?

**Comment by brucelee90** [comment]
I didn't find a solution yet, but it seems like this issue is known already. And there seems to be an Pull request already:

[https://github.com/osiset/laravel-shopify/pull/935](https://github.com/osiset/laravel-shopify/pull/935)

**Comment by Kyon147** [comment]
Please see #1208 and closing in favor of this ticket.

**Comment by jhaineymilevis** [comment]
hi! can you share and example of how you implement it with vue?

**Comment by jhaineymilevis** [comment]
@roguestack 

hi! can you share and example of how you implement it with react?
