### ISSUE TITLE
Usage charge billing question (not a bug) 

### ISSUE THREAD

**Issue by sergeyantonuk** [osiset/laravel-shopify#999]
I am developing an application and I need to create a plan that will be free, but after sending the fifth email I have to start charging $10 monthly.
for this i did:
1. first I create a recurring application charge with  price = 0 and capped_amount = 10. This returns the ID that I'll need to create an associated usage charge.
2. after sending the fifth email I create usage charge with price = $10 

It works successfully and charges $10 after sending the fifth email.
The question is whether in this case there will be an automatic charge of $10 every month?
Or should I handle this on my side myself? (for example, I can create a cron task that will run once a month and use usage charge, that will bill the merchant for $10 every month)

Can someone please give me a hand?
thank you in advance!

Package Version: v12.0.1
Laravel Version: v7.19.1
PHP Version: v7.2.24

**Comment by Kyon147** [comment]
Ho @sergeyantonuk 

Usage charges are "one-off" payments that happen when you generate them and are paid for. If you need to do more say every 5 emails. You would need to track this internally and trigger another usage charge for the store.
